<!-- GENERATED by awf: do not edit; change .awf/ and run `awf render` -->
# Git access

The one semantic git seam - entrypoints, backends, and their pinned contracts.

**Applicability:** Owning domain selectors: `cmd/**`, `internal/audit/**`, `internal/changelog/**`, `internal/clispec/**`, `internal/contextdelivery/**`, `internal/contextspill/**`, `internal/coverage/**`, `internal/effort/**`, `internal/evals/**`, `internal/git/**`, `internal/initspec/**`, `internal/memorycite/**`, `internal/prosegate/**`, `internal/snapshot/**`, `internal/testsupport/**`, `internal/upgrade/**`, `internal/worktree/**`, `tools/**`, `x`. Topic selectors: `internal/git/**`, `internal/testsupport/gitfixture/**`. Both domain and topic selectors must match. Run `awf topic tooling/git-access --coverage` for current matched paths and marker sites.

This package provides every git capability awf consumes, native and library-backed alike, behind one semantic seam.

## Claims
