package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestLegacyLayoutsRequireManualMigrationWithoutMutation(t *testing.T) {
	for _, legacy := range []struct{ path, body string }{
		{".awf/project.md", "---\nformat: 1\n---\n# Existing project\n"},
		{".awf/project.md", "---\nformat: 2\n---\nUnrendered instructions\n"},
		{".awf/agents-doc.yaml", "data:\n  invariants:\n    - text: 'Unrendered repository rule'\n"},
		{".awf/parts/agents-doc/invariants.md", "Unrendered repository rule.\n"},
		{".awf/topics/code/go.md", "---\npaths: ['src/**/*.go']\n---\n# Existing topic\n"},
		{".awf/topics/metadata/go.yaml", "paths: ['src/**']\n"},
	} {
		t.Run(legacy.path+legacy.body, func(t *testing.T) {
			root := t.TempDir()
			path := filepath.Join(root, filepath.FromSlash(legacy.path))
			if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
				t.Fatal(err)
			}
			if err := os.WriteFile(path, []byte(legacy.body), 0o644); err != nil {
				t.Fatal(err)
			}
			for _, args := range [][]string{{"resolve"}, {"resolve", "src/new.go"}, {"resolve", "--coverage", "src/new.go"}, {"init"}, {"render"}, {"check"}} {
				code, stdout, stderr := runCLI(t, root, args...)
				if code != 1 || stdout != "" || !strings.Contains(stderr, "legacy AWF source") || !strings.Contains(stderr, "docs integration") {
					t.Errorf("unmigrated %v = code %d, stdout %q, stderr %q", args, code, stdout, stderr)
				}
			}
			got, err := os.ReadFile(path)
			if err != nil || string(got) != legacy.body {
				t.Fatalf("legacy content changed: %q, %v", got, err)
			}
			for _, path := range []string{"AGENTS.md", "docs", "awf", ".awf/VERSION"} {
				if _, err := os.Stat(filepath.Join(root, path)); !os.IsNotExist(err) {
					t.Fatalf("unmigrated commands created %s: %v", path, err)
				}
			}
		})
	}
}

func TestManualOwnershipTransitionPreservesAuthoredAndUnrenderedGuidance(t *testing.T) {
	root := t.TempDir()
	projectPath := filepath.Join(root, ".awf", "project.md")
	legacyTopics := filepath.Join(root, ".awf", "topics")
	topic := []byte("---\ntype: Project Topic\ndescription: Existing source guidance\npaths: ['src/**/*.go']\n---\n# Existing topic\n")
	marker := "<!-- GENERATED by awf; remove this comment to take ownership -->\n"
	files := map[string][]byte{
		".awf/project.md":                 []byte("---\nformat: 1\n---\nProject rule.\nUnrendered rule.\n"),
		"AGENTS.md":                       []byte(marker + "Superseded shared workflow.\nProject rule.\nAuthored guide edit.\n"),
		"CLAUDE.md":                       []byte("@AGENTS.md\nClaude rule.\n"),
		".awf/topics/code/go.md":          topic,
		".awf/efforts/active/memory.md":   []byte("opaque checkpoint\x00\xff\n"),
		".awf/worktrees/active/local.txt": []byte("local work\n"),
		"docs/plans/active.md":            []byte("---\ntype: Implementation Plan\ndescription: An active plan\n---\nactive plan\n"),
		"docs/decisions/active.md":        []byte("---\ntype: Architecture Decision\ndescription: An active decision\ndecision_status: active\nstatus: stable\n---\nactive decision\n"),
	}
	for relative, body := range files {
		path := filepath.Join(root, filepath.FromSlash(relative))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, body, 0o644); err != nil {
			t.Fatal(err)
		}
	}

	// The adopter reconciles both files, removes superseded shared prose and the
	// ownership marker, then retires the descriptor and moves complete topics.
	agents := []byte("Project rule.\nUnrendered rule.\nAuthored guide edit.\n")
	if err := os.WriteFile(filepath.Join(root, "AGENTS.md"), agents, 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.Remove(projectPath); err != nil {
		t.Fatal(err)
	}
	if err := os.Rename(legacyTopics, filepath.Join(root, "docs", "topics")); err != nil {
		t.Fatal(err)
	}
	delete(files, ".awf/project.md")
	delete(files, ".awf/topics/code/go.md")
	files["AGENTS.md"] = agents
	files["docs/topics/code/go.md"] = topic

	code, stdout, stderr := runCLI(t, root, "resolve", "src/new.go")
	if code != 0 || stdout != "code/go\tdocs/topics/code/go.md\n" || stderr != "" {
		t.Fatalf("migrated resolve = code %d, stdout %q, stderr %q", code, stdout, stderr)
	}
	for _, command := range []string{"render", "check", "init"} {
		if code, _, stderr := runCLI(t, root, command); code != 0 || stderr != "" {
			t.Fatalf("migrated %s = code %d, stderr %q", command, code, stderr)
		}
	}
	for path, want := range files {
		got, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(path)))
		if err != nil || !bytes.Equal(got, want) {
			t.Errorf("migrated %s changed: %q, %v", path, got, err)
		}
	}
}
