package main

import (
	"bytes"
	"errors"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestHelpExposesOnlyFinalCommands(t *testing.T) {
	code, stdout, stderr := runCLI(t, t.TempDir(), "--help")
	if code != 0 || stderr != "" {
		t.Fatalf("help = code %d, stderr %q", code, stderr)
	}
	for _, command := range []string{"init", "render", "check", "resolve", "effort", "adr", "plan", "version"} {
		if !strings.Contains(stdout, "  "+command) {
			t.Errorf("help missing %s:\n%s", command, stdout)
		}
	}
	for _, retired := range []string{"  audit ", "  upgrade ", "  uninstall ", "  changelog ", "  edit ", "  reset "} {
		if strings.Contains(stdout, retired) {
			t.Errorf("help contains retired command %q:\n%s", retired, stdout)
		}
	}

	code, stdout, stderr = runCLI(t, t.TempDir(), "effort", "--help")
	if code != 0 || stderr != "" {
		t.Fatalf("effort help = code %d, stderr %q", code, stderr)
	}
	for _, command := range []string{"new <slug>", "list", "show <slug>", "finish <slug>"} {
		if !strings.Contains(stdout, command) {
			t.Errorf("effort help missing %q", command)
		}
	}
	for _, retired := range []string{"integrate", "worktree"} {
		if strings.Contains(stdout, retired) {
			t.Errorf("effort help contains retired command %q", retired)
		}
	}
	for _, command := range []string{"adr", "plan"} {
		code, stdout, stderr = runCLI(t, t.TempDir(), command, "--help")
		if code != 0 || stderr != "" || !strings.Contains(stdout, "new <") {
			t.Errorf("%s help = code %d, stdout %q, stderr %q", command, code, stdout, stderr)
		}
	}
}

func TestInitRenderCheckRoundTripWithoutGit(t *testing.T) {
	root := t.TempDir()
	t.Setenv("PATH", t.TempDir())

	code, stdout, stderr := runCLI(t, root, "init")
	if code != 0 || stderr != "" || !strings.Contains(stdout, "rendered: AGENTS.md") {
		t.Fatalf("init = code %d, stdout %q, stderr %q", code, stdout, stderr)
	}
	if _, err := os.Stat(filepath.Join(root, ".git")); !errors.Is(err, fs.ErrNotExist) {
		t.Fatalf("init created Git state: %v", err)
	}

	code, stdout, stderr = runCLI(t, root, "check")
	if code != 0 || stdout != "check: ok\n" || stderr != "" {
		t.Fatalf("check = code %d, stdout %q, stderr %q", code, stdout, stderr)
	}
	code, stdout, stderr = runCLI(t, root, "render")
	if code != 0 || stdout != "render: up to date\n" || stderr != "" {
		t.Fatalf("repeat render = code %d, stdout %q, stderr %q", code, stdout, stderr)
	}
}

func TestRenderReportsAndCheckFailsUnmanagedMarker(t *testing.T) {
	root := t.TempDir()
	if code, _, stderr := runCLI(t, root, "init"); code != 0 {
		t.Fatal(stderr)
	}
	oldPath := filepath.Join(root, "old.md")
	if err := os.WriteFile(oldPath, []byte("<!-- GENERATED by awf: do not edit; change .awf/ and run `awf render` -->\nold\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	code, stdout, stderr := runCLI(t, root, "render")
	if code != 0 || stderr != "" || !strings.Contains(stdout, "unmanaged AWF-marked file: old.md") {
		t.Fatalf("render = code %d, stdout %q, stderr %q", code, stdout, stderr)
	}
	code, stdout, stderr = runCLI(t, root, "check")
	if code != 1 || stderr != "" || !strings.Contains(stdout, "old.md: unmanaged file still carries an AWF ownership marker") {
		t.Fatalf("check = code %d, stdout %q, stderr %q", code, stdout, stderr)
	}

	if err := os.WriteFile(oldPath, []byte("ordinary file\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	code, stdout, stderr = runCLI(t, root, "check")
	if code != 0 || stdout != "check: ok\n" || stderr != "" {
		t.Fatalf("check after ownership removal = code %d, stdout %q, stderr %q", code, stdout, stderr)
	}
}

func TestResolveAndEffortLifecycle(t *testing.T) {
	root := t.TempDir()
	if code, _, stderr := runCLI(t, root, "init"); code != 0 {
		t.Fatal(stderr)
	}
	code, stdout, stderr := runCLI(t, root, "resolve")
	if code != 0 || stdout != "none\n" || stderr != "" {
		t.Fatalf("resolve without globals = code %d, stdout %q, stderr %q", code, stdout, stderr)
	}
	topicPath := filepath.Join(root, ".awf", "topics", "code", "render.md")
	if err := os.MkdirAll(filepath.Dir(topicPath), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(topicPath, []byte("---\npaths: [internal/projector/**]\n---\n# Render\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	globalPath := filepath.Join(root, ".awf", "topics", "global.md")
	if err := os.WriteFile(globalPath, []byte("---\npaths: ['**']\n---\n# Global\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	code, stdout, stderr = runCLI(t, root, "resolve")
	if code != 0 || stdout != "global\t.awf/topics/global.md\n" || stderr != "" {
		t.Fatalf("resolve globals = code %d, stdout %q, stderr %q", code, stdout, stderr)
	}
	code, stdout, stderr = runCLI(t, root, "resolve", "internal/projector/new.go")
	if code != 0 || stdout != "code/render\t.awf/topics/code/render.md\nglobal\t.awf/topics/global.md\n" || stderr != "" {
		t.Fatalf("resolve = code %d, stdout %q, stderr %q", code, stdout, stderr)
	}
	if err := os.Remove(globalPath); err != nil {
		t.Fatal(err)
	}
	code, stdout, stderr = runCLI(t, root, "resolve", "README.md")
	if code != 0 || stdout != "none\n" || stderr != "" {
		t.Fatalf("resolve none = code %d, stdout %q, stderr %q", code, stdout, stderr)
	}

	code, stdout, stderr = runCLI(t, root, "effort", "new", "simple")
	if code != 0 || stdout != "memory: .awf/efforts/simple/memory.md\n" || stderr != "" {
		t.Fatalf("effort new = code %d, stdout %q, stderr %q", code, stdout, stderr)
	}
	code, stdout, stderr = runCLI(t, root, "plan", "new", "simple")
	if code != 0 || stdout != "plan: .awf/efforts/simple/plan.md\n" || stderr != "" {
		t.Fatalf("plan new = code %d, stdout %q, stderr %q", code, stdout, stderr)
	}
	code, stdout, stderr = runCLI(t, root, "adr", "new", "simple-choice")
	if code != 0 || stdout != "adr: docs/decisions/simple-choice.md\n" || stderr != "" {
		t.Fatalf("adr new = code %d, stdout %q, stderr %q", code, stdout, stderr)
	}
	artifacts := map[string][]byte{
		filepath.Join(".awf", "efforts", "simple", "plan.md"):  []byte("edited plan\n"),
		filepath.Join("docs", "decisions", "simple-choice.md"): []byte("edited adr\n"),
	}
	for relative, body := range artifacts {
		if err := os.WriteFile(filepath.Join(root, relative), body, 0o644); err != nil {
			t.Fatal(err)
		}
	}
	code, _, stderr = runCLI(t, root, "render")
	if code != 0 || stderr != "" {
		t.Fatalf("render with artifacts = code %d, stderr %q", code, stderr)
	}
	code, stdout, stderr = runCLI(t, root, "check")
	if code != 0 || stdout != "check: ok\n" || stderr != "" {
		t.Fatalf("check with artifacts = code %d, stdout %q, stderr %q", code, stdout, stderr)
	}
	for relative, want := range artifacts {
		got, err := os.ReadFile(filepath.Join(root, relative))
		if err != nil || !bytes.Equal(got, want) {
			t.Fatalf("artifact %s after render/check = %q, %v", relative, got, err)
		}
	}
	code, stdout, stderr = runCLI(t, root, "effort", "list")
	if code != 0 || stdout != "simple\n" || stderr != "" {
		t.Fatalf("effort list = code %d, stdout %q, stderr %q", code, stdout, stderr)
	}
	code, stdout, stderr = runCLI(t, root, "effort", "show", "simple")
	if code != 0 || stderr != "" || !strings.Contains(stdout, "# Effort: simple") {
		t.Fatalf("effort show = code %d, stdout %q, stderr %q", code, stdout, stderr)
	}
	code, stdout, stderr = runCLI(t, root, "effort", "finish", "simple")
	if code != 0 || stdout != "archive: .awf/effort-archive/simple\n" || stderr != "" {
		t.Fatalf("effort finish = code %d, stdout %q, stderr %q", code, stdout, stderr)
	}
}

func TestUsageAndOperationalFailuresUseStderr(t *testing.T) {
	code, stdout, stderr := runCLI(t, t.TempDir(), "unknown")
	if code != 2 || stdout != "" || !strings.Contains(stderr, "unknown command") {
		t.Fatalf("unknown = code %d, stdout %q, stderr %q", code, stdout, stderr)
	}
	code, stdout, stderr = runCLI(t, t.TempDir(), "check")
	if code != 1 || stdout != "" || !strings.Contains(stderr, ".awf/project.md") {
		t.Fatalf("check without source = code %d, stdout %q, stderr %q", code, stdout, stderr)
	}
}

func runCLI(t *testing.T, root string, arguments ...string) (int, string, string) {
	t.Helper()
	var stdout, stderr bytes.Buffer
	args := append([]string{"awf"}, arguments...)
	code := run(root, args, &stdout, &stderr)
	return code, stdout.String(), stderr.String()
}
