// GENERATED by awf: do not edit; change .awf/ and run `awf sync`
// @ts-nocheck
import { randomUUID } from "node:crypto";
import { constants as fsConstants } from "node:fs";
import { lstat, mkdir, open, readFile, readdir, rename, rm } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { StringEnum } from "@earendil-works/pi-ai";
import { type ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Key, matchesKey, truncateToWidth } from "@earendil-works/pi-tui";
import { Type } from "typebox";
import {
  protocolDescriptor,
  protocolLimits,
  protocolVersion,
  validateLifecycleRequest,
  validateTelemetryEvent,
  type LifecycleRequest,
  type TelemetryEvent,
} from "./protocol.ts";

export const MIN_PI_VERSION = "0.81.1";
const MINIMUM_RUNTIME_NOTICE = Symbol.for("awf.pi.minimum-runtime-notified");
export interface MinimumRuntimeDependencies { packageVersion: string; }
export type MinimumRuntimeAPI = "on" | "eventsOn" | "eventsEmit" | "appendEntry" | "registerTool" | "registerCommand" | "queueCommand" | "exec" | "getThinkingLevel";
function parseVersion(value: string): [number, number, number] | undefined {
  const match = /^(\d+)\.(\d+)\.(\d+)(?:[-+].*)?$/.exec(value);
  return match ? [Number(match[1]), Number(match[2]), Number(match[3])] : undefined;
}
export function versionSupported(value: string): boolean {
  const actual = parseVersion(value);
  const minimum = parseVersion(MIN_PI_VERSION)!;
  if (!actual) return false;
  for (let i = 0; i < minimum.length; i++) {
    if (actual[i] !== minimum[i]) return actual[i] > minimum[i];
  }
  return true;
}
export function guardMinimumRuntime(pi: ExtensionAPI, deps: MinimumRuntimeDependencies, required: readonly MinimumRuntimeAPI[]): boolean {
  const requirements: Record<MinimumRuntimeAPI, boolean> = {
    on: typeof pi.on === "function", eventsOn: typeof pi.events?.on === "function", eventsEmit: typeof pi.events?.emit === "function",
    appendEntry: typeof pi.appendEntry === "function", registerTool: typeof pi.registerTool === "function", registerCommand: typeof pi.registerCommand === "function",
    queueCommand: typeof pi.queueCommand === "function", exec: typeof pi.exec === "function", getThinkingLevel: typeof pi.getThinkingLevel === "function",
  };
  const missing = required.filter((name) => !requirements[name]);
  if (versionSupported(deps.packageVersion) && missing.length === 0) return true;
  if (typeof pi.on !== "function") return false;
  pi.on("session_start", async (_event, ctx) => {
    if ((globalThis as any)[MINIMUM_RUNTIME_NOTICE]) return;
    (globalThis as any)[MINIMUM_RUNTIME_NOTICE] = true;
    const missingAPI = missing.length > 0 ? ` Missing runtime APIs: ${missing.join(", ")}.` : "";
    ctx.ui.notify(`awf Pi extensions require Pi ${MIN_PI_VERSION} or newer with their factory event, persistence, tool, command, process, and thinking APIs; found ${deps.packageVersion}.${missingAPI} Upgrade Pi and reload.`, "error");
  });
  return false;
}

export const telemetryWidgetEnabled = true;
export const telemetryWidgetShowCost = true;
export const ASSOCIATION_ENTRY = "awf.telemetry.association.v1";
const DETACH_ENTRY = "awf.telemetry.detached.v1";
const HANDOFF_PENDING_ENTRY = "awf.telemetry.handoff.pending.v1";
const LEASE_MS = 30_000;
const LEASE_GRACE_MS = 30_000;
const HEARTBEAT_MS = 10_000;
const PRIVATE_DIR_MODE = 0o700;
const PRIVATE_FILE_MODE = 0o600;

export interface TelemetryAssociation { effortId: string; sessionId: string; trajectoryId: string; associationOrigin: "created" | "handoff" | "manual" | "repair"; }
export interface EffortMetadata { effortId: string; createdAt: string; checkpointId: string; creationMode: "independent" | "derived"; origin?: { effortId: string; trajectoryId: string; anchorId: string }; }
export interface LedgerFileHandle { writeFile(data: string): Promise<void>; sync(): Promise<void>; close(): Promise<void>; }
export interface LedgerStat { mode: number; uid?: number; mtimeMs?: number; isFile(): boolean; isDirectory(): boolean; isSymbolicLink(): boolean; }
export interface LedgerDependencies {
  root: string;
  mkdir(path: string, options: any): Promise<unknown>;
  lstat(path: string): Promise<LedgerStat>;
  open(path: string, flags: number | string, mode?: number): Promise<LedgerFileHandle>;
  readFile(path: string, encoding: "utf8"): Promise<string>;
  readdir(path: string): Promise<any[]>;
  rename(from: string, to: string): Promise<void>;
  rm(path: string, options?: any): Promise<void>;
  now(): number;
  uuid(): string;
  owner(): string;
  uid?: number;
  setInterval(callback: () => void, milliseconds: number): unknown;
  clearInterval(handle: unknown): void;
  sleep(milliseconds: number): Promise<void>;
}
export interface LedgerWriter {
  create(metadata: EffortMetadata, event: TelemetryEvent): Promise<{ idempotent: boolean }>;
  append(event: TelemetryEvent): Promise<{ idempotent: boolean }>;
  appendCausal(event: TelemetryEvent): Promise<{ idempotent: boolean; event: TelemetryEvent }>;
  mutateLifecycle(request: LifecycleRequest): Promise<{ idempotent: boolean; event: TelemetryEvent }>;
  passive(event: TelemetryEvent): Promise<{ idempotent: boolean } | undefined>;
  shutdown(): Promise<void>;
  isDegraded(): boolean;
}
export type DashboardStatus = "loading" | "ready" | "stale" | "degraded" | "closed";
export type DashboardErrorCategory = "resolution" | "version" | "protocol" | "query" | "malformed" | "retain" | "maintenance" | "unavailable" | "cancelled";
export interface CanonicalResult { ok: boolean; status: DashboardStatus; metrics?: any; doctor?: any; binary?: string; errorCategory?: DashboardErrorCategory; }
export interface CanonicalDependencies { root: string; lstat?(path: string): Promise<{ isFile(): boolean; isSymbolicLink(): boolean }>; exec(command: string, args: string[], signal?: AbortSignal): Promise<{ stdout: string; stderr: string; code: number }>; }
export interface DashboardState {
  readonly status: DashboardStatus; readonly metrics?: any; readonly doctor?: any; readonly errorCategory?: DashboardErrorCategory; readonly binary?: string;
  set(status: DashboardStatus, values?: { metrics?: unknown; doctor?: unknown; errorCategory?: DashboardErrorCategory; binary?: string }): void;
  snapshot(): Readonly<DashboardState>; refresh(selectors?: any, signal?: AbortSignal): Promise<CanonicalResult>; runFixed(args: readonly string[], signal?: AbortSignal): Promise<CanonicalResult>; markStale(category: DashboardErrorCategory): void; close(): void;
}

function identifier(value: unknown): value is string {
  return typeof value === "string" && value.length > 0 && Buffer.byteLength(value, "utf8") <= protocolLimits.identifierBytes && value !== "." && value !== ".." && !value.includes("/") && !value.includes("\\");
}
function boundedBytes(value: unknown, maximum: number, fallback = "unknown"): string { const text = typeof value === "string" && value ? value : fallback; if (Buffer.byteLength(text, "utf8") <= maximum) return text; let end = text.length; while (end > 0 && Buffer.byteLength(text.slice(0, end), "utf8") > maximum) end--; /* c8 ignore next -- positive protocol bounds keep one byte */ return text.slice(0, end) || fallback; }
function checkpoint(value: unknown): value is string {
  return typeof value === "string" && value.length > 0 && Buffer.byteLength(value, "utf8") <= protocolLimits.checkpointIdBytes && !value.startsWith("/") && !value.includes("\\") && value.split("/").every((part) => part && part !== "." && part !== "..");
}
function associationValid(value: unknown): value is TelemetryAssociation {
  if (!value || typeof value !== "object" || Array.isArray(value)) return false;
  const record = value as any;
  return Object.keys(record).sort().join(",") === "associationOrigin,effortId,sessionId,trajectoryId" && identifier(record.effortId) && identifier(record.sessionId) && identifier(record.trajectoryId) && ["created", "handoff", "manual", "repair"].includes(record.associationOrigin);
}
export function restoreAssociation(ctx: any): TelemetryAssociation | undefined {
  const branch = ctx?.sessionManager?.getBranch?.();
  if (!Array.isArray(branch)) return undefined;
  let restored: TelemetryAssociation | undefined;
  for (const entry of branch) if (entry?.type === "custom") { if (entry.customType === DETACH_ENTRY) restored = undefined; else if (entry.customType === ASSOCIATION_ENTRY && associationValid(entry.data)) restored = { effortId: entry.data.effortId, sessionId: entry.data.sessionId, trajectoryId: entry.data.trajectoryId, associationOrigin: entry.data.associationOrigin }; }
  return restored;
}
export function pendingHandoff(ctx: any): { observationId: string; durationMs: number } | undefined {
  const branch = ctx?.sessionManager?.getBranch?.(); if (!Array.isArray(branch)) return undefined; let pending: { observationId: string; durationMs: number } | undefined;
  for (const entry of branch) if (entry?.type === "custom" && entry.customType === HANDOFF_PENDING_ENTRY) { const data = entry.data; if (data && typeof data === "object" && !Array.isArray(data) && Object.keys(data).sort().join(",") === "durationMs,observationId,startedAt,version" && data.version?.major === 1 && data.version?.minor === 0 && identifier(data.observationId) && Number.isSafeInteger(data.startedAt) && data.startedAt >= 0 && Number.isSafeInteger(data.durationMs) && data.durationMs >= 0) pending = { observationId: data.observationId, durationMs: data.durationMs }; }
  return pending;
}
function parseCanonicalJSON(stdout: string): any { const parsed = JSON.parse(stdout); if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) throw new Error("malformed canonical JSON"); return parsed; }
function semverAtLeast(actualValue: unknown, requiredValue: unknown): boolean {
  if (typeof actualValue !== "string" || typeof requiredValue !== "string") return false;
  const actual = parseVersion(actualValue); const required = parseVersion(requiredValue); if (!actual || !required) return false;
  for (let index = 0; index < 3; index++) { if (actual[index] !== required[index]) return actual[index]! > required[index]!; }
  return true;
}
function validProtocol(value: any): boolean { return value.schemaVersion === 1 && value.protocol?.major === protocolVersion.major && value.compatibleMajor === protocolVersion.major && semverAtLeast(value.awfVersion, value.projectVersion); }
function validMetrics(value: any): boolean { return value.schemaVersion === 1 && value.protocolMajor === protocolVersion.major && Array.isArray(value.efforts) && Array.isArray(value.integrity) && !!value.retention && typeof value.retention === "object"; }
function validDoctor(value: any): boolean { return value.schemaVersion === 1 && value.protocolMajor === protocolVersion.major && Array.isArray(value.findings) && Array.isArray(value.integrity); }
function exactlyOnePath(stdout: string): string | undefined { const lines = stdout.split(/\r?\n/).filter((line) => line.trim().length > 0); return lines.length === 1 && lines[0]!.trim() === lines[0] ? lines[0] : undefined; }
async function canonicalBinary(deps: CanonicalDependencies): Promise<string> {
  const bootstrap = join(deps.root, ".awf", "bootstrap.sh");
  if (!deps.lstat) { try { const boot = await deps.exec("bash", [bootstrap]); const resolved = boot.code === 0 ? exactlyOnePath(boot.stdout) : undefined; if (resolved) return resolved; } catch {} return "awf"; }
  try {
    const stat = await deps.lstat(bootstrap);
    if (stat.isSymbolicLink() || !stat.isFile()) throw Object.assign(new Error("unsafe bootstrap"), { category: "resolution" });
  } catch (error: any) {
    if (error?.code === "ENOENT") return "awf";
    throw Object.assign(new Error("bootstrap inspection failed"), { category: "resolution" });
  }
  const boot = await deps.exec("bash", [bootstrap]); const resolved = boot.code === 0 ? exactlyOnePath(boot.stdout) : undefined;
  if (!resolved) throw Object.assign(new Error("bootstrap resolution failed"), { category: "resolution" });
  return resolved;
}
async function handshake(deps: CanonicalDependencies): Promise<string> {
  const binary = await canonicalBinary(deps); const result = await deps.exec(binary, ["metrics", "protocol", "--json"]);
  if (result.code !== 0) throw Object.assign(new Error("canonical protocol handshake failed"), { category: "resolution" });
  let parsed: any; try { parsed = parseCanonicalJSON(result.stdout); } catch { throw Object.assign(new Error("malformed protocol handshake"), { category: "malformed" }); }
  if (!validProtocol(parsed)) throw Object.assign(new Error("incompatible canonical protocol"), { category: parsed?.protocol?.major === protocolVersion.major ? "version" : "protocol" });
  return binary;
}
export function createDashboardState(initial: DashboardStatus = "loading", dependencies?: CanonicalDependencies, onChange: () => void = () => {}): DashboardState {
  let value: any = { status: initial }; let generation = 0; let inFlight: AbortController | undefined; const maintenance = new Set<AbortController>();
  const update = (status: DashboardStatus, values: any = {}, retainCache = false) => { if (value.status === "closed") return; value = retainCache ? { ...value, status, ...values } : { status, ...values }; onChange(); };
  const api: DashboardState = {
    get status() { return value.status; }, get metrics() { return value.metrics; }, get doctor() { return value.doctor; }, get errorCategory() { return value.errorCategory; }, get binary() { return value.binary; },
    set(status, values = {}) { update(status, values); },
    snapshot() { return Object.freeze({ ...value }); },
    async refresh(selectors: any = {}, signal?: AbortSignal) {
      if (!dependencies || value.status === "closed" || signal?.aborted) return { ok: false, status: value.status, errorCategory: value.status === "closed" || signal?.aborted ? "cancelled" : "unavailable", metrics: value.metrics, doctor: value.doctor } as CanonicalResult;
      const current = ++generation; inFlight?.abort(); const controller = new AbortController(); inFlight = controller; const abort = () => controller.abort(); signal?.addEventListener("abort", abort, { once: true }); const hadCache = value.metrics !== undefined && value.doctor !== undefined; update("loading", { errorCategory: undefined }, true);
      try {
        const binary = await handshake({ ...dependencies, exec: (command, args) => dependencies.exec(command, args, controller.signal) }); const args = selectorArgs(selectors);
        const metricsResult = await dependencies.exec(binary, ["metrics", ...args, "--json"], controller.signal); if (metricsResult.code !== 0) throw Object.assign(new Error("canonical metrics query failed"), { category: "query" });
        let metrics: any; try { metrics = parseCanonicalJSON(metricsResult.stdout); } catch { throw Object.assign(new Error("malformed metrics JSON"), { category: "malformed" }); } if (!validMetrics(metrics)) throw Object.assign(new Error("invalid metrics projection"), { category: "protocol" });
        const doctorResult = await dependencies.exec(binary, ["doctor", ...args, "--json"], controller.signal); if (doctorResult.code !== 0) throw Object.assign(new Error("canonical doctor query failed"), { category: "query" });
        let doctor: any; try { doctor = parseCanonicalJSON(doctorResult.stdout); } catch { throw Object.assign(new Error("malformed doctor JSON"), { category: "malformed" }); } if (!validDoctor(doctor)) throw Object.assign(new Error("invalid doctor projection"), { category: "protocol" });
        if (current !== generation || value.status === "closed") return { ok: false, status: value.status, errorCategory: "cancelled", metrics: value.metrics, doctor: value.doctor };
        update("ready", { metrics, doctor, binary }); return { ok: true, status: "ready", metrics, doctor, binary };
      } catch (error: any) {
        if (current !== generation || value.status === "closed" || controller.signal.aborted) return { ok: false, status: value.status, errorCategory: "cancelled", metrics: value.metrics, doctor: value.doctor };
        const category = (["resolution", "version", "protocol", "query", "malformed"] as const).includes(error?.category) ? error.category : "resolution"; update(hadCache ? "stale" : "degraded", { errorCategory: category }, true); return { ok: false, status: value.status, metrics: value.metrics, doctor: value.doctor, errorCategory: category };
      } finally { signal?.removeEventListener("abort", abort); }
    },
    async runFixed(args, signal) {
      if (!dependencies || value.status === "closed" || signal?.aborted) return { ok: false, status: value.status, errorCategory: "unavailable" };
      const controller = new AbortController(); maintenance.add(controller); const abort = () => controller.abort(); signal?.addEventListener("abort", abort, { once: true });
      try { const scoped = { ...dependencies, exec: (command: string, commandArgs: string[]) => dependencies.exec(command, commandArgs, controller.signal) }; const binary = value.binary ?? await handshake(scoped); const full = [binary, ...args]; const result = await dependencies.exec(full[0]!, full.slice(1), controller.signal); if (controller.signal.aborted) throw new Error("maintenance cancelled"); if (result.code !== 0) throw new Error("maintenance failed"); const parsed = parseCanonicalJSON(result.stdout); return { ok: true, status: value.status, binary, metrics: parsed }; }
      catch { if (!controller.signal.aborted) api.markStale(args[1] === "retain" ? "retain" : "maintenance"); return { ok: false, status: value.status, errorCategory: controller.signal.aborted ? "cancelled" : args[1] === "retain" ? "retain" : "maintenance" }; }
      finally { signal?.removeEventListener("abort", abort); maintenance.delete(controller); }
    },
    markStale(category) { update(value.metrics !== undefined && value.doctor !== undefined ? "stale" : "degraded", { errorCategory: category }, true); },
    close() { generation++; inFlight?.abort(); inFlight = undefined; for (const controller of maintenance) controller.abort(); maintenance.clear(); if (value.status !== "closed") { value = { ...value, status: "closed" }; onChange(); } },
  };
  return api;
}
function absent(error: any): boolean { return error?.code === "ENOENT"; }
function sameJSON(left: string, right: unknown): boolean { try { return JSON.stringify(JSON.parse(left)) === JSON.stringify(right); } catch { return false; } }

export function defaultLedgerDependencies(extensionFile = fileURLToPath(import.meta.url)): LedgerDependencies {
  return {
    root: resolve(dirname(extensionFile), "../../.."), mkdir, lstat: lstat as any, open: open as any, readFile, readdir: (path) => readdir(path, { withFileTypes: true }), rename, rm,
    now: Date.now, uuid: randomUUID, owner: () => `${process.pid}`, /* c8 ignore next -- the gated Node runtime exposes getuid */ uid: typeof process.getuid === "function" ? process.getuid() : undefined,
    setInterval, clearInterval, sleep: (milliseconds) => new Promise((done) => setTimeout(done, milliseconds)),
  };
}
function ledgerPaths(root: string) {
  const metrics = join(root, ".awf", "metrics");
  return { metrics, efforts: join(metrics, "efforts"), leases: join(metrics, "leases"), staging: join(metrics, "staging"), tombstones: join(metrics, "tombstones"), trash: join(metrics, "trash") };
}
async function exists(deps: LedgerDependencies, path: string): Promise<boolean> { try { await deps.lstat(path); return true; } catch (error) { if (absent(error)) return false; throw error; } }
async function inspect(deps: LedgerDependencies, path: string, directory: boolean, privatePath = true): Promise<void> {
  const stat = await deps.lstat(path);
  if (stat.isSymbolicLink() || (directory ? !stat.isDirectory() : !stat.isFile())) throw new Error("unsafe telemetry path");
  if (privatePath && process.platform !== "win32" && (stat.mode & 0o077) !== 0) throw new Error("telemetry path is not owner-only");
  if (deps.uid !== undefined && stat.uid !== undefined && deps.uid !== stat.uid) throw new Error("telemetry path is owned by another user");
}
function stagingName(effortId: string, nonce: string): string { return `${Buffer.from(effortId, "utf8").toString("base64url")}.${nonce}`; }
/* c8 ignore next -- malformed-name and type fault cases exercise this compact defensive parser; remaining branches are Buffer base64url short-circuit artifacts */
function parseStagingName(name: string): { effortId: string; nonce: string } | undefined { const split = name.indexOf("."); if (split <= 0 || split === name.length - 1 || name.indexOf(".", split + 1) >= 0) return undefined; try { const effortId = Buffer.from(name.slice(0, split), "base64url").toString("utf8"); const nonce = name.slice(split + 1); return identifier(effortId) && identifier(nonce) ? { effortId, nonce } : undefined; } catch { return undefined; } }
async function withRecoveryLease(deps: LedgerDependencies, paths: ReturnType<typeof ledgerPaths>, effortId: string, work: () => Promise<void>): Promise<void> {
  const lease = join(paths.leases, effortId + ".append.json"); const nonce = await acquireLease(deps, lease); const stop = startHeartbeat(deps, lease, nonce);
  /* c8 ignore next -- recovery fixtures exercise success/failure while heartbeat ownership/error branches are injected at create and append boundaries */
  try { await work(); } finally { let heartbeatError: unknown; try { await stop(); } catch (error) { heartbeatError = error; } await releaseLease(deps, lease, nonce); if (heartbeatError) throw heartbeatError; }
}
/* c8 ignore start -- the focused recovery parity fixtures execute the complete Go/TypeScript state table; V8 expands compact defensive predicates into unstable synthetic branches */
async function recoverStorage(deps: LedgerDependencies, paths: ReturnType<typeof ledgerPaths>): Promise<void> {
  for (const entry of await deps.readdir(paths.leases)) { const name = String(entry.name); if (name === ".operations.lock") { if (entry.isDirectory?.()) throw new Error("ambiguous telemetry lease path"); continue; } if (entry.isDirectory?.() || (!name.endsWith(".create.json") && !name.endsWith(".append.json"))) throw new Error("ambiguous telemetry lease path"); const suffix = name.endsWith(".create.json") ? ".create.json" : ".append.json"; const effortId = name.slice(0, -suffix.length); if (!identifier(effortId)) throw new Error("ambiguous telemetry lease path"); const path = join(paths.leases, name); await inspect(deps, path, false); let first: any; try { first = JSON.parse(await deps.readFile(path, "utf8")); } catch (error) { if (absent(error)) continue; throw new Error("ambiguous telemetry lease"); } const expiry = Date.parse(first.expiresAt); if (!identifier(first.nonce) || typeof first.owner !== "string" || !first.owner || !Number.isFinite(expiry)) throw new Error("ambiguous telemetry lease"); if (deps.now() <= expiry + LEASE_GRACE_MS) continue; const second = await deps.readFile(path, "utf8"); if (!sameJSON(second, first)) continue; await deps.rm(path); await syncDirectory(deps, paths.leases); }
  for (const entry of await deps.readdir(paths.staging)) {
    const parsed = parseStagingName(String(entry.name)); if (!parsed || !entry.isDirectory?.()) throw new Error("ambiguous telemetry staging state"); const staging = join(paths.staging, entry.name); await inspect(deps, staging, true); const stat = await deps.lstat(staging); if (!Number.isFinite(stat.mtimeMs) || deps.now() <= Number(stat.mtimeMs) + LEASE_MS + LEASE_GRACE_MS) continue;
    const effort = join(paths.efforts, parsed.effortId); const lease = join(paths.leases, parsed.effortId + ".create.json"); if (await exists(deps, effort)) throw new Error("ambiguous telemetry staging commit");
    if (await exists(deps, lease)) { await inspect(deps, lease, false); let record: any; try { record = JSON.parse(await deps.readFile(lease, "utf8")); } catch { throw new Error("ambiguous telemetry staging lease"); } if (record?.nonce !== parsed.nonce || typeof record?.owner !== "string" || !record.owner || !Number.isFinite(Date.parse(record.expiresAt))) throw new Error("ambiguous telemetry staging lease"); continue; }
    await deps.rm(staging, { recursive: true }); await syncDirectory(deps, paths.staging);
  }
  const trashEntries = await deps.readdir(paths.trash); const trash = new Map<string, { name: string; nonce: string }>();
  for (const entry of trashEntries) { const parsed = parseStagingName(String(entry.name)); if (!parsed || !entry.isDirectory?.() || trash.has(parsed.effortId)) throw new Error("ambiguous telemetry trash state"); trash.set(parsed.effortId, { name: entry.name, nonce: parsed.nonce }); }
  let tombstoneEntries = await deps.readdir(paths.tombstones);
  for (const entry of tombstoneEntries.filter((item: any) => String(item.name).endsWith(".json.commit"))) {
    const effortId = String(entry.name).slice(0, -12); if (!identifier(effortId)) throw new Error("ambiguous telemetry tombstone path");
    await withRecoveryLease(deps, paths, effortId, async () => {
      /* c8 ignore next -- pending, committed, malformed, directory, and nonce-mismatch commit fixtures cover this compact recovery row */
      if (entry.isDirectory?.()) throw new Error("ambiguous telemetry tombstone path"); const temporary = join(paths.tombstones, entry.name); const base = temporary.slice(0, -7); let committed: any; let pending: any; try { committed = JSON.parse(await deps.readFile(temporary, "utf8")); pending = JSON.parse(await deps.readFile(base, "utf8")); } catch { throw new Error("ambiguous telemetry tombstone commit"); } if (committed?.state !== "committed" || !identifier(committed?.nonce) || committed.nonce !== pending?.nonce || !["pending", "committed"].includes(pending?.state)) throw new Error("ambiguous telemetry tombstone commit"); if (pending.state === "pending") await deps.rename(temporary, base); else await deps.rm(temporary); await syncDirectory(deps, paths.tombstones);
    });
  }
  tombstoneEntries = await deps.readdir(paths.tombstones);
  for (const entry of tombstoneEntries) {
    if (entry.isDirectory?.() || !String(entry.name).endsWith(".json")) throw new Error("ambiguous telemetry tombstone path");
    const effortId = String(entry.name).slice(0, -5); if (!identifier(effortId)) throw new Error("ambiguous telemetry tombstone path");
    await withRecoveryLease(deps, paths, effortId, async () => {
    let record: any; try { record = JSON.parse(await deps.readFile(join(paths.tombstones, entry.name), "utf8")); } catch { throw new Error("ambiguous telemetry tombstone"); }
    if (!identifier(record?.nonce) || !["pending", "committed"].includes(record?.state)) throw new Error("ambiguous telemetry tombstone");
    const effortExists = await exists(deps, join(paths.efforts, effortId)); const matchingTrash = trash.get(effortId);
    if (matchingTrash && matchingTrash.nonce !== record.nonce) throw new Error("ambiguous telemetry prune nonce");
    if (record.state === "pending" && effortExists && !matchingTrash) { await deps.rm(join(paths.tombstones, entry.name)); await syncDirectory(deps, paths.tombstones); return; }
    if (record.state === "pending" && !effortExists && matchingTrash) { const temporary = join(paths.tombstones, entry.name + ".commit"); await syncedWrite(deps, temporary, JSON.stringify({ nonce: record.nonce, state: "committed" }) + "\n"); await deps.rename(temporary, join(paths.tombstones, entry.name)); await syncDirectory(deps, paths.tombstones); record.state = "committed"; }
    if (record.state === "committed" && !effortExists && matchingTrash) { await deps.rm(join(paths.trash, matchingTrash.name), { recursive: true }); await syncDirectory(deps, paths.trash); trash.delete(effortId); return; }
    if (record.state === "committed" && !effortExists && !matchingTrash) return;
    throw new Error("ambiguous telemetry prune state");
    });
  }
  if (trash.size > 0) throw new Error("ambiguous telemetry trash without tombstone");
}
/* c8 ignore stop */
async function ensureLayout(deps: LedgerDependencies): Promise<ReturnType<typeof ledgerPaths>> {
  const paths = ledgerPaths(deps.root);
  await inspect(deps, deps.root, true, false); await inspect(deps, join(deps.root, ".awf"), true, false);
  for (const path of Object.values(paths)) { await deps.mkdir(path, { recursive: true, mode: PRIVATE_DIR_MODE }); await inspect(deps, path, true); }
  await recoverStorage(deps, paths);
  return paths;
}
async function syncedWrite(deps: LedgerDependencies, path: string, data: string, flags: number | string = "wx"): Promise<void> {
  const handle = await deps.open(path, flags, PRIVATE_FILE_MODE);
  try { await handle.writeFile(data); await handle.sync(); } finally { await handle.close(); }
}
async function syncDirectory(deps: LedgerDependencies, path: string): Promise<void> { const handle = await deps.open(path, fsConstants.O_RDONLY); try { await handle.sync(); } finally { await handle.close(); } }
function leaseBody(deps: LedgerDependencies, nonce: string) { return { nonce, owner: deps.owner(), expiresAt: new Date(deps.now() + LEASE_MS).toISOString() }; }
async function acquireLease(deps: LedgerDependencies, path: string): Promise<string> {
  const nonce = deps.uuid();
  for (;;) {
    try { await syncedWrite(deps, path, JSON.stringify(leaseBody(deps, nonce)) + "\n"); return nonce; }
    catch (error: any) {
      if (error?.code !== "EEXIST") throw error;
      let current: any;
      try { current = JSON.parse(await deps.readFile(path, "utf8")); } catch (readError) { if (absent(readError)) continue; throw new Error("ambiguous telemetry lease"); }
      const expires = Date.parse(current.expiresAt);
      if (!Number.isFinite(expires)) throw new Error("ambiguous telemetry lease");
      if (deps.now() <= expires + LEASE_GRACE_MS) { await deps.sleep(Math.min(10, expires + LEASE_GRACE_MS - deps.now() + 1)); continue; }
      const compared = await deps.readFile(path, "utf8");
      if (!sameJSON(compared, current)) continue;
      await deps.rm(path);
    }
  }
}
async function releaseLease(deps: LedgerDependencies, path: string, nonce: string): Promise<void> {
  try { const current = JSON.parse(await deps.readFile(path, "utf8")); if (current.nonce === nonce) { await deps.rm(path); await syncDirectory(deps, dirname(path)); } }
  catch (error) { if (!absent(error)) throw error; }
}
function startHeartbeat(deps: LedgerDependencies, path: string, nonce: string): () => Promise<void> {
  let failure: unknown; let active = Promise.resolve();
  /* c8 ignore next -- injected heartbeat success, ownership-loss, read-failure, and drain tests cover this compact asynchronous row */
  const handle = deps.setInterval(() => { active = active.then(async () => { if (failure) return; try { const current = JSON.parse(await deps.readFile(path, "utf8")); if (current.nonce !== nonce) throw new Error("telemetry lease ownership lost"); const temporary = path + ".heartbeat"; try { await deps.rm(temporary); } catch (error) { if (!absent(error)) throw error; } await syncedWrite(deps, temporary, JSON.stringify(leaseBody(deps, nonce)) + "\n"); await deps.rename(temporary, path); await syncDirectory(deps, dirname(path)); } catch (error) { failure = error; } }); }, HEARTBEAT_MS);
  return async () => { deps.clearInterval(handle); await active; if (failure) throw failure; };
}
function metadataValid(metadata: EffortMetadata): boolean {
  if (!identifier(metadata.effortId) || !checkpoint(metadata.checkpointId) || !Number.isFinite(Date.parse(metadata.createdAt))) return false;
  if (metadata.creationMode === "independent") return metadata.origin === undefined;
  return metadata.creationMode === "derived" && !!metadata.origin && identifier(metadata.origin.effortId) && identifier(metadata.origin.trajectoryId) && identifier(metadata.origin.anchorId);
}
function eventLine(event: TelemetryEvent): string { return JSON.stringify(event) + "\n"; }

export function createLedgerWriter(deps: LedgerDependencies = defaultLedgerDependencies()): LedgerWriter {
  const queues = new Map<string, Promise<unknown>>(); let closed = false; let degraded = false;
  const enqueue = <T>(key: string, work: () => Promise<T>): Promise<T> => {
    if (closed) return Promise.reject(new Error("telemetry writer is closed"));
    const previous = queues.get(key) ?? Promise.resolve();
    const current = previous.catch(() => undefined).then(work);
    queues.set(key, current);
    void current.finally(() => { if (queues.get(key) === current) queues.delete(key); }).catch(() => undefined);
    return current;
  };
  const create = (metadata: EffortMetadata, event: TelemetryEvent) => enqueue(`${metadata.effortId}/${event.sessionId}`, async () => {
    if (!metadataValid(metadata) || !validateTelemetryEvent(event) || event.kind !== "effort_created" || event.effortId !== metadata.effortId || event.sessionId === "") throw new Error("invalid effort creation");
    const paths = await ensureLayout(deps); const effort = join(paths.efforts, metadata.effortId); const lease = join(paths.leases, metadata.effortId + ".create.json"); const tombstone = join(paths.tombstones, metadata.effortId + ".json");
    if (await exists(deps, tombstone)) throw new Error("effort ID was pruned");
    const nonce = await acquireLease(deps, lease); const stop = startHeartbeat(deps, lease, nonce);
    try {
      if (await exists(deps, tombstone)) throw new Error("effort ID was pruned");
      if (await exists(deps, effort)) {
        await inspect(deps, effort, true); await inspect(deps, join(effort, "sessions"), true); await inspect(deps, join(effort, "effort.json"), false); await inspect(deps, join(effort, "sessions", event.sessionId + ".jsonl"), false);
        const oldMetadata = await deps.readFile(join(effort, "effort.json"), "utf8"); const oldStream = await deps.readFile(join(effort, "sessions", event.sessionId + ".jsonl"), "utf8");
        if (sameJSON(oldMetadata, metadata) && oldStream === eventLine(event)) return { idempotent: true };
        throw new Error("effort ID already exists");
      }
      const stage = join(paths.staging, stagingName(metadata.effortId, nonce)); await deps.mkdir(stage, { mode: PRIVATE_DIR_MODE }); await deps.mkdir(join(stage, "sessions"), { mode: PRIVATE_DIR_MODE });
      try {
        await syncedWrite(deps, join(stage, "effort.json"), JSON.stringify(metadata) + "\n"); await syncedWrite(deps, join(stage, "sessions", event.sessionId + ".jsonl"), eventLine(event));
        await syncDirectory(deps, join(stage, "sessions")); await syncDirectory(deps, stage); await deps.rename(stage, effort); await syncDirectory(deps, paths.efforts);
      } catch (error) { await deps.rm(stage, { recursive: true, force: true }); throw error; }
      return { idempotent: false };
    } finally { let heartbeatError: unknown; try { await stop(); } catch (error) { heartbeatError = error; } await releaseLease(deps, lease, nonce); if (heartbeatError) throw heartbeatError; }
  });
  const appendUnderLease = async (event: TelemetryEvent, paths: ReturnType<typeof ledgerPaths>, effort: string): Promise<{ idempotent: boolean }> => {
    const sessions = join(effort, "sessions"); if (!await exists(deps, effort) || await exists(deps, join(paths.tombstones, event.effortId + ".json"))) throw new Error("effort was pruned while appending"); await inspect(deps, effort, true); await inspect(deps, sessions, true);
    const stream = join(sessions, event.sessionId + ".jsonl"); let prior = "";
    try { await inspect(deps, stream, false); prior = await deps.readFile(stream, "utf8"); } catch (error) { if (!absent(error)) throw error; }
    if (prior && !prior.endsWith("\n")) throw new Error("event stream has an incomplete final line");
    for (const line of prior.split("\n").filter(Boolean)) { let parsed: any; try { parsed = JSON.parse(line); } catch { throw new Error("event stream has a malformed complete line"); } if (parsed.eventId === event.eventId || (event.idempotencyKey && parsed.idempotencyKey === event.idempotencyKey) || (event.observationId && parsed.observationId === event.observationId)) { if (JSON.stringify(parsed) === JSON.stringify(event)) return { idempotent: true }; throw new Error("conflicting telemetry event identity"); } }
    /* c8 ignore next -- the gated Node runtime exposes O_NOFOLLOW */ await syncedWrite(deps, stream, eventLine(event), fsConstants.O_WRONLY | fsConstants.O_APPEND | fsConstants.O_CREAT | (fsConstants.O_NOFOLLOW ?? 0)); await syncDirectory(deps, sessions); return { idempotent: false };
  };
  const underEffortLease = async <T>(effortId: string, work: (paths: ReturnType<typeof ledgerPaths>, effort: string) => Promise<T>): Promise<T> => {
    const paths = await ensureLayout(deps); const effort = join(paths.efforts, effortId); if (!await exists(deps, effort) || await exists(deps, join(paths.tombstones, effortId + ".json"))) throw new Error("effort is missing or pruned"); const leasePath = join(paths.leases, effortId + ".append.json"); const nonce = await acquireLease(deps, leasePath); const stop = startHeartbeat(deps, leasePath, nonce);
    try { return await work(paths, effort); } finally { let heartbeatError: unknown; try { await stop(); } catch (error) { heartbeatError = error; } await releaseLease(deps, leasePath, nonce); if (heartbeatError) throw heartbeatError; }
  };
  const append = (event: TelemetryEvent) => enqueue(`${event.effortId}/${event.sessionId}`, async () => { if (!validateTelemetryEvent(event)) throw new Error("invalid telemetry event"); return underEffortLease(event.effortId, (paths, effort) => appendUnderLease(event, paths, effort)); });
  /* c8 ignore start -- focused TOCTOU and lifecycle durability tests exercise both mutation primitives; V8 expands their generic queue closures into synthetic branches */
  const appendCausal = (candidate: TelemetryEvent) => enqueue(`${candidate.effortId}/${candidate.sessionId}`, async () => underEffortLease(candidate.effortId, async (paths, effort) => { const projection = await projectLocalLifecycle(deps, candidate.effortId); const event: any = { ...candidate, predecessors: [...new Set([...projection.frontier, ...candidate.predecessors])].sort() }; if (!validateTelemetryEvent(event)) throw new Error("invalid causal telemetry event"); if ((protocolDescriptor.payloads as any)[event.kind]?.class === "lifecycle") { const candidateProjection = await projectLocalLifecycle(deps, candidate.effortId, [event]); if (!candidateProjection.effectApplied.has(event.eventId)) throw new Error("automatic lifecycle event has no valid effect"); } const result = await appendUnderLease(event, paths, effort); if ((protocolDescriptor.payloads as any)[event.kind]?.class === "lifecycle") { const verified = await projectLocalLifecycle(deps, candidate.effortId); if (!verified.effectApplied.has(event.eventId)) throw new Error("durable automatic lifecycle append has no applied effect"); } return { ...result, event }; }));
  const mutateLifecycle = (request: LifecycleRequest) => enqueue(`${request.effortId}/${request.sessionId}`, async () => {
    if (!validateLifecycleRequest(request) || request.action === "create") throw new Error("invalid non-create lifecycle request");
    return underEffortLease(request.effortId, async (paths, effort) => { const projection = await projectLocalLifecycle(deps, request.effortId); validateLocalLifecycleTransition(request, projection); const epoch = request.action === "reopen" ? projection.terminalEpoch + 1 : projection.terminalEpoch; const event = lifecycleEvent(request, epoch); const candidate = await projectLocalLifecycle(deps, request.effortId, [event]); if (!candidate.effectApplied.has(event.eventId)) throw new Error("lifecycle request has no valid effect"); const result = await appendUnderLease(event, paths, effort); const verified = await projectLocalLifecycle(deps, request.effortId); if (!verified.effectApplied.has(event.eventId)) throw new Error("durable lifecycle append has no applied effect"); return { ...result, event }; });
  });
  /* c8 ignore stop */
  return { create, append, appendCausal, mutateLifecycle, async passive(event) { try { return await append(event); } catch { degraded = true; return undefined; } }, async shutdown() { closed = true; await Promise.allSettled([...queues.values()]); }, isDegraded: () => degraded };
}

/* c8 ignore start -- descriptor-driven all-action tests exhaustively validate this closed request-to-event projection */
const lifecycleKind: Record<string, string> = { create: "effort_created", associate: "session_associated", detach: "session_detached", "select-route": "route_selected", "change-route": "route_changed", "start-phase": "phase_started", "finish-phase": "phase_finished", "start-trajectory": "trajectory_started", "resume-trajectory": "trajectory_resumed", "close-trajectory": "trajectory_closed", "fork-trajectory": "trajectory_forked", complete: "effort_completed", abandon: "effort_abandoned", reopen: "effort_reopened", waive: "finding_waived", repair: "repair_applied" };
function lifecyclePayload(request: any): any {
  const omit = new Set(["action", "idempotencyKey", "eventId", "effortId", "sessionId", "timestamp", "predecessors"]); const payload: any = {};
  for (const [key, value] of Object.entries(request)) if (!omit.has(key) && value !== undefined) payload[key] = value;
  if (request.action === "create") { if (payload.origin) { payload.originEffortId = payload.origin.effortId; payload.originTrajectoryId = payload.origin.trajectoryId; payload.originAnchorId = payload.origin.anchorId; delete payload.origin; } }
  if (request.action === "repair") { payload.proposalKind = payload.proposal.kind; payload.sourceEventIds = payload.proposal.sourceEventIds; payload.replacement = payload.proposal.replacement; delete payload.proposal; }
  return payload;
}
function lifecycleEvent(request: any, terminalEpoch = 1): TelemetryEvent {
  const payload = lifecyclePayload(request); if (["complete", "abandon", "reopen"].includes(request.action)) payload.terminalEpoch = terminalEpoch;
  const event: any = { version: protocolVersion, eventId: request.eventId, idempotencyKey: request.idempotencyKey, effortId: request.effortId, sessionId: request.sessionId, timestamp: request.timestamp, kind: lifecycleKind[request.action], predecessors: request.predecessors, payload };
  if (request.trajectoryId) event.trajectoryId = request.trajectoryId; if (request.parentTrajectoryId) event.parentTrajectoryId = request.parentTrajectoryId; if (request.forkAnchorId) event.forkAnchorId = request.forkAnchorId;
  /* c8 ignore next -- descriptor validation of the request and fixed mapping imply a valid event */ if (!validateTelemetryEvent(event)) throw new Error("lifecycle request does not produce a valid event"); return event;
}
/* c8 ignore stop */
interface LocalInterval { phase: string; startEventId: string; finishEventId?: string; terminalEpoch: number; }
interface LocalTrajectory { eventId: string; parentTrajectoryId?: string; closed: boolean; }
interface LocalLifecycleProjection { state: "absent" | "discovery" | "active" | "completed" | "abandoned"; route?: string; frontier: string[]; openPhases: Map<string, LocalInterval>; phaseIntervals: LocalInterval[]; terminalEpoch: number; trajectories: Map<string, LocalTrajectory>; activeTrajectoryId?: string; associations: Map<string, TelemetryAssociation>; associationEvents: Map<string, string>; effectApplied: Set<string>; events: Map<string, any>; before(left: string, right: string): boolean; }
const routeRequirements: Record<string, string[]> = { direct: ["brainstorming", "implementation", "implementation-review", "retrospective"], adr: ["brainstorming", "adr-authoring", "adr-review", "implementation", "implementation-review", "retrospective"], plan: ["brainstorming", "planning", "plan-review", "implementation", "implementation-review", "retrospective"], "adr-plan": ["brainstorming", "adr-authoring", "adr-review", "planning", "plan-review", "adr-plan-resync", "implementation", "implementation-review", "retrospective"], bugfix: ["brainstorming", "implementation", "implementation-review", "retrospective"], "investigation-only": ["investigation", "retrospective"] };
/* c8 ignore start -- route/freshness and causal lifecycle behavior are exhaustively exercised by focused parity fixtures; V8 expands compact searches into unstable synthetic branches */
function latestPhase(projection: LocalLifecycleProjection, phase: string): LocalInterval | undefined { let latest: LocalInterval | undefined; for (const interval of projection.phaseIntervals) if (interval.phase === phase && interval.terminalEpoch === projection.terminalEpoch && interval.finishEventId && (!latest || projection.before(latest.finishEventId!, interval.finishEventId))) latest = interval; return latest; }
function routeComplete(projection: LocalLifecycleProjection): boolean {
  const required = routeRequirements[projection.route ?? ""]; if (!required || (projection.route === "investigation-only" && (latestPhase(projection, "implementation") || [...projection.openPhases.values()].some((item) => item.phase === "implementation")))) return false;
  let previous = ""; for (const phase of required) { const interval = projection.phaseIntervals.find((candidate) => candidate.phase === phase && candidate.terminalEpoch === projection.terminalEpoch && !!candidate.finishEventId && (!previous || projection.before(previous, candidate.startEventId))); if (!interval) return false; previous = interval.finishEventId!; }
  for (const [upstream, downstream] of [["adr-authoring", "adr-review"], ["planning", "plan-review"], ["implementation", "implementation-review"]]) { const up = latestPhase(projection, upstream); if (up) { const down = latestPhase(projection, downstream); if (!down || !projection.before(up.finishEventId!, down.startEventId)) return false; } }
  if (projection.route === "adr-plan") { const resync = latestPhase(projection, "adr-plan-resync"); for (const phase of ["adr-review", "plan-review"]) { const up = latestPhase(projection, phase); if (up && (!resync || !projection.before(up.finishEventId!, resync.startEventId))) return false; } }
  return true;
}
function lifecycleConflictKey(event: any): string { if (["route_selected", "route_changed", "effort_completed", "effort_abandoned", "effort_reopened"].includes(event.kind)) return "effort-state"; if (event.kind === "phase_started") return "phase-open"; if (event.kind === "phase_finished") return `phase-finish:${event.payload.startEventId}`; if (["session_associated", "session_detached"].includes(event.kind)) return `association:${event.sessionId}`; if (["trajectory_started", "trajectory_resumed", "trajectory_closed", "trajectory_forked"].includes(event.kind)) return "trajectory-active"; return ""; }
export async function projectLocalLifecycle(deps: LedgerDependencies, effortId: string, additional: readonly TelemetryEvent[] = []): Promise<LocalLifecycleProjection> {
  const events: any[] = []; const sessions = join(ledgerPaths(deps.root).efforts, effortId, "sessions"); let entries: any[]; try { entries = await deps.readdir(sessions); } catch (error) { if (absent(error)) { const empty: any = { state: "absent", frontier: [], openPhases: new Map(), phaseIntervals: [], terminalEpoch: 1, trajectories: new Map(), associations: new Map(), associationEvents: new Map(), effectApplied: new Set(), events: new Map(), before: () => false }; return empty; } throw error; }
  for (const entry of [...entries].sort((a, b) => String(a.name).localeCompare(String(b.name)))) { if (!entry.isFile?.() || !String(entry.name).endsWith(".jsonl")) continue; const raw = await deps.readFile(join(sessions, entry.name), "utf8"); const lines = raw.split("\n"); if (lines.at(-1) !== "") throw new Error("event stream has an incomplete final line"); for (const line of lines.slice(0, -1)) { if (!line) continue; let event: any; try { event = JSON.parse(line); } catch { continue; } if (validateTelemetryEvent(event) && !events.some((prior) => prior.eventId === event.eventId)) events.push(event); } }
  for (const event of additional) if (!events.some((prior) => prior.eventId === event.eventId)) events.push(event);
  const byId = new Map(events.map((event) => [event.eventId, event])); const frontiers = new Map<string, string[]>(); const previousSession = new Map<string, string>(); const trajectoryOrigins = new Map<string, string>(); const anchors = new Map<string, string>(); const ambiguousAnchors = new Set<string>();
  for (const event of events) { if (event.piAnchorId) { if (anchors.has(event.piAnchorId)) ambiguousAnchors.add(event.piAnchorId); else anchors.set(event.piAnchorId, event.eventId); } if (event.kind === "trajectory_started" || event.kind === "trajectory_forked" || event.kind === "effort_reopened") trajectoryOrigins.set(event.payload.trajectoryId, trajectoryOrigins.get(event.payload.trajectoryId) ?? event.eventId); } for (const anchor of ambiguousAnchors) anchors.delete(anchor);
  for (const event of events) { const frontier = [...event.predecessors]; const prior = previousSession.get(event.sessionId); if (prior && !frontier.includes(prior)) frontier.push(prior); if (event.kind === "session_associated" && event.payload.handoffEventId && !frontier.includes(event.payload.handoffEventId)) frontier.push(event.payload.handoffEventId); if (["trajectory_resumed", "trajectory_closed", "effort_reopened"].includes(event.kind)) { const linked = anchors.get(event.payload.anchorId); if (linked && linked !== event.eventId && !frontier.includes(linked)) frontier.push(linked); } if (event.kind === "trajectory_forked") for (const linked of [trajectoryOrigins.get(event.payload.parentTrajectoryId), anchors.get(event.payload.forkAnchorId)]) if (linked && linked !== event.eventId && !frontier.includes(linked)) frontier.push(linked); frontiers.set(event.eventId, [...new Set(frontier)].sort()); previousSession.set(event.sessionId, event.eventId); }
  const ancestors = new Map<string, Set<string>>(); const invalid = new Set<string>(); const visiting = new Set<string>(); const visit = (id: string): Set<string> => { if (ancestors.has(id)) return ancestors.get(id)!; if (visiting.has(id)) { invalid.add(id); return new Set(); } visiting.add(id); const result = new Set<string>(); for (const predecessor of frontiers.get(id) ?? []) { if (!byId.has(predecessor)) { invalid.add(id); continue; } result.add(predecessor); for (const ancestor of visit(predecessor)) result.add(ancestor); } visiting.delete(id); ancestors.set(id, result); return result; }; for (const event of events) visit(event.eventId); const before = (left: string, right: string) => left !== right && !!ancestors.get(right)?.has(left); const concurrent = (left: string, right: string) => left !== right && !before(left, right) && !before(right, left);
  const lifecycle = events.filter((event) => (protocolDescriptor.payloads as any)[event.kind]?.class === "lifecycle"); for (let left = 0; left < lifecycle.length; left++) for (let right = left + 1; right < lifecycle.length; right++) { const a = lifecycle[left]!, b = lifecycle[right]!; const same = lifecycleConflictKey(a) && lifecycleConflictKey(a) === lifecycleConflictKey(b); const repairConflict = a.kind === "repair_applied" && b.kind === "repair_applied" && a.payload.sourceEventIds.some((id: string) => b.payload.sourceEventIds.includes(id)); const terminalConflict = (["effort_completed", "effort_abandoned", "effort_reopened"].includes(a.kind) && !["effort_created", "finding_waived", "repair_applied"].includes(b.kind)) || (["effort_completed", "effort_abandoned", "effort_reopened"].includes(b.kind) && !["effort_created", "finding_waived", "repair_applied"].includes(a.kind)); if ((same || repairConflict || terminalConflict) && concurrent(a.eventId, b.eventId)) { invalid.add(a.eventId); invalid.add(b.eventId); } }
  const remaining = new Map(events.map((event) => [event.eventId, event])); const ordered: any[] = []; while (remaining.size) { const ready = [...remaining.values()].filter((event) => (frontiers.get(event.eventId) ?? []).every((id) => !remaining.has(id))).sort((a, b) => a.eventId.localeCompare(b.eventId)); if (!ready.length) { for (const event of [...remaining.values()].sort((a, b) => a.eventId.localeCompare(b.eventId))) { invalid.add(event.eventId); ordered.push(event); } break; } for (const event of ready) { remaining.delete(event.eventId); ordered.push(event); } }
  const projection: LocalLifecycleProjection = { state: "absent", frontier: [], openPhases: new Map(), phaseIntervals: [], terminalEpoch: 1, trajectories: new Map(), associations: new Map(), associationEvents: new Map(), effectApplied: new Set(), events: byId, before };
  const fail = (event: any, message: string) => { invalid.add(event.eventId); return message; }; const apply = (event: any): string | undefined => { if ((protocolDescriptor.payloads as any)[event.kind]?.class !== "lifecycle") return; if (projection.state === "absent" && event.kind !== "effort_created") return fail(event, "mutation requires an existing effort"); if (["completed", "abandoned"].includes(projection.state) && !["finding_waived", "repair_applied", "effort_reopened"].includes(event.kind)) return fail(event, "mutation is illegal after terminal state");
    switch (event.kind) {
      case "effort_created": if (projection.effectApplied.size) return fail(event, "effort already exists"); projection.state = "discovery"; projection.terminalEpoch = 1; break;
      case "session_associated": { const node = projection.trajectories.get(event.payload.trajectoryId); if (!node || !before(node.eventId, event.eventId)) return fail(event, "session association requires a causally visible trajectory"); projection.associations.set(event.sessionId, { effortId: event.effortId, sessionId: event.sessionId, trajectoryId: event.payload.trajectoryId, associationOrigin: event.payload.associationOrigin }); projection.associationEvents.set(event.sessionId, event.eventId); break; }
      case "session_detached": projection.associations.delete(event.sessionId); projection.associationEvents.delete(event.sessionId); break;
      case "route_selected": if (projection.state !== "discovery") return fail(event, "route selection requires discovery state"); if (event.payload.route === "investigation-only" && (latestPhase(projection, "implementation") || [...projection.openPhases.values()].some((item) => item.phase === "implementation"))) return fail(event, "investigation-only cannot follow implementation"); projection.route = event.payload.route; projection.state = "active"; break;
      case "route_changed": if (projection.state !== "active" || !projection.route) return fail(event, "route change requires an active selected route"); if (event.payload.route === "investigation-only" && latestPhase(projection, "implementation")) return fail(event, "investigation-only cannot include implementation"); projection.route = event.payload.route; break;
      case "phase_started": if (projection.openPhases.size) return fail(event, "a top-level phase is already open"); projection.openPhases.set(event.eventId, { phase: event.payload.phase, startEventId: event.eventId, terminalEpoch: projection.terminalEpoch }); break;
      case "phase_finished": { const interval = projection.openPhases.get(event.payload.startEventId); if (!interval || interval.phase !== event.payload.phase || !before(event.payload.startEventId, event.eventId)) return fail(event, "phase finish does not name a causally visible unmatched matching start"); interval.finishEventId = event.eventId; projection.openPhases.delete(event.payload.startEventId); projection.phaseIntervals.push(interval); break; }
      case "trajectory_started": if (projection.trajectories.has(event.payload.trajectoryId)) return fail(event, "trajectory already exists"); projection.trajectories.set(event.payload.trajectoryId, { eventId: event.eventId, closed: false }); projection.activeTrajectoryId = event.payload.trajectoryId; break;
      case "trajectory_resumed": { const node = projection.trajectories.get(event.payload.trajectoryId); if (!node || !before(node.eventId, event.eventId)) return fail(event, "cannot resume a causally unknown trajectory"); node.closed = false; projection.activeTrajectoryId = event.payload.trajectoryId; const associated = projection.associations.get(event.sessionId); if (associated) { let cursor: string | undefined = event.payload.trajectoryId; let contains = false; const seen = new Set<string>(); while (cursor && !seen.has(cursor)) { if (cursor === associated.trajectoryId) { contains = true; break; } seen.add(cursor); cursor = projection.trajectories.get(cursor)?.parentTrajectoryId; } const anchorEvent = anchors.get(event.payload.anchorId); const associationEvent = projection.associationEvents.get(event.sessionId); if (!contains || !!anchorEvent && !!associationEvent && projection.effectApplied.has(anchorEvent) && before(anchorEvent, associationEvent)) { projection.associations.delete(event.sessionId); projection.associationEvents.delete(event.sessionId); } } break; }
      case "trajectory_closed": { const node = projection.trajectories.get(event.payload.trajectoryId); if (!node || !before(node.eventId, event.eventId)) return fail(event, "cannot close unknown trajectory"); if (node.closed) return fail(event, "cannot close inactive trajectory"); if (projection.activeTrajectoryId !== event.payload.trajectoryId) return fail(event, "cannot close a non-active trajectory"); node.closed = true; projection.activeTrajectoryId = undefined; break; }
      case "trajectory_forked": { if (projection.trajectories.has(event.payload.trajectoryId)) return fail(event, "fork trajectory already exists"); const parent = projection.trajectories.get(event.payload.parentTrajectoryId); if (!parent || !before(parent.eventId, event.eventId)) return fail(event, "fork parent trajectory is not causally visible"); projection.trajectories.set(event.payload.trajectoryId, { eventId: event.eventId, parentTrajectoryId: event.payload.parentTrajectoryId, closed: false }); projection.activeTrajectoryId = event.payload.trajectoryId; break; }
      case "effort_completed": if (projection.state !== "active" || !projection.route || event.payload.terminalEpoch !== projection.terminalEpoch || projection.openPhases.size || !routeComplete(projection)) return fail(event, "effort completion requirements are not satisfied"); projection.state = "completed"; break;
      case "effort_abandoned": if (!["discovery", "active"].includes(projection.state) || event.payload.terminalEpoch !== projection.terminalEpoch) return fail(event, "effort abandonment requires mutable state and the active epoch"); projection.state = "abandoned"; break;
      case "effort_reopened": if (projection.state !== "completed" || event.payload.terminalEpoch !== projection.terminalEpoch + 1 || projection.trajectories.has(event.payload.trajectoryId)) return fail(event, "only a completed effort can reopen into the next epoch and a new trajectory"); projection.terminalEpoch = event.payload.terminalEpoch; projection.trajectories.set(event.payload.trajectoryId, { eventId: event.eventId, closed: false }); projection.activeTrajectoryId = event.payload.trajectoryId; projection.state = "active"; break;
      case "finding_waived": break;
    } };
  const repairs = new Map<string, any>(); const sourceRepair = new Map<string, string>(); for (const event of lifecycle.filter((candidate) => candidate.kind === "repair_applied" && !invalid.has(candidate.eventId))) { const payload = event.payload; const replacementDescriptor = (protocolDescriptor.payloads as any)[payload.replacement?.eventKind]; const replacementClass = replacementDescriptor?.class; const proposalMatches = payload.proposalKind === "supersede-event" || payload.proposalKind === "correct-phase" && ["phase_started", "phase_finished"].includes(payload.replacement?.eventKind) || payload.proposalKind === "correct-association" && ["session_associated", "session_detached"].includes(payload.replacement?.eventKind) || payload.proposalKind === "correct-trajectory" && ["trajectory_started", "trajectory_resumed", "trajectory_closed", "trajectory_forked"].includes(payload.replacement?.eventKind); if (!payload.sourceEventIds?.length || replacementClass !== "lifecycle" || replacementDescriptor?.repairable !== true || payload.replacement.eventKind === "repair_applied" || !proposalMatches || payload.sourceEventIds.some((id: string) => !byId.has(id) || !before(id, event.eventId) || (protocolDescriptor.payloads as any)[byId.get(id)?.kind]?.class !== "lifecycle")) { invalid.add(event.eventId); continue; } repairs.set(event.eventId, payload); for (const source of payload.sourceEventIds) sourceRepair.set(source, event.eventId); }
  const replacementApplied = new Set<string>(); for (const event of ordered) { for (const predecessor of frontiers.get(event.eventId) ?? []) projection.frontier = projection.frontier.filter((id) => id !== predecessor); if (!projection.frontier.includes(event.eventId)) projection.frontier.push(event.eventId); projection.frontier.sort(); const repairId = sourceRepair.get(event.eventId); if (repairId) { if (invalid.has(repairId)) { if (!invalid.has(event.eventId)) { const sourceError = apply(event); if (!sourceError) projection.effectApplied.add(event.eventId); } continue; } if (!replacementApplied.has(repairId)) { const sourceWasInvalid = invalid.has(event.eventId); const replacement = repairs.get(repairId).replacement; const corrected = { ...event, kind: replacement.eventKind, payload: replacement.payload }; const error = apply(corrected); if (!error) replacementApplied.add(repairId); else { invalid.add(repairId); if (!sourceWasInvalid) invalid.delete(event.eventId); if (!invalid.has(event.eventId)) { const sourceError = apply(event); if (!sourceError) projection.effectApplied.add(event.eventId); } } } continue; } if (event.kind === "repair_applied" && repairs.has(event.eventId)) { if (replacementApplied.has(event.eventId)) projection.effectApplied.add(event.eventId); continue; } if (invalid.has(event.eventId)) continue; const error = apply(event); if (!error) projection.effectApplied.add(event.eventId); }
  return projection;
}
/* c8 ignore stop */
/* c8 ignore start -- focused closed-matrix tests exercise every legal source family and illegal transition class; V8 expands compact predicates into synthetic branches */
function validateLocalLifecycleTransition(request: any, projection: LocalLifecycleProjection): void {
  const predecessors = [...request.predecessors].sort(); if (JSON.stringify(predecessors) !== JSON.stringify(projection.frontier)) throw new Error(`lifecycle request does not observe the current causal frontier: got ${JSON.stringify(predecessors)}, want ${JSON.stringify(projection.frontier)}`);
  const source = projection.state; const mutable = source === "discovery" || source === "active";
  if (["associate", "detach", "start-phase", "finish-phase", "start-trajectory", "resume-trajectory", "close-trajectory", "fork-trajectory"].includes(request.action) && !mutable) throw new Error("illegal lifecycle source state");
  if (request.action === "select-route" && source !== "discovery") throw new Error("route selection requires discovery state"); if (request.action === "change-route" && (source !== "active" || !projection.route)) throw new Error("route change requires active state"); if (request.action === "start-phase" && projection.openPhases.size) throw new Error("a lifecycle phase is already open"); const open = projection.openPhases.get(request.startEventId); const startVisible = request.predecessors.some((id: string) => id === request.startEventId || projection.before(request.startEventId, id)); if (request.action === "finish-phase" && (!open || open.phase !== request.phase || !startVisible)) throw new Error("phase finish does not name the visible open phase"); if (request.action === "complete" && (source !== "active" || projection.openPhases.size || !routeComplete(projection))) throw new Error("effort completion requirements are not satisfied"); if (request.action === "abandon" && !mutable) throw new Error("effort abandonment requires mutable state"); if (request.action === "reopen" && source !== "completed") throw new Error("only a completed effort can reopen"); if (["waive", "repair"].includes(request.action) && source === "absent") throw new Error("post-state lifecycle mutation requires an effort");
}
/* c8 ignore stop */
function toolResult(value: unknown) { return { content: [{ type: "text" as const, text: JSON.stringify(value) }], details: value }; }
function selectorArgs(params: any): string[] { const args: string[] = []; for (const [field, flag] of [["effort", "--effort"], ["session", "--session"], ["phase", "--phase"], ["since", "--since"], ["until", "--until"]]) if (params[field] !== undefined) args.push(flag, String(params[field])); return args; }
function passiveEvent(association: TelemetryAssociation, kind: string, payload: any, deps: LedgerDependencies, anchor?: string, observationId?: string): TelemetryEvent {
  const event: any = { version: protocolVersion, eventId: deps.uuid(), effortId: association.effortId, sessionId: association.sessionId, trajectoryId: association.trajectoryId, timestamp: new Date(deps.now()).toISOString(), kind, predecessors: [], payload };
  if ((protocolDescriptor.payloads as any)[kind]?.class === "lifecycle") event.idempotencyKey = deps.uuid(); else event.observationId = identifier(observationId) ? observationId : deps.uuid();
  if (anchor && identifier(anchor)) event.piAnchorId = anchor; if (!validateTelemetryEvent(event)) throw new Error("invalid passive observation"); return event;
}

export const DASHBOARD_VIEWS = ["overview", "phases", "history", "findings", "maintenance"] as const;
type DashboardView = typeof DASHBOARD_VIEWS[number];
function metricEfforts(state: DashboardState): any[] { return Array.isArray(state.metrics?.efforts) ? state.metrics.efforts : []; }
function terminalEfforts(state: DashboardState): any[] { return metricEfforts(state).filter((effort) => ["completed", "abandoned"].includes(effort?.state) && identifier(effort?.effortId)); }
function rowText(value: unknown): string { return typeof value === "string" ? value : JSON.stringify(value); }
function findingRows(state: DashboardState): any[] { return Array.isArray(state.doctor?.findings) ? state.doctor.findings : []; }
function actionRequest(action: any, association: TelemetryAssociation | undefined, deps: LedgerDependencies): LifecycleRequest | undefined {
  if (!association || !action?.finding) return undefined; const finding = action.finding; const base: any = { idempotencyKey: deps.uuid(), eventId: deps.uuid(), effortId: association.effortId, sessionId: association.sessionId, timestamp: new Date(deps.now()).toISOString(), predecessors: [] };
  if (action.kind === "repair" && finding.reconciliation) return { ...base, action: "repair", proposal: finding.reconciliation } as any;
  if (action.kind === "waive" && typeof finding.code === "string") return { ...base, action: "waive", ruleCode: finding.code, scope: boundedBytes(finding.scope, protocolLimits.categoryBytes), evidenceIds: Array.isArray(finding.evidence?.eventIds) ? finding.evidence.eventIds.filter(identifier) : [], reasonCode: "approved-route-deviation" } as any;
  return undefined;
}
export class DashboardOverlay {
  view: DashboardView = "overview"; row = 0; confirmation?: { action: any; stage: number }; private disposed = false;
  private controller = new AbortController();
  constructor(private state: DashboardState, private options: { requestRender(): void; close(): void; refresh(signal?: AbortSignal): Promise<unknown>; lifecycle(request: LifecycleRequest, signal?: AbortSignal): Promise<unknown>; association(): TelemetryAssociation | undefined; ledger: LedgerDependencies; }) {}
  private rows(): any[] {
    if (this.view === "overview") return metricEfforts(this.state);
    if (this.view === "phases") return metricEfforts(this.state).flatMap((effort) => Array.isArray(effort.phases) ? effort.phases : []);
    if (this.view === "history") return metricEfforts(this.state);
    if (this.view === "findings") return findingRows(this.state);
    return [{ kind: "retain-dry", label: "retain dry-run" }, { kind: "retain", label: "retain apply" }, ...terminalEfforts(this.state).map((effort) => ({ kind: "purge", label: `purge ${effort.effortId}`, effortId: effort.effortId }))];
  }
  private clamp(): void { this.row = Math.max(0, Math.min(this.row, Math.max(0, this.rows().length - 1))); }
  private async confirmYes(): Promise<void> {
    const pending = this.confirmation; if (!pending || this.disposed) return; if (pending.action.kind === "purge" && pending.stage === 1) { this.confirmation = { ...pending, stage: 2 }; this.options.requestRender(); return; }
    this.confirmation = undefined;
    if (pending.action.kind === "retain") await this.state.runFixed(["metrics", "retain", "--json"], this.controller.signal);
    else if (pending.action.kind === "purge" && identifier(pending.action.effortId)) await this.state.runFixed(["metrics", "purge", "--effort", pending.action.effortId, "--confirm", "--json"], this.controller.signal);
    else { const request = actionRequest(pending.action, this.options.association(), this.options.ledger); if (request && validateLifecycleRequest(request)) await this.options.lifecycle(request, this.controller.signal); }
    if (!this.disposed) this.options.requestRender();
  }
  handleInput(data: string): void {
    if (this.disposed) return;
    if (this.confirmation) { if (data.toLowerCase() === "y" || matchesKey(data, Key.enter)) void this.confirmYes(); else if (data.toLowerCase() === "n" || matchesKey(data, Key.escape)) { this.confirmation = undefined; this.options.requestRender(); } return; }
    if (matchesKey(data, Key.escape)) { this.options.close(); return; }
    if (matchesKey(data, Key.left) || matchesKey(data, Key.shift("tab"))) { this.view = DASHBOARD_VIEWS[(DASHBOARD_VIEWS.indexOf(this.view) + DASHBOARD_VIEWS.length - 1) % DASHBOARD_VIEWS.length]!; this.row = 0; }
    else if (matchesKey(data, Key.right) || matchesKey(data, Key.tab)) { this.view = DASHBOARD_VIEWS[(DASHBOARD_VIEWS.indexOf(this.view) + 1) % DASHBOARD_VIEWS.length]!; this.row = 0; }
    else if (matchesKey(data, Key.up)) { this.row--; this.clamp(); }
    else if (matchesKey(data, Key.down)) { this.row++; this.clamp(); }
    else if (data.toLowerCase() === "r") void this.options.refresh(this.controller.signal).finally(() => { if (!this.disposed) this.options.requestRender(); });
    else if (matchesKey(data, Key.enter)) { const selected = this.rows()[this.row]; if (!selected) return; if (this.view === "maintenance") { if (selected.kind === "retain-dry") void this.state.runFixed(["metrics", "retain", "--dry-run", "--json"], this.controller.signal).finally(() => { if (!this.disposed) this.options.requestRender(); }); else this.confirmation = { action: selected, stage: 1 }; } else if (this.view === "findings") { const kind = selected.reconciliation ? "repair" : selected.waived ? undefined : "waive"; if (kind) this.confirmation = { action: { kind, finding: selected }, stage: 1 }; } }
    this.options.requestRender();
  }
  render(width: number): string[] {
    const safe = Math.max(1, width); const tabs = DASHBOARD_VIEWS.map((view) => view === this.view ? `[${view}]` : view).join(" "); const lines = [`awf dashboard: ${this.state.status}${this.state.errorCategory ? ` (${this.state.errorCategory})` : ""}`, tabs];
    if (this.confirmation) lines.push(this.confirmation.stage === 2 ? "DESTRUCTIVE confirmation: purge permanently? y/n" : `Confirm ${this.confirmation.action.label ?? this.confirmation.action.kind}? y/n`);
    else {
      const rows = this.rows(); if (rows.length === 0) lines.push("No data.");
      for (let index = 0; index < rows.length; index++) { const item = rows[index]; let text: string;
        if (this.view === "findings") text = `${item.code} ${item.severity} evidence=${rowText(item.evidence)} threshold=${rowText(item.threshold ?? item.baseline ?? "none")} confidence=${item.confidence} next=${item.nextAction}`;
        else if (this.view === "maintenance") text = item.label;
        else if (this.view === "phases") text = `${item.phase ?? item.id ?? "phase"} duration=${item.durationMs ?? item.durationSeconds ?? 0} tokens=${item.usage?.totalTokens ?? item.tokens ?? 0}`;
        else text = `${item.effortId ?? "effort"} ${item.state ?? "unknown"} route=${item.route ?? "undecided"}`;
        lines.push(`${index === this.row ? ">" : " "} ${text}`);
      }
    }
    lines.push("left/right or tab: view  up/down: row  enter: action  r: refresh  esc: close"); return lines.map((line) => truncateToWidth(line, safe));
  }
  invalidate(): void {}
  dispose(): void { this.disposed = true; this.controller.abort(); this.confirmation = undefined; }
}
export function dashboardWidget(state: DashboardState, counters: { inputTokens: number; outputTokens: number; costUsd: number }, width: number): string[] {
  const effort = metricEfforts(state)[0]; const tokens = counters.inputTokens + counters.outputTokens; let line = `awf ${state.status}${state.errorCategory ? `:${state.errorCategory}` : ""}`; if (effort) line += ` ${effort.effortId} ${effort.state ?? "unknown"}`; line += ` session tokens=${tokens}`; /* c8 ignore next -- both generated constant variants are proven by Go render tests */ if (telemetryWidgetShowCost) line += ` cost=$${counters.costUsd.toFixed(4)}`; return [truncateToWidth(line, Math.max(1, width))];
}

export interface DashboardDependencies extends MinimumRuntimeDependencies { extensionFile: string; ledger: LedgerDependencies; exec(command: string, args: string[], signal?: AbortSignal): Promise<{ stdout: string; stderr: string; code: number }>; }
export function defaultDashboardDependencies(pi: ExtensionAPI): DashboardDependencies {
  const extensionFile = fileURLToPath(import.meta.url); return { extensionFile, ledger: defaultLedgerDependencies(extensionFile), packageVersion: process.env.npm_package_version ?? MIN_PI_VERSION, exec: (command, args, signal) => pi.exec(command, args, signal ? { signal } : undefined) as any };
}
export function registerDashboard(pi: ExtensionAPI, deps: DashboardDependencies = defaultDashboardDependencies(pi)): void {
  if (!guardMinimumRuntime(pi, deps, ["on", "eventsOn", "eventsEmit", "appendEntry", "registerTool", "registerCommand", "exec"])) return;
  const writer = createLedgerWriter(deps.ledger); let widgetRender = () => {}; const state = createDashboardState("loading", { root: deps.ledger.root, lstat: deps.ledger.lstat, exec: deps.exec }, () => widgetRender()); let association: TelemetryAssociation | undefined; let context: any; let overlay: DashboardOverlay | undefined; let closeOverlay: (() => void) | undefined; const sessionCounters = { inputTokens: 0, outputTokens: 0, costUsd: 0 };
  /* c8 ignore start -- every caller checks association and passive writer failure is intentionally absorbed */
  const observe = async (kind: string, payload: any, anchor?: string, observationId?: string) => { if (!association) return; try { const event = passiveEvent(association, kind, payload, deps.ledger, anchor, observationId); if ((protocolDescriptor.payloads as any)[kind]?.class === "lifecycle") await writer.appendCausal(event); else await writer.passive(event); } catch {} };
  /* c8 ignore stop */
  const submitLifecycle = async (params: LifecycleRequest, signal?: AbortSignal) => { const tool = lifecycleTool; return tool.execute("dashboard", params, signal); };
  const lifecycleSchema = Type.Object({ action: StringEnum(Object.keys(protocolDescriptor.lifecycleRequests) as any), idempotencyKey: Type.String(), eventId: Type.String(), effortId: Type.String(), sessionId: Type.String(), timestamp: Type.String(), predecessors: Type.Array(Type.String()), checkpointId: Type.Optional(Type.String()), creationMode: Type.Optional(Type.String()), origin: Type.Optional(Type.Unknown()), trajectoryId: Type.Optional(Type.String()), associationOrigin: Type.Optional(Type.String()), handoffEventId: Type.Optional(Type.String()), reason: Type.Optional(Type.String()), route: Type.Optional(Type.String()), phase: Type.Optional(Type.String()), activity: Type.Optional(Type.String()), implementationMode: Type.Optional(Type.String()), startEventId: Type.Optional(Type.String()), outcome: Type.Optional(Type.String()), anchorId: Type.Optional(Type.String()), parentTrajectoryId: Type.Optional(Type.String()), forkAnchorId: Type.Optional(Type.String()), ruleCode: Type.Optional(Type.String()), scope: Type.Optional(Type.String()), evidenceIds: Type.Optional(Type.Array(Type.String())), reasonCode: Type.Optional(Type.String()), proposal: Type.Optional(Type.Unknown()) }, { additionalProperties: false });
  const selectorSchema = Type.Object({ effort: Type.Optional(Type.String()), session: Type.Optional(Type.String()), phase: Type.Optional(Type.String()), since: Type.Optional(Type.String()), until: Type.Optional(Type.String()) }, { additionalProperties: false });
  const lifecycleTool: any = { name: "awf_lifecycle", label: "awf lifecycle", description: "Record one explicit workflow lifecycle mutation.", parameters: lifecycleSchema, async execute(_id: string, params: LifecycleRequest, signal?: AbortSignal) {
    if (!validateLifecycleRequest(params)) throw new Error("invalid lifecycle request"); if (signal?.aborted) throw new Error("lifecycle request canceled"); const createEvent = params.action === "create" ? lifecycleEvent(params, 1) : undefined;
    const metadata = params.action === "create" ? { effortId: params.effortId, createdAt: params.timestamp, checkpointId: (params as any).checkpointId, creationMode: (params as any).creationMode, origin: (params as any).origin } : undefined;
    const mutation = metadata ? { ...(await writer.create(metadata, createEvent!)), event: createEvent! } : await writer.mutateLifecycle(params); const event = mutation.event; const result = mutation; if (["associate", "reopen"].includes(params.action)) { association = { effortId: params.effortId, sessionId: params.sessionId, trajectoryId: (params as any).trajectoryId, associationOrigin: params.action === "associate" ? (params as any).associationOrigin : "manual" }; pi.appendEntry(ASSOCIATION_ENTRY, { effortId: association.effortId, sessionId: association.sessionId, trajectoryId: association.trajectoryId, associationOrigin: association.associationOrigin }); }
    if (params.action === "detach") { association = undefined; pi.appendEntry(DETACH_ENTRY, { eventId: event.eventId }); }
    await state.refresh(); const retained = await state.runFixed(["metrics", "retain", "--json"]); if (!retained.ok) state.markStale("retain"); return toolResult({ eventId: event.eventId, idempotent: result.idempotent, refresh: state.snapshot() });
  }}; pi.registerTool(lifecycleTool);
  for (const [name, command] of [["awf_metrics", "metrics"], ["awf_doctor", "doctor"]] as const) pi.registerTool({ name, label: name.replace("_", " "), description: `Query canonical workflow ${command}.`, parameters: selectorSchema, async execute(_id: string, params: any) { const refreshed = await state.refresh(params); if (!refreshed.ok) return toolResult({ degraded: true, status: refreshed.status, errorCategory: refreshed.errorCategory }); return toolResult(command === "metrics" ? refreshed.metrics : refreshed.doctor); } });
  pi.registerCommand("awf-dashboard", { description: "Open the workflow telemetry dashboard.", handler: async (_args: string, ctx: any) => {
    context = ctx; await state.refresh(); if (ctx.mode !== "tui" || typeof ctx.ui?.custom !== "function") { ctx.ui?.notify?.(`awf dashboard ${state.status}`, state.status === "ready" ? "info" : "warning"); return; }
    await ctx.ui.custom((_tui: any, _theme: any, _keys: any, done: () => void) => { closeOverlay = done; overlay = new DashboardOverlay(state, { requestRender: () => _tui.requestRender(), close: done, refresh: (signal) => state.refresh({}, signal), lifecycle: submitLifecycle, association: () => association, ledger: deps.ledger }); return overlay; }, { overlay: true, overlayOptions: { anchor: "right-center", width: "70%", minWidth: 40, maxHeight: "85%", margin: 1 } }); overlay?.dispose(); overlay = undefined; closeOverlay = undefined;
  }});
  pi.events.on("awf.telemetry.association.request.v1", (request: any) => { if (association) try { request?.respond?.({ version: protocolVersion, association: { effortId: association.effortId, sessionId: association.sessionId, trajectoryId: association.trajectoryId, associationOrigin: association.associationOrigin } }); } catch {} });
  pi.events.on("awf.telemetry.context.request.v1", (request: any) => { if (association) try { const leaf = context?.sessionManager?.getLeafId?.(); request?.respond?.({ version: protocolVersion, context: { effortId: association.effortId, sessionId: association.sessionId, trajectoryId: association.trajectoryId, ...(identifier(leaf) ? { piAnchorId: leaf } : {}) } }); } catch {} });
  pi.events.on("awf.telemetry.subagent.v1", (observation: any) => { if (!association || !observation || observation.version?.major !== protocolVersion.major || !identifier(observation.observationId) || observation.effortId !== association.effortId || observation.sessionId !== association.sessionId || observation.trajectoryId !== association.trajectoryId) return; /* c8 ignore start -- field construction is non-throwing */ try { const payload = { role: boundedBytes(observation.role, protocolLimits.categoryBytes), requestedModel: boundedBytes(observation.requestedModel, protocolLimits.modelBytes), resolvedModel: boundedBytes(observation.resolvedModel, protocolLimits.modelBytes), thinkingLevel: boundedBytes(observation.thinkingLevel, protocolLimits.categoryBytes), queueDurationMs: observation.queueDurationMs, runDurationMs: observation.runDurationMs, inputTokens: observation.inputTokens, outputTokens: observation.outputTokens, cacheReadTokens: observation.cacheReadTokens, cacheWriteTokens: observation.cacheWriteTokens, costUsd: observation.costUsd, outcome: observation.outcome, stopReason: observation.stopReason, toolCount: observation.toolCount, toolFailureCount: observation.toolFailureCount, ...(observation.errorCategory ? { errorCategory: observation.errorCategory } : {}) }; void observe("subagent_observed", payload, observation.piAnchorId, observation.observationId); } catch {} /* c8 ignore stop */ });
  pi.events.on("awf.telemetry.handoff.v1", (observation: any) => { if (!association || !identifier(observation?.observationId) || !identifier(observation?.targetSessionId)) return; void observe("handoff_observed", { outcome: observation.outcome === "success" ? "success" : "failure", targetSessionId: observation.targetSessionId, ...(Number.isSafeInteger(observation.durationMs) && observation.durationMs >= 0 ? { durationMs: observation.durationMs } : {}), ...(observation.errorCategory ? { errorCategory: observation.errorCategory } : {}) }, observation.piAnchorId, observation.observationId); });
  pi.on("session_start", async (_event: any, ctx: any) => { context = ctx; association = restoreAssociation(ctx); if (!ctx?.sessionManager?.getBranch) { state.set("degraded", { errorCategory: "unavailable" }); return; }
    /* c8 ignore next -- both generated constant variants are proven by Go render tests */ if (telemetryWidgetEnabled && typeof ctx?.ui?.setWidget === "function") ctx.ui.setWidget("awf-workflow", (tui: any) => { widgetRender = () => tui.requestRender(); return { render: (width: number) => dashboardWidget(state, sessionCounters, width), invalidate() {} }; });
    if (typeof ctx?.ui?.custom !== "function") state.markStale("unavailable");
    await state.refresh();
    const currentSession = ctx.sessionManager.getSessionId?.(); let handoffEventId: string | undefined; const transferredHandoff = pendingHandoff(ctx);
    if (association && transferredHandoff && identifier(currentSession) && currentSession !== association.sessionId) { const handoff = passiveEvent(association, "handoff_observed", { outcome: "success", targetSessionId: currentSession, durationMs: transferredHandoff.durationMs }, deps.ledger, ctx.sessionManager.getLeafId?.(), transferredHandoff.observationId); await writer.passive(handoff); handoffEventId = handoff.eventId; }
    if (association && identifier(currentSession) && currentSession !== association.sessionId) { const prior = association; const forked = _event?.reason === "fork" || _event?.reason === "clone"; const nextTrajectory = forked ? deps.ledger.uuid() : prior.trajectoryId; association = { effortId: prior.effortId, sessionId: currentSession, trajectoryId: nextTrajectory, associationOrigin: "handoff" }; let predecessors: string[] = handoffEventId ? [handoffEventId] : [];
      if (forked) { const forkEvent: any = passiveEvent(prior, "trajectory_forked", { trajectoryId: nextTrajectory, parentTrajectoryId: prior.trajectoryId, forkAnchorId: ctx.sessionManager.getLeafId?.() ?? nextTrajectory }, deps.ledger, ctx.sessionManager.getLeafId?.()); forkEvent.parentTrajectoryId = prior.trajectoryId; forkEvent.forkAnchorId = forkEvent.payload.forkAnchorId; forkEvent.predecessors = predecessors; const appendedFork = await writer.appendCausal(forkEvent); predecessors = [appendedFork.event.eventId]; }
      const event: any = { version: protocolVersion, eventId: deps.ledger.uuid(), idempotencyKey: deps.ledger.uuid(), effortId: association.effortId, sessionId: association.sessionId, trajectoryId: association.trajectoryId, timestamp: new Date(deps.ledger.now()).toISOString(), kind: "session_associated", predecessors, payload: { associationOrigin: "handoff", trajectoryId: association.trajectoryId, ...(handoffEventId ? { handoffEventId } : {}) } }; await writer.appendCausal(event); pi.appendEntry(ASSOCIATION_ENTRY, { effortId: association.effortId, sessionId: association.sessionId, trajectoryId: association.trajectoryId, associationOrigin: association.associationOrigin }); }
    if (association) await observe("session_started", { outcome: "success" }, ctx.sessionManager.getLeafId?.()); });
  const toolStarts = new Map<string, number>(); pi.on("tool_execution_start", (event: any) => { toolStarts.set(event.toolCallId, deps.ledger.now()); });
  pi.on("tool_execution_end", (event: any, ctx: any) => { if (!association) return; const started = toolStarts.get(event.toolCallId) ?? deps.ledger.now(); toolStarts.delete(event.toolCallId); void observe("tool_observed", { tool: boundedBytes(event.toolName, protocolLimits.toolBytes), outcome: event.isError ? "failure" : "success", durationMs: Math.max(0, deps.ledger.now() - started), ...(event.isError ? { errorCategory: "tool" } : {}) }, ctx?.sessionManager?.getLeafId?.()); });
  pi.on("turn_end", (event: any, ctx: any) => { if (!event?.message?.usage) return; const usage = event.message.usage; sessionCounters.inputTokens += Number.isFinite(usage.input) ? usage.input : 0; sessionCounters.outputTokens += Number.isFinite(usage.output) ? usage.output : 0; sessionCounters.costUsd += Number.isFinite(usage.cost?.total) ? usage.cost.total : 0; widgetRender(); if (association) void observe("usage_observed", { model: boundedBytes(event.message.model, protocolLimits.modelBytes), inputTokens: usage.input ?? 0, outputTokens: usage.output ?? 0, cacheReadTokens: usage.cacheRead ?? 0, cacheWriteTokens: usage.cacheWrite ?? 0, costUsd: usage.cost?.total ?? 0, durationMs: 0 }, ctx?.sessionManager?.getLeafId?.()); });
  pi.on("session_compact", (_event: any, ctx: any) => { if (association) void observe("compaction_observed", { count: 1 }, ctx?.sessionManager?.getLeafId?.()); });
  pi.on("session_before_fork", async (event: any, ctx: any) => { const active = restoreAssociation(ctx); if (active) association = active; if (association && identifier(event?.entryId)) await observe("trajectory_closed", { trajectoryId: association.trajectoryId, anchorId: event.entryId, reason: event.position === "at" ? "clone" : "fork" }, event.entryId); });
  pi.on("session_tree", async (event: any, ctx: any) => { if (!association) return; const prior = association; const destination = restoreAssociation(ctx); if (!destination) { const detached = passiveEvent(prior, "session_detached", { reason: "pre-association-anchor" }, deps.ledger, event?.newLeafId); await writer.appendCausal(detached); association = undefined; pi.appendEntry(DETACH_ENTRY, { reason: "pre-association-anchor" }); return; } if (!identifier(event?.newLeafId)) return; let predecessors: string[] = [];
    if (identifier(event.oldLeafId)) { const closed = passiveEvent(prior, "trajectory_closed", { trajectoryId: prior.trajectoryId, anchorId: event.oldLeafId, reason: "tree" }, deps.ledger, event.oldLeafId); const appendedClose = await writer.appendCausal(closed); predecessors = [appendedClose.event.eventId]; }
    association = { effortId: destination.effortId, sessionId: destination.sessionId, trajectoryId: destination.trajectoryId, associationOrigin: destination.associationOrigin }; const associated: any = passiveEvent(association, "session_associated", { associationOrigin: association.associationOrigin, trajectoryId: association.trajectoryId }, deps.ledger, event.newLeafId); associated.predecessors = predecessors; const appendedAssociation = await writer.appendCausal(associated); const resumed: any = passiveEvent(association, "trajectory_resumed", { trajectoryId: association.trajectoryId, anchorId: event.newLeafId, reason: "tree" }, deps.ledger, event.newLeafId); resumed.predecessors = [appendedAssociation.event.eventId]; await writer.appendCausal(resumed); pi.appendEntry(ASSOCIATION_ENTRY, { effortId: association.effortId, sessionId: association.sessionId, trajectoryId: association.trajectoryId, associationOrigin: association.associationOrigin }); });
  pi.on("session_shutdown", async (_event: any, ctx: any) => { if (association) await observe("session_ended", { outcome: "success" }, ctx?.sessionManager?.getLeafId?.()); state.close(); overlay?.dispose(); overlay = undefined; closeOverlay?.(); closeOverlay = undefined; await writer.shutdown(); context?.ui?.setWidget?.("awf-workflow", undefined); widgetRender = () => {}; });
}

export default function (pi: ExtensionAPI): void { registerDashboard(pi); }
