package project

import (
	"strings"

	"github.com/hypnotox/agentic-workflows/internal/frontmatter"
	"github.com/hypnotox/agentic-workflows/internal/render"
)

const bannerText = "GENERATED by awf: do not edit; change .awf/ and run `awf render`"

// injectBanner inserts the generated-by banner into rendered content: for the
// resident-root gitignores, a leading `#` comment (a valid .gitignore comment);
// for shebang scripts, a `#`-comment after the shebang line (keeping the script
// executable); for frontmatter targets, an HTML comment after the closing `---`;
// otherwise an HTML comment as the first line. A supplied target comment style
// overrides that default for non-Markdown output such as TOML profiles.
// touches-state: rendering/sync-and-drift:provenance-banner - generated-by banner injection; proof in banner_test.go
// injectSourceMarker appends one informational source marker directly after an
// already-injected HTML generated-by banner. Sources are renderer-owned
// reader-facing authorities, not render dependencies or edit boundaries.
// touches-state: rendering/render-engine:source-marker-informational - informational source marker insertion; proofs in banner_test.go and topics_test.go
func injectSourceMarker(content string, sources []string) string {
	if len(sources) == 0 {
		return content
	}
	banner := "<!-- " + bannerText + " -->\n"
	at := strings.Index(content, banner)
	if at < 0 { // coverage-ignore: source markers are only applied after an HTML banner
		return content
	}
	marker := "<!-- awf:source " + strings.Join(sources, " ") + " -->\n"
	return content[:at+len(banner)] + marker + content[at+len(banner):]
}

func injectBanner(content, tid string, styles ...render.CommentStyle) string {
	if isResidentGitignoreTID(tid) {
		return "# " + bannerText + "\n" + content
	}
	if strings.HasPrefix(content, "#!") {
		// Shell/script target: banner as a # comment after the shebang line.
		nl := strings.IndexByte(content, '\n')
		if nl < 0 { // coverage-ignore: a rendered shebang script always has a trailing newline body
			return content
		}
		return content[:nl+1] + "# " + bannerText + "\n" + content[nl+1:]
	}
	line := "<!-- " + bannerText + " -->\n"
	if len(styles) != 0 {
		switch styles[0] {
		case render.HTMLComment:
			// Keep the default HTML banner.
		case render.HashComment:
			line = "# " + bannerText + "\n"
		case render.SlashComment:
			line = "// " + bannerText + "\n"
		}
	}
	if yamlBlock, body, found := frontmatter.Split([]byte(content)); found {
		return "---\n" + string(yamlBlock) + "---\n" + line + string(body)
	}
	return line + content
}
