package project

import (
	"strings"

	"github.com/hypnotox/agentic-workflows/internal/frontmatter"
)

const bannerText = "GENERATED by awf — do not edit; change .awf/ and run `awf sync`"

// injectBanner inserts the generated-by banner into rendered content: for hooks,
// a `#` comment after the shebang line; for frontmatter targets, an HTML comment
// after the closing `---`; otherwise an HTML comment as the first line.
// invariant: provenance-banner
func injectBanner(content, tid string) string {
	if strings.HasPrefix(tid, "hooks/") {
		line := "# " + bannerText + "\n"
		if i := strings.IndexByte(content, '\n'); i >= 0 {
			return content[:i+1] + line + content[i+1:]
		}
		return content + "\n" + line
	}
	line := "<!-- " + bannerText + " -->\n"
	if yamlBlock, body, found := frontmatter.Split([]byte(content)); found {
		return "---\n" + string(yamlBlock) + "---\n" + line + string(body)
	}
	return line + content
}
