package project

import (
	"strings"

	"github.com/hypnotox/agentic-workflows/internal/frontmatter"
)

const bannerText = "GENERATED by awf — do not edit; change .awf/ and run `awf sync`"

// injectBanner inserts the generated-by banner into rendered content: for the
// memory gitignore, a leading `#` comment (a valid .gitignore comment — ADR-0069);
// for shebang scripts, a `#`-comment after the shebang line (keeping the script
// executable); for frontmatter targets, an HTML comment after the closing `---`;
// otherwise an HTML comment as the first line.
// invariant: provenance-banner
func injectBanner(content, tid string) string {
	if tid == memoryTID {
		return "# " + bannerText + "\n" + content
	}
	if strings.HasPrefix(content, "#!") {
		// Shell/script target: banner as a # comment after the shebang line.
		nl := strings.IndexByte(content, '\n')
		if nl < 0 { // coverage-ignore: a rendered shebang script always has a trailing newline body
			return content
		}
		return content[:nl+1] + "# " + bannerText + "\n" + content[nl+1:]
	}
	line := "<!-- " + bannerText + " -->\n"
	if yamlBlock, body, found := frontmatter.Split([]byte(content)); found {
		return "---\n" + string(yamlBlock) + "---\n" + line + string(body)
	}
	return line + content
}
