package project

import (
	"os"
	"strings"
	"testing"
)

// TestSundialCurrentStateMigrated pins the committed sundial fixture as a
// current-state adopter after the Plan 4 cutover: it carries a currentState
// config block (not legacy invariants), an authored topic corpus, sits at schema
// generation 14, and its committed lock records no bridge attestation. These
// properties hold identically in the preparation slice and after the final
// cutover, so the sealed contract stays green across both. Reading the fixture
// as data (never executing the binary) keeps this a static contract alongside
// the other example-wiring assertions.

// ADR-0090: the committed example adopter is kept deterministic through ./x -
// sync re-renders it from source; check drift-, invariant-, note-, and
// test-gates it. The example is its own Go module so the enclosing ./...
// sweeps never see it; this test pins the wiring so it cannot be silently
// dropped.
//
// invariant: tooling/quality-gates:example-adopter-checked
// invariant: tooling/quality-gates:example-zero-notes
// invariant: tooling/quality-gates:example-module-isolated
func TestExampleAdopterWiring(t *testing.T) {
	raw, err := os.ReadFile("../../x")
	if err != nil {
		t.Fatalf("read x: %v", err)
	}
	script := string(raw)
	for _, want := range []string{
		`context)`,
		`./awf context "$@" >"$capture"`,
		`go run ./cmd/contextspilllog --root "$PWD"`,
		`resolve or promote the issue`,
		`|check|context|`,
		`(cd examples/sundial && "$bindir/awf" render)`,
		`out="$(cd examples/sundial && "$bindir/awf" check)"`,
		`grep -q '^note: '`,
		`(cd examples/sundial && "$bindir/awf" check invariants)`,
		`(cd examples/sundial && go test ./...)`,
	} {
		if !strings.Contains(script, want) {
			t.Errorf("x lost the example-adopter step %q (ADR-0090)", want)
		}
	}
	if _, err := os.Stat("../../examples/sundial/go.mod"); err != nil {
		t.Errorf("examples/sundial must stay its own Go module (ADR-0090): %v", err)
	}
}

// invariant: tooling/quality-gates:pi-extension-container-gate

// The sundial example adopts the wrapper split (ADR-0156): the runner singleton
// renders the pure `awf` forwarder (default bootstrap-then-PATH body, no in-place
// region), its project verbs live in a hand-written `./x` outside the render set,
// and its config carries none of the awf-verb command vars, so it dogfoods the
// rendered defaults a fresh adopter gets.
//
// invariant: rendering/companion-scripts:runner-example-adopted
func TestExampleAdoptsRunner(t *testing.T) {
	cfg, err := os.ReadFile("../../examples/sundial/.awf/config.yaml")
	if err != nil {
		t.Fatalf("read example config: %v", err)
	}
	if !strings.Contains(string(cfg), "runner:") {
		t.Error("the sundial example must enable the runner singleton (ADR-0156)")
	}
	for _, dropped := range []string{"activeMdRegenCmd", "checkCmd", "commitGateCmd", "proseGateCmd", "memoryGateCmd"} {
		if strings.Contains(string(cfg), dropped) {
			t.Errorf("the sundial config must carry no awf-verb command var %q: it dogfoods the rendered defaults", dropped)
		}
	}
	raw, err := os.ReadFile("../../examples/sundial/awf")
	if err != nil {
		t.Fatalf("the sundial example must render awf: %v", err)
	}
	wrapper := string(raw)
	for _, want := range []string{
		"#!/usr/bin/env bash",
		`if [ -f .awf/bootstrap.sh ] && pinned="$(bash .awf/bootstrap.sh)"; then`,
		`exec "$pinned" "$@"`,
		`exec awf "$@"`,
	} {
		if !strings.Contains(wrapper, want) {
			t.Errorf("rendered examples/sundial/awf missing %q", want)
		}
	}
	if strings.Contains(wrapper, "awf:edit-in-place") {
		t.Errorf("the rendered wrapper must carry no in-place region:\n%s", wrapper)
	}
	x, err := os.ReadFile("../../examples/sundial/x")
	if err != nil {
		t.Fatalf("the sundial example must keep a hand-written project runner x: %v", err)
	}
	for _, want := range []string{"gate)", "test)"} {
		if !strings.Contains(string(x), want) {
			t.Errorf("hand-written examples/sundial/x missing project verb arm %q", want)
		}
	}
	if strings.Contains(string(x), "GENERATED by awf") {
		t.Error("examples/sundial/x must be hand-written, outside the render set")
	}
}

// The generated Pi extension carries `// @ts-nocheck` on the line after its
// provenance banner so adopter IDEs stay quiet without a resolvable
// `@types/node`, and the container gate strips that exact directive before
// `tsc` so the static type-check still covers the real extension code. Neither
// half stands alone: a missing strip leaves the lane green while `tsc` silently
// skips the file, so only this static assertion enforces the coupling.
//
// invariant: rendering/pi-workflows:pi-extension-editor-quiet-strip
