package project

import (
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/hypnotox/agentic-workflows/internal/config"
	"github.com/hypnotox/agentic-workflows/internal/manifest"
	"github.com/hypnotox/agentic-workflows/internal/testsupport"
)

// scaffold writes a .awf/config.yaml tree under a fresh temp root.
func scaffold(t *testing.T, configYAML string) string {
	return scaffoldFiles(t, configYAML, nil)
}

// testLayout returns a complete .layout template map — every key
// Layout.templateMap produces, with canonical docs/-rooted values — so a test
// that renders a template directly doesn't need to hand-pick which keys that
// template happens to reference today. A future Layout field addition only
// needs updating here, not at every hand-built fixture across the package.
func testLayout() map[string]any {
	return map[string]any{
		"docsDir":          "docs",
		"adrDir":           "docs/decisions",
		"activeMd":         "docs/decisions/ACTIVE.md",
		"adrReadme":        "docs/decisions/README.md",
		"adrTemplate":      "docs/decisions/template.md",
		"plansDir":         "docs/plans",
		"plansReadme":      "docs/plans/README.md",
		"docs":             map[string]any{},
		"workflowRef":      "docs/workflow.md",
		"docStandard":      "docs/doc-standard.md",
		"agentsMdStandard": "docs/agents-md-standard.md",
		"domainsDir":       "docs/domains",
	}
}

// scaffoldFiles writes config.yaml plus optional sidecar/part files keyed by path
// relative to .awf/ (e.g. "skills/tdd.yaml", "skills/parts/x/y.md").
func scaffoldFiles(t *testing.T, configYAML string, files map[string]string) string {
	t.Helper()
	root := t.TempDir()
	testsupport.WriteAwfConfig(t, root, configYAML)
	for rel, body := range files {
		testsupport.WriteFile(t, filepath.Join(root, ".awf", rel), body)
	}
	return root
}

// lockFile is the relocated lock path under the tree.
func lockFile(root string) string {
	return filepath.Join(root, ".awf", "awf.lock")
}

// configPath is the tree config file path.
func configPath(root string) string {
	return filepath.Join(root, ".awf", "config.yaml")
}

const sampleYAML = `prefix: example
vars:
  testCmd: go test ./...
  gateCmd: make gate
  gateCmdFull: make gate full
skills:
  - tdd
agents:
  - code-reviewer
`

func TestSyncWritesFilesAndLock(t *testing.T) {
	root := scaffold(t, sampleYAML)
	p, err := Open(root)
	if err != nil {
		t.Fatal(err)
	}
	if err := p.Sync(); err != nil {
		t.Fatal(err)
	}
	skill := filepath.Join(root, ".claude/skills/example-tdd/SKILL.md")
	b, err := os.ReadFile(skill)
	if err != nil {
		t.Fatalf("skill not written: %v", err)
	}
	if !strings.Contains(string(b), "# example-tdd") || strings.Contains(string(b), "awf:section") {
		t.Errorf("rendered skill wrong:\n%s", b)
	}
	if !strings.Contains(string(b), "GENERATED by awf") || !strings.Contains(string(b), "<!-- awf:edit ") {
		t.Errorf("rendered skill missing provenance banner/pointer:\n%s", b)
	}
	for _, rel := range []string{".claude/agents/code-reviewer.md", ".awf/awf.lock"} {
		if _, err := os.Stat(filepath.Join(root, rel)); err != nil {
			t.Errorf("missing %s: %v", rel, err)
		}
	}
}

// invariant: target-prune-ancestors
func TestSyncPrunesRemovedTargetTree(t *testing.T) {
	root := scaffold(t, sampleYAML+"targets:\n  - claude\n  - cursor\n")
	p, err := Open(root)
	if err != nil {
		t.Fatal(err)
	}
	if err := p.Sync(); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(root, ".cursor/skills/example-tdd/SKILL.md")); err != nil {
		t.Fatalf("expected cursor skill rendered on first sync: %v", err)
	}
	// Drop the cursor target (sampleYAML has no targets: key → defaults to claude).
	if err := os.WriteFile(filepath.Join(root, ".awf", "config.yaml"), []byte(sampleYAML), 0o644); err != nil {
		t.Fatal(err)
	}
	p2, err := Open(root)
	if err != nil {
		t.Fatal(err)
	}
	if err := p2.Sync(); err != nil {
		t.Fatal(err)
	}
	// The whole .cursor/ tree is gone — every empty ancestor, not just the leaf parent.
	for _, dir := range []string{".cursor/skills/example-tdd", ".cursor/skills", ".cursor/agents", ".cursor"} {
		if _, err := os.Stat(filepath.Join(root, dir)); !os.IsNotExist(err) {
			t.Errorf("expected %s removed, stat err = %v", dir, err)
		}
	}
}

func TestCheckCleanAfterSync(t *testing.T) {
	root := scaffold(t, sampleYAML)
	p, _ := Open(root)
	if err := p.Sync(); err != nil {
		t.Fatal(err)
	}
	drift, err := p.Check()
	if err != nil {
		t.Fatal(err)
	}
	if len(drift) != 0 {
		t.Errorf("expected clean, got drift: %#v", drift)
	}
}

func TestCheckDetectsHandEdit(t *testing.T) {
	root := scaffold(t, sampleYAML)
	p, _ := Open(root)
	_ = p.Sync()
	skill := filepath.Join(root, ".claude/skills/example-tdd/SKILL.md")
	_ = os.WriteFile(skill, []byte("hand edited\n"), 0o644)
	drift, _ := p.Check()
	if len(drift) == 0 || drift[0].Kind != "hand-edited" {
		t.Errorf("expected hand-edited drift, got %#v", drift)
	}
}

func TestCheckStaleTakesPrecedence(t *testing.T) {
	root := scaffold(t, sampleYAML)
	p, _ := Open(root)
	if err := p.Sync(); err != nil {
		t.Fatal(err)
	}
	skillPath := ".claude/skills/example-tdd/SKILL.md"
	// Make the lock entry stale by corrupting its TemplateHash.
	lock, err := manifest.Load(lockFile(root))
	if err != nil {
		t.Fatal(err)
	}
	e := lock.Files[skillPath]
	e.TemplateHash = "sha256:bogus"
	lock.Files[skillPath] = e
	if err := lock.Save(lockFile(root)); err != nil {
		t.Fatal(err)
	}
	// Also hand-edit the rendered file so its on-disk content differs too.
	if err := os.WriteFile(filepath.Join(root, skillPath), []byte("hand edited\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	drift, err := p.Check()
	if err != nil {
		t.Fatal(err)
	}
	var forPath []manifest.Drift
	for _, d := range drift {
		if d.Path == skillPath {
			forPath = append(forPath, d)
		}
	}
	if len(forPath) != 1 {
		t.Fatalf("expected exactly one drift entry for %s, got %#v", skillPath, forPath)
	}
	if forPath[0].Kind != "stale" {
		t.Errorf("expected stale, got %q", forPath[0].Kind)
	}
}

func TestSyncSkipsLocalSkill(t *testing.T) {
	cfg := `prefix: example
vars:
  testCmd: go test ./...
  gateCmd: make gate
skills:
  - adding-thing
  - tdd
agents:
  - code-reviewer
`
	root := scaffoldFiles(t, cfg, map[string]string{
		"skills/adding-thing.yaml": "local: true\n",
	})
	// A local skill is hand-authored; provide its on-disk file with valid frontmatter.
	localPath := ".claude/skills/example-adding-thing/SKILL.md"
	writeLocalSkill(t, root, localPath)
	p, err := Open(root)
	if err != nil {
		t.Fatal(err)
	}
	if err := p.Sync(); err != nil {
		t.Fatal(err)
	}
	lock, err := manifest.Load(lockFile(root))
	if err != nil {
		t.Fatal(err)
	}
	if _, ok := lock.Files[localPath]; ok {
		t.Errorf("local skill should be absent from lock")
	}
	if _, ok := lock.Files[".claude/skills/example-tdd/SKILL.md"]; !ok {
		t.Errorf("tdd skill should still be present in lock")
	}
}

// writeLocalSkill writes a hand-authored local skill file with valid frontmatter.
func writeLocalSkill(t *testing.T, root, rel string) {
	t.Helper()
	abs := filepath.Join(root, rel)
	if err := os.MkdirAll(filepath.Dir(abs), 0o755); err != nil {
		t.Fatal(err)
	}
	body := "---\nname: local-skill\ndescription: a hand-authored local skill\n---\nbody\n"
	if err := os.WriteFile(abs, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
}

func TestOpenRejectsUnknownAgent(t *testing.T) {
	root := scaffold(t, "prefix: example\nskills: []\nagents: [does-not-exist]\n")
	_, err := Open(root)
	if err == nil {
		t.Fatal("expected error for unknown agent")
	}
	if !strings.Contains(err.Error(), "does-not-exist") {
		t.Errorf("error should mention the offending agent name, got: %v", err)
	}
}

func TestOpenRejectsUnknownDoc(t *testing.T) {
	root := scaffold(t, "prefix: example\nskills: []\nagents: []\ndocs: [nonexistent]\n")
	_, err := Open(root)
	if err == nil {
		t.Fatal("expected error for unknown doc")
	}
	if !strings.Contains(err.Error(), "nonexistent") {
		t.Errorf("error should mention the offending doc name, got: %v", err)
	}
}

func TestSyncRendersDeclaredDoc(t *testing.T) {
	root := scaffold(t, "prefix: example\nskills: []\nagents: []\ndocs: [architecture]\n")
	p, err := Open(root)
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	if err := p.Sync(); err != nil {
		t.Fatalf("Sync: %v", err)
	}
	b, err := os.ReadFile(filepath.Join(root, "docs", "architecture.md"))
	if err != nil {
		t.Fatalf("docs/architecture.md not written: %v", err)
	}
	if !strings.Contains(string(b), "# Architecture") {
		t.Errorf("docs/architecture.md missing heading:\n%s", b)
	}
}

// TestSyncAutoLinksDocsInAgentsDoc covers the project-level wiring that the
// template golden cannot: RenderAll injects resolvedDocs() into the agents-doc
// data map so the Document map auto-links every declared (non-local) doc with
// its catalog title/desc. A local doc must not appear.
func TestSyncAutoLinksDocsInAgentsDoc(t *testing.T) {
	cfg := `prefix: example
vars:
  gateCmd: ""
skills: []
agents: []
docs:
  - architecture
  - glossary
`
	root := scaffoldFiles(t, cfg, map[string]string{
		"docs/glossary.yaml": "local: true\n",
	})
	p, err := Open(root)
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	if err := p.Sync(); err != nil {
		t.Fatalf("Sync: %v", err)
	}
	b, err := os.ReadFile(filepath.Join(root, "AGENTS.md"))
	if err != nil {
		t.Fatalf("AGENTS.md not written: %v", err)
	}
	got := string(b)
	if !strings.Contains(got, "[docs/architecture.md](docs/architecture.md)") {
		t.Errorf("Document map should auto-link the declared architecture doc:\n%s", got)
	}
	if !strings.Contains(got, "system shape, packages, key components, dependencies") {
		t.Errorf("Document map should carry the catalog desc for architecture:\n%s", got)
	}
	if strings.Contains(got, "docs/glossary.md") {
		t.Errorf("local doc must not appear in the Document map:\n%s", got)
	}
}

func TestOpenRejectsUnknownSkill(t *testing.T) {
	root := scaffold(t, "prefix: example\nskills: [no-such-skill]\nagents: []\n")
	_, err := Open(root)
	if err == nil {
		t.Fatal("expected error for unknown skill")
	}
	if !strings.Contains(err.Error(), "no-such-skill") {
		t.Errorf("error should mention the offending skill name, got: %v", err)
	}
}

func TestOpenValidConfigSucceeds(t *testing.T) {
	root := scaffold(t, sampleYAML)
	_, err := Open(root)
	if err != nil {
		t.Fatalf("expected valid config to open cleanly, got: %v", err)
	}
}

func TestOpenAllowsLocalSkillNotInCatalog(t *testing.T) {
	cfg := strings.Replace(sampleYAML, "skills:\n  - tdd\n", "skills:\n  - totally-unknown-local\n  - tdd\n", 1)
	root := scaffoldFiles(t, cfg, map[string]string{
		"skills/totally-unknown-local.yaml": "local: true\n",
	})
	_, err := Open(root)
	if err != nil {
		t.Fatalf("local skill not in catalog should be allowed, got: %v", err)
	}
}

func TestSyncPrunesRemovedSkill(t *testing.T) {
	root := scaffold(t, sampleYAML)
	p, _ := Open(root)
	_ = p.Sync()
	// Rewrite config without the tdd skill, re-open, re-sync.
	noTDD := strings.Replace(sampleYAML, "skills:\n  - tdd\n", "skills: []\n", 1)
	_ = os.WriteFile(configPath(root), []byte(noTDD), 0o644)
	p2, _ := Open(root)
	if err := p2.Sync(); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(root, ".claude/skills/example-tdd/SKILL.md")); !os.IsNotExist(err) {
		t.Errorf("removed skill should be pruned")
	}
}

func TestOpenRejectsUnknownSectionOverride(t *testing.T) {
	// tdd in the catalog has sections [surfaces, notes]; "bogus" is not declared.
	cfg := "prefix: example\nskills: [tdd]\nagents: [code-reviewer]\n"
	root := scaffoldFiles(t, cfg, map[string]string{
		"skills/tdd.yaml": "sections:\n  bogus:\n    drop: true\n",
	})
	_, err := Open(root)
	if err == nil {
		t.Fatal("expected error for unknown section override 'bogus'")
	}
	if !strings.Contains(err.Error(), "bogus") {
		t.Errorf("error should mention 'bogus', got: %v", err)
	}
}

func TestOpenAllowsValidSectionOverride(t *testing.T) {
	// "notes" is a declared section for tdd.
	cfg := "prefix: example\nskills: [tdd]\nagents: [code-reviewer]\n"
	root := scaffoldFiles(t, cfg, map[string]string{
		"skills/tdd.yaml": "sections:\n  notes:\n    drop: true\n",
	})
	_, err := Open(root)
	if err != nil {
		t.Fatalf("valid section override 'notes' should succeed, got: %v", err)
	}
}

func TestOpenAllowsLocalAgentNotInCatalog(t *testing.T) {
	cfg := "prefix: example\nskills: []\nagents: [my-custom-agent]\n"
	root := scaffoldFiles(t, cfg, map[string]string{
		"agents/my-custom-agent.yaml": "local: true\n",
	})
	_, err := Open(root)
	if err != nil {
		t.Fatalf("local agent not in catalog should be allowed, got: %v", err)
	}
}

func TestOpenRejectsUnknownAgentSectionOverride(t *testing.T) {
	// code-reviewer in the catalog has sections universal-lenses/project-focus/doc-currency.
	cfg := "prefix: example\nskills: []\nagents: [code-reviewer]\n"
	root := scaffoldFiles(t, cfg, map[string]string{
		"agents/code-reviewer.yaml": "sections:\n  bogus:\n    drop: true\n",
	})
	_, err := Open(root)
	if err == nil {
		t.Fatal("expected error for unknown agent section override 'bogus'")
	}
	if !strings.Contains(err.Error(), "bogus") {
		t.Errorf("error should mention 'bogus', got: %v", err)
	}
}

func TestSyncRendersAgentFromMap(t *testing.T) {
	root := scaffold(t, "prefix: myproject\nagents: [code-reviewer]\nskills: []\n")
	p, err := Open(root)
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	if err := p.Sync(); err != nil {
		t.Fatalf("Sync: %v", err)
	}
	agentPath := filepath.Join(root, ".claude/agents/code-reviewer.md")
	b, err := os.ReadFile(agentPath)
	if err != nil {
		t.Fatalf("agent file not written: %v", err)
	}
	if !strings.Contains(string(b), "myproject") {
		t.Errorf("agent file should contain prefix 'myproject', got:\n%s", b)
	}
}

// TestSyncErrorsOnMissingVar verifies that Sync returns an error when a rendered
// template would contain the literal string "<no value>" due to a missing var.
// The tdd skill references {{ .vars.testCmd }} and {{ .vars.gateCmd }} without
// guards, so omitting them from vars triggers the check.
func TestSyncErrorsOnMissingVar(t *testing.T) {
	root := scaffold(t, "prefix: example\nvars: {}\nskills: [tdd]\nagents: []\n")
	p, err := Open(root)
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	err = p.Sync()
	if err == nil {
		t.Fatal("expected Sync to return an error when vars are missing, got nil")
	}
	if !strings.Contains(err.Error(), "<no value>") {
		t.Errorf("error should mention \"<no value>\", got: %v", err)
	}
}

func TestSyncRendersAgentsDoc(t *testing.T) {
	t.Run("always-on by default", func(t *testing.T) {
		root := scaffold(t, "prefix: example\nvars:\n  testCmd: go test ./...\n  gateCmd: make gate\nskills: []\nagents: []\n")
		p, err := Open(root)
		if err != nil {
			t.Fatalf("Open: %v", err)
		}
		if err := p.Sync(); err != nil {
			t.Fatalf("Sync: %v", err)
		}
		b, err := os.ReadFile(filepath.Join(root, "AGENTS.md"))
		if err != nil {
			t.Fatalf("AGENTS.md not written: %v", err)
		}
		if !strings.Contains(string(b), "example") {
			t.Errorf("AGENTS.md should contain prefix 'example', got:\n%s", b)
		}
	})

	t.Run("a local agents-doc sidecar suppresses it", func(t *testing.T) {
		root := scaffoldFiles(t, "prefix: example\nskills: []\nagents: []\n", map[string]string{
			"agents-doc.yaml": "local: true\n",
		})
		p, err := Open(root)
		if err != nil {
			t.Fatalf("Open: %v", err)
		}
		if err := p.Sync(); err != nil {
			t.Fatalf("Sync: %v", err)
		}
		if _, err := os.Stat(filepath.Join(root, "AGENTS.md")); !os.IsNotExist(err) {
			t.Errorf("AGENTS.md should not exist when agents-doc is local")
		}
	})
}

// TestSyncPrunesEmptySkillDir verifies that after a skill is removed from config
// and Sync runs again, both the SKILL.md file and its now-empty parent directory
// are removed.
func TestSyncPrunesEmptySkillDir(t *testing.T) {
	root := scaffold(t, sampleYAML)
	p, err := Open(root)
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	if err := p.Sync(); err != nil {
		t.Fatalf("first Sync: %v", err)
	}
	skillDir := filepath.Join(root, ".claude/skills/example-tdd")
	if _, err := os.Stat(skillDir); err != nil {
		t.Fatalf("skill dir should exist after first sync: %v", err)
	}

	noTDD := strings.Replace(sampleYAML, "skills:\n  - tdd\n", "skills: []\n", 1)
	if err := os.WriteFile(configPath(root), []byte(noTDD), 0o644); err != nil {
		t.Fatalf("rewrite config: %v", err)
	}
	p2, err := Open(root)
	if err != nil {
		t.Fatalf("Open after removing tdd skill: %v", err)
	}
	if err := p2.Sync(); err != nil {
		t.Fatalf("second Sync: %v", err)
	}

	if _, err := os.Stat(filepath.Join(skillDir, "SKILL.md")); !os.IsNotExist(err) {
		t.Errorf("SKILL.md should have been pruned")
	}
	if _, err := os.Stat(skillDir); !os.IsNotExist(err) {
		t.Errorf("skill directory %s should have been pruned when empty", skillDir)
	}
}

// invariant: layout-derivation
func TestLayoutDerivesFromDocsDir(t *testing.T) {
	p := &Project{Cfg: &config.Config{DocsDir: "documentation", Docs: []string{"architecture"}}}
	l := p.layout()
	if l.DocsDir != "documentation" || l.ADRDir != "documentation/decisions" ||
		l.ActiveMd != "documentation/decisions/ACTIVE.md" || l.AdrReadme != "documentation/decisions/README.md" ||
		l.AdrTemplate != "documentation/decisions/template.md" || l.PlansDir != "documentation/plans" ||
		l.PlansReadme != "documentation/plans/README.md" {
		t.Errorf("layout = %+v", l)
	}
	// invariant: domains-dir-given
	if l.DomainsDir != "documentation/domains" {
		t.Errorf("domainsDir = %q", l.DomainsDir)
	}
	// workflow/doc-standard/agents-md-standard are mandatory singletons (ADR-0043):
	// their paths are always fixed, never fall back or depend on Cfg.Docs.
	if l.WorkflowRef != "documentation/workflow.md" {
		t.Errorf("workflowRef = %q", l.WorkflowRef)
	}
	if l.DocStandard != "documentation/doc-standard.md" {
		t.Errorf("docStandard = %q", l.DocStandard)
	}
	if l.AgentsMdStandard != "documentation/agents-md-standard.md" {
		t.Errorf("agentsMdStandard = %q", l.AgentsMdStandard)
	}
	// invariant: layout-docs-enabled-only
	wantDocs := map[string]string{
		"architecture": "documentation/architecture.md",
	}
	if !reflect.DeepEqual(l.Docs, wantDocs) {
		t.Errorf("Docs = %v, want %v", l.Docs, wantDocs)
	}
	// templateMap reproduces the historical .layout map (ConfigHash stability).
	tm := l.templateMap()
	for _, k := range []string{"docsDir", "adrDir", "activeMd", "adrReadme", "adrTemplate",
		"plansDir", "plansReadme", "docs", "workflowRef", "docStandard", "agentsMdStandard", "domainsDir"} {
		if _, ok := tm[k]; !ok {
			t.Errorf("templateMap missing key %q", k)
		}
	}
	if got := p.docOutPath("architecture"); got != "documentation/architecture.md" {
		t.Errorf("docOutPath = %q", got)
	}
}

// invariant: doc-gated-skill-suppressed
func TestRenderAllSuppressesDocGatedSkill(t *testing.T) {
	// roadmap-graduation cites .layout.docs.roadmap (populated when the roadmap doc
	// is enabled); agents-doc is suppressed via a local sidecar so RenderAll renders
	// only the gated skill (and, when its doc is enabled, the roadmap doc itself).
	cfg := "prefix: example\nskills: [roadmap-graduation]\nagents: []\n"
	root := scaffoldFiles(t, cfg, map[string]string{"agents-doc.yaml": "local: true\n"})
	p, err := Open(root)
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	// Gate roadmap-graduation on the roadmap doc (the catalog sets requiresDoc in a
	// later phase; assert the mechanism independently here).
	sk := p.Cat.Skills["roadmap-graduation"]
	sk.RequiresDoc = "roadmap"
	p.Cat.Skills["roadmap-graduation"] = sk

	const rel = ".claude/skills/example-roadmap-graduation/SKILL.md"
	rendered := func() bool {
		files, err := p.RenderAll()
		if err != nil {
			t.Fatalf("RenderAll: %v", err)
		}
		for _, f := range files {
			if f.Path == rel {
				return true
			}
		}
		return false
	}
	// Doc not enabled → suppressed.
	if rendered() {
		t.Error("roadmap-graduation should be suppressed when the roadmap doc is not enabled")
	}
	// Doc enabled → rendered.
	p.Cfg.Docs = []string{"roadmap"}
	if !rendered() {
		t.Error("roadmap-graduation should render when the roadmap doc is enabled")
	}
}

// invariant: sync-generates-active-md
// invariant: check-active-md-stale
func TestSyncGeneratesActiveMDAndCheckDetectsStaleness(t *testing.T) {
	root := scaffold(t, "prefix: example\nskills: []\nagents: []\n")
	adrDir := filepath.Join(root, "docs", "decisions")
	if err := os.MkdirAll(adrDir, 0o755); err != nil {
		t.Fatal(err)
	}
	adrBody := "---\nstatus: Accepted\ndate: 2026-06-25\ntags: [x]\n---\n# ADR-0001: First\n## Context\nx\n"
	if err := os.WriteFile(filepath.Join(adrDir, "0001-first.md"), []byte(adrBody), 0o644); err != nil {
		t.Fatal(err)
	}

	p, err := Open(root)
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	if err := p.Sync(); err != nil {
		t.Fatalf("Sync: %v", err)
	}
	active, err := os.ReadFile(filepath.Join(adrDir, "ACTIVE.md"))
	if err != nil {
		t.Fatalf("ACTIVE.md not generated: %v", err)
	}
	if !strings.Contains(string(active), "ADR-0001: First") {
		t.Errorf("ACTIVE.md missing the ADR entry:\n%s", active)
	}
	if drift, err := p.Check(); err != nil || len(drift) != 0 {
		t.Fatalf("expected clean check after sync, got drift=%#v err=%v", drift, err)
	}

	// Change frontmatter status; the on-disk ACTIVE.md is now stale.
	adr2 := strings.Replace(adrBody, "status: Accepted", "status: Implemented", 1)
	if err := os.WriteFile(filepath.Join(adrDir, "0001-first.md"), []byte(adr2), 0o644); err != nil {
		t.Fatal(err)
	}
	drift, err := p.Check()
	if err != nil {
		t.Fatalf("Check: %v", err)
	}
	found := false
	for _, d := range drift {
		if strings.HasSuffix(d.Path, "decisions/ACTIVE.md") && d.Kind == "stale" {
			found = true
		}
	}
	if !found {
		t.Errorf("expected stale drift for ACTIVE.md, got %#v", drift)
	}
}

// invariant: sync-generates-active-md
func TestSyncRendersPlaceholderActiveMDWithoutADRs(t *testing.T) {
	root := scaffold(t, "prefix: example\nskills: []\nagents: []\n")
	p, err := Open(root)
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	if err := p.Sync(); err != nil {
		t.Fatalf("Sync: %v", err)
	}
	got, err := os.ReadFile(filepath.Join(root, "docs", "decisions", "ACTIVE.md"))
	if err != nil {
		t.Fatalf("expected a placeholder ACTIVE.md when no ADRs exist: %v", err)
	}
	if !strings.Contains(string(got), "No decisions recorded yet") {
		t.Errorf("expected placeholder index, got:\n%s", got)
	}
	if drift, err := p.Check(); err != nil || len(drift) != 0 {
		t.Errorf("expected clean check with no ADRs, got drift=%#v err=%v", drift, err)
	}
}

// invariant: check-invalid-frontmatter
func TestCheckDetectsInvalidFrontmatter(t *testing.T) {
	root := scaffold(t, sampleYAML)
	p, _ := Open(root)
	if err := p.Sync(); err != nil {
		t.Fatal(err)
	}
	skillPath := ".claude/skills/example-tdd/SKILL.md"
	broken := "---\nname: \"\"\ndescription: \"\"\n---\nbody\n"
	if err := os.WriteFile(filepath.Join(root, skillPath), []byte(broken), 0o644); err != nil {
		t.Fatal(err)
	}
	// Re-point the lock OutputHash to the edited content so the file is "in sync"
	// by hash and the frontmatter check is what fires.
	lock, err := manifest.Load(lockFile(root))
	if err != nil {
		t.Fatal(err)
	}
	e := lock.Files[skillPath]
	e.OutputHash = manifest.Hash([]byte(broken))
	lock.Files[skillPath] = e
	if err := lock.Save(lockFile(root)); err != nil {
		t.Fatal(err)
	}
	drift, err := p.Check()
	if err != nil {
		t.Fatal(err)
	}
	found := false
	for _, d := range drift {
		if d.Path == skillPath && d.Kind == "invalid-frontmatter" {
			found = true
		}
	}
	if !found {
		t.Errorf("expected invalid-frontmatter drift for %s, got %#v", skillPath, drift)
	}
}

// invariant: adr-system-singletons-rendered
// invariant: plain-singleton-via-renderkind
func TestAdrSingletonsRenderedAndSuppressible(t *testing.T) {
	root := scaffold(t, sampleYAML)
	p, err := Open(root)
	if err != nil {
		t.Fatal(err)
	}
	files, err := p.RenderAll()
	if err != nil {
		t.Fatal(err)
	}
	want := map[string]bool{
		"docs/decisions/README.md":   false,
		"docs/decisions/template.md": false,
		"docs/plans/README.md":       false,
		"docs/workflow.md":           false,
		"docs/doc-standard.md":       false,
		"docs/agents-md-standard.md": false,
	}
	for _, f := range files {
		if _, ok := want[f.Path]; ok {
			want[f.Path] = true
		}
	}
	for path, seen := range want {
		if !seen {
			t.Errorf("%s not rendered", path)
		}
	}
	// local: true suppresses the README singleton.
	if err := os.WriteFile(filepath.Join(root, ".awf", "adr-readme.yaml"), []byte("local: true\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	// local: true also suppresses a newly-mandatory singleton, matching the other four (ADR-0043
	// Decision item 1: "not togglable" keeps the local: true escape hatch).
	if err := os.WriteFile(filepath.Join(root, ".awf", "workflow.yaml"), []byte("local: true\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	p2, err := Open(root)
	if err != nil {
		t.Fatal(err)
	}
	files2, err := p2.RenderAll()
	if err != nil {
		t.Fatal(err)
	}
	for _, f := range files2 {
		if f.Path == "docs/decisions/README.md" {
			t.Error("README should be suppressed by local: true")
		}
		if f.Path == "docs/workflow.md" {
			t.Error("workflow.md should be suppressed by local: true")
		}
	}
}

func TestSyncReportBacksUpForeignIndexNotManaged(t *testing.T) {
	root := scaffold(t, sampleYAML)
	p, err := Open(root)
	if err != nil {
		t.Fatal(err)
	}
	lay := p.layout()
	// Plant a foreign ADR index with hand content before the first sync (no lock yet),
	// so its path is absent from the prior lock and therefore foreign.
	foreign := filepath.Join(root, lay.ActiveMd)
	if err := os.MkdirAll(filepath.Dir(foreign), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(foreign, []byte("hand index\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	backups, err := p.SyncReport()
	if err != nil {
		t.Fatalf("SyncReport: %v", err)
	}
	var got *Backup
	for i := range backups {
		if backups[i].Path == lay.ActiveMd {
			got = &backups[i]
		}
	}
	if got == nil {
		t.Fatalf("foreign ACTIVE.md not backed up; backups=%#v", backups)
	}
	if !got.Index {
		t.Errorf("ACTIVE.md backup must be flagged Index=true")
	}
	if b, _ := os.ReadFile(filepath.Join(root, got.Bak)); string(b) != "hand index\n" {
		t.Errorf("backup = %q, want original hand content", b)
	}
	// A path recorded in the prior lock is awf-managed: a second sync backs up nothing.
	again, err := p.SyncReport()
	if err != nil {
		t.Fatal(err)
	}
	if len(again) != 0 {
		t.Errorf("re-sync of awf-managed output must not back up, got %#v", again)
	}
}

func TestIsGeneratedIndex(t *testing.T) {
	root := scaffold(t, sampleYAML)
	p, err := Open(root)
	if err != nil {
		t.Fatal(err)
	}
	lay := p.layout()
	if !p.isGeneratedIndex(lay.ActiveMd) {
		t.Errorf("ActiveMd must be a generated index (true via ==)")
	}
	if !p.isGeneratedIndex(lay.DomainsDir + "/rendering.md") {
		t.Errorf("a per-domain index must be a generated index (true via prefix)")
	}
	if p.isGeneratedIndex(lay.DocsDir + "/architecture.md") {
		t.Errorf("an ordinary doc must not be a generated index (false)")
	}
}

// invariant: document-map-lists-mandatory-docs
func TestAgentsDocDocumentMapListsMandatorySingletonsUnconditionally(t *testing.T) {
	root := scaffold(t, "prefix: example\nskills: []\nagents: []\ndocs: []\n")
	p, err := Open(root)
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	if err := p.Sync(); err != nil {
		t.Fatalf("Sync: %v", err)
	}
	b, err := os.ReadFile(filepath.Join(root, "AGENTS.md"))
	if err != nil {
		t.Fatalf("AGENTS.md not written: %v", err)
	}
	got := string(b)
	for _, want := range []string{
		"[docs/workflow.md](docs/workflow.md)",
		"[docs/doc-standard.md](docs/doc-standard.md)",
		"[docs/agents-md-standard.md](docs/agents-md-standard.md)",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("Document map should unconditionally cite %s (docs: array is empty):\n%s", want, got)
		}
	}
}
