package project

import (
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"github.com/hypnotox/agentic-workflows/internal/catalog"
	"github.com/hypnotox/agentic-workflows/internal/manifest"
)

var fixedAWFSkillNames = []string{"awf-decisions", "awf-effort", "awf-maintenance", "awf-topics"}

func TestFreshSyncPublishesExactlyFourFixedSkillsAcrossPrefixes(t *testing.T) {
	for _, prefix := range []string{"awf", "custom-project"} {
		t.Run(prefix, func(t *testing.T) {
			root := scaffold(t, "prefix: "+prefix+"\nintegrationBranch: main\n")
			p, err := loadTestSession(testContext(t), root)
			if err != nil {
				t.Fatal(err)
			}
			if err := syncProject(p); err != nil {
				t.Fatal(err)
			}
			for _, rel := range []string{".claude/skills", ".pi/skills"} {
				entries, err := os.ReadDir(filepath.Join(root, rel))
				if err != nil {
					t.Fatal(err)
				}
				got := make([]string, 0, len(entries))
				for _, entry := range entries {
					if entry.IsDir() {
						got = append(got, entry.Name())
					}
				}
				slices.Sort(got)
				if !slices.Equal(got, fixedAWFSkillNames) {
					t.Fatalf("%s skills = %v, want %v", rel, got, fixedAWFSkillNames)
				}
			}
			for _, rel := range []string{".claude/agents", ".pi/agents", ".pi/extensions/awf-subagents"} {
				if _, err := os.Lstat(filepath.Join(root, rel)); !os.IsNotExist(err) {
					t.Fatalf("retired AWF role or adapter path %s exists: %v", rel, err)
				}
			}
		})
	}
}

func TestSyncCoexistsWithAgenticSkillAndRoleIdentities(t *testing.T) {
	root := scaffold(t, "prefix: project\nintegrationBranch: main\n")
	foreign := map[string]string{
		".claude/skills/agentic-context/SKILL.md":             "claude generic skill\n",
		".claude/agents/agentic-explorer.md":                  "claude role\n",
		".pi/skills/agentic-context/SKILL.md":                 "pi generic skill\n",
		".pi/agents/agentic-explorer.md":                      "pi role\n",
		".pi/extensions/agentic-skills-pi-subagents/index.ts": "pi adapter\n",
	}
	for rel, body := range foreign {
		path := filepath.Join(root, filepath.FromSlash(rel))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(body), 0o640); err != nil {
			t.Fatal(err)
		}
	}
	p, err := loadTestSession(testContext(t), root)
	if err != nil {
		t.Fatal(err)
	}
	if err := syncProject(p); err != nil {
		t.Fatal(err)
	}
	for rel, want := range foreign {
		path := filepath.Join(root, filepath.FromSlash(rel))
		got, err := os.ReadFile(path)
		if err != nil || string(got) != want {
			t.Fatalf("foreign package artifact %s = %q, %v; want %q", rel, got, err, want)
		}
		info, err := os.Stat(path)
		if err != nil || info.Mode().Perm() != 0o640 {
			t.Fatalf("foreign package artifact %s mode = %v, %v", rel, info, err)
		}
	}
	for _, target := range p.Targets() {
		for _, name := range fixedAWFSkillNames {
			if _, err := os.Stat(filepath.Join(root, target.SkillPath(name))); err != nil {
				t.Fatalf("AWF skill %s missing beside external identities: %v", name, err)
			}
		}
	}
}

func TestSyncWritesFilesAndLock(t *testing.T) {
	root := scaffold(t, sampleYAML)
	p, err := loadTestSession(testContext(t), root)
	if err != nil {
		t.Fatal(err)
	}
	if err := syncProject(p); err != nil {
		t.Fatal(err)
	}
	skill := filepath.Join(root, ".claude/skills/awf-maintenance/SKILL.md")
	b, err := os.ReadFile(skill)
	if err != nil {
		t.Fatalf("skill not written: %v", err)
	}
	if !strings.Contains(string(b), "# AWF maintenance") || (strings.Contains(string(b), "awf:section") && !strings.Contains(string(b), "awf:edit")) {
		t.Errorf("rendered skill wrong:\n%s", b)
	}
	if !strings.Contains(string(b), "GENERATED by awf") || !strings.Contains(string(b), "<!-- awf:edit ") {
		t.Errorf("rendered skill missing provenance banner/pointer:\n%s", b)
	}
	for _, rel := range []string{".claude/skills/awf-effort/SKILL.md", ".awf/awf.lock"} {
		if _, err := os.Stat(filepath.Join(root, rel)); err != nil {
			t.Errorf("missing %s: %v", rel, err)
		}
	}
}

func TestSyncRendersDeclaredDoc(t *testing.T) {
	root := scaffold(t, "prefix: example\nintegrationBranch: main\n")
	p, err := loadTestSession(testContext(t), root)
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	if err := syncProject(p); err != nil {
		t.Fatalf("Sync: %v", err)
	}
	b, err := os.ReadFile(filepath.Join(root, "docs", "architecture.md"))
	if err != nil {
		t.Fatalf("docs/architecture.md not written: %v", err)
	}
	if !strings.Contains(string(b), "# Architecture") {
		t.Errorf("docs/architecture.md missing heading:\n%s", b)
	}
}

// TestSyncErrorsOnUnresolvedValueToken verifies the publication-safety net:
// Sync errors when rendered output contains the literal unresolved-value token.
// Since ADR-0045 every shipped var interpolation degrades gracefully, so the
// trigger here is content that carries the token itself (the ADR-0011/ADR-0014
// gotcha: prose containing the literal token trips the guard).
func TestSyncRendersAgentsDoc(t *testing.T) {
	t.Run("always-on by default", func(t *testing.T) {
		root := scaffold(t, "prefix: example\nintegrationBranch: main\nvars:\n  testCmd: go test ./...\n  gateCmd: make gate\n")
		p, err := loadTestSession(testContext(t), root)
		if err != nil {
			t.Fatalf("Open: %v", err)
		}
		if err := syncProject(p); err != nil {
			t.Fatalf("Sync: %v", err)
		}
		b, err := os.ReadFile(filepath.Join(root, "AGENTS.md"))
		if err != nil {
			t.Fatalf("AGENTS.md not written: %v", err)
		}
		if !strings.Contains(string(b), "example") {
			t.Errorf("AGENTS.md should contain prefix 'example', got:\n%s", b)
		}
	})
}

// invariant: rendering/project-output-plan:output-plan-complete (TestRenderAllRendersFullCatalogForBothTargets)
func TestRenderAllRendersFullCatalogForBothTargets(t *testing.T) {
	cfg := "prefix: example\nintegrationBranch: main\n"
	root := scaffold(t, cfg)
	p, err := loadTestSession(testContext(t), root)
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	if got := len(p.Targets()); got != len(KnownTargets()) {
		t.Fatalf("targets = %d, want full built-in set of %d", got, len(KnownTargets()))
	}
	files, err := renderAll(p)
	if err != nil {
		t.Fatalf("RenderAll: %v", err)
	}
	paths := map[string]bool{}
	for _, file := range files {
		paths[file.Path] = true
	}
	for _, target := range p.Targets() {
		for name := range catalog.Standard.Skills {
			if path := target.SkillPath(name); !paths[path] {
				t.Errorf("missing catalog skill output %q", path)
			}
		}
	}
	for name, entry := range catalog.Standard.Docs {
		path := "docs/" + name + ".md"
		if entry.Path != "" {
			path = "docs/" + entry.Path
		}
		if entry.AgentsDoc {
			path = "AGENTS.md"
		}
		if !paths[path] {
			t.Errorf("missing catalog document %q at %q", name, path)
		}
	}
	for _, path := range []string{"docs/debugging.md"} {
		if !paths[path] {
			t.Errorf("missing unconditional catalog output %q", path)
		}
	}
	notes, err := advisoryNotesProject(p)
	if err != nil {
		t.Fatalf("AdvisoryNotes: %v", err)
	}
	joined := strings.Join(notes, "\n")
	for _, path := range []string{"docs/debugging.md"} {
		if !strings.Contains(joined, path+" has unauthored stub content") {
			t.Errorf("missing non-failing stub advisory for %s in:\n%s", path, joined)
		}
	}
}

// invariant: rendering/guide-and-doc-templates:document-map-lists-mandatory-docs (TestAgentsDocDocumentMapListsMandatorySingletonsUnconditionally)
func TestAgentsDocDocumentMapListsMandatorySingletonsUnconditionally(t *testing.T) {
	root := scaffold(t, "prefix: example\nintegrationBranch: main\n")
	p, err := loadTestSession(testContext(t), root)
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	if err := syncProject(p); err != nil {
		t.Fatalf("Sync: %v", err)
	}
	b, err := os.ReadFile(filepath.Join(root, "AGENTS.md"))
	if err != nil {
		t.Fatalf("AGENTS.md not written: %v", err)
	}
	got := string(b)
	// Iterate the catalog's DocumentMap entries (default docsDir "docs") so a new
	// mandatory document-map doc cannot silently stop being covered (ADR-0061).
	mapped := 0
	for name, e := range catalog.Standard.Docs {
		if !e.DocumentMap {
			continue
		}
		mapped++
		// Assert the whole rendered line - title, link, and catalog desc - so a
		// mandatory doc is cited with its data-driven title/desc, not just linked.
		line := fmt.Sprintf("- **%s:** [docs/%s](docs/%s), %s", e.Title, e.Path, e.Path, e.Desc)
		if !strings.Contains(got, line) {
			t.Errorf("Document map should unconditionally cite %q (%s; %s", line, name, got)
		}
	}
	if mapped != 7 {
		t.Errorf("expected 7 DocumentMap entries, iterated %d", mapped)
	}
}

// A skill enabled without its dispatched agent fails project open - the error
// names both sides and the fix. The fixture carries reviewing-impl's skill
// closure so the agent edge is the failing one, and validation walks the
// declared config order, so reviewing-impl's missing reviewer is reported
// deterministically (ADR-0050, generalized by ADR-0081's closure validation).
func TestSyncRecordsTopicOutputsInManifest(t *testing.T) {
	root := topicProject(t)
	writeProjectTopic(t, root)
	p, _ := loadTestSession(testContext(t), root)
	if err := syncProject(p); err != nil {
		t.Fatal(err)
	}
	lock, err := manifest.Load(lockFile(root))
	if err != nil {
		t.Fatal(err)
	}
	if _, ok := lock.Files["docs/topics/rendering/contracts.md"]; !ok {
		t.Fatal("topic output missing from manifest")
	}
}
