package publisher

import (
	"strings"

	"github.com/hypnotox/agentic-workflows/internal/frontmatter"
)

const bannerText = "GENERATED by awf: do not edit; change .awf/ and run `awf render`"

// injectBanner inserts the generated-by banner into rendered content: for the
// resident-root gitignores, a leading `#` comment (a valid .gitignore comment);
// for shebang scripts, a `#`-comment after the shebang line (keeping the script
// executable); for frontmatter targets, an HTML comment after the closing `---`;
// otherwise an HTML comment as the first line.
// injectSourceMarker appends one informational source marker directly after an
// already-injected HTML generated-by banner. Sources are renderer-owned
// reader-facing authorities, not render dependencies or edit boundaries.
func injectSourceMarker(content string, sources []string) string {
	if len(sources) == 0 {
		return content
	}
	banner := "<!-- " + bannerText + " -->\n"
	at := strings.Index(content, banner)
	if at < 0 {
		return content
	}
	marker := "<!-- awf:source " + strings.Join(sources, " ") + " -->\n"
	return content[:at+len(banner)] + marker + content[at+len(banner):]
}

func injectBanner(content, tid string) string {
	// The renderer places a root template symbol first. Lift it out before
	// framing so YAML frontmatter remains the leading construct, then restore it
	// directly after the banner (and, subsequently, any awf:source marker).
	rootSymbol := ""
	if strings.HasPrefix(content, "<!-- awf:template-source ") {
		if end := strings.IndexByte(content, '\n'); end >= 0 {
			rootSymbol, content = content[:end+1], content[end+1:]
		}
	}
	if isResidentGitignoreTID(tid) {
		return "# " + bannerText + "\n" + rootSymbol + content
	}
	if strings.HasPrefix(content, "#!") {
		// Shell/script target: banner as a # comment after the shebang line.
		nl := strings.IndexByte(content, '\n')
		if nl < 0 {
			return content
		}
		return content[:nl+1] + "# " + bannerText + "\n" + rootSymbol + content[nl+1:]
	}
	line := "<!-- " + bannerText + " -->\n"
	if yamlBlock, body, found := frontmatter.Split([]byte(content)); found {
		return "---\n" + string(yamlBlock) + "---\n" + line + rootSymbol + string(body)
	}
	return line + rootSymbol + content
}
