// Package adr parses ADR files under docs/decisions and renders the ACTIVE.md
// index. Generated by awf sync (regenerates docs/decisions/ACTIVE.md).
package adr

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/hypnotox/agentic-workflows/internal/frontmatter"
)

// statusOrder defines the section order in ACTIVE.md.
var statusOrder = []string{"Accepted", "Implemented", "Proposed", "Superseded"}

// ADR is a parsed ADR record.
type ADR struct {
	Number       string            // e.g. "0001"
	Title        string            // e.g. "ADR-0001: Template Overlay Rendering Engine"
	Status       string            // e.g. "Accepted"
	Filename     string            // e.g. "0001-template-overlay-rendering-engine.md"
	Path         string            // path as globbed
	Domains      []string          // `domains:` frontmatter (ADR-0014)
	SupersededBy string            // `superseded_by:` frontmatter (e.g. "0008", or "")
	Sections     map[string]string // `## ` heading -> section body
}

var fileRe = regexp.MustCompile(`^(\d{4})-.*\.md$`)

// ParseDir scans dir for ADR files (NNNN-*.md) and parses each into an ADR.
func ParseDir(dir string) ([]ADR, error) {
	matches, err := filepath.Glob(filepath.Join(dir, "*.md"))
	if err != nil {
		return nil, fmt.Errorf("glob %s: %w", dir, err)
	}
	var adrs []ADR
	for _, path := range matches {
		base := filepath.Base(path)
		m := fileRe.FindStringSubmatch(base)
		if m == nil {
			continue // skip ACTIVE.md, README.md, template.md
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return nil, fmt.Errorf("read %s: %w", base, err)
		}
		a, err := parse(data)
		if err != nil {
			return nil, fmt.Errorf("parse %s: %w", base, err)
		}
		a.Number, a.Filename, a.Path = m[1], base, path
		adrs = append(adrs, a)
	}
	return adrs, nil
}

// adrFrontmatter holds the YAML fields we care about.
type adrFrontmatter struct {
	Status       string   `yaml:"status"`
	Domains      []string `yaml:"domains"`
	SupersededBy string   `yaml:"superseded_by"`
}

// parse extracts status (frontmatter) and title (first `# ` heading) from one ADR.
func parse(data []byte) (ADR, error) {
	var fm adrFrontmatter
	body, _, err := frontmatter.Parse(data, &fm)
	if err != nil {
		return ADR{}, err
	}
	a := ADR{Status: fm.Status, Domains: fm.Domains, SupersededBy: fm.SupersededBy, Sections: sections(string(body))}
	for _, line := range strings.Split(string(body), "\n") {
		if strings.HasPrefix(line, "# ") {
			a.Title = strings.TrimPrefix(line, "# ")
			break
		}
	}
	return a, nil
}

// RenderActiveMD renders the ACTIVE.md index for dir, grouped by status. It
// returns "" when dir holds no ADRs (so callers produce no file).
func RenderActiveMD(dir string) (string, error) {
	adrs, err := ParseDir(dir)
	if err != nil {
		return "", err
	}
	if len(adrs) == 0 {
		return "", nil
	}

	groups := make(map[string][]ADR)
	for _, a := range adrs {
		groups[a.Status] = append(groups[a.Status], a)
	}
	for k := range groups {
		sort.Slice(groups[k], func(i, j int) bool { return groups[k][i].Number < groups[k][j].Number })
	}

	seen := make(map[string]bool)
	var ordered []string
	for _, s := range statusOrder {
		if len(groups[s]) > 0 {
			ordered = append(ordered, s)
			seen[s] = true
		}
	}
	var extra []string
	for k := range groups {
		if !seen[k] {
			extra = append(extra, k)
		}
	}
	sort.Strings(extra)
	ordered = append(ordered, extra...)

	var sb strings.Builder
	sb.WriteString("<!-- GENERATED by awf sync — do not edit by hand. -->\n")
	for _, status := range ordered {
		sb.WriteString("\n## ")
		sb.WriteString(status)
		sb.WriteString("\n\n")
		for _, a := range groups[status] {
			fmt.Fprintf(&sb, "- [%s](%s) — %s\n", a.Title, a.Filename, a.Status)
		}
	}
	return sb.String(), nil
}

// sections splits a markdown body into a map of `## ` heading text -> section
// body (the lines until the next `## ` heading).
func sections(body string) map[string]string {
	out := map[string]string{}
	var name string
	var b strings.Builder
	flush := func() {
		if name != "" {
			out[name] = b.String()
		}
		b.Reset()
	}
	for _, line := range strings.Split(body, "\n") {
		if h, ok := strings.CutPrefix(line, "## "); ok {
			flush()
			name = strings.TrimSpace(h)
			continue
		}
		if name != "" {
			b.WriteString(line)
			b.WriteString("\n")
		}
	}
	flush()
	return out
}
