// Package adr parses ADR files under docs/decisions, renders the ACTIVE.md
// index, and scaffolds new ADR files from the rendered template (awf new
// adr). Generated by awf sync (regenerates docs/decisions/ACTIVE.md).
package adr

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/hypnotox/agentic-workflows/internal/frontmatter"
)

// statusOrder defines the section order in ACTIVE.md.
var statusOrder = []string{"Accepted", "Implemented", "Proposed", "Superseded"}

// bucketKey maps a status to its index group. The lifecycle convention mandates
// the suffixed form "Superseded by ADR-NNNN", so every superseded ADR must fold
// into the one Superseded group - the bare statusOrder entry would otherwise
// never match and each successor would mint its own alphabetical section. The
// per-entry line keeps the full status, so the successor stays visible.
func bucketKey(status string) string {
	if strings.HasPrefix(status, "Superseded") {
		return "Superseded"
	}
	return status
}

// ADR is a parsed ADR record.
type ADR struct {
	Number        string            // e.g. "0001"
	Title         string            // e.g. "ADR-0001: Template Overlay Rendering Engine"
	Status        string            // e.g. "Accepted"
	Filename      string            // e.g. "0001-template-overlay-rendering-engine.md"
	Path          string            // path as globbed
	Domains       []string          // `domains:` frontmatter (ADR-0014)
	Tags          []string          // `tags:` frontmatter (keyword labels)
	Related       []int             // `related:` frontmatter (ADR numbers)
	SupersededBy  string            // `superseded_by:` frontmatter (e.g. "0008", or "")
	Supersedes    []int             // `supersedes:` frontmatter: full-supersession claims (ADR-0120)
	Refs          []SupersessionRef // inline partial-supersession tokens in the Decision section (ADR-0120)
	Sections      map[string]string // `## ` heading -> non-fenced section body
	DecisionStart int               // raw file byte offset of the Decision heading; 0 when absent
	DecisionEnd   int               // raw file byte offset immediately after the Decision section; 0 when absent
}

// SupersessionRef is one inline partial-supersession token (ADR-0120):
// `supersedes: ADR-NNNN#<item>` or `supersedes-invariant: ADR-NNNN#<slug>`
// as an inline code token inside a Decision section. Exactly one of
// Item/Slug is set; the key names the kind, never the anchor's shape.
type SupersessionRef struct {
	Target string // 4-digit target ADR number, e.g. "0116"
	Item   int    // Decision item number; 0 for an invariant ref
	Slug   string // invariant slug; "" for an item ref
}

var (
	// itemRefRe / invRefRe match the two token keys inside inline code. The
	// superseded kind is named by the key, never inferred from the anchor
	// (ADR-0120 item 1): items are [1-9][0-9]*, slugs the declRe grammar.
	itemRefRe = regexp.MustCompile("`supersedes: ADR-([0-9]{4})#([1-9][0-9]*)`")
	invRefRe  = regexp.MustCompile("`supersedes-invariant: ADR-([0-9]{4})#([a-z0-9-]+)`")
	// decisionItemRe matches a column-0 numbered Decision item lead. Column-0
	// anchoring is load-bearing: 0067 and 0115 carry indented numbered
	// sub-lists that must not enumerate (ADR-0120 item 2).
	decisionItemRe = regexp.MustCompile(`(?m)^([0-9]+)\. `)
)

// parseRefs extracts every supersession token from a Decision section body.
// Tokens anywhere else in the ADR are inert prose (ADR-0120 item 1), which
// parse guarantees by passing only Sections["Decision"].
func parseRefs(decision string) []SupersessionRef {
	var refs []SupersessionRef
	for _, m := range itemRefRe.FindAllStringSubmatch(decision, -1) {
		n, _ := strconv.Atoi(m[2]) // the regex admits only digits
		refs = append(refs, SupersessionRef{Target: m[1], Item: n})
	}
	for _, m := range invRefRe.FindAllStringSubmatch(decision, -1) {
		refs = append(refs, SupersessionRef{Target: m[1], Slug: m[2]})
	}
	return refs
}

// DecisionItems returns the numbers of the column-0 numbered items of the
// Decision section, in order of appearance.
func (a ADR) DecisionItems() []int {
	var items []int
	for _, m := range decisionItemRe.FindAllStringSubmatch(a.Sections["Decision"], -1) {
		n, _ := strconv.Atoi(m[1])
		items = append(items, n)
	}
	return items
}

// Override is one superseded anchor on a live ADR: the anchor (item number or
// slug) and the successor that superseded it (ADR-0120 item 10).
type Override struct {
	Item      int    // 0 for a slug override
	Slug      string // "" for an item override
	Successor string // 4-digit successor number
}

// SupersessionIndex derives the render view: full chains (predecessor,
// successor) sorted by predecessor, and per-target overrides from every
// non-Superseded ADR's refs, item refs before slug refs, in (anchor,
// successor) order. Only entries whose target is live (Accepted/Implemented)
// are kept - ADR-0120 item 10 scopes annotations to live ADRs whose anchors
// are superseded; a token into a Superseded target is already surfaced as a
// check advisory rather than an annotation on a dead record. Proposed
// carriers are deliberately included where the conflict advisory excludes
// them: the annotation is discoverability, not enforcement.
func SupersessionIndex(adrs []ADR) ([][2]string, map[string][]Override) {
	byNum := map[string]ADR{}
	for _, a := range adrs {
		byNum[a.Number] = a
	}
	var chains [][2]string
	overrides := map[string][]Override{}
	for _, a := range adrs {
		for _, n := range a.Supersedes {
			chains = append(chains, [2]string{fmt.Sprintf("%04d", n), a.Number})
		}
		if strings.HasPrefix(a.Status, "Superseded") {
			continue
		}
		for _, r := range a.Refs {
			t, ok := byNum[r.Target]
			if !ok || (t.Status != "Accepted" && t.Status != "Implemented") {
				continue
			}
			overrides[r.Target] = append(overrides[r.Target], Override{Item: r.Item, Slug: r.Slug, Successor: a.Number})
		}
	}
	sort.Slice(chains, func(i, j int) bool { return chains[i][0] < chains[j][0] })
	for _, list := range overrides {
		sort.Slice(list, func(i, j int) bool {
			a, b := list[i], list[j]
			if (a.Slug == "") != (b.Slug == "") {
				return a.Slug == "" // item refs before slug refs
			}
			if a.Slug == "" && a.Item != b.Item {
				return a.Item < b.Item
			}
			if a.Slug != b.Slug {
				return a.Slug < b.Slug
			}
			return a.Successor < b.Successor
		})
	}
	return chains, overrides
}

// Label renders the override's anchor for a human line: "item N" or
// "slug `<slug>`".
func (o Override) Label() string {
	if o.Slug != "" {
		return "slug `" + o.Slug + "`"
	}
	return fmt.Sprintf("item %d", o.Item)
}

// FilenameRe matches an ADR filename (NNNN-slug.md); group 1 is the 4-digit number.
var FilenameRe = regexp.MustCompile(`^(\d{4})-.+\.md$`)

// ParseDir scans dir for ADR files (NNNN-*.md) and parses each into an ADR.
func ParseDir(dir string) ([]ADR, error) {
	matches, err := filepath.Glob(filepath.Join(dir, "*.md"))
	if err != nil {
		return nil, fmt.Errorf("glob %s: %w", dir, err)
	}
	var adrs []ADR
	for _, path := range matches {
		base := filepath.Base(path)
		m := FilenameRe.FindStringSubmatch(base)
		if m == nil {
			continue // skip ACTIVE.md, README.md, template.md
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return nil, fmt.Errorf("read %s: %w", base, err)
		}
		a, err := parse(data)
		if err != nil {
			return nil, fmt.Errorf("parse %s: %w", base, err)
		}
		a.Number, a.Filename, a.Path = m[1], base, path
		adrs = append(adrs, a)
	}
	return adrs, nil
}

// adrFrontmatter holds the YAML fields we care about.
type adrFrontmatter struct {
	Status       string   `yaml:"status"`
	Domains      []string `yaml:"domains"`
	Tags         []string `yaml:"tags"`
	Related      []int    `yaml:"related"`
	SupersededBy string   `yaml:"superseded_by"`
	Supersedes   []int    `yaml:"supersedes"`
}

// parse extracts status (frontmatter) and title (first `# ` heading) from one ADR.
func parse(data []byte) (ADR, error) {
	var fm adrFrontmatter
	body, _, err := frontmatter.Parse(data, &fm)
	if err != nil {
		return ADR{}, err
	}
	parsed := sections(string(body), len(data)-len(body))
	a := ADR{Status: fm.Status, Domains: fm.Domains, Tags: fm.Tags, Related: fm.Related, SupersededBy: fm.SupersededBy, Supersedes: fm.Supersedes, Sections: parsed.bodies}
	if decision, ok := parsed.ranges["Decision"]; ok {
		a.DecisionStart, a.DecisionEnd = decision.start, decision.end
	}
	a.Refs = parseRefs(a.Sections["Decision"])
	for _, line := range strings.Split(string(body), "\n") {
		if strings.HasPrefix(line, "# ") {
			a.Title = strings.TrimPrefix(line, "# ")
			break
		}
	}
	return a, nil
}

// RenderActiveMD renders the ACTIVE.md index for dir, grouped by status. It
// returns a placeholder index when dir holds no ADRs (ADR-0020). The content
// carries no generated-by banner - like RenderDomainIndex, that is the
// caller's job (internal/project's generateActiveMD, via injectBanner) so
// every rendered artifact's banner comes from the one canonical source.
func RenderActiveMD(dir string) (string, error) {
	adrs, err := ParseDir(dir)
	if err != nil {
		return "", err
	}
	if len(adrs) == 0 {
		return "## Decisions\n\n_No decisions recorded yet._\n", nil
	}

	groups, ordered := groupByStatus(adrs, func(ADR) bool { return true })

	var sb strings.Builder
	for i, status := range ordered {
		if i > 0 {
			sb.WriteString("\n")
		}
		sb.WriteString("## ")
		sb.WriteString(status)
		sb.WriteString("\n\n")
		for _, a := range groups[status] {
			fmt.Fprintf(&sb, "- [%s](%s) (%s)\n", a.Title, a.Filename, a.Status)
		}
	}
	// Supersedence rendering (ADR-0120 item 10). Either subsection is omitted
	// when empty: publication-safe degradation, and a supersession-free corpus
	// renders byte-identically to the pre-ADR-0120 index.
	// touches-invariant: active-md-supersedence-rendering - the section render below; proof in adr_test.go
	chains, overrides := SupersessionIndex(adrs)
	if len(chains) > 0 || len(overrides) > 0 {
		sb.WriteString("\n## Supersedence\n")
		if len(chains) > 0 {
			sb.WriteString("\n### Chains\n\n")
			for _, c := range chains {
				fmt.Fprintf(&sb, "- ADR-%s superseded by ADR-%s\n", c[0], c[1])
			}
		}
		if len(overrides) > 0 {
			sb.WriteString("\n### Superseded anchors on live ADRs\n\n")
			targets := make([]string, 0, len(overrides))
			for num := range overrides {
				targets = append(targets, num)
			}
			sort.Strings(targets)
			for _, num := range targets {
				parts := make([]string, len(overrides[num]))
				for i, o := range overrides[num] {
					parts[i] = o.Label() + " superseded by ADR-" + o.Successor
				}
				fmt.Fprintf(&sb, "- ADR-%s: %s\n", num, strings.Join(parts, "; "))
			}
		}
	}
	return sb.String(), nil
}

// groupByStatus buckets the ADRs that pass include by bucketKey(Status), sorts each bucket
// by Number, and returns the buckets together with their status keys ordered by
// statusOrder, with any unknown statuses appended in alphabetical order. Shared
// by RenderActiveMD and RenderDomainIndex.
func groupByStatus(adrs []ADR, include func(ADR) bool) (map[string][]ADR, []string) {
	groups := make(map[string][]ADR)
	for _, a := range adrs {
		if include(a) {
			groups[bucketKey(a.Status)] = append(groups[bucketKey(a.Status)], a)
		}
	}
	for k := range groups {
		sort.Slice(groups[k], func(i, j int) bool { return groups[k][i].Number < groups[k][j].Number })
	}
	seen := make(map[string]bool)
	var ordered []string
	for _, s := range statusOrder {
		if len(groups[s]) > 0 {
			ordered = append(ordered, s)
			seen[s] = true
		}
	}
	var extra []string
	for k := range groups {
		if !seen[k] {
			extra = append(extra, k)
		}
	}
	sort.Strings(extra)
	ordered = append(ordered, extra...)
	return groups, ordered
}

type sectionRange struct{ start, end int }

type parsedSections struct {
	bodies map[string]string
	ranges map[string]sectionRange
}

// sections walks Markdown lines, ignoring fenced examples when it derives ADR
// structure. Ranges retain raw file offsets so migrations can edit around an
// opaque fenced block without reserializing the document.
func sections(body string, offset int) parsedSections {
	out := parsedSections{bodies: map[string]string{}, ranges: map[string]sectionRange{}}
	var name string
	var start int
	var b strings.Builder
	var fence byte
	var fenceLen int
	flush := func(end int) {
		if name != "" {
			out.bodies[name] = b.String()
			out.ranges[name] = sectionRange{start: start, end: end}
		}
		b.Reset()
	}
	pos := 0
	for _, rawLine := range rangeLines(body) {
		line := strings.TrimSuffix(rawLine, "\n")
		if marker, n, ok := fenceMarker(line); ok {
			if fence == 0 {
				fence, fenceLen = marker, n
				pos += len(rawLine)
				continue
			}
			if marker == fence && n >= fenceLen {
				fence, fenceLen = 0, 0
			}
			pos += len(rawLine)
			continue
		}
		if fence != 0 {
			pos += len(rawLine)
			continue
		}
		if h, ok := strings.CutPrefix(line, "## "); ok {
			flush(offset + pos)
			name, start = strings.TrimSpace(h), offset+pos
		} else if name != "" {
			b.WriteString(rawLine)
		}
		pos += len(rawLine)
	}
	flush(offset + len(body))
	return out
}

func rangeLines(s string) []string {
	lines := strings.SplitAfter(s, "\n")
	if len(lines) > 0 && lines[len(lines)-1] == "" {
		return lines[:len(lines)-1]
	}
	return lines
}

// fenceMarker identifies a Markdown backtick or tilde fence with up to three
// leading spaces. It returns the marker and its run length.
func fenceMarker(line string) (byte, int, bool) {
	indent := len(line) - len(strings.TrimLeft(line, " "))
	if indent > 3 || indent == len(line) {
		return 0, 0, false
	}
	marker := line[indent]
	if marker != '`' && marker != '~' {
		return 0, 0, false
	}
	n := 0
	for indent+n < len(line) && line[indent+n] == marker {
		n++
	}
	return marker, n, n >= 3
}

// now returns the current time; overridden in tests for deterministic
// date-stamping (mirrors cmd/awf's getwd/isInteractive seam pattern).
var now = time.Now

// markerLineRe matches an awf-injected marker comment line, so NewFile can
// strip every one - the GENERATED banner and each per-section awf:edit
// provenance pointer - from a copied template.
var markerLineRe = regexp.MustCompile(`(?m)^<!-- (GENERATED by awf|awf:edit).*-->\n`)

// slugNonAlnumRe collapses everything but lowercase letters and digits into a
// single hyphen for slugify.
var slugNonAlnumRe = regexp.MustCompile(`[^a-z0-9]+`)

// NextNumber returns the next available 4-digit ADR number for dir: one more
// than the highest number ParseDir finds, or "0001" for an ADR-less dir.
// touches-invariant: adr-new-sequential-numbering - NextNumber returns highest-plus-one; proof in adr_test.go
func NextNumber(dir string) (string, error) {
	adrs, err := ParseDir(dir)
	if err != nil {
		return "", err
	}
	max := 0
	for _, a := range adrs {
		n, err := strconv.Atoi(a.Number)
		if err != nil { // coverage-ignore: a.Number is always a 4-digit numeral matched by FilenameRe
			return "", err
		}
		if n > max {
			max = n
		}
	}
	return fmt.Sprintf("%04d", max+1), nil
}

// slugify lowercases title and collapses every run of non-alphanumeric
// characters into a single hyphen, trimming leading/trailing hyphens. A title
// with no alphanumeric characters is a hard error - there is no reasonable
// filename to derive.
func slugify(title string) (string, error) {
	s := slugNonAlnumRe.ReplaceAllString(strings.ToLower(title), "-")
	s = strings.Trim(s, "-")
	if s == "" {
		return "", fmt.Errorf("adr: title %q has no usable characters for a filename", title)
	}
	return s, nil
}

// replaceOnce replaces the first occurrence of old in s, erroring if old is
// absent so a drifted template (a renamed or missing placeholder) fails loudly
// instead of shipping an unresolved placeholder into a committed ADR.
func replaceOnce(s, old, replacement string) (string, error) {
	if !strings.Contains(s, old) {
		return "", fmt.Errorf("adr: template missing expected %q", old)
	}
	return strings.Replace(s, old, replacement, 1), nil
}

// NewFile scaffolds a new ADR under dir: the next sequential number, the
// rendered template.md with every marker comment stripped and its date and
// title heading filled in, named NNNN-slug.md. Refuses to overwrite an
// existing file at that path.
// touches-invariant: adr-new-strips-markers - NewFile strips every marker comment from the copied template; proof in adr_test.go
// touches-invariant: adr-new-heading-matches-file - NewFile fills the heading from the allocated file number; proof in adr_test.go
// touches-invariant: adr-new-no-overwrite - refuse-overwrite guard; unbacked (unreachable), see ADR-0042 Verify note
func NewFile(dir, title string) (string, error) {
	title = strings.TrimSpace(title)
	number, err := NextNumber(dir)
	if err != nil {
		return "", err
	}
	slug, err := slugify(title)
	if err != nil {
		return "", err
	}
	path := filepath.Join(dir, number+"-"+slug+".md")
	if _, err := os.Stat(path); err == nil { // coverage-ignore: NextNumber always returns one more than every existing NNNN-*.md file, so this path can only pre-exist via a concurrent-process race a single-threaded test cannot construct
		return "", fmt.Errorf("adr: %s already exists", path)
	} else if !os.IsNotExist(err) { // coverage-ignore: Stat fails here only on a permission fault a test cannot trigger
		return "", err
	}
	raw, err := os.ReadFile(filepath.Join(dir, "template.md"))
	if err != nil {
		return "", fmt.Errorf("adr: read template: %w", err)
	}
	content := markerLineRe.ReplaceAllString(string(raw), "")
	content, err = replaceOnce(content, "date: YYYY-MM-DD", "date: "+now().Format("2006-01-02"))
	if err != nil {
		return "", err
	}
	content, err = replaceOnce(content, "# ADR-NNNN: Title", fmt.Sprintf("# ADR-%s: %s", number, title))
	if err != nil {
		return "", err
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil { // coverage-ignore: post-Stat write into a dir just read by NextNumber/ParseDir; fails only on a permission fault a test cannot trigger
		return "", err
	}
	return path, nil
}
