// Package adr parses ADR files under docs/decisions, renders the INDEX.md
// decision index, and scaffolds new ADR files from the rendered template (awf
// new adr). Generated by awf render (regenerates docs/decisions/INDEX.md).
package adr

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"time"

	"github.com/hypnotox/agentic-workflows/internal/filesystem"
	"github.com/hypnotox/agentic-workflows/internal/frontmatter"
)

// ADR is a parsed ADR record.
type ADR struct {
	Number         string            // e.g. "0001"
	Title          string            // e.g. "ADR-0001: Template Overlay Rendering Engine"
	Status         string            // e.g. "Accepted"
	Date           string            // frontmatter date, retained verbatim as YYYY-MM-DD text
	Filename       string            // e.g. "0001-template-overlay-rendering-engine.md"
	Path           string            // path as globbed
	Domains        []string          // `domains:` frontmatter (ADR-0014)
	Tags           []string          // `tags:` frontmatter (keyword labels)
	Related        []int             // `related:` frontmatter (ADR numbers)
	Sections       map[string]string // `## ` heading -> non-fenced section body
	decisions      []decisionItem    // package-owned parsed Decision items
	decisionBySlug map[string]int
	source         string
	decisionStart  int
	decisionEnd    int

	// Governed fields are populated only for a record carrying a recognized
	// intrinsic format marker. A legacy-format record leaves them zero.
	Format     Format         // Legacy, CurrentStateV1, CurrentStateV2, or CurrentStateV3
	NoneState  bool           // State changes section is exactly "None."
	Operations []Operation    // parsed `## State changes` operations
	History    []HistoryEvent // parsed `## Status history` events
	// Slug is the mandatory retained `slug:` frontmatter key of a V3 record. It
	// is the identity of a pending record (Number is empty until numbering) and
	// survives numbering so an `ADR-<slug>` reference stays resolvable
	// (ADR-0202 items 2 and 3). Pre-V3 records carry none.
	Slug string
}

// Identity returns the record's single identity key: the four-digit number for
// a numbered record, and the retained slug for a pending V3 record that has not
// been numbered yet (ADR-0202 item 4).
func (a ADR) Identity() string {
	if a.Number != "" {
		return a.Number
	}
	return a.Slug
}

// IsPending reports whether the record is a V3 record awaiting its number at
// integration: slug identity, no number.
func (a ADR) IsPending() bool { return a.Number == "" && a.Slug != "" }

// numberRe matches the four-digit numbered identity form.
var numberRe = regexp.MustCompile(`^\d{4}$`)

// IsSlugIdentity reports whether an identity reference is the pending slug form
// rather than the four-digit number form.
func IsSlugIdentity(ref string) bool { return !numberRe.MatchString(ref) }

// pendingIdentityOrder ranks every pending identity above every four-digit
// number, which is where numbering will in fact place it: a pending record
// takes the corpus's next numbers at integration (ADR-0202 item 10). No
// numbered record can reach the rank, so the two regions never interleave.
const pendingIdentityOrder = 100000

// IdentityOrder returns the provenance sort rank of an identity reference. A
// stable sort over it leaves pending identities in their authored order after
// every numbered one.
func IdentityOrder(id string) int {
	if IsSlugIdentity(id) {
		return pendingIdentityOrder
	}
	n, _ := strconv.Atoi(id) // a non-slug identity is exactly four decimal digits
	return n
}

// Format distinguishes legacy, current-state-v1, and current-state-v2 ADRs.
type Format int

const (
	// Legacy is a pre-cutover ADR: identity, status, and date only.
	Legacy Format = iota
	// CurrentStateV1 is a `format: current-state-v1` ADR with State changes and
	// status-only history.
	CurrentStateV1
	// CurrentStateV2 is a `format: current-state-v2` ADR with heterogeneous
	// status and application history.
	CurrentStateV2
	// CurrentStateV3 is a `format: current-state-v3` ADR: V2 semantics exactly,
	// plus the mandatory retained slug identity and the pending record form
	// (ADR-0202 item 1).
	CurrentStateV3
	// CurrentStateV4 adds stable Decision item slugs while retaining V3 identity
	// and V2 lifecycle semantics.
	CurrentStateV4
)

// IsV1 reports whether the record was parsed as current-state-v1.
func (a ADR) IsV1() bool { return a.Format == CurrentStateV1 }

// IsV2 reports whether the record was parsed as current-state-v2.
func (a ADR) IsV2() bool { return a.Format == CurrentStateV2 }

// IsV3 reports whether the record was parsed as current-state-v3.
func (a ADR) IsV3() bool { return a.Format == CurrentStateV3 }

// IsV4 reports whether the record was parsed as current-state-v4.
func (a ADR) IsV4() bool { return a.Format == CurrentStateV4 }

// HasV2Semantics reports whether the record uses the V2 heterogeneous history,
// amendability, and digest rules. V3 inherits them unchanged, so every rule
// keyed on "V2 or later" asks this rather than enumerating formats.
func (a ADR) HasV2Semantics() bool { return a.IsV2() || a.IsV3() || a.IsV4() }

// IsGoverned reports whether the record uses any current-state format.
func (a ADR) IsGoverned() bool { return a.IsV1() || a.HasV2Semantics() }

// FormatMarker returns the governed `format:` frontmatter value for format, or
// the empty string for Legacy.
func FormatMarker(format Format) string {
	switch format {
	case CurrentStateV1:
		return V1FormatMarker
	case CurrentStateV2:
		return V2FormatMarker
	case CurrentStateV3:
		return V3FormatMarker
	case CurrentStateV4:
		return V4FormatMarker
	case Legacy:
	}
	return ""
}

// DecisionItems returns the numbers of the column-0 numbered items of the
// Decision section, in order of appearance.
func (a ADR) DecisionItems() []int {
	if len(a.decisions) == 0 {
		return nil
	}
	items := make([]int, len(a.decisions))
	for i, item := range a.decisions {
		items[i] = item.ordinal
	}
	return items
}

// FilenameRe matches an ADR filename (NNNN-slug.md); group 1 is the 4-digit number.
var FilenameRe = regexp.MustCompile(`^(\d{4})-.+\.md$`)

// reservedBasenames are the decisions-directory files that are never records:
// the hand-written README, the generated INDEX, and the rendered scaffold
// template (ADR-0202 item 4).
var reservedBasenames = map[string]bool{"README.md": true, "INDEX.md": true, "template.md": true}

// IsReservedBasename reports whether a decisions-directory basename is one of
// the three reserved non-record files. Every corpus walk excludes exactly these
// and treats what remains as a record, so the exclusion set has one home.
func IsReservedBasename(name string) bool { return reservedBasenames[name] }

// ErrNotADRRecord names a decisions-directory file that is neither a numbered
// record nor a pending current-state-v3 record. Such a file used to be silently
// ignored; ADR-0202 item 4 makes it a corpus error.
func ErrNotADRRecord(name string) error {
	return fmt.Errorf("%s: not an ADR record (expected NNNN-*.md or a pending current-state-v3 file)", name)
}

// FileIdentity returns the identity a decisions-directory basename declares:
// the four-digit number of a numbered record, the slug of a pending record, or
// the empty string for a reserved or non-Markdown file. Callers classifying a
// path as a decision record ask this rather than matching the filename grammar
// themselves, so the pending form is recognized everywhere it is legal.
func FileIdentity(base string) string {
	if IsReservedBasename(base) || !strings.HasSuffix(base, ".md") {
		return ""
	}
	if m := FilenameRe.FindStringSubmatch(base); m != nil {
		return m[1]
	}
	return strings.TrimSuffix(base, ".md")
}

// ParseDir scans dir for ADR records and parses each into an ADR. Every
// non-reserved `*.md` file is a record: a numbered `NNNN-*.md` file or a pending
// `<slug>.md` file declaring the current format. Anything else is an error
// rather than a silent skip.
func ParseDir(dir string) ([]ADR, error) {
	matches, err := filepath.Glob(filepath.Join(dir, "*.md"))
	if err != nil {
		return nil, fmt.Errorf("glob %s: %w", dir, err)
	}
	var adrs []ADR
	for _, path := range matches {
		base := filepath.Base(path)
		if IsReservedBasename(base) {
			continue
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return nil, fmt.Errorf("read %s: %w", base, err)
		}
		a, _, err := ParseBytes(base, data)
		if err != nil {
			return nil, fmt.Errorf("parse %s: %w", base, err)
		}
		if a.Number == "" && a.Format != CurrentFormat() && !a.IsV3() {
			return nil, ErrNotADRRecord(base)
		}
		a.Path = path
		adrs = append(adrs, a)
	}
	return adrs, nil
}

// adrFrontmatter holds the YAML fields we care about.
type adrFrontmatter struct {
	Format  string   `yaml:"format"`
	Status  string   `yaml:"status"`
	Date    string   `yaml:"date"`
	Domains []string `yaml:"domains"`
	Tags    []string `yaml:"tags"`
	Related []int    `yaml:"related"`
	Slug    string   `yaml:"slug"`
}

// ParseBytes parses one ADR from bytes: status and the other frontmatter
// fields, plus the title from the first `# ` heading. It is the seam the git-blob consumers
// take (ADR-0130 item 5): internal/audit reads history rather than the working
// tree, so it cannot take a Corpus, but it can share the parser and the
// frontmatter schema, which is where the duplication actually was.
//
// found reports whether frontmatter was present at all, which is the tri-state
// the audit needs: absent frontmatter is a legitimate empty status, while
// present-but-unparseable is an error. name is the ADR's base filename, from
// which Filename and Number are derived; Path is left empty, since a
// blob-sourced record has no working-tree path.
func ParseBytes(name string, data []byte) (ADR, bool, error) {
	var fm adrFrontmatter
	body, found, err := frontmatter.Parse(data, &fm)
	if err != nil {
		return ADR{}, found, err
	}
	parsed := sections(string(body), len(data)-len(body))
	a := ADR{Status: fm.Status, Date: fm.Date, Domains: fm.Domains, Tags: fm.Tags, Related: fm.Related, Slug: fm.Slug, Sections: parsed.bodies, source: string(data)}
	switch fm.Format {
	case V1FormatMarker:
		a.Format = CurrentStateV1
	case V2FormatMarker:
		a.Format = CurrentStateV2
	case V3FormatMarker:
		a.Format = CurrentStateV3
	case V4FormatMarker:
		a.Format = CurrentStateV4
	}
	if decision, ok := parsed.ranges["Decision"]; ok {
		a.decisionStart, a.decisionEnd = decision.start, decision.end
	}
	retainDecisionItems(&a)
	for _, line := range strings.Split(string(body), "\n") {
		if strings.HasPrefix(line, "# ") {
			a.Title = strings.TrimPrefix(line, "# ")
			break
		}
	}
	a.Filename = name
	if m := FilenameRe.FindStringSubmatch(name); m != nil {
		a.Number = m[1]
	}
	return a, found, nil
}

type sectionRange struct{ start, end int }

type parsedSections struct {
	bodies map[string]string
	ranges map[string]sectionRange
}

// sections walks Markdown lines, ignoring fenced examples when it derives ADR
// structure. Ranges retain raw file offsets so migrations can edit around an
// opaque fenced block without reserializing the document.
func sections(body string, offset int) parsedSections {
	out := parsedSections{bodies: map[string]string{}, ranges: map[string]sectionRange{}}
	var name string
	var start int
	var b strings.Builder
	var fence byte
	var fenceLen int
	flush := func(end int) {
		if name != "" {
			out.bodies[name] = b.String()
			out.ranges[name] = sectionRange{start: start, end: end}
		}
		b.Reset()
	}
	pos := 0
	for _, rawLine := range rangeLines(body) {
		line := strings.TrimSuffix(rawLine, "\n")
		if marker, n, ok := fenceMarker(line); ok {
			if fence == 0 {
				fence, fenceLen = marker, n
				pos += len(rawLine)
				continue
			}
			if marker == fence && n >= fenceLen && fenceCloser(line, n) {
				fence, fenceLen = 0, 0
			}
			pos += len(rawLine)
			continue
		}
		if fence != 0 {
			pos += len(rawLine)
			continue
		}
		if h, ok := strings.CutPrefix(line, "## "); ok {
			flush(offset + pos)
			name, start = strings.TrimSpace(h), offset+pos
		} else if name != "" {
			b.WriteString(rawLine)
		}
		pos += len(rawLine)
	}
	flush(offset + len(body))
	return out
}

func rangeLines(s string) []string {
	lines := strings.SplitAfter(s, "\n")
	if len(lines) > 0 && lines[len(lines)-1] == "" {
		return lines[:len(lines)-1]
	}
	return lines
}

// fenceMarker identifies a Markdown backtick or tilde fence with up to three
// leading spaces. It returns the marker and its run length.
func fenceMarker(line string) (byte, int, bool) {
	indent := len(line) - len(strings.TrimLeft(line, " "))
	if indent > 3 || indent == len(line) {
		return 0, 0, false
	}
	marker := line[indent]
	if marker != '`' && marker != '~' {
		return 0, 0, false
	}
	n := 0
	for indent+n < len(line) && line[indent+n] == marker {
		n++
	}
	return marker, n, n >= 3
}

// fenceCloser reports whether the marker run is followed only by whitespace.
// Unlike an opening fence, a Markdown closing fence cannot carry info text.
func fenceCloser(line string, n int) bool {
	indent := len(line) - len(strings.TrimLeft(line, " "))
	return strings.TrimSpace(line[indent+n:]) == ""
}

// now returns the current time; overridden in tests for deterministic
// date-stamping (mirrors cmd/awf's getwd/isInteractive seam pattern).
var now = time.Now

// markerLineRe matches an awf-injected marker comment line, so NewFile can
// strip every one - the GENERATED banner plus awf:edit and awf:template-source
// provenance pointers - from a copied template.
var markerLineRe = regexp.MustCompile(`(?m)^<!-- (GENERATED by awf|awf:(edit|template-source)).*-->\n`)

// slugNonAlnumRe collapses everything but lowercase letters and digits into a
// single hyphen for slugify.
var slugNonAlnumRe = regexp.MustCompile(`[^a-z0-9]+`)

// loadIdentityCorpusConfined indexes the decisions directory through the selected-root handle.
// It reads only identity-bearing frontmatter, so incomplete ADR bodies do not block authoring.
func loadIdentityCorpusConfined(files *filesystem.Handle, dir string) (Corpus, error) {
	var adrs []ADR
	err := files.Walk(dir, func(name string, info fs.FileInfo) (bool, error) {
		if name == dir {
			if !info.IsDir() {
				return false, fmt.Errorf("adr: decisions path %s is not a directory", dir)
			}
			return true, nil
		}
		if path.Dir(name) != dir || info.IsDir() || IsReservedBasename(path.Base(name)) || path.Ext(name) != ".md" {
			return false, nil
		}
		data, err := files.Read(name)
		if err != nil {
			return false, fmt.Errorf("read %s: %w", path.Base(name), err)
		}
		a, _, err := ParseBytes(path.Base(name), data)
		if err != nil {
			return false, fmt.Errorf("parse %s: %w", path.Base(name), err)
		}
		if a.Number == "" && a.Format != CurrentFormat() && !a.IsV3() {
			return false, ErrNotADRRecord(path.Base(name))
		}
		a.Path = name
		adrs = append(adrs, a)
		return false, nil
	})
	if err != nil {
		return Corpus{}, err
	}
	return NewCorpus(adrs)
}

// slugify lowercases title and collapses every run of non-alphanumeric
// characters into a single hyphen, trimming leading/trailing hyphens. A title
// with no alphanumeric characters is a hard error - there is no reasonable
// filename to derive.
func slugify(title string) (string, error) {
	s := slugNonAlnumRe.ReplaceAllString(strings.ToLower(title), "-")
	s = strings.Trim(s, "-")
	if s == "" {
		return "", fmt.Errorf("adr: title %q has no usable characters for a filename", title)
	}
	return s, nil
}

// replaceOnce replaces the first occurrence of old in s, erroring if old is
// absent so a drifted template (a renamed or missing placeholder) fails loudly
// instead of shipping an unresolved placeholder into a committed ADR.
func replaceOnce(s, old, replacement string) (string, error) {
	if !strings.Contains(s, old) {
		return "", fmt.Errorf("adr: template missing expected %q", old)
	}
	return strings.Replace(s, old, replacement, 1), nil
}

// numberedSlugRe matches a slug that opens like a numbered filename. Such a
// slug is refused at authoring time (ADR-0202 item 2): ParseRecord routes by
// filename before it peeks the format marker, so a pending `2026-roadmap.md`
// would be read as numbered record 2026, fail the filename-equals-slug check,
// and take the whole corpus down instead of producing a scoped finding.
var numberedSlugRe = regexp.MustCompile(`^\d{4}-`)

// allDigitSlugRe matches a slug made only of digits, which is refused at
// authoring time because it collides with the number identity form rather than
// with a filename. Corpus.ByIdentity routes a four-digit key to the number
// index, so a `2026` slug names a record nothing can find, and a plan's `adrs:`
// entry reads any digits-only spelling as a number, so a slug of any length
// made only of digits is unlinkable. The hyphen numberedSlugRe requires is
// exactly what lets an all-digit slug past it.
var allDigitSlugRe = regexp.MustCompile(`^\d+$`)

// reservedSlugStems are the reserved basenames' stems. A title slugifying to
// one of these would scaffold a pending file every corpus walk skips.
var reservedSlugStems = map[string]bool{"readme": true, "index": true, "template": true}

// NewFileLeased scaffolds a numbered ADR through the caller-held selected-root
// capability. The lease must cover root through the command's presented outcome.
func NewFileLeased(root string, lease *filesystem.Lease, files *filesystem.Handle, dir, title string) (string, error) {
	if err := requireScaffoldCapability(root, lease, files); err != nil {
		return "", err
	}
	return scaffoldRecordConfined(files, dir, title, CurrentFormat(), false)
}

// NewPendingFileLeased scaffolds a slug-identified pending ADR through the
// caller-held selected-root capability.
func NewPendingFileLeased(root string, lease *filesystem.Lease, files *filesystem.Handle, dir, title string) (string, error) {
	if err := requireScaffoldCapability(root, lease, files); err != nil {
		return "", err
	}
	return scaffoldRecordConfined(files, dir, title, CurrentFormat(), true)
}

func requireScaffoldCapability(root string, lease *filesystem.Lease, files *filesystem.Handle) error {
	if lease == nil || !lease.CoversTracked(root) {
		return errors.New("ADR creation requires a covering tracked lease")
	}
	if files == nil {
		return errors.New("ADR creation requires a selected-root handle")
	}
	matches, err := files.RootMatches(root)
	if err != nil {
		return err
	}
	if !matches {
		return errors.New("ADR creation handle does not match selected root")
	}
	return nil
}

// scaffoldRecordConfined is the sole production writer of scaffolded decision
// records. Corpus, template, destination, and publication all stay beneath files.
func scaffoldRecordConfined(files *filesystem.Handle, dir, title string, format Format, pending bool) (string, error) {
	title = strings.TrimSpace(title)
	slug, err := slugify(title)
	if err != nil {
		return "", err
	}
	if reservedSlugStems[slug] {
		return "", fmt.Errorf("adr: title slugifies to reserved name %q", slug)
	}
	if numberedSlugRe.MatchString(slug) {
		return "", fmt.Errorf("adr: title slugifies to %q, which reads as a numbered filename", slug)
	}
	if allDigitSlugRe.MatchString(slug) {
		return "", fmt.Errorf("adr: title slugifies to %q, which collides with the number identity form", slug)
	}
	corpus, err := loadIdentityCorpusConfined(files, dir)
	if err != nil {
		return "", err
	}
	if existing, ok := corpusSlugOwner(corpus, slug); ok {
		return "", fmt.Errorf("adr: slug %q already used by %s", slug, existing)
	}
	next, err := corpus.NextIdentity()
	if err != nil {
		return "", err
	}
	number := fmt.Sprintf("%04d", next)
	base := number + "-" + slug + ".md"
	heading := "# ADR-" + number + ": " + title
	if pending {
		base = slug + ".md"
		heading = "# ADR-" + slug + ": " + title
	}
	destination := path.Join(dir, base)
	raw, err := files.Read(path.Join(dir, "template.md"))
	if err != nil {
		return "", fmt.Errorf("adr: read template: %w", err)
	}
	content := markerLineRe.ReplaceAllString(string(raw), "")
	marker := CurrentFormatMarker()
	block, body, found := frontmatter.Split([]byte(content))
	if !found {
		return "", errors.New("adr: template missing frontmatter")
	}
	var formatMarkers []string
	declaresSlug := false
	for _, line := range strings.Split(string(block), "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "format:") {
			formatMarkers = append(formatMarkers, strings.TrimSpace(strings.TrimPrefix(line, "format:")))
		}
		if strings.HasPrefix(line, "slug:") {
			declaresSlug = true
		}
	}
	if len(formatMarkers) == 0 {
		return "", errors.New("adr: template frontmatter missing governed format marker")
	}
	if len(formatMarkers) != 1 {
		return "", errors.New("adr: template frontmatter must contain exactly one governed format marker")
	}
	templateMarker := formatMarkers[0]
	if !KnownFormatMarker(templateMarker) {
		return "", fmt.Errorf("adr: template frontmatter has unsupported governed format marker %q", templateMarker)
	}
	if declaresSlug {
		return "", errors.New("adr: template frontmatter must not declare slug, which the scaffold derives per record")
	}
	front := strings.Replace(string(block), "format: "+templateMarker, "format: "+marker, 1)
	if format == CurrentFormat() {
		front = strings.Replace(front, "format: "+marker, "format: "+marker+"\nslug: "+slug, 1)
	}
	content = "---\n" + front + "---\n" + string(body)
	date := now().Format("2006-01-02")
	content, err = replaceOnce(content, "date: YYYY-MM-DD", "date: "+date)
	if err != nil {
		return "", err
	}
	content, err = replaceOnce(content, "- YYYY-MM-DD: Proposed", "- "+date+": Proposed")
	if err != nil {
		return "", fmt.Errorf("ADR template Proposed history: %w", err)
	}
	content, err = replaceOnce(content, "# ADR-NNNN: Title", heading)
	if err != nil {
		return "", err
	}
	if err := files.Publish(destination, []byte(content), 0o644); err != nil {
		return "", err
	}
	return destination, nil
}

// corpusSlugOwner reports the file already claiming slug, over both spellings a
// slug can occupy: a record's retained `slug:` key, and the slug segment of a
// numbered filename, which pre-V3 records carry without any frontmatter key.
// Both matter, because a slug reused from either would collide the moment the
// new record is numbered.
func corpusSlugOwner(c Corpus, slug string) (string, bool) {
	if a, ok := c.BySlug(slug); ok {
		return a.Filename, true
	}
	for _, a := range c.All() {
		if m := FilenameRe.FindStringSubmatch(a.Filename); m != nil {
			if strings.TrimSuffix(strings.TrimPrefix(a.Filename, m[1]+"-"), ".md") == slug {
				return a.Filename, true
			}
		}
	}
	return "", false
}
