package adr_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/hypnotox/agentic-workflows/internal/adr"
)

// TestRenderActiveMDGroupsByStatus is a hermetic unit test using a temp dir.
// invariant: render-active-md
func TestRenderActiveMDGroupsByStatus(t *testing.T) {
	dir := t.TempDir()

	files := map[string]string{
		"0001-first-accepted.md": `---
status: Accepted
date: 2026-06-24
tags: [tooling]
---
# ADR-0001: First Accepted
## Context
Something.
`,
		"0002-a-proposal.md": `---
status: Proposed
date: 2026-06-24
tags: []
---
# ADR-0002: A Proposal
## Context
Another thing.
`,
		"0003-already-implemented.md": `---
status: Implemented
date: 2026-06-24
tags: []
---
# ADR-0003: Already Implemented
## Context
Done.
`,
	}

	for name, content := range files {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(content), 0644); err != nil {
			t.Fatalf("write fixture %s: %v", name, err)
		}
	}

	got, err := adr.RenderActiveMD(dir)
	if err != nil {
		t.Fatalf("RenderActiveMD: %v", err)
	}

	// Must start with the generator header comment.
	if !strings.HasPrefix(got, "<!-- GENERATED by awf sync") {
		t.Errorf("missing header comment; got start: %q", got[:min(60, len(got))])
	}

	// Accepted must appear before Proposed.
	acceptedPos := strings.Index(got, "## Accepted")
	implementedPos := strings.Index(got, "## Implemented")
	proposedPos := strings.Index(got, "## Proposed")

	if acceptedPos < 0 {
		t.Error("missing ## Accepted section")
	}
	if implementedPos < 0 {
		t.Error("missing ## Implemented section")
	}
	if proposedPos < 0 {
		t.Error("missing ## Proposed section")
	}
	if acceptedPos > 0 && implementedPos > 0 && acceptedPos > implementedPos {
		t.Errorf("Accepted (%d) should come before Implemented (%d)", acceptedPos, implementedPos)
	}
	if implementedPos > 0 && proposedPos > 0 && implementedPos > proposedPos {
		t.Errorf("Implemented (%d) should come before Proposed (%d)", implementedPos, proposedPos)
	}

	// Each ADR entry should appear under the correct section.
	checkEntry := func(section, title, filename string) {
		t.Helper()
		sectionHeader := "## " + section
		sectionStart := strings.Index(got, sectionHeader)
		if sectionStart < 0 {
			t.Errorf("section %q not found", sectionHeader)
			return
		}
		// Find next section after this one.
		nextSection := strings.Index(got[sectionStart+len(sectionHeader):], "\n## ")
		var sectionBody string
		if nextSection < 0 {
			sectionBody = got[sectionStart:]
		} else {
			sectionBody = got[sectionStart : sectionStart+len(sectionHeader)+nextSection]
		}
		if !strings.Contains(sectionBody, title) {
			t.Errorf("expected %q in section %q; section body:\n%s", title, section, sectionBody)
		}
		if !strings.Contains(sectionBody, filename) {
			t.Errorf("expected filename %q in section %q", filename, section)
		}
	}

	checkEntry("Accepted", "ADR-0001: First Accepted", "0001-first-accepted.md")
	checkEntry("Implemented", "ADR-0003: Already Implemented", "0003-already-implemented.md")
	checkEntry("Proposed", "ADR-0002: A Proposal", "0002-a-proposal.md")
}

// invariant: render-active-md
func TestRenderActiveMDEmptyWhenNoADRs(t *testing.T) {
	dir := t.TempDir()
	// A non-ADR markdown file must not count.
	if err := os.WriteFile(filepath.Join(dir, "README.md"), []byte("# readme\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	got, err := adr.RenderActiveMD(dir)
	if err != nil {
		t.Fatalf("RenderActiveMD: %v", err)
	}
	if got != "" {
		t.Errorf("expected empty output for an ADR-less dir, got:\n%s", got)
	}
}

func TestParseDirExtractsStatusAndTitle(t *testing.T) {
	dir := t.TempDir()
	content := "---\nstatus: Accepted\ndate: 2026-06-25\ntags: [x]\n---\n# ADR-0007: Example Title\n## Context\nx\n"
	if err := os.WriteFile(filepath.Join(dir, "0007-example.md"), []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
	// A non-ADR file must be skipped.
	if err := os.WriteFile(filepath.Join(dir, "README.md"), []byte("# readme\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	adrs, err := adr.ParseDir(dir)
	if err != nil {
		t.Fatalf("ParseDir: %v", err)
	}
	if len(adrs) != 1 {
		t.Fatalf("expected 1 ADR, got %d", len(adrs))
	}
	got := adrs[0]
	if got.Number != "0007" || got.Status != "Accepted" || got.Title != "ADR-0007: Example Title" || got.Filename != "0007-example.md" {
		t.Errorf("unexpected ADR: %+v", got)
	}
}

// TestParseDirGlobError exercises the glob-pattern failure path: a directory
// whose name contains an unterminated "[" yields an ErrBadPattern from Glob.
func TestParseDirGlobError(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "bad[")
	if err := os.Mkdir(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	if _, err := adr.ParseDir(dir); err == nil {
		t.Fatal("expected glob error for malformed pattern, got nil")
	}
}

// TestParseDirReadError exercises the os.ReadFile failure path: a directory
// squatting on a path that matches the ADR filename pattern cannot be read as a
// file (fails for all users, including root).
func TestParseDirReadError(t *testing.T) {
	dir := t.TempDir()
	if err := os.Mkdir(filepath.Join(dir, "0001-squatter.md"), 0o755); err != nil {
		t.Fatal(err)
	}
	if _, err := adr.ParseDir(dir); err == nil {
		t.Fatal("expected read error for directory in file's place, got nil")
	}
}

// TestParseDirParseError exercises the parse failure path: malformed YAML
// frontmatter in an ADR file makes parse return an error.
func TestParseDirParseError(t *testing.T) {
	dir := t.TempDir()
	content := "---\nstatus: [unterminated\n---\n# ADR-0001: Broken\n"
	if err := os.WriteFile(filepath.Join(dir, "0001-broken.md"), []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := adr.ParseDir(dir); err == nil {
		t.Fatal("expected parse error for malformed frontmatter, got nil")
	}
}

// TestRenderActiveMDParseError ensures RenderActiveMD propagates a ParseDir
// error instead of producing output.
func TestRenderActiveMDParseError(t *testing.T) {
	dir := t.TempDir()
	content := "---\nstatus: [unterminated\n---\n# ADR-0001: Broken\n"
	if err := os.WriteFile(filepath.Join(dir, "0001-broken.md"), []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
	got, err := adr.RenderActiveMD(dir)
	if err == nil {
		t.Fatal("expected error from malformed frontmatter, got nil")
	}
	if got != "" {
		t.Errorf("expected empty output on error, got: %q", got)
	}
}

// TestRenderActiveMDSortsWithinStatusAndOrdersExtra covers two paths: sorting
// multiple ADRs within one status group (by number), and appending a status not
// present in statusOrder (sorted after the known statuses).
func TestRenderActiveMDSortsWithinStatusAndOrdersExtra(t *testing.T) {
	dir := t.TempDir()
	files := map[string]string{
		"0002-second-accepted.md": "---\nstatus: Accepted\n---\n# ADR-0002: Second Accepted\n",
		"0001-first-accepted.md":  "---\nstatus: Accepted\n---\n# ADR-0001: First Accepted\n",
		"0003-draft-status.md":    "---\nstatus: Draft\n---\n# ADR-0003: Draft Status\n",
	}
	for name, content := range files {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(content), 0o644); err != nil {
			t.Fatalf("write fixture %s: %v", name, err)
		}
	}

	got, err := adr.RenderActiveMD(dir)
	if err != nil {
		t.Fatalf("RenderActiveMD: %v", err)
	}

	// Within the Accepted group, 0001 must be listed before 0002.
	first := strings.Index(got, "ADR-0001: First Accepted")
	second := strings.Index(got, "ADR-0002: Second Accepted")
	if first < 0 || second < 0 {
		t.Fatalf("missing accepted entries; got:\n%s", got)
	}
	if first > second {
		t.Errorf("0001 (%d) should be listed before 0002 (%d)", first, second)
	}

	// The unknown "Draft" status must appear as its own section, after the
	// known statuses.
	acceptedPos := strings.Index(got, "## Accepted")
	draftPos := strings.Index(got, "## Draft")
	if draftPos < 0 {
		t.Fatalf("missing ## Draft section; got:\n%s", got)
	}
	if acceptedPos > draftPos {
		t.Errorf("Accepted (%d) should come before extra status Draft (%d)", acceptedPos, draftPos)
	}
}

// invariant: adr-sections-parsed
func TestParseDirExtractsSections(t *testing.T) {
	dir := t.TempDir()
	content := "---\nstatus: Implemented\ndate: 2026-06-25\ntags: [x]\n---\n# ADR-0009: S\n## Context\nctx body\n## Invariants\n- `inv: example-slug` — a thing.\n## Consequences\ncons\n"
	if err := os.WriteFile(filepath.Join(dir, "0009-s.md"), []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
	adrs, err := adr.ParseDir(dir)
	if err != nil {
		t.Fatalf("ParseDir: %v", err)
	}
	if len(adrs) != 1 {
		t.Fatalf("expected 1 ADR, got %d", len(adrs))
	}
	inv := adrs[0].Sections["Invariants"]
	if !strings.Contains(inv, "inv: example-slug") {
		t.Errorf("Invariants section missing tag; got: %q", inv)
	}
	if !strings.Contains(adrs[0].Sections["Context"], "ctx body") {
		t.Errorf("Context section wrong: %q", adrs[0].Sections["Context"])
	}
}
