#!/usr/bin/env bash
# GENERATED by awf: do not edit; change .awf/ and run `awf sync`
# Pre-commit payload: drift check, the staged current-state check, then the
# project gate. Inert until wired into a hook setup you own, e.g. a
# .git/hooks/pre-commit stub containing:
#   exec bash .awf/hooks/pre-commit.sh "$@"
set -euo pipefail

# Run the pinned awf when the bootstrap resolves; fall back to PATH awf.
awf() { local pinned; if [ -f .awf/bootstrap.sh ] && pinned="$(bash .awf/bootstrap.sh 2>/dev/null)"; then "$pinned" "$@"; else command awf "$@"; fi; }
./x check
./x check --staged
./x gate
awf prose-gate
