#!/usr/bin/env bash
# GENERATED by awf — do not edit; change .awf/ and run `awf sync`
# Pre-push payload: the fullest gate tier the project configures. Inert until
# wired into a hook setup you own — e.g. a .git/hooks/pre-push stub containing:
#   exec bash .awf/hooks/pre-push.sh "$@"
set -euo pipefail
./x gate full
