// Package adrtools generates the ACTIVE.md index for docs/decisions/.
// Run via: go test ./internal/adrtools/
package adrtools

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// statusOrder defines the section order in ACTIVE.md.
var statusOrder = []string{"Accepted", "Implemented", "Proposed", "Superseded"}

// frontmatter holds the YAML fields we care about.
type frontmatter struct {
	Status string `yaml:"status"`
}

// adrEntry is a parsed ADR record.
type adrEntry struct {
	Number   string // e.g. "0001"
	Title    string // e.g. "ADR-0001: Template Overlay Rendering Engine"
	Filename string // e.g. "0001-template-overlay-rendering-engine.md"
	Status   string // e.g. "Accepted"
}

var adrFileRe = regexp.MustCompile(`^(\d{4})-.*\.md$`)

// GenerateActiveMD scans decisionsDir for ADR files (NNNN-*.md), parses their
// YAML frontmatter and first `# ` heading, and returns the content of a
// regenerated ACTIVE.md grouped by status.
func GenerateActiveMD(decisionsDir string) (string, error) {
	pattern := filepath.Join(decisionsDir, "*.md")
	matches, err := filepath.Glob(pattern)
	if err != nil {
		return "", fmt.Errorf("glob %s: %w", pattern, err)
	}

	var entries []adrEntry
	for _, path := range matches {
		base := filepath.Base(path)
		m := adrFileRe.FindStringSubmatch(base)
		if m == nil {
			continue // skip ACTIVE.md, README.md, template.md
		}
		number := m[1]

		data, err := os.ReadFile(path)
		if err != nil {
			return "", fmt.Errorf("read %s: %w", base, err)
		}

		fm, title, err := parseFrontmatterAndTitle(data)
		if err != nil {
			return "", fmt.Errorf("parse %s: %w", base, err)
		}

		entries = append(entries, adrEntry{
			Number:   number,
			Title:    title,
			Filename: base,
			Status:   fm.Status,
		})
	}

	// Group by status.
	groups := make(map[string][]adrEntry)
	for _, e := range entries {
		groups[e.Status] = append(groups[e.Status], e)
	}

	// Sort within each group by ADR number.
	for k := range groups {
		sort.Slice(groups[k], func(i, j int) bool {
			return groups[k][i].Number < groups[k][j].Number
		})
	}

	// Collect sections in defined order, then any remaining statuses.
	seen := make(map[string]bool)
	var orderedStatuses []string
	for _, s := range statusOrder {
		if len(groups[s]) > 0 {
			orderedStatuses = append(orderedStatuses, s)
			seen[s] = true
		}
	}
	// Append any unknown statuses, sorted alphabetically.
	var extra []string
	for k := range groups {
		if !seen[k] {
			extra = append(extra, k)
		}
	}
	sort.Strings(extra)
	orderedStatuses = append(orderedStatuses, extra...)

	var sb strings.Builder
	sb.WriteString("<!-- GENERATED by internal/adrtools — do not edit by hand. Run: go test ./internal/adrtools/ -->\n")

	for _, status := range orderedStatuses {
		sb.WriteString("\n## ")
		sb.WriteString(status)
		sb.WriteString("\n\n")
		for _, e := range groups[status] {
			fmt.Fprintf(&sb, "- [%s](%s) — %s\n", e.Title, e.Filename, e.Status)
		}
	}

	return sb.String(), nil
}

// parseFrontmatterAndTitle extracts YAML frontmatter and the first `# ` heading.
func parseFrontmatterAndTitle(data []byte) (frontmatter, string, error) {
	content := string(data)

	var fm frontmatter
	var title string

	// Extract YAML frontmatter between --- delimiters.
	if strings.HasPrefix(content, "---") {
		end := strings.Index(content[3:], "\n---")
		if end >= 0 {
			yamlBlock := content[3 : end+3]
			if err := yaml.Unmarshal([]byte(yamlBlock), &fm); err != nil {
				return fm, "", fmt.Errorf("yaml unmarshal: %w", err)
			}
			content = content[end+7:] // skip past closing ---\n
		}
	}

	// Find first `# ` heading.
	for _, line := range strings.Split(content, "\n") {
		if strings.HasPrefix(line, "# ") {
			title = strings.TrimPrefix(line, "# ")
			break
		}
	}

	return fm, title, nil
}
