package adrtools_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"agentic-workflows/internal/adrtools"
)

// TestGenerateActiveMDGroupsByStatus is a hermetic unit test using a temp dir.
func TestGenerateActiveMDGroupsByStatus(t *testing.T) {
	dir := t.TempDir()

	files := map[string]string{
		"0001-first-accepted.md": `---
status: Accepted
date: 2026-06-24
tags: [tooling]
---
# ADR-0001: First Accepted
## Context
Something.
`,
		"0002-a-proposal.md": `---
status: Proposed
date: 2026-06-24
tags: []
---
# ADR-0002: A Proposal
## Context
Another thing.
`,
		"0003-already-implemented.md": `---
status: Implemented
date: 2026-06-24
tags: []
---
# ADR-0003: Already Implemented
## Context
Done.
`,
	}

	for name, content := range files {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(content), 0644); err != nil {
			t.Fatalf("write fixture %s: %v", name, err)
		}
	}

	got, err := adrtools.GenerateActiveMD(dir)
	if err != nil {
		t.Fatalf("GenerateActiveMD: %v", err)
	}

	// Must start with the generator header comment.
	if !strings.HasPrefix(got, "<!-- GENERATED by awf sync") {
		t.Errorf("missing header comment; got start: %q", got[:min(60, len(got))])
	}

	// Accepted must appear before Proposed.
	acceptedPos := strings.Index(got, "## Accepted")
	implementedPos := strings.Index(got, "## Implemented")
	proposedPos := strings.Index(got, "## Proposed")

	if acceptedPos < 0 {
		t.Error("missing ## Accepted section")
	}
	if implementedPos < 0 {
		t.Error("missing ## Implemented section")
	}
	if proposedPos < 0 {
		t.Error("missing ## Proposed section")
	}
	if acceptedPos > 0 && implementedPos > 0 && acceptedPos > implementedPos {
		t.Errorf("Accepted (%d) should come before Implemented (%d)", acceptedPos, implementedPos)
	}
	if implementedPos > 0 && proposedPos > 0 && implementedPos > proposedPos {
		t.Errorf("Implemented (%d) should come before Proposed (%d)", implementedPos, proposedPos)
	}

	// Each ADR entry should appear under the correct section.
	checkEntry := func(section, title, filename string) {
		t.Helper()
		sectionHeader := "## " + section
		sectionStart := strings.Index(got, sectionHeader)
		if sectionStart < 0 {
			t.Errorf("section %q not found", sectionHeader)
			return
		}
		// Find next section after this one.
		nextSection := strings.Index(got[sectionStart+len(sectionHeader):], "\n## ")
		var sectionBody string
		if nextSection < 0 {
			sectionBody = got[sectionStart:]
		} else {
			sectionBody = got[sectionStart : sectionStart+len(sectionHeader)+nextSection]
		}
		if !strings.Contains(sectionBody, title) {
			t.Errorf("expected %q in section %q; section body:\n%s", title, section, sectionBody)
		}
		if !strings.Contains(sectionBody, filename) {
			t.Errorf("expected filename %q in section %q", filename, section)
		}
	}

	checkEntry("Accepted", "ADR-0001: First Accepted", "0001-first-accepted.md")
	checkEntry("Implemented", "ADR-0003: Already Implemented", "0003-already-implemented.md")
	checkEntry("Proposed", "ADR-0002: A Proposal", "0002-a-proposal.md")
}

func TestGenerateActiveMDEmptyWhenNoADRs(t *testing.T) {
	dir := t.TempDir()
	// A non-ADR markdown file must not count.
	if err := os.WriteFile(filepath.Join(dir, "README.md"), []byte("# readme\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	got, err := adrtools.GenerateActiveMD(dir)
	if err != nil {
		t.Fatalf("GenerateActiveMD: %v", err)
	}
	if got != "" {
		t.Errorf("expected empty output for an ADR-less dir, got:\n%s", got)
	}
}
