// GENERATED by awf: do not edit; change .awf/ and run `awf render`
// @ts-nocheck
import { isAbsolute, normalize } from "node:path";

export type CheckoutRole = "managed" | "receiving";
export type ActivityCondition =
  | "ready"
  | "attached"
  | "taken-over"
  | "heartbeat"
  | "checkout-updated"
  | "detached"
  | "not-owner"
  | "missing"
  | "invalid-memory"
  | "unsafe-resident"
  | "repository-mismatch";

export type ActivityFact = Readonly<{
  schemaVersion: 1;
  owner: string;
  attachedAt: string;
  heartbeatAt: string;
  cwd: string;
  receivingCheckout: string;
  role: CheckoutRole;
}>;
export type EffortFact = Readonly<{ slug: string; title: string }>;
export type MemoryFact = Readonly<{ effort: string; phase: string; next: string; updated: string }>;
export type DestinationFact = Readonly<{ cwd: string; role: CheckoutRole; receivingCheckout: string }>;
export type ActionableOutcome = Readonly<{
  category: "operation" | "topology" | "repository-identity";
  condition: ActivityCondition;
  changedActivity: boolean;
  changedMemory: boolean;
  changedCwd: boolean;
  nextActions: readonly string[];
  cause?: string;
}>;
export type ActivityReply = Readonly<{
  schemaVersion: 1;
  condition: ActivityCondition;
  effort?: EffortFact;
  memory?: MemoryFact;
  destination?: DestinationFact;
  activity?: ActivityFact;
  priorClaim?: ActivityFact;
  outcome?: ActionableOutcome;
}>;
export type ExecResult = Readonly<{ code?: number; stdout?: string; stderr?: string }>;
export type ActivityExecutor = (
  command: string,
  argv: readonly string[],
  options: Readonly<{ cwd: string; signal?: AbortSignal; timeout: number }>,
) => Promise<ExecResult>;

const MAX_OUTPUT = 50 * 1024;
const MAX_TEXT = 4096;
const MAX_CHECKPOINT = 500;
const UUID_V4 = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
const UTC_TIME = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,9})?Z$/;
const SUCCESS = new Set<ActivityCondition>(["ready", "attached", "taken-over", "heartbeat", "checkout-updated", "detached"]);
const CONDITIONS = new Set<ActivityCondition>([
  ...SUCCESS,
  "not-owner",
  "missing",
  "invalid-memory",
  "unsafe-resident",
  "repository-mismatch",
]);
const CATEGORIES = new Set(["operation", "topology", "repository-identity"] as const);

export class EffortProtocolError extends Error {
  constructor(message: string, readonly stdout = "", readonly stderr = "") {
    super(message);
    this.name = "EffortProtocolError";
  }
}

function record(value: unknown): Record<string, unknown> | undefined {
  return value !== null && typeof value === "object" && !Array.isArray(value)
    ? value as Record<string, unknown>
    : undefined;
}
function closed(value: Record<string, unknown>, keys: readonly string[]): boolean {
  const actual = Object.keys(value);
  return actual.length <= keys.length && actual.every((key) => keys.includes(key));
}
function bounded(value: unknown, maximum = MAX_TEXT): value is string {
  return typeof value === "string" && Buffer.byteLength(value, "utf8") <= maximum;
}
function nonblank(value: unknown, maximum = MAX_TEXT): value is string {
  return bounded(value, maximum) && value.trim() !== "";
}
function role(value: unknown): value is CheckoutRole {
  return value === "managed" || value === "receiving";
}
function utc(value: unknown): value is string {
  return bounded(value) && UTC_TIME.test(value) && !Number.isNaN(Date.parse(value));
}
function cleanAbsolute(value: unknown): value is string {
  return nonblank(value) && isAbsolute(value) && normalize(value) === value;
}
function effortFact(value: unknown): EffortFact | undefined {
  const item = record(value);
  if (!item || !closed(item, ["slug", "title"]) || Object.keys(item).length !== 2 || !nonblank(item.slug, 255) || !nonblank(item.title, 500)) return undefined;
  return Object.freeze({ slug: item.slug, title: item.title });
}
function memoryFact(value: unknown): MemoryFact | undefined {
  const item = record(value);
  if (!item || !closed(item, ["effort", "phase", "next", "updated"]) || Object.keys(item).length !== 4 || !nonblank(item.effort, 255) || !nonblank(item.phase, MAX_CHECKPOINT) || !nonblank(item.next, MAX_CHECKPOINT) || !(item.updated === "Not yet updated." || utc(item.updated))) return undefined;
  return Object.freeze({ effort: item.effort, phase: item.phase, next: item.next, updated: item.updated });
}
function destinationFact(value: unknown): DestinationFact | undefined {
  const item = record(value);
  if (!item || !closed(item, ["cwd", "role", "receivingCheckout"]) || Object.keys(item).length !== 3 || !cleanAbsolute(item.cwd) || !role(item.role) || !cleanAbsolute(item.receivingCheckout)) return undefined;
  return Object.freeze({ cwd: item.cwd, role: item.role, receivingCheckout: item.receivingCheckout });
}
function activityFact(value: unknown): ActivityFact | undefined {
  const item = record(value);
  if (!item || !closed(item, ["schemaVersion", "owner", "attachedAt", "heartbeatAt", "cwd", "receivingCheckout", "role"]) || Object.keys(item).length !== 7 || item.schemaVersion !== 1 || !bounded(item.owner) || !UUID_V4.test(item.owner) || !utc(item.attachedAt) || !utc(item.heartbeatAt) || !cleanAbsolute(item.cwd) || !cleanAbsolute(item.receivingCheckout) || !role(item.role)) return undefined;
  return Object.freeze({ schemaVersion: 1, owner: item.owner, attachedAt: item.attachedAt, heartbeatAt: item.heartbeatAt, cwd: item.cwd, receivingCheckout: item.receivingCheckout, role: item.role });
}
function outcomeFact(value: unknown, condition: ActivityCondition): ActionableOutcome | undefined {
  const item = record(value);
  if (!item || !closed(item, ["category", "condition", "changedActivity", "changedMemory", "changedCwd", "nextActions", "cause"]) || !bounded(item.category) || !CATEGORIES.has(item.category as ActionableOutcome["category"]) || item.condition !== condition || typeof item.changedActivity !== "boolean" || typeof item.changedMemory !== "boolean" || typeof item.changedCwd !== "boolean" || !Array.isArray(item.nextActions) || item.nextActions.length === 0 || !item.nextActions.every((next) => nonblank(next)) || (item.cause !== undefined && !nonblank(item.cause))) return undefined;
  return Object.freeze({
    category: item.category as ActionableOutcome["category"],
    condition,
    changedActivity: item.changedActivity,
    changedMemory: item.changedMemory,
    changedCwd: item.changedCwd,
    nextActions: Object.freeze([...(item.nextActions as string[])]),
    ...(item.cause === undefined ? {} : { cause: item.cause as string }),
  });
}
function exactPresence(item: Record<string, unknown>, required: readonly string[], optional: readonly string[] = []): boolean {
  const allowed = ["schemaVersion", "condition", ...required, ...optional];
  return closed(item, allowed) && required.every((key) => item[key] !== undefined) && Object.keys(item).every((key) => allowed.includes(key));
}
function validPresence(item: Record<string, unknown>, condition: ActivityCondition): boolean {
  switch (condition) {
    case "ready": return exactPresence(item, ["effort", "memory", "destination"], ["priorClaim"]);
    case "attached": return exactPresence(item, ["effort", "memory", "activity"]);
    case "taken-over": return exactPresence(item, ["effort", "memory", "activity", "priorClaim"]);
    case "heartbeat":
    case "checkout-updated": return exactPresence(item, ["effort", "memory", "activity"]);
    case "detached": return exactPresence(item, [], ["effort"]);
    case "not-owner": return exactPresence(item, ["effort", "activity", "outcome"]);
    case "missing": return exactPresence(item, ["outcome"]);
    case "invalid-memory": return exactPresence(item, ["effort", "outcome"]);
    case "unsafe-resident":
    case "repository-mismatch": return exactPresence(item, ["outcome"]);
  }
}
function decodeReply(value: unknown): ActivityReply | undefined {
  const item = record(value);
  if (!item || item.schemaVersion !== 1 || !bounded(item.condition) || !CONDITIONS.has(item.condition as ActivityCondition)) return undefined;
  const condition = item.condition as ActivityCondition;
  if (!validPresence(item, condition)) return undefined;
  const effort = item.effort === undefined ? undefined : effortFact(item.effort);
  const memory = item.memory === undefined ? undefined : memoryFact(item.memory);
  const destination = item.destination === undefined ? undefined : destinationFact(item.destination);
  const activityValue = item.activity === undefined ? undefined : activityFact(item.activity);
  const priorClaim = item.priorClaim === undefined ? undefined : activityFact(item.priorClaim);
  const outcome = item.outcome === undefined ? undefined : outcomeFact(item.outcome, condition);
  if ((item.effort !== undefined && !effort) || (item.memory !== undefined && !memory) || (item.destination !== undefined && !destination) || (item.activity !== undefined && !activityValue) || (item.priorClaim !== undefined && !priorClaim) || (item.outcome !== undefined && !outcome)) return undefined;
  if (effort && memory && effort.slug !== memory.effort) return undefined;
  return Object.freeze({
    schemaVersion: 1,
    condition,
    ...(effort ? { effort } : {}),
    ...(memory ? { memory } : {}),
    ...(destination ? { destination } : {}),
    ...(activityValue ? { activity: activityValue } : {}),
    ...(priorClaim ? { priorClaim } : {}),
    ...(outcome ? { outcome } : {}),
  });
}
function diagnostic(value: unknown): string {
  const rendered = value instanceof Error ? `${value.name}: ${value.message}` : String(value);
  return Buffer.from(rendered).subarray(0, MAX_OUTPUT).toString("utf8");
}

export async function activity(
  exec: ActivityExecutor,
  cwd: string,
  args: readonly string[],
  signal?: AbortSignal,
): Promise<ActivityReply> {
  let result: ExecResult;
  try {
    result = await exec("./awf", ["effort", "activity", ...args, "--json"], { cwd, signal, timeout: 15_000 });
  } catch (error) {
    throw new EffortProtocolError("awf activity execution failed", "", diagnostic(error));
  }
  const stdout = String(result.stdout ?? "");
  const stderr = String(result.stderr ?? "");
  if (Buffer.byteLength(stdout, "utf8") > MAX_OUTPUT || Buffer.byteLength(stderr, "utf8") > MAX_OUTPUT) throw new EffortProtocolError("awf activity output exceeded bounds", Buffer.from(stdout).subarray(0, MAX_OUTPUT).toString("utf8"), Buffer.from(stderr).subarray(0, MAX_OUTPUT).toString("utf8"));
  if (result.code !== undefined && result.code !== 0) throw new EffortProtocolError("awf activity failed", stdout, stderr);
  if (!stdout.endsWith("\n") || stdout.slice(0, -1).includes("\n") || stdout === "\n") throw new EffortProtocolError("awf activity returned no single JSON envelope", stdout, stderr);
  let decoded: unknown;
  try {
    decoded = JSON.parse(stdout.slice(0, -1));
  } catch {
    throw new EffortProtocolError("awf activity returned malformed JSON", stdout, stderr);
  }
  const reply = decodeReply(decoded);
  if (!reply) throw new EffortProtocolError("awf activity returned an invalid envelope", stdout, stderr);
  return reply;
}
