import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { chmod, mkdir, mkdtemp, readFile, readdir, rename, rm, symlink, utimes, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { promisify } from "node:util";
import { visibleWidth } from "@earendil-works/pi-tui";
import defaultDashboard, {
  ASSOCIATION_ENTRY,
  DashboardOverlay,
  createDashboardState,
  dashboardWidget,
  createLedgerWriter,
  defaultDashboardDependencies,
  defaultLedgerDependencies,
  pendingHandoff,
  projectLocalLifecycle,
  registerDashboard,
  restoreAssociation,
  telemetryWidgetEnabled,
  telemetryWidgetShowCost,
  versionSupported,
} from "../../../.pi/extensions/awf-dashboard/index.ts";
import { protocolVersion, validateTelemetryEvent } from "../../../.pi/extensions/awf-dashboard/protocol.ts";

function creation(effortId = "effort", sessionId = "session"): any {
  return { version: protocolVersion, eventId: "create-event", idempotencyKey: "create-key", effortId, sessionId, timestamp: "2026-07-22T00:00:00Z", kind: "effort_created", predecessors: [], payload: { checkpointId: ".awf/memory/work.md", creationMode: "independent" } };
}
function association(effortId = "effort", sessionId = "session", eventId = "associate-event"): any {
  return { version: protocolVersion, eventId, idempotencyKey: eventId, effortId, sessionId, trajectoryId: "trajectory", timestamp: "2026-07-22T00:00:01Z", kind: "session_associated", predecessors: ["create-event"], payload: { associationOrigin: "created", trajectoryId: "trajectory" } };
}
async function root(): Promise<string> { const value = await mkdtemp(join(tmpdir(), "awf-dashboard-")); await mkdir(join(value, ".awf"), { mode: 0o700 }); return value; }

test("dashboard constants, state, association restoration, and gate projection are closed", () => {
  assert.equal(typeof telemetryWidgetEnabled, "boolean"); assert.equal(typeof telemetryWidgetShowCost, "boolean");
  const state = createDashboardState(); assert.equal(state.status, "loading"); assert.equal(state.errorCategory, undefined); state.set("ready", { metrics: { ok: 1 }, doctor: { findings: [] } }); assert.deepEqual(state.metrics, { ok: 1 }); assert.deepEqual(state.doctor, { findings: [] }); const snapshot = state.snapshot(); assert.equal(snapshot.status, "ready"); assert.throws(() => { (snapshot as any).status = "bad"; }); state.set("closed"); state.set("ready"); assert.equal(state.status, "closed");
  const good = { effortId: "effort", sessionId: "session", trajectoryId: "trajectory", associationOrigin: "manual" };
  const ctx = { sessionManager: { getBranch: () => [{ type: "custom", customType: ASSOCIATION_ENTRY, data: good }, { type: "custom", customType: ASSOCIATION_ENTRY, data: { ...good, trajectoryId: "latest" } }] } };
  assert.deepEqual(restoreAssociation(ctx), { ...good, trajectoryId: "latest" });
  for (const invalid of [undefined, { sessionManager: {} }, { sessionManager: { getBranch: () => [{ type: "custom", customType: ASSOCIATION_ENTRY, data: { ...good, extra: true } }] } }, { sessionManager: { getBranch: () => [{ type: "custom", customType: ASSOCIATION_ENTRY, data: { ...good, effortId: "../bad" } }] } }]) assert.equal(restoreAssociation(invalid), undefined);
  assert.equal(versionSupported("0.81.1"), true); assert.equal(versionSupported("0.80.9"), false); assert.equal(versionSupported("garbage"), false); assert.equal(versionSupported("1.0.0"), true); assert.equal(versionSupported("0.82.0-beta"), true);
  const detached = { sessionManager: { getBranch: () => [{ type: "custom", customType: ASSOCIATION_ENTRY, data: good }, { type: "custom", customType: "awf.telemetry.detached.v1", data: {} }, { type: "message" }] } }; assert.equal(restoreAssociation(detached), undefined);
  assert.equal(restoreAssociation({ sessionManager: { getBranch: () => [{ type: "custom", customType: ASSOCIATION_ENTRY, data: [] }] } }), undefined); for (const value of ["", ".", "..", "a/b", "a\\b", "x".repeat(129), 1, [], null]) { const bad = { sessionManager: { getBranch: () => [{ type: "custom", customType: ASSOCIATION_ENTRY, data: { ...good, effortId: value } }] } }; assert.equal(restoreAssociation(bad), undefined); }
});

test("pending handoff setup data is exact closed and bounded", () => {
  const entry = (data: any) => ({ type: "custom", customType: "awf.telemetry.handoff.pending.v1", data }); const valid = { version: protocolVersion, observationId: "observation", startedAt: 1, durationMs: 2 }; assert.deepEqual(pendingHandoff({ sessionManager: { getBranch: () => [entry(valid)] } }), { observationId: "observation", durationMs: 2 });
  for (const ctx of [undefined, {}, { sessionManager: { getBranch: () => null } }, { sessionManager: { getBranch: () => [{ type: "message" }] } }, ...[null, [], { ...valid, extra: true }, { ...valid, version: { major: 2, minor: 0 } }, { ...valid, observationId: "bad/id" }, { ...valid, startedAt: -1 }, { ...valid, durationMs: -1 }].map((data) => ({ sessionManager: { getBranch: () => [entry(data)] } }))]) assert.equal(pendingHandoff(ctx), undefined);
});

test("fake executable proves bootstrap binary resolution and canonical process handshake", async () => {
  const project = await root();
  try { const fake = join(process.cwd(), "tools/pi-extension-test/fixtures/fake-awf.mjs"); const bootstrap = join(project, ".awf/bootstrap.sh"); await writeFile(bootstrap, `#!/usr/bin/env bash\nprintf '%s\\n' '${fake}'\n`); await chmod(bootstrap, 0o700); const run = promisify(execFile); const calls: any[] = []; const state = createDashboardState("loading", { root: project, exec: async (command, args) => { calls.push([command, args]); try { const result = await run(command === "bash" ? "sh" : command, args, { cwd: project }); calls.push(["result", result.stdout, result.stderr]); return { stdout: result.stdout, stderr: result.stderr, code: 0 }; } catch (error: any) { calls.push(["error", error.message, error.code]); return { stdout: error.stdout ?? "", stderr: error.stderr ?? "", code: error.code ?? 1 }; } } }); const refreshed = await state.refresh(); assert.equal(refreshed.ok, true, JSON.stringify({ refreshed, calls })); assert.equal(state.binary, fake); }
  finally { await rm(project, { recursive: true, force: true, maxRetries: 5, retryDelay: 10 }); }
});

test("canonical refresh resolves, handshakes, orders projections, retains atomically, and cancels late work", async () => {
  const calls: any[] = []; let failDoctor = false;
  const deps: any = { root: "/project", exec: async (command: string, args: string[]) => { calls.push([command, args]); if (command === "bash") return { stdout: "/cache/awf\n", stderr: "", code: 0 }; if (args[0] === "metrics" && args[1] === "protocol") return { stdout: protocolJSON(), stderr: "", code: 0 }; if (args[0] === "metrics" && args[1] === "retain") return { stdout: "{}", stderr: "", code: 0 }; if (args[0] === "metrics") return { stdout: metricsJSON({ efforts: [{ effortId: "one" }] }), stderr: "", code: 0 }; if (args[0] === "doctor") return failDoctor ? { stdout: "", stderr: "bad", code: 1 } : { stdout: doctorJSON({ findings: [{ code: "ok" }] }), stderr: "", code: 0 }; throw new Error("unexpected"); } };
  let changes = 0; const state = createDashboardState("loading", deps, () => { changes++; }); const refreshController = new AbortController(); const ready = await state.refresh({ effort: "one", session: "s", phase: "planning", since: "a", until: "b" }, refreshController.signal); assert.equal(ready.ok, true); assert.equal(state.status, "ready"); assert.equal(state.binary, "/cache/awf"); assert.equal(changes >= 2, true);
  assert.deepEqual(calls.map(([command, args]) => [command, args]), [["bash", ["/project/.awf/bootstrap.sh"]], ["/cache/awf", ["metrics", "protocol", "--json"]], ["/cache/awf", ["metrics", "--effort", "one", "--session", "s", "--phase", "planning", "--since", "a", "--until", "b", "--json"]], ["/cache/awf", ["doctor", "--effort", "one", "--session", "s", "--phase", "planning", "--since", "a", "--until", "b", "--json"]]]);
  assert.equal((await state.runFixed(["metrics", "retain", "--json"])).ok, true); failDoctor = true; const stale = await state.refresh(); assert.equal(stale.status, "stale"); assert.equal(stale.errorCategory, "query"); assert.equal(state.metrics.efforts[0].effortId, "one"); assert.equal(state.doctor.findings[0].code, "ok"); state.markStale("retain"); assert.equal(state.errorCategory, "retain");
  let release!: (value: any) => void; let pendingSignal: AbortSignal | undefined; const pendingDeps: any = { root: "/project", exec: async (command: string, args: string[], signal?: AbortSignal) => { pendingSignal = signal; if (command === "bash") return { stdout: "bad\npath\n", stderr: "", code: 0 }; if (args[1] === "protocol") return new Promise((done) => { release = done; }); throw new Error("late query must not run"); } }; const pendingState = createDashboardState("loading", pendingDeps); const pending = pendingState.refresh(); await new Promise((done) => setImmediate(done)); pendingState.close(); assert.equal(pendingSignal?.aborted, true); release({ stdout: protocolJSON(), stderr: "", code: 0 }); const cancelled = await pending; assert.equal(cancelled.errorCategory, "cancelled"); assert.equal(pendingState.status, "closed"); assert.equal((await pendingState.refresh()).errorCategory, "cancelled"); assert.equal((await pendingState.runFixed(["metrics", "retain", "--json"])).errorCategory, "unavailable"); pendingState.set("ready"); assert.equal(pendingState.status, "closed"); pendingState.close();
  let maintenanceSignal: AbortSignal | undefined; let finishMaintenance!: (value: any) => void; const maintenanceState = createDashboardState("ready", { root: "/p", exec: async (_command, _args, signal) => { maintenanceSignal = signal; return new Promise((done) => { finishMaintenance = done; }); } }); maintenanceState.set("ready", { binary: "/awf", metrics: {}, doctor: {} }); const maintenanceTask = maintenanceState.runFixed(["metrics", "retain", "--json"]); await new Promise((done) => setImmediate(done)); maintenanceState.close(); assert.equal(maintenanceSignal?.aborted, true); finishMaintenance({ stdout: "{}", stderr: "", code: 0 }); assert.equal((await maintenanceTask).errorCategory, "cancelled");
  let firstMetrics!: (value: any) => void; let metricsCalls = 0; const superseded = createDashboardState("loading", { root: "/p", exec: async (command, args) => { if (command === "bash") return { stdout: "", stderr: "", code: 1 }; if (args[1] === "protocol") return { stdout: protocolJSON(), stderr: "", code: 0 }; if (args[0] === "metrics" && ++metricsCalls === 1) return new Promise((done) => { firstMetrics = done; }); if (args[0] === "metrics") return { stdout: metricsJSON(), stderr: "", code: 0 }; return { stdout: doctorJSON(), stderr: "", code: 0 }; } }); const oldRefresh = superseded.refresh(); await new Promise((done) => setImmediate(done)); const newRefresh = superseded.refresh(); assert.equal((await newRefresh).ok, true); firstMetrics({ stdout: metricsJSON(), stderr: "", code: 0 }); assert.equal((await oldRefresh).errorCategory, "cancelled");
});

test("canonical refresh degrades for every resolution, version, protocol, and JSON boundary with PATH fallback", async () => {
  const cases: Array<[string, (command: string, args: string[]) => any]> = [
    ["resolution", (_command, args) => args[1] === "protocol" ? { stdout: "", stderr: "", code: 1 } : { stdout: "x\ny\n", stderr: "", code: 0 }],
    ["malformed", (_command, args) => args[1] === "protocol" ? { stdout: "[]", stderr: "", code: 0 } : { stdout: "", stderr: "", code: 1 }],
    ["protocol", (_command, args) => args[1] === "protocol" ? { stdout: protocolJSON({ protocol: { major: 2, minor: 0 } }), stderr: "", code: 0 } : { stdout: "", stderr: "", code: 1 }],
    ["version", (_command, args) => args[1] === "protocol" ? { stdout: protocolJSON({ awfVersion: "0.21.0", projectVersion: "0.22.0" }), stderr: "", code: 0 } : { stdout: "", stderr: "", code: 1 }],
    ["protocol", (_command, args) => args[1] === "protocol" ? { stdout: protocolJSON(), stderr: "", code: 0 } : args[0] === "metrics" ? { stdout: metricsJSON({ schemaVersion: 2 }), stderr: "", code: 0 } : { stdout: doctorJSON(), stderr: "", code: 0 }],
    ["malformed", (_command, args) => args[1] === "protocol" ? { stdout: protocolJSON(), stderr: "", code: 0 } : args[0] === "metrics" ? { stdout: "not-json", stderr: "", code: 0 } : { stdout: doctorJSON(), stderr: "", code: 0 }],
    ["protocol", (_command, args) => args[1] === "protocol" ? { stdout: protocolJSON(), stderr: "", code: 0 } : args[0] === "metrics" ? { stdout: metricsJSON(), stderr: "", code: 0 } : { stdout: doctorJSON({ protocolMajor: 2 }), stderr: "", code: 0 }],
    ["malformed", (_command, args) => args[1] === "protocol" ? { stdout: protocolJSON(), stderr: "", code: 0 } : args[0] === "metrics" ? { stdout: metricsJSON(), stderr: "", code: 0 } : { stdout: "null", stderr: "", code: 0 }],
  ];
  for (const [category, response] of cases) { const calls: any[] = []; const state = createDashboardState("loading", { root: "/project", exec: async (command, args) => { calls.push([command, args]); if (command === "bash") return { stdout: "bad\npath\n", stderr: "", code: 0 }; return response(command, args); } }); const result = await state.refresh(); assert.equal(result.status, "degraded"); assert.equal(result.errorCategory, category); assert.equal(calls.some(([command]) => command === "awf"), true); }
  const metricsFailure = createDashboardState("loading", { root: "/p", exec: async (command, args) => command === "bash" ? { stdout: "", stderr: "", code: 1 } : args[1] === "protocol" ? { stdout: protocolJSON(), stderr: "", code: 0 } : { stdout: "", stderr: "", code: 1 } }); assert.equal((await metricsFailure.refresh()).errorCategory, "query");
  const unknownFailure = createDashboardState("loading", { root: "/p", exec: async (command, args) => { if (command === "bash") return { stdout: "", stderr: "", code: 1 }; if (args[1] === "protocol") return { stdout: protocolJSON(), stderr: "", code: 0 }; throw new Error("unexpected"); } }); assert.equal((await unknownFailure.refresh()).errorCategory, "resolution");
  const noBinary = createDashboardState("ready", { root: "/p", exec: async (command, args) => command === "bash" ? { stdout: "", stderr: "", code: 1 } : args[1] === "protocol" ? { stdout: protocolJSON(), stderr: "", code: 0 } : { stdout: "{}", stderr: "", code: 0 } }); assert.equal((await noBinary.runFixed(["metrics", "retain", "--json"])).ok, true);
  const noDeps = createDashboardState(); assert.equal((await noDeps.refresh()).errorCategory, "unavailable"); assert.equal((await noDeps.runFixed(["metrics", "purge"])).errorCategory, "unavailable"); const preaborted = new AbortController(); preaborted.abort(); assert.equal((await noDeps.refresh({}, preaborted.signal)).errorCategory, "cancelled"); assert.equal((await noDeps.runFixed(["metrics", "retain"], preaborted.signal)).errorCategory, "unavailable"); const abortedWithDeps = createDashboardState("loading", { root: "/p", exec: async () => ({ stdout: "", stderr: "", code: 1 }) }); assert.equal((await abortedWithDeps.refresh({}, preaborted.signal)).errorCategory, "cancelled"); assert.equal((await abortedWithDeps.runFixed(["metrics", "retain"], preaborted.signal)).errorCategory, "unavailable"); noDeps.markStale("maintenance"); assert.equal(noDeps.status, "degraded");
});

test("canonical validators and maintenance cover every malformed field and executable fallback", async () => {
  const protocolMutations = [
    { schemaVersion: 2 }, { protocol: { major: 2, minor: 0 } }, { compatibleMajor: 2 }, { awfVersion: 1 }, { awfVersion: "" }, { awfVersion: "0.21.0", projectVersion: "0.22.0" },
  ];
  const metricsMutations = [{ schemaVersion: 2 }, { protocolMajor: 2 }, { efforts: {} }, { integrity: {} }, { retention: null }, { retention: "bad" }];
  const doctorMutations = [{ schemaVersion: 2 }, { protocolMajor: 2 }, { findings: {} }, { integrity: {} }];
  const scenarios: any[] = [
    ...protocolMutations.map((mutation) => ({ protocol: protocolJSON(mutation), expected: mutation.protocol ? "protocol" : "version" })),
    ...metricsMutations.map((mutation) => ({ protocol: protocolJSON(), metrics: metricsJSON(mutation), expected: "protocol" })),
    ...doctorMutations.map((mutation) => ({ protocol: protocolJSON(), metrics: metricsJSON(), doctor: doctorJSON(mutation), expected: "protocol" })),
    { protocol: "null", expected: "malformed" }, { protocol: "{", expected: "malformed" }, { protocol: protocolJSON(), metrics: "[]", expected: "malformed" }, { protocol: protocolJSON(), metrics: metricsJSON(), doctor: "[]", expected: "malformed" },
  ];
  for (const scenario of scenarios) { const state = createDashboardState("loading", { root: "/p", exec: async (command, args) => { if (command === "bash") return { stdout: "", stderr: "", code: 1 }; if (args[1] === "protocol") return { stdout: scenario.protocol, stderr: "", code: 0 }; if (args[0] === "metrics") return { stdout: scenario.metrics ?? metricsJSON(), stderr: "", code: 0 }; return { stdout: scenario.doctor ?? doctorJSON(), stderr: "", code: 0 }; } }); assert.equal((await state.refresh()).errorCategory, scenario.expected); }
  for (const bootstrap of [{ stdout: "", code: 0 }, { stdout: " /bad ", code: 0 }, { stdout: "/a\n/b\n", code: 0 }, { stdout: "", code: 1 }]) { const calls: string[] = []; const state = createDashboardState("loading", { root: "/p", exec: async (command, args) => { calls.push(command); if (command === "bash") return { ...bootstrap, stderr: "" }; if (args[1] === "protocol") return { stdout: protocolJSON(), stderr: "", code: 0 }; if (args[0] === "metrics") return { stdout: metricsJSON(), stderr: "", code: 0 }; return { stdout: doctorJSON(), stderr: "", code: 0 }; } }); await state.refresh(); assert.equal(calls.includes("awf"), true); }
  const thrownCalls: string[] = []; const thrown = createDashboardState("loading", { root: "/p", exec: async (command, args) => { thrownCalls.push(command); if (command === "bash") throw new Error("missing"); if (args[1] === "protocol") return { stdout: protocolJSON(), stderr: "", code: 0 }; if (args[0] === "metrics") return { stdout: metricsJSON(), stderr: "", code: 0 }; return { stdout: doctorJSON(), stderr: "", code: 0 }; } }); assert.equal((await thrown.refresh()).ok, true); assert.equal(thrownCalls.includes("awf"), true);
  for (const args of [["metrics", "retain", "--json"], ["metrics", "purge", "--effort", "x", "--confirm", "--json"]]) { const state = createDashboardState("ready", { root: "/p", exec: async () => ({ stdout: "bad", stderr: "", code: args[1] === "retain" ? 1 : 0 }) }); state.set("ready", { binary: "/bin/awf", metrics: {}, doctor: {} }); const result = await state.runFixed(args); assert.equal(result.ok, false); assert.equal(result.errorCategory, args[1] === "retain" ? "retain" : "maintenance"); assert.equal(state.status, "stale"); }
});

test("bootstrap presence is authoritative and newer compatible binaries satisfy the project gate", async () => {
  const file = { isFile: () => true, isSymbolicLink: () => false }; const missing: any = new Error("missing"); missing.code = "ENOENT";
  for (const [name, lstatResult, bootstrap, expected, fallback] of [
    ["absent", missing, undefined, true, true], ["failed", file, { stdout: "", code: 1 }, false, false], ["malformed", file, { stdout: "/one\n/two\n", code: 0 }, false, false], ["unsafe", { isFile: () => false, isSymbolicLink: () => true }, undefined, false, false],
  ] as const) {
    const calls: string[] = []; const state = createDashboardState("loading", { root: "/p", lstat: async () => { if (lstatResult instanceof Error) throw lstatResult; return lstatResult; }, exec: async (command, args) => { calls.push(command); if (command === "bash") return { ...(bootstrap ?? { stdout: "", code: 1 }), stderr: "" }; if (args[1] === "protocol") return { stdout: protocolJSON(), stderr: "", code: 0 }; if (args[0] === "metrics") return { stdout: metricsJSON(), stderr: "", code: 0 }; return { stdout: doctorJSON(), stderr: "", code: 0 }; } });
    assert.equal((await state.refresh()).ok, expected, name); assert.equal(calls.includes("awf"), fallback, name);
  }
  const ahead = createDashboardState("loading", { root: "/p", lstat: async () => file, exec: async (command, args) => command === "bash" ? { stdout: "/awf\n", stderr: "", code: 0 } : args[1] === "protocol" ? { stdout: protocolJSON({ awfVersion: "1.0.0", projectVersion: "0.22.0" }), stderr: "", code: 0 } : args[0] === "metrics" ? { stdout: metricsJSON(), stderr: "", code: 0 } : { stdout: doctorJSON(), stderr: "", code: 0 } }); assert.equal((await ahead.refresh()).ok, true); const equal = createDashboardState("loading", { root: "/p", lstat: async () => file, exec: async (command, args) => command === "bash" ? { stdout: "/awf\n", stderr: "", code: 0 } : args[1] === "protocol" ? { stdout: protocolJSON({ awfVersion: "0.22.0", projectVersion: "0.22.0" }), stderr: "", code: 0 } : args[0] === "metrics" ? { stdout: metricsJSON(), stderr: "", code: 0 } : { stdout: doctorJSON(), stderr: "", code: 0 } }); assert.equal((await equal.refresh()).ok, true);
});

test("invariant: dashboard public contract covers overlay, maintenance, widget, and disposal", async () => {
  const execs: any[] = []; const state = createDashboardState("ready", { root: "/project", exec: async (command, args) => { execs.push([command, args]); return { stdout: "{}", stderr: "", code: 0 }; } }); state.set("ready", { binary: "/bin/awf", metrics: { efforts: [{ effortId: "active", state: "active", route: "plan", phases: [{ phase: "planning", durationMs: 5, usage: { totalTokens: 9 } }] }, { effortId: "done", state: "completed", route: "direct" }] }, doctor: { findings: [{ code: "WFV1-PHASE-ORDER", severity: "warning", scope: "effort", evidence: { eventIds: ["evidence"] }, threshold: { value: 1 }, confidence: "high", nextAction: "waive", waived: false }] } });
  const ledger = defaultLedgerDependencies("/project/.pi/extensions/awf-dashboard/index.ts"); let renders = 0; let closes = 0; let refreshes = 0; const lifecycle: any[] = []; const overlay = new DashboardOverlay(state, { requestRender: () => { renders++; }, close: () => { closes++; }, refresh: async () => { refreshes++; }, lifecycle: async (request) => { lifecycle.push(request); }, association: () => ({ effortId: "active", sessionId: "session", trajectoryId: "trajectory", associationOrigin: "manual" }), ledger });
  const beforeRender = execs.length; assert.equal(overlay.render(0).every((line) => visibleWidth(line) <= 1), true); assert.equal(execs.length, beforeRender); overlay.handleInput("\x1b[B"); overlay.handleInput("\x1b[B"); assert.equal(overlay.row, 1); overlay.handleInput("\x1b[A"); assert.equal(overlay.row, 0);
  overlay.handleInput("\x1b[C"); assert.equal(overlay.view, "phases"); assert.match(overlay.render(200).join("\n"), /planning/); overlay.handleInput("\t"); assert.equal(overlay.view, "history"); overlay.handleInput("\x1b[Z"); assert.equal(overlay.view, "phases"); overlay.handleInput("\x1b[D"); assert.equal(overlay.view, "overview"); overlay.handleInput("r"); await new Promise((done) => setImmediate(done)); assert.equal(refreshes, 1);
  overlay.view = "findings"; overlay.row = 0; assert.match(overlay.render(200).join("\n"), /evidence=.*threshold=.*confidence=high.*next=waive/); overlay.handleInput("\r"); assert.ok(overlay.confirmation); overlay.handleInput("n"); assert.equal(overlay.confirmation, undefined); overlay.handleInput("\r"); overlay.handleInput("y"); await new Promise((done) => setImmediate(done)); assert.equal(lifecycle[0].action, "waive");
  overlay.view = "maintenance"; overlay.row = 0; assert.match(overlay.render(200).join("\n"), /retain dry-run/); overlay.handleInput("\r"); await new Promise((done) => setImmediate(done)); assert.deepEqual(execs.at(-1), ["/bin/awf", ["metrics", "retain", "--dry-run", "--json"]]); overlay.row = 1; overlay.handleInput("\r"); overlay.handleInput("\r"); await new Promise((done) => setImmediate(done)); assert.deepEqual(execs.at(-1), ["/bin/awf", ["metrics", "retain", "--json"]]); overlay.row = 2; overlay.handleInput("\r"); overlay.handleInput("y"); assert.equal((overlay as any).confirmation?.stage, 2); assert.match(overlay.render(200).join("\n"), /DESTRUCTIVE/); overlay.handleInput("y"); await new Promise((done) => setImmediate(done)); assert.deepEqual(execs.at(-1), ["/bin/awf", ["metrics", "purge", "--effort", "done", "--confirm", "--json"]]);
  assert.match(dashboardWidget(state, { inputTokens: 2, outputTokens: 3, costUsd: 0.25 }, 200)[0], /tokens=5.*cost=\$0.2500/); state.markStale("query"); assert.match(dashboardWidget(state, { inputTokens: 0, outputTokens: 0, costUsd: 0 }, 12)[0], /awf stale/); overlay.handleInput("\x1b"); assert.equal(closes, 1); overlay.invalidate(); overlay.dispose(); const rendered = renders; overlay.handleInput("r"); assert.equal(renders, rendered);
});

test("overlay empty, repair, waiver, confirmation, and maintenance edge branches stay typed and clamped", async () => {
  const calls: any[] = []; const state = createDashboardState("degraded", { root: "/p", exec: async (command, args) => { calls.push([command, args]); return { stdout: "{}", stderr: "", code: 0 }; } }); state.set("degraded", { errorCategory: "unavailable", binary: "/bin/awf", metrics: { efforts: [{ phases: "bad" }, { effortId: "../bad", state: "completed" }, { effortId: "abandoned", state: "abandoned", phases: [{ id: "phase", durationSeconds: 2, tokens: 3 }, {}] }] }, doctor: { findings: [{ code: "WFV1-PHASE-ORDER", severity: "info", scope: "effort", evidence: "event", baseline: { value: 2 }, confidence: "low", nextAction: "none", waived: true }, { code: "WFV1-PHASE-ORDER", severity: "warning", scope: "effort", evidence: { eventIds: ["source"] }, confidence: "high", nextAction: "repair", waived: false, reconciliation: { kind: "supersede-event", sourceEventIds: ["source"], replacement: { eventKind: "session_detached", payload: { reason: "manual" } } } }] } });
  const lifecycle: any[] = []; let refreshDone!: () => void; const refresh = new Promise<void>((done) => { refreshDone = done; }); let overlaySignal: AbortSignal | undefined; let renders = 0; const options: any = { requestRender: () => { renders++; }, close() {}, refresh: (signal?: AbortSignal) => { overlaySignal = signal; return refresh; }, lifecycle: async (request: any) => { lifecycle.push(request); }, association: () => ({ effortId: "effort", sessionId: "session", trajectoryId: "trajectory", associationOrigin: "manual" }), ledger: defaultLedgerDependencies("/p/.pi/extensions/awf-dashboard/index.ts") }; const overlay = new DashboardOverlay(state, options);
  overlay.view = "overview"; assert.match(overlay.render(200).join("\n"), /effort unknown route=undecided/); overlay.view = "phases"; assert.match(overlay.render(200).join("\n"), /duration=2 tokens=3/); overlay.view = "findings"; overlay.row = 0; assert.match(overlay.render(200).join("\n"), /threshold=\{\"value\":2\}/); overlay.handleInput("\r"); assert.equal(overlay.confirmation, undefined); overlay.row = 1; overlay.handleInput("\r"); overlay.handleInput("\r"); await new Promise((done) => setImmediate(done)); assert.equal(lifecycle[0].action, "repair");
  overlay.view = "maintenance"; overlay.row = 99; overlay.handleInput("\r"); overlay.handleInput("\x1b[B"); assert.equal(overlay.row, 2); overlay.handleInput("\r"); overlay.handleInput("\x1b"); assert.equal(overlay.confirmation, undefined); overlay.view = "overview"; overlay.handleInput("\x1b[D"); assert.equal(overlay.view, "maintenance"); overlay.handleInput("\x1b[C"); assert.equal(overlay.view, "overview");
  overlay.handleInput("r"); overlay.dispose(); assert.equal(overlaySignal?.aborted, true); refreshDone(); await new Promise((done) => setImmediate(done)); assert.equal(renders > 0, true); await (overlay as any).confirmYes();
  const empty = createDashboardState("loading"); const noAssociation = new DashboardOverlay(empty, { ...options, association: () => undefined, refresh: async () => {} }); for (const view of ["overview", "phases", "history", "findings"] as const) { noAssociation.view = view; assert.match(noAssociation.render(40).join("\n"), /No data/); } noAssociation.view = "findings"; noAssociation.row = 5; noAssociation.handleInput("\r"); noAssociation.confirmation = { action: { kind: "unknown" }, stage: 1 }; assert.match(noAssociation.render(80).join("\n"), /Confirm unknown/); noAssociation.handleInput("y"); await new Promise((done) => setImmediate(done)); noAssociation.dispose(); const malformedFinding = new DashboardOverlay(empty, { ...options, association: () => ({ effortId: "effort", sessionId: "session", trajectoryId: "trajectory", associationOrigin: "manual" }) }); malformedFinding.confirmation = { action: { kind: "waive", finding: { code: "WFV1-PHASE-ORDER", scope: "effort", evidence: "bad" } }, stage: 1 }; malformedFinding.handleInput("y"); await new Promise((done) => setImmediate(done)); malformedFinding.confirmation = { action: { kind: "unknown", finding: {} }, stage: 1 }; malformedFinding.handleInput("y"); await new Promise((done) => setImmediate(done));
});

test("default dependency factories expose bounded process, clock, owner, UUID, and timer seams", async () => {
  const calls: any[] = []; const pi: any = { exec: async (command: string, args: string[], options?: any) => { calls.push([command, args, options]); return { stdout: "{}", stderr: "", code: 0 }; } }; const priorVersion = process.env.npm_package_version; process.env.npm_package_version = "9.9.9"; const dashboard = defaultDashboardDependencies(pi); assert.equal(dashboard.packageVersion, "9.9.9"); if (priorVersion === undefined) delete process.env.npm_package_version; else process.env.npm_package_version = priorVersion; const controller = new AbortController(); await dashboard.exec("awf", ["metrics"], controller.signal); await dashboard.exec("awf", ["doctor"]); assert.deepEqual(calls, [["awf", ["metrics"], { signal: controller.signal }], ["awf", ["doctor"], undefined]]);
  const ledger = dashboard.ledger; assert.equal(typeof ledger.owner(), "string"); assert.equal(typeof ledger.uuid(), "string"); assert.equal(typeof ledger.now(), "number"); await ledger.sleep(0); let fired = false; const handle = ledger.setInterval(() => { fired = true; }, 1); await new Promise((done) => setTimeout(done, 5)); ledger.clearInterval(handle); assert.equal(fired, true);
});

test("ledger writer creates atomically, appends serially, deduplicates, and drains", async () => {
  const project = await root();
  try {
    const deps = defaultLedgerDependencies(join(project, ".pi/extensions/awf-dashboard/index.ts")); let id = 0; deps.uuid = () => `nonce-${++id}`;
    const writer = createLedgerWriter(deps); const first = creation();
    assert.deepEqual(await writer.create({ effortId: "effort", createdAt: first.timestamp, checkpointId: first.payload.checkpointId, creationMode: "independent" }, first), { idempotent: false });
    assert.deepEqual(await writer.create({ effortId: "effort", createdAt: first.timestamp, checkpointId: first.payload.checkpointId, creationMode: "independent" }, first), { idempotent: true });
    const conflictingCreation = { ...first, eventId: "different-create", idempotencyKey: "different-key" }; await assert.rejects(writer.create({ effortId: "effort", createdAt: first.timestamp, checkpointId: first.payload.checkpointId, creationMode: "independent" }, conflictingCreation), /already exists/);
    const second = association(); assert.equal(validateTelemetryEvent(second), true); assert.deepEqual(await writer.append(second), { idempotent: false }); assert.deepEqual(await writer.append(second), { idempotent: true });
    const third = association("effort", "session", "third"); third.predecessors = [second.eventId];
    const fourth = association("effort", "session", "fourth"); fourth.predecessors = [third.eventId];
    await Promise.all([writer.append(third), writer.append(fourth)]);
    const stream = await readFile(join(project, ".awf/metrics/efforts/effort/sessions/session.jsonl"), "utf8"); assert.deepEqual(stream.trim().split("\n").map((line) => JSON.parse(line).eventId), ["create-event", "associate-event", "third", "fourth"]);
    const conflict = { ...fourth, payload: { ...fourth.payload, associationOrigin: "manual" } }; await assert.rejects(writer.append(conflict), /conflicting/);
    await writer.shutdown(); await assert.rejects(writer.append(association("effort", "session", "closed")), /closed/); assert.equal(writer.isDegraded(), false);
  } finally { await rm(project, { recursive: true, force: true, maxRetries: 5, retryDelay: 10 }); }
});

test("writer rejects invalid creation, pruning, unsafe paths, and isolates passive failure", async () => {
  const project = await root();
  try {
    const deps = defaultLedgerDependencies(join(project, ".pi/extensions/awf-dashboard/index.ts")); const writer = createLedgerWriter(deps); const first = creation();
    await assert.rejects(writer.create({ effortId: "../bad", createdAt: first.timestamp, checkpointId: first.payload.checkpointId, creationMode: "independent" }, first), /invalid/);
    await assert.rejects(writer.append({} as any), /invalid telemetry/);
    assert.equal(await writer.passive(association()), undefined); assert.equal(writer.isDegraded(), true);
    await mkdir(join(project, ".awf/metrics/tombstones"), { recursive: true, mode: 0o700 }); await writeFile(join(project, ".awf/metrics/tombstones/effort.json"), JSON.stringify({ nonce: "pruned", state: "committed" }), { mode: 0o600 });
    await assert.rejects(writer.create({ effortId: "effort", createdAt: first.timestamp, checkpointId: first.payload.checkpointId, creationMode: "independent" }, first), /pruned/);
    await writer.shutdown();
  } finally { await rm(project, { recursive: true, force: true, maxRetries: 5, retryDelay: 10 }); }
  const unsafe = await root();
  try { await symlink(tmpdir(), join(unsafe, ".awf/metrics")); const writer = createLedgerWriter(defaultLedgerDependencies(join(unsafe, ".pi/extensions/awf-dashboard/index.ts"))); await assert.rejects(writer.create({ effortId: "effort", createdAt: creation().timestamp, checkpointId: ".awf/memory/work.md", creationMode: "independent" }, creation()), /unsafe/); }
  finally { await rm(unsafe, { recursive: true, force: true, maxRetries: 5, retryDelay: 10 }); }
});

test("writer recovers stale and active leases and reports ambiguous lease state", async () => {
  const project = await root();
  try {
    const setup = createLedgerWriter(defaultLedgerDependencies(join(project, ".pi/extensions/awf-dashboard/index.ts"))); const first = creation("seed"); await setup.create({ effortId: "seed", createdAt: first.timestamp, checkpointId: first.payload.checkpointId, creationMode: "independent" }, first); await setup.shutdown();
    let now = 100_000; const deps = defaultLedgerDependencies(join(project, ".pi/extensions/awf-dashboard/index.ts")); deps.now = () => now; deps.uuid = () => "new-nonce"; deps.sleep = async (milliseconds) => { now += Math.max(milliseconds, 60_001); };
    const leaseDir = join(project, ".awf/metrics/leases");
    await writeFile(join(leaseDir, "stale.create.json"), JSON.stringify({ nonce: "old", owner: "old", expiresAt: new Date(0).toISOString() }) + "\n", { mode: 0o600 });
    const stale = creation("stale"); const writer = createLedgerWriter(deps); assert.deepEqual(await writer.create({ effortId: "stale", createdAt: stale.timestamp, checkpointId: stale.payload.checkpointId, creationMode: "independent" }, stale), { idempotent: false });
    await writeFile(join(leaseDir, "active.create.json"), JSON.stringify({ nonce: "active", owner: "old", expiresAt: new Date(now + 1).toISOString() }) + "\n", { mode: 0o600 });
    const active = creation("active"); assert.deepEqual(await writer.create({ effortId: "active", createdAt: active.timestamp, checkpointId: active.payload.checkpointId, creationMode: "independent" }, active), { idempotent: false });
    await writeFile(join(leaseDir, "ambiguous.create.json"), "not-json\n", { mode: 0o600 }); const ambiguous = creation("ambiguous"); await assert.rejects(writer.create({ effortId: "ambiguous", createdAt: ambiguous.timestamp, checkpointId: ambiguous.payload.checkpointId, creationMode: "independent" }, ambiguous), /ambiguous/); await writer.shutdown();
  } finally { await rm(project, { recursive: true, force: true, maxRetries: 5, retryDelay: 10 }); }
});

test("lease acquisition handles disappearance, invalid expiry, and compare-before-remove races", async () => {
  for (const mode of ["disappeared", "read-error", "invalid", "changed"] as const) { const project = await root(); try { const extension = join(project, ".pi/extensions/awf-dashboard/index.ts"); const layout = createLedgerWriter(defaultLedgerDependencies(extension)); const seed = creation("seed"); await layout.create({ effortId: "seed", createdAt: seed.timestamp, checkpointId: seed.payload.checkpointId, creationMode: "independent" }, seed); await layout.shutdown(); const deps = defaultLedgerDependencies(extension); const target = join(project, `.awf/metrics/leases/${mode}.create.json`); await writeFile(target, JSON.stringify({ nonce: "old", owner: "old", expiresAt: mode === "invalid" ? "bad" : new Date(0).toISOString() }), { mode: 0o600 }); const realReaddir = deps.readdir; deps.readdir = async (path) => path.endsWith("/leases") ? [] : realReaddir(path); const realRead = deps.readFile; let reads = 0; deps.readFile = async (path, encoding) => { if (path === target) { reads++; if ((mode === "disappeared" || mode === "read-error") && reads === 1) { if (mode === "disappeared") await rm(path); const error: any = new Error(mode); error.code = mode === "disappeared" ? "ENOENT" : "EACCES"; throw error; } const value = await realRead(path, encoding); if (mode === "changed" && reads === 2) return JSON.stringify({ nonce: "changed", owner: "other", expiresAt: new Date(0).toISOString() }); return value; } return realRead(path, encoding); }; const writer = createLedgerWriter(deps); const event = creation(mode); const operation = writer.create({ effortId: mode, createdAt: event.timestamp, checkpointId: event.payload.checkpointId, creationMode: "independent" }, event); if (mode === "invalid" || mode === "read-error") await assert.rejects(operation, /ambiguous/); else await operation; await writer.shutdown(); } finally { await rm(project, { recursive: true, force: true }); } }
});

test("writer removes failed staging, rejects non-private storage, and drains heartbeat work", async () => {
  const project = await root();
  try {
    const deps = defaultLedgerDependencies(join(project, ".pi/extensions/awf-dashboard/index.ts")); const originalOpen = deps.open; deps.open = async (path, flags, mode) => { if (path.endsWith("effort.json")) throw new Error("injected write failure"); return originalOpen(path, flags, mode); };
    const writer = createLedgerWriter(deps); const first = creation("failed"); await assert.rejects(writer.create({ effortId: "failed", createdAt: first.timestamp, checkpointId: first.payload.checkpointId, creationMode: "independent" }, first), /injected/); assert.deepEqual(await readdir(join(project, ".awf/metrics/staging")), []); await writer.shutdown();
    await chmod(join(project, ".awf/metrics"), 0o755); const unsafe = createLedgerWriter(defaultLedgerDependencies(join(project, ".pi/extensions/awf-dashboard/index.ts"))); await assert.rejects(unsafe.create({ effortId: "mode", createdAt: first.timestamp, checkpointId: first.payload.checkpointId, creationMode: "independent" }, creation("mode")), /owner-only/); await unsafe.shutdown(); await chmod(join(project, ".awf/metrics"), 0o700);
    const heartbeat = defaultLedgerDependencies(join(project, ".pi/extensions/awf-dashboard/index.ts")); heartbeat.setInterval = (callback) => { queueMicrotask(callback); return 1; }; heartbeat.clearInterval = () => {}; const beatWriter = createLedgerWriter(heartbeat); const beat = creation("beat"); await beatWriter.create({ effortId: "beat", createdAt: beat.timestamp, checkpointId: beat.payload.checkpointId, creationMode: "independent" }, beat); await beatWriter.shutdown();
    for (const mode of ["mismatch", "throw"] as const) { const branch = defaultLedgerDependencies(join(project, ".pi/extensions/awf-dashboard/index.ts")); const branchRead = branch.readFile; let leaseReads = 0; branch.setInterval = (callback) => { queueMicrotask(callback); return 1; }; branch.clearInterval = () => {}; branch.readFile = async (path, encoding) => { if (path.endsWith(`${mode}.create.json`) && ++leaseReads === 1) { if (mode === "throw") throw new Error("heartbeat read"); return JSON.stringify({ nonce: "other" }); } return branchRead(path, encoding); }; const branchWriter = createLedgerWriter(branch); const branchEvent = creation(mode); await assert.rejects(branchWriter.create({ effortId: mode, createdAt: branchEvent.timestamp, checkpointId: branchEvent.payload.checkpointId, creationMode: "independent" }, branchEvent), mode === "throw" ? /heartbeat read/ : /ownership lost/); await branchWriter.shutdown(); }
    const release = defaultLedgerDependencies(join(project, ".pi/extensions/awf-dashboard/index.ts")); const releaseRead = release.readFile; release.readFile = async (path, encoding) => { if (path.endsWith("release.create.json")) { const error: any = new Error("release read failed"); error.code = "EACCES"; throw error; } return releaseRead(path, encoding); }; const releaseWriter = createLedgerWriter(release); const releaseEvent = creation("release"); await assert.rejects(releaseWriter.create({ effortId: "release", createdAt: releaseEvent.timestamp, checkpointId: releaseEvent.payload.checkpointId, creationMode: "independent" }, releaseEvent), /release read failed/); release.readFile = releaseRead; await rm(join(project, ".awf/metrics/leases/release.create.json")); assert.deepEqual(await releaseWriter.create({ effortId: "release", createdAt: releaseEvent.timestamp, checkpointId: releaseEvent.payload.checkpointId, creationMode: "independent" }, releaseEvent), { idempotent: true }); await releaseWriter.shutdown();
  } finally { await rm(project, { recursive: true, force: true, maxRetries: 5, retryDelay: 10 }); }
});

test("writer dependency faults cover ownership, lookup, lease disappearance, and pruning races", async () => {
  const project = await root();
  try {
    const first = creation("fault");
    const ownership = defaultLedgerDependencies(join(project, ".pi/extensions/awf-dashboard/index.ts")); ownership.uid = -1; await assert.rejects(createLedgerWriter(ownership).create({ effortId: "fault", createdAt: first.timestamp, checkpointId: first.payload.checkpointId, creationMode: "independent" }, first), /another user/);
    const lookup = defaultLedgerDependencies(join(project, ".pi/extensions/awf-dashboard/index.ts")); const lookupLstat = lookup.lstat; lookup.lstat = async (path) => { if (path.endsWith("fault.json")) { const error: any = new Error("lookup"); error.code = "EACCES"; throw error; } return lookupLstat(path); }; await assert.rejects(createLedgerWriter(lookup).create({ effortId: "fault", createdAt: first.timestamp, checkpointId: first.payload.checkpointId, creationMode: "independent" }, first), /lookup/);
    const openFailure = defaultLedgerDependencies(join(project, ".pi/extensions/awf-dashboard/index.ts")); const oldOpen = openFailure.open; openFailure.open = async (path, flags, mode) => { if (path.endsWith("fault.create.json")) { const error: any = new Error("lease open"); error.code = "EACCES"; throw error; } return oldOpen(path, flags, mode); }; await assert.rejects(createLedgerWriter(openFailure).create({ effortId: "fault", createdAt: first.timestamp, checkpointId: first.payload.checkpointId, creationMode: "independent" }, first), /lease open/);
    const race = defaultLedgerDependencies(join(project, ".pi/extensions/awf-dashboard/index.ts")); const raceLstat = race.lstat; let tombstoneChecks = 0; race.lstat = async (path) => { if (path.endsWith("fault.json") && ++tombstoneChecks === 2) return { mode: 0o600, uid: race.uid, isFile: () => true, isDirectory: () => false, isSymbolicLink: () => false }; return raceLstat(path); }; await assert.rejects(createLedgerWriter(race).create({ effortId: "fault", createdAt: first.timestamp, checkpointId: first.payload.checkpointId, creationMode: "independent" }, first), /pruned/);
    const derived = creation("derived"); const writer = createLedgerWriter(defaultLedgerDependencies(join(project, ".pi/extensions/awf-dashboard/index.ts"))); await writer.create({ effortId: "derived", createdAt: derived.timestamp, checkpointId: derived.payload.checkpointId, creationMode: "derived", origin: { effortId: "origin", trajectoryId: "trajectory", anchorId: "anchor" } }, { ...derived, payload: { checkpointId: derived.payload.checkpointId, creationMode: "derived", originEffortId: "origin", originTrajectoryId: "trajectory", originAnchorId: "anchor" } }); await writer.shutdown();
    await writeFile(join(project, ".awf/metrics/efforts/derived/effort.json"), "not-json\n", { mode: 0o600 }); const corrupt = createLedgerWriter(defaultLedgerDependencies(join(project, ".pi/extensions/awf-dashboard/index.ts"))); await assert.rejects(corrupt.create({ effortId: "derived", createdAt: derived.timestamp, checkpointId: derived.payload.checkpointId, creationMode: "derived", origin: { effortId: "origin", trajectoryId: "trajectory", anchorId: "anchor" } }, { ...derived, payload: { checkpointId: derived.payload.checkpointId, creationMode: "derived", originEffortId: "origin", originTrajectoryId: "trajectory", originAnchorId: "anchor" } }), /already exists/); await corrupt.shutdown();
    const leases = join(project, ".awf/metrics/leases"); const disappearing = defaultLedgerDependencies(join(project, ".pi/extensions/awf-dashboard/index.ts")); await writeFile(join(leases, "disappearing.create.json"), JSON.stringify({ nonce: "old", owner: "old", expiresAt: new Date(0).toISOString() }), { mode: 0o600 }); const disappearingRead = disappearing.readFile; let disappeared = false; disappearing.readFile = async (path, encoding) => { if (!disappeared && path.endsWith("disappearing.create.json")) { disappeared = true; await rm(path); const error: any = new Error("gone"); error.code = "ENOENT"; throw error; } return disappearingRead(path, encoding); }; const disappearingEvent = creation("disappearing"); const disappearingWriter = createLedgerWriter(disappearing); await disappearingWriter.create({ effortId: "disappearing", createdAt: disappearingEvent.timestamp, checkpointId: disappearingEvent.payload.checkpointId, creationMode: "independent" }, disappearingEvent); await disappearingWriter.shutdown();
    await writeFile(join(leases, "invalid-expiry.create.json"), JSON.stringify({ nonce: "old", owner: "old", expiresAt: "bad" }), { mode: 0o600 }); const invalidExpiryEvent = creation("invalid-expiry"); const invalidExpiryWriter = createLedgerWriter(defaultLedgerDependencies(join(project, ".pi/extensions/awf-dashboard/index.ts"))); await assert.rejects(invalidExpiryWriter.create({ effortId: "invalid-expiry", createdAt: invalidExpiryEvent.timestamp, checkpointId: invalidExpiryEvent.payload.checkpointId, creationMode: "independent" }, invalidExpiryEvent), /ambiguous/); await invalidExpiryWriter.shutdown(); await rm(join(leases, "invalid-expiry.create.json"));
    for (const name of await readdir(leases)) await rm(join(leases, name), { recursive: true, force: true }); let compareReads = 0; const compare = defaultLedgerDependencies(join(project, ".pi/extensions/awf-dashboard/index.ts")); await writeFile(join(leases, "compare.create.json"), JSON.stringify({ nonce: "old", owner: "old", expiresAt: new Date(0).toISOString() }), { mode: 0o600 }); const compareRead = compare.readFile; compare.readFile = async (path, encoding) => { const value = await compareRead(path, encoding); if (path.endsWith("compare.create.json") && ++compareReads === 2) return JSON.stringify({ nonce: "changed", owner: "other", expiresAt: new Date(0).toISOString() }); return value; }; const compareEvent = creation("compare"); const compareWriter = createLedgerWriter(compare); await compareWriter.create({ effortId: "compare", createdAt: compareEvent.timestamp, checkpointId: compareEvent.payload.checkpointId, creationMode: "independent" }, compareEvent); await compareWriter.shutdown();
  } finally { await rm(project, { recursive: true, force: true, maxRetries: 5, retryDelay: 10 }); }
});

test("invariant: recovery parity executes staging, tombstone, trash, and ambiguity states", async () => {
  const project = await root(); const extension = join(project, ".pi/extensions/awf-dashboard/index.ts");
  try {
    const recoveryFixture = JSON.parse(await readFile(join(process.cwd(), "internal/telemetry/testdata/recovery-cross-language.json"), "utf8")); assert.deepEqual(recoveryFixture.recoveries, ["orphan-staging", "pending-effort", "pending-trash", "committed-trash"]); assert.deepEqual(recoveryFixture.ambiguous, ["active-staging", "nonce-mismatch", "trash-without-tombstone"]);
    const createNamed = async (effortId: string) => { const writer = createLedgerWriter(defaultLedgerDependencies(extension)); const event = creation(effortId); await writer.create({ effortId, createdAt: event.timestamp, checkpointId: event.payload.checkpointId, creationMode: "independent" }, event); await writer.shutdown(); };
    await createNamed("kept"); const metrics = join(project, ".awf/metrics"); const stageName = recoveryFixture.stagingName; await mkdir(join(metrics, "staging", stageName), { mode: 0o700 }); await utimes(join(metrics, "staging", stageName), new Date(0), new Date(0)); await createNamed("trigger"); assert.equal((await readdir(join(metrics, "staging"))).length, 0);
    await writeFile(join(metrics, "tombstones/kept.json"), JSON.stringify({ nonce: "pending", state: "pending" }), { mode: 0o600 }); await createNamed("pending-trigger"); await assert.rejects(readFile(join(metrics, "tombstones/kept.json")), /ENOENT/); await writeFile(join(metrics, "tombstones/kept.json"), JSON.stringify({ nonce: "bad", state: "committed" }), { mode: 0o600 }); const conflicted = creation("conflicted"); await assert.rejects(createLedgerWriter(defaultLedgerDependencies(extension)).create({ effortId: "conflicted", createdAt: conflicted.timestamp, checkpointId: conflicted.payload.checkpointId, creationMode: "independent" }, conflicted), /ambiguous telemetry prune state/); await rm(join(metrics, "tombstones/kept.json"));
    await createNamed("moved"); const movedTrash = `${Buffer.from("moved").toString("base64url")}.prune`; await rename(join(metrics, "efforts/moved"), join(metrics, "trash", movedTrash)); await writeFile(join(metrics, "tombstones/moved.json"), JSON.stringify({ nonce: "prune", state: "pending" }), { mode: 0o600 }); await createNamed("commit-trigger"); assert.deepEqual(JSON.parse(await readFile(join(metrics, "tombstones/moved.json"), "utf8")), { nonce: "prune", state: "committed" }); await assert.rejects(readFile(join(metrics, "trash", movedTrash, "effort.json")), /ENOENT/); await writeFile(join(metrics, "tombstones/moved.json.commit"), JSON.stringify({ nonce: "prune", state: "committed" }), { mode: 0o600 }); await createNamed("commit-temp-trigger"); await assert.rejects(readFile(join(metrics, "tombstones/moved.json.commit")), /ENOENT/); await writeFile(join(metrics, "tombstones/pending-temp.json"), JSON.stringify({ nonce: "temp", state: "pending" }), { mode: 0o600 }); await writeFile(join(metrics, "tombstones/pending-temp.json.commit"), JSON.stringify({ nonce: "temp", state: "committed" }), { mode: 0o600 }); await createNamed("pending-temp-trigger"); assert.deepEqual(JSON.parse(await readFile(join(metrics, "tombstones/pending-temp.json"), "utf8")), { nonce: "temp", state: "committed" });
    const activeStage = `${Buffer.from("active-stage").toString("base64url")}.lease`; await mkdir(join(metrics, "staging", activeStage), { mode: 0o700 }); await writeFile(join(metrics, "leases/active-stage.create.json"), JSON.stringify({ nonce: "lease", owner: "owner", expiresAt: new Date(Date.now() + 60_000).toISOString() }), { mode: 0o600 }); const blocked = creation("blocked"); await createLedgerWriter(defaultLedgerDependencies(extension)).create({ effortId: "blocked", createdAt: blocked.timestamp, checkpointId: blocked.payload.checkpointId, creationMode: "independent" }, blocked); assert.equal((await readdir(join(metrics, "staging"))).includes(activeStage), true); await utimes(join(metrics, "staging", activeStage), new Date(0), new Date(0)); await writeFile(join(metrics, "leases/active-stage.create.json"), JSON.stringify({ nonce: "lease", owner: "owner", expiresAt: new Date(0).toISOString() }), { mode: 0o600 }); const recovered = creation("recovered-staging"); await createLedgerWriter(defaultLedgerDependencies(extension)).create({ effortId: "recovered-staging", createdAt: recovered.timestamp, checkpointId: recovered.payload.checkpointId, creationMode: "independent" }, recovered); await assert.rejects(readFile(join(metrics, "staging", activeStage)), /ENOENT/);
    await mkdir(join(metrics, "trash", `${Buffer.from("unknown").toString("base64url")}.nonce`), { mode: 0o700 }); const ambiguous = creation("ambiguous-recovery"); await assert.rejects(createLedgerWriter(defaultLedgerDependencies(extension)).create({ effortId: "ambiguous-recovery", createdAt: ambiguous.timestamp, checkpointId: ambiguous.payload.checkpointId, creationMode: "independent" }, ambiguous), /trash without tombstone/);
  } finally { await rm(project, { recursive: true, force: true, maxRetries: 5, retryDelay: 10 }); }
});

test("writer reports every malformed recovery namespace without guessing", async () => {
  const cases: Array<[string, (metrics: string) => Promise<void>, RegExp]> = [
    ["staging-name", async (m) => { await mkdir(join(m, "staging/bad")); }, /staging state/],
    ["staging-type", async (m) => { await writeFile(join(m, `staging/${Buffer.from("x").toString("base64url")}.nonce`), "x"); }, /staging state/],
    ["trash-name", async (m) => { await mkdir(join(m, "trash/bad")); }, /trash state/],
    ["trash-type", async (m) => { await writeFile(join(m, `trash/${Buffer.from("x").toString("base64url")}.nonce`), "x"); }, /trash state/],
    ["trash-duplicate", async (m) => { await mkdir(join(m, "trash", `${Buffer.from("x").toString("base64url")}.one`)); await mkdir(join(m, "trash", `${Buffer.from("x").toString("base64url")}.two`)); }, /trash state/],
    ["commit-directory", async (m) => { await mkdir(join(m, "tombstones/x.json.commit")); }, /tombstone path/],
    ["commit-id", async (m) => { await writeFile(join(m, "tombstones/...json.commit"), "{}"); }, /tombstone path/],
    ["tombstone-suffix", async (m) => { await writeFile(join(m, "tombstones/x.bad"), "{}"); }, /tombstone path/],
    ["tombstone-id", async (m) => { await writeFile(join(m, "tombstones/...json"), "{}"); }, /tombstone path/],
    ["tombstone-json", async (m) => { await writeFile(join(m, "tombstones/x.json"), "bad"); }, /ambiguous telemetry tombstone$/],
    ["tombstone-record", async (m) => { await writeFile(join(m, "tombstones/x.json"), JSON.stringify({ nonce: "bad/id", state: "pending" })); }, /ambiguous telemetry tombstone$/],
    ["nonce-mismatch", async (m) => { await mkdir(join(m, "trash", `${Buffer.from("x").toString("base64url")}.trash`)); await writeFile(join(m, "tombstones/x.json"), JSON.stringify({ nonce: "other", state: "pending" })); }, /prune nonce/],
    ["commit-mismatch", async (m) => { await writeFile(join(m, "tombstones/x.json"), JSON.stringify({ nonce: "one", state: "pending" })); await writeFile(join(m, "tombstones/x.json.commit"), JSON.stringify({ nonce: "two", state: "committed" })); }, /tombstone commit/],
  ];
  for (const [name, setup, expected] of cases) { const project = await root(); try { const extension = join(project, ".pi/extensions/awf-dashboard/index.ts"); const seed = creation("seed"); const first = createLedgerWriter(defaultLedgerDependencies(extension)); await first.create({ effortId: "seed", createdAt: seed.timestamp, checkpointId: seed.payload.checkpointId, creationMode: "independent" }, seed); await first.shutdown(); await setup(join(project, ".awf/metrics")); const event = creation("trigger"); await assert.rejects(createLedgerWriter(defaultLedgerDependencies(extension)).create({ effortId: "trigger", createdAt: event.timestamp, checkpointId: event.payload.checkpointId, creationMode: "independent" }, event), expected, name); } finally { await rm(project, { recursive: true, force: true }); } }
});

test("writer append detects prune and stream read races after lease acquisition", async () => {
  const project = await root();
  try {
    const setup = createLedgerWriter(defaultLedgerDependencies(join(project, ".pi/extensions/awf-dashboard/index.ts"))); const first = creation("append-race"); await setup.create({ effortId: "append-race", createdAt: first.timestamp, checkpointId: first.payload.checkpointId, creationMode: "independent" }, first); await setup.shutdown(); const event = association("append-race");
    const prune = defaultLedgerDependencies(join(project, ".pi/extensions/awf-dashboard/index.ts")); const oldLstat = prune.lstat; let checks = 0; prune.lstat = async (path) => { if (path.endsWith("append-race.json") && ++checks === 2) return { mode: 0o600, uid: prune.uid, isFile: () => true, isDirectory: () => false, isSymbolicLink: () => false }; return oldLstat(path); }; const pruneWriter = createLedgerWriter(prune); await assert.rejects(pruneWriter.append(event), /pruned while appending/); await pruneWriter.shutdown();
    const readFailure = defaultLedgerDependencies(join(project, ".pi/extensions/awf-dashboard/index.ts")); const oldRead = readFailure.readFile; readFailure.readFile = async (path, encoding) => { if (path.endsWith("session.jsonl")) { const error: any = new Error("stream read"); error.code = "EACCES"; throw error; } return oldRead(path, encoding); }; const readWriter = createLedgerWriter(readFailure); await assert.rejects(readWriter.append(event), /stream read/); await readWriter.shutdown();
  } finally { await rm(project, { recursive: true, force: true, maxRetries: 5, retryDelay: 10 }); }
});

function protocolJSON(overrides: any = {}) { return JSON.stringify({ schemaVersion: 1, protocol: protocolVersion, compatibleMajor: protocolVersion.major, descriptorSha256: "hash", awfVersion: "0.23.0", projectVersion: "0.22.0", ...overrides }); }
function metricsJSON(overrides: any = {}) { return JSON.stringify({ schemaVersion: 1, protocolMajor: protocolVersion.major, generatedAt: "2026-07-22T00:00:00Z", selector: {}, efforts: [], retention: {}, integrity: [], ...overrides }); }
function doctorJSON(overrides: any = {}) { return JSON.stringify({ schemaVersion: 1, protocolMajor: protocolVersion.major, generatedAt: "2026-07-22T00:00:00Z", selector: {}, findings: [], integrity: [], ...overrides }); }
function harness(project: string, version = "0.81.1") {
  const tools = new Map<string, any>(); const commands = new Map<string, any>(); const hooks = new Map<string, any>(); const bus = new Map<string, any>(); const entries: any[] = []; const execs: any[] = [];
  const pi: any = { queueCommand() {}, registerCommand(name: string, command: any) { commands.set(name, command); }, registerTool(tool: any) { tools.set(tool.name, tool); }, appendEntry(type: string, data: any) { entries.push({ type, data }); }, exec: async () => ({ stdout: "{}", stderr: "", code: 0 }), events: { on(name: string, fn: any) { bus.set(name, fn); }, emit() {} }, on(name: string, fn: any) { hooks.set(name, fn); } };
  const ledger = defaultLedgerDependencies(join(project, ".pi/extensions/awf-dashboard/index.ts")); let uuid = 0; ledger.uuid = () => `generated-${++uuid}`;
  const deps: any = { packageVersion: version, extensionFile: join(project, ".pi/extensions/awf-dashboard/index.ts"), ledger }; deps.exec = async (command: string, args: string[]) => { execs.push([command, args]); if (deps.fail) return { stdout: "", stderr: "missing", code: 1 }; if (command === "bash") return { stdout: "", stderr: "missing", code: 1 }; if (args[0] === "metrics" && args[1] === "protocol") return { stdout: protocolJSON(), stderr: "", code: 0 }; if (args[0] === "metrics" && args.includes("--dry-run")) return { stdout: "{}", stderr: "", code: 0 }; if (args[0] === "metrics" && args[1] === "retain") return { stdout: "{}", stderr: "", code: 0 }; if (args[0] === "metrics" && args[1] === "purge") return { stdout: "{}", stderr: "", code: 0 }; if (args[0] === "metrics") return { stdout: metricsJSON(), stderr: "", code: 0 }; if (args[0] === "doctor") return { stdout: doctorJSON(), stderr: "", code: 0 }; return { stdout: "{}", stderr: "", code: 0 }; };
  registerDashboard(pi, deps); return { pi, tools, commands, hooks, bus, entries, execs, deps };
}
async function execute(tool: any, params: any) { return tool.execute("id", params, undefined, undefined, {}); }

test("append refuses partial and malformed durable tails before mutation", async () => {
  for (const [tail, expected] of [["partial", /incomplete final line/], ["not-json\n", /malformed complete line/]] as const) { const project = await root(); try { const extension = join(project, ".pi/extensions/awf-dashboard/index.ts"); const first = creation("corrupt-tail"); const writer = createLedgerWriter(defaultLedgerDependencies(extension)); await writer.create({ effortId: "corrupt-tail", createdAt: first.timestamp, checkpointId: first.payload.checkpointId, creationMode: "independent" }, first); await writeFile(join(project, ".awf/metrics/efforts/corrupt-tail/sessions/session.jsonl"), JSON.stringify(first) + "\n" + tail, { mode: 0o600 }); await assert.rejects(writer.append(association("corrupt-tail")), expected); await writer.shutdown(); } finally { await rm(project, { recursive: true, force: true }); } }
});

test("append heartbeat ownership failure is surfaced and releases its lease", async () => {
  const project = await root(); try { const extension = join(project, ".pi/extensions/awf-dashboard/index.ts"); const seed = creation("append-heartbeat"); const setup = createLedgerWriter(defaultLedgerDependencies(extension)); await setup.create({ effortId: "append-heartbeat", createdAt: seed.timestamp, checkpointId: seed.payload.checkpointId, creationMode: "independent" }, seed); await setup.shutdown(); const deps = defaultLedgerDependencies(extension); const read = deps.readFile; deps.setInterval = (callback) => { queueMicrotask(callback); return 1; }; deps.clearInterval = () => {}; deps.readFile = async (path, encoding) => path.endsWith("append-heartbeat.append.json") ? JSON.stringify({ nonce: "other" }) : read(path, encoding); const writer = createLedgerWriter(deps); await assert.rejects(writer.append(association("append-heartbeat")), /ownership lost/); await writer.shutdown();
  } finally { await rm(project, { recursive: true, force: true }); }
});

test("dashboard command refreshes at open, registers widget overlays only in TUI, and degrades canonical tools structurally", async () => {
  const project = await root();
  try {
    const h = harness(project); const notifications: any[] = []; await h.commands.get("awf-dashboard").handler("", { mode: "json", ui: { notify: (...args: any[]) => notifications.push(args) } }); assert.equal(notifications[0][0], "awf dashboard ready");
    let component: any; let customOptions: any; await h.commands.get("awf-dashboard").handler("", { mode: "tui", ui: { custom: async (factory: any, options: any) => { customOptions = options; component = factory({ requestRender() {} }, {}, {}, () => {}); component.handleInput("\x1b"); return undefined; } } }); assert.equal(customOptions.overlay, true); assert.ok(component instanceof DashboardOverlay);
    let widgetFactory: any; let widgetCleared = false; const associationEntry = { effortId: "effort", sessionId: "session", trajectoryId: "trajectory", associationOrigin: "manual" }; await h.hooks.get("session_start")({}, { mode: "tui", sessionManager: { getBranch: () => [{ type: "custom", customType: ASSOCIATION_ENTRY, data: associationEntry }], getLeafId: () => "leaf" }, ui: { custom() {}, setWidget(_name: string, value: any) { if (value) widgetFactory = value; else widgetCleared = true; } } }); let widgetRequests = 0; const widget = widgetFactory({ requestRender() { widgetRequests++; } }); assert.equal(widget.render(20).length, 1); widget.invalidate(); h.hooks.get("turn_end")({ message: { model: "model", usage: { input: NaN, output: Infinity, cost: { total: NaN } } } }, {}); assert.equal(widgetRequests > 0, true, "turn_end did not rerender widget");
    h.deps.fail = true; const degraded = await execute(h.tools.get("awf_metrics"), {}); assert.equal(degraded.details.degraded, true); await execute(h.tools.get("awf_lifecycle"), { action: "create", idempotencyKey: "retain-fail-key", eventId: "retain-fail-event", effortId: "retain-fail", sessionId: "retain-session", timestamp: "2026-07-22T00:00:00Z", predecessors: [], checkpointId: ".awf/memory/retain.md", creationMode: "independent" }); const warnings: any[] = []; await h.commands.get("awf-dashboard").handler("", { mode: "print", ui: { notify: (...args: any[]) => warnings.push(args), setWidget(_name: string, value: any) { if (!value) widgetCleared = true; } } }); assert.equal(warnings[0][1], "warning"); let finishOverlay!: () => void; const openOverlay = h.commands.get("awf-dashboard").handler("", { mode: "tui", ui: { custom: async (factory: any) => { factory({ requestRender() {} }, {}, {}, () => {}); return new Promise<void>((done) => { finishOverlay = done; }); }, setWidget(_name: string, value: any) { if (!value) widgetCleared = true; } } }); await new Promise((done) => setImmediate(done)); await h.hooks.get("session_shutdown")({}, {}); finishOverlay(); await openOverlay; assert.equal(widgetCleared, true, "shutdown did not clear widget");
    const missingBranch = harness(await root()); await missingBranch.hooks.get("session_start")({}, { sessionManager: {}, ui: {} }); await missingBranch.hooks.get("session_shutdown")({}, {});
    const nonTui = harness(await root()); await nonTui.hooks.get("session_start")({}, { mode: "print", sessionManager: { getBranch: () => [] }, ui: {} }); const noNotify = nonTui.commands.get("awf-dashboard"); nonTui.deps.fail = true; await noNotify.handler("", { mode: "print", ui: {} }); await nonTui.hooks.get("session_shutdown")({}, {});
  } finally { await rm(project, { recursive: true, force: true, maxRetries: 5, retryDelay: 10 }); }
});

test("invariant: dashboard runtime covers lifecycle, queries, privacy, association, and passive telemetry", async () => {
  const project = await root();
  try {
    const h = harness(project); assert.deepEqual([...h.tools.keys()], ["awf_lifecycle", "awf_metrics", "awf_doctor"]);
    const createRequest = { action: "create", idempotencyKey: "create-key", eventId: "create-event", effortId: "effort", sessionId: "session", timestamp: "2026-07-22T00:00:00Z", predecessors: [], checkpointId: ".awf/memory/work.md", creationMode: "independent" };
    const created = await execute(h.tools.get("awf_lifecycle"), createRequest); assert.equal(created.details.idempotent, false); assert.equal(h.entries.length, 0);
    await execute(h.tools.get("awf_lifecycle"), { action: "start-trajectory", idempotencyKey: "trajectory-key", eventId: "trajectory-event", effortId: "effort", sessionId: "session", timestamp: "2026-07-22T00:00:01Z", predecessors: ["create-event"], trajectoryId: "trajectory", anchorId: "root-anchor" });
    await execute(h.tools.get("awf_lifecycle"), { action: "associate", idempotencyKey: "associate-key", eventId: "associate-event", effortId: "effort", sessionId: "session", timestamp: "2026-07-22T00:00:02Z", predecessors: ["trajectory-event"], trajectoryId: "trajectory", associationOrigin: "created" }); assert.equal(h.entries.length, 1);
    const beforeIllegal = await readFile(join(project, ".awf/metrics/efforts/effort/sessions/session.jsonl"), "utf8"); await assert.rejects(execute(h.tools.get("awf_lifecycle"), { action: "complete", idempotencyKey: "illegal", eventId: "illegal", effortId: "effort", sessionId: "session", timestamp: "2026-07-22T00:00:02Z", predecessors: [] }), /current causal frontier/); assert.equal(await readFile(join(project, ".awf/metrics/efforts/effort/sessions/session.jsonl"), "utf8"), beforeIllegal);
    const beforeQueries = h.execs.length; await execute(h.tools.get("awf_metrics"), { effort: "effort", phase: "planning" }); await execute(h.tools.get("awf_doctor"), { session: "session" }); const queryExecs = h.execs.slice(beforeQueries);
    assert.equal(queryExecs.some(([command, args]) => command === "awf" && args.join(" ") === "metrics --effort effort --phase planning --json"), true); assert.equal(queryExecs.some(([command, args]) => command === "awf" && args.join(" ") === "doctor --session session --json"), true); assert.equal(queryExecs.filter(([, args]) => args[0] === "metrics" && args[1] === "protocol").length, 2);
    let response: any; h.bus.get("awf.telemetry.association.request.v1")({ respond: (value: any) => { response = value; } }); h.bus.get("awf.telemetry.association.request.v1")({}); h.bus.get("awf.telemetry.association.request.v1")({ respond() { throw new Error("response failed"); } }); assert.equal(response.association.effortId, "effort");
    await h.hooks.get("session_start")({}, { sessionManager: { getBranch: () => [{ type: "custom", customType: ASSOCIATION_ENTRY, data: h.entries[0].data }], getLeafId: () => "leaf" }, ui: { setWidget() {}, custom() {} } });
    h.bus.get("awf.telemetry.subagent.v1")({ version: protocolVersion, observationId: "sub", effortId: "effort", sessionId: "session", trajectoryId: "trajectory", role: "explore", requestedModel: "model", resolvedModel: "model", thinkingLevel: "high", queueDurationMs: 1, runDurationMs: 2, inputTokens: 1, outputTokens: 2, cacheReadTokens: 0, cacheWriteTokens: 0, costUsd: 0, outcome: "success", stopReason: "complete", toolCount: 1, toolFailureCount: 0 }); h.bus.get("awf.telemetry.subagent.v1")({ version: protocolVersion, role: "bad", queueDurationMs: "bad" }); h.bus.get("awf.telemetry.subagent.v1")({ version: protocolVersion, observationId: "sub-error", effortId: "effort", sessionId: "session", trajectoryId: "trajectory", role: "x".repeat(200), queueDurationMs: 0, runDurationMs: 0, inputTokens: 0, outputTokens: 0, cacheReadTokens: 0, cacheWriteTokens: 0, costUsd: 0, outcome: "failure", stopReason: "error", toolCount: 0, toolFailureCount: 0, errorCategory: "subagent" }); h.bus.get("awf.telemetry.handoff.v1")({ observationId: "handoff-success", targetSessionId: "child-session", outcome: "success", durationMs: 3 }); h.bus.get("awf.telemetry.handoff.v1")({ observationId: "handoff-failure", targetSessionId: "failed-child", outcome: "failure", errorCategory: "handoff" }); h.bus.get("awf.telemetry.handoff.v1")({ targetSessionId: "../bad" });
    h.bus.get("awf.telemetry.subagent.v1")({ version: protocolVersion, observationId: "sub", effortId: "effort", sessionId: "session", trajectoryId: "trajectory", role: "explore", requestedModel: "model", resolvedModel: "model", thinkingLevel: "high", queueDurationMs: 1, runDurationMs: 2, inputTokens: 1, outputTokens: 2, cacheReadTokens: 0, cacheWriteTokens: 0, costUsd: 0, outcome: "success", stopReason: "complete", toolCount: 1, toolFailureCount: 0 }); h.bus.get("awf.telemetry.subagent.v1")({ version: protocolVersion, observationId: "association-change", effortId: "other", sessionId: "session", trajectoryId: "trajectory", role: "explore" });
    h.hooks.get("tool_execution_start")({ toolCallId: "tool", toolName: "read" }); h.hooks.get("tool_execution_end")({ toolCallId: "tool", toolName: "read", isError: false }, { sessionManager: { getLeafId: () => "leaf" } }); h.hooks.get("tool_execution_end")({ toolCallId: "missing", toolName: "write", isError: true }, {});
    h.hooks.get("turn_end")({ message: { model: "model", usage: { input: 1, output: 2, cacheRead: 3, cacheWrite: 4, cost: { total: 0.1 } } } }, { sessionManager: { getLeafId: () => "leaf" } }); h.hooks.get("turn_end")({ message: { usage: {} } }, {});
    h.hooks.get("session_compact")({}, { sessionManager: { getLeafId: () => "leaf" } }); await h.hooks.get("session_before_fork")({ entryId: "../bad" }); await h.hooks.get("session_tree")({ oldLeafId: "leaf", newLeafId: "../bad" }, { sessionManager: { getBranch: () => [{ type: "custom", customType: ASSOCIATION_ENTRY, data: h.entries[0].data }] } }); await h.hooks.get("session_tree")({ oldLeafId: "leaf", newLeafId: "leaf-two" }, { sessionManager: { getBranch: () => [{ type: "custom", customType: ASSOCIATION_ENTRY, data: h.entries[0].data }] } }); await h.hooks.get("session_tree")({ oldLeafId: "../bad", newLeafId: "leaf-three" }, { sessionManager: { getBranch: () => [{ type: "custom", customType: ASSOCIATION_ENTRY, data: h.entries[0].data }] } });
    await h.hooks.get("session_shutdown")({}, { sessionManager: { getLeafId: () => "leaf-two" } });
    const stream = await readFile(join(project, ".awf/metrics/efforts/effort/sessions/session.jsonl"), "utf8"); assert.equal(stream.split("subagent_observed").length - 1, 2); assert.doesNotMatch(stream, /shell_observed/); for (const kind of ["effort_created", "session_started", "subagent_observed", "handoff_observed", "tool_observed", "usage_observed", "compaction_observed", "trajectory_closed", "trajectory_resumed", "session_ended"]) assert.match(stream, new RegExp(kind));
  } finally { await rm(project, { recursive: true, force: true, maxRetries: 5, retryDelay: 10 }); }
});

test("child startup reassociates only a copied active-branch association", async () => {
  const project = await root();
  try {
    const h = harness(project); const lifecycle = h.tools.get("awf_lifecycle"); await execute(lifecycle, { action: "create", idempotencyKey: "create", eventId: "create", effortId: "handoff", sessionId: "parent", timestamp: "2026-07-22T00:00:00Z", predecessors: [], checkpointId: ".awf/memory/handoff.md", creationMode: "independent" }); await execute(lifecycle, { action: "start-trajectory", idempotencyKey: "trajectory", eventId: "trajectory", effortId: "handoff", sessionId: "parent", timestamp: "2026-07-22T00:00:01Z", predecessors: ["create"], trajectoryId: "trajectory", anchorId: "root" }); await execute(lifecycle, { action: "associate", idempotencyKey: "associate", eventId: "associate", effortId: "handoff", sessionId: "parent", timestamp: "2026-07-22T00:00:02Z", predecessors: ["trajectory"], trajectoryId: "trajectory", associationOrigin: "created" });
    await h.hooks.get("session_start")({ reason: "new" }, { sessionManager: { getBranch: () => [{ type: "custom", customType: ASSOCIATION_ENTRY, data: h.entries.at(-1).data }, { type: "custom", customType: "awf.telemetry.handoff.pending.v1", data: { version: protocolVersion, observationId: "handoff-pending", startedAt: 1, durationMs: 2 } }], getSessionId: () => "child", getLeafId: () => "child-leaf" }, ui: { setWidget() {}, custom() {} } }); await h.hooks.get("session_shutdown")({}, { sessionManager: { getLeafId: () => "child-leaf" } });
    const cloneHarness = harness(project); await cloneHarness.hooks.get("session_start")({ reason: "clone" }, { sessionManager: { getBranch: () => [{ type: "custom", customType: ASSOCIATION_ENTRY, data: h.entries.at(-1).data }], getSessionId: () => "clone-child", getLeafId: () => "clone-leaf" }, ui: { setWidget() {}, custom() {} } }); await cloneHarness.hooks.get("session_shutdown")({}, { sessionManager: { getLeafId: () => "clone-leaf" } }); const cloneEvents = (await readFile(join(project, ".awf/metrics/efforts/handoff/sessions/clone-child.jsonl"), "utf8")).trim().split("\n").map((line) => JSON.parse(line)); assert.equal(cloneEvents[0].kind, "session_associated"); const sourceEvents = (await readFile(join(project, ".awf/metrics/efforts/handoff/sessions/child.jsonl"), "utf8")).trim().split("\n").map((line) => JSON.parse(line)); assert.equal(sourceEvents.some((event) => event.kind === "trajectory_forked"), true);
    const events = (await readFile(join(project, ".awf/metrics/efforts/handoff/sessions/child.jsonl"), "utf8")).trim().split("\n").map((line) => JSON.parse(line)); assert.deepEqual(events.slice(0, 3).map((event) => event.kind), ["session_associated", "session_started", "session_ended"]); const parentAfterHandoff = (await readFile(join(project, ".awf/metrics/efforts/handoff/sessions/parent.jsonl"), "utf8")).trim().split("\n").map((line) => JSON.parse(line)); assert.equal(parentAfterHandoff.some((event) => event.kind === "handoff_observed" && event.observationId === "handoff-pending"), true); assert.equal(events[0].payload.associationOrigin, "handoff");
  } finally { await rm(project, { recursive: true, force: true, maxRetries: 5, retryDelay: 10 }); }
});

test("fork and pre-association tree navigation preserve trajectory truth without guessing", async () => {
  const project = await root();
  try {
    const h = harness(project); const lifecycle = h.tools.get("awf_lifecycle"); await execute(lifecycle, { action: "create", idempotencyKey: "create", eventId: "create", effortId: "tree", sessionId: "parent", timestamp: "2026-07-22T00:00:00Z", predecessors: [], checkpointId: ".awf/memory/tree.md", creationMode: "independent" }); await execute(lifecycle, { action: "start-trajectory", idempotencyKey: "trajectory", eventId: "trajectory", effortId: "tree", sessionId: "parent", timestamp: "2026-07-22T00:00:01Z", predecessors: ["create"], trajectoryId: "parent-trajectory", anchorId: "root" }); await execute(lifecycle, { action: "associate", idempotencyKey: "associate", eventId: "associate", effortId: "tree", sessionId: "parent", timestamp: "2026-07-22T00:00:02Z", predecessors: ["trajectory"], trajectoryId: "parent-trajectory", associationOrigin: "created" }); const copied = h.entries.at(-1).data;
    await h.hooks.get("session_start")({ reason: "fork" }, { sessionManager: { getBranch: () => [{ type: "custom", customType: ASSOCIATION_ENTRY, data: copied }], getSessionId: () => "fork-child", getLeafId: () => undefined }, ui: { setWidget() {}, custom() {} } }); await h.hooks.get("session_tree")({ oldLeafId: "fork-leaf", newLeafId: "restored-leaf" }, { sessionManager: { getBranch: () => [{ type: "custom", customType: ASSOCIATION_ENTRY, data: { ...copied, sessionId: "fork-child" } }] } }); await h.hooks.get("session_tree")({ oldLeafId: "fork-anchor", newLeafId: "before" }, { sessionManager: { getBranch: () => [] } }); let response: any; h.bus.get("awf.telemetry.association.request.v1")({ respond: (value: any) => { response = value; } }); assert.equal(response, undefined); await h.hooks.get("session_shutdown")({}, {});
    const events = (await readFile(join(project, ".awf/metrics/efforts/tree/sessions/fork-child.jsonl"), "utf8")).trim().split("\n").map((line) => JSON.parse(line)); assert.deepEqual(events.slice(0, 2).map((event) => event.kind), ["session_associated", "session_started"]); const parentEvents = (await readFile(join(project, ".awf/metrics/efforts/tree/sessions/parent.jsonl"), "utf8")).trim().split("\n").map((line) => JSON.parse(line)); assert.equal(parentEvents.find((event) => event.kind === "trajectory_forked").parentTrajectoryId, "parent-trajectory"); assert.equal(events.find((event) => event.kind === "trajectory_resumed").trajectoryId, "parent-trajectory"); assert.equal(events.at(-1).kind, "session_detached");
  } finally { await rm(project, { recursive: true, force: true, maxRetries: 5, retryDelay: 10 }); }
});

test("lifecycle tool maps every closed action without guessing association", async () => {
  const project = await root();
  try {
    const h = harness(project); const tool = h.tools.get("awf_lifecycle"); let index = 0; let predecessor: string | undefined; const base = (action: string, extra: any = {}) => { index++; const request = { action, idempotencyKey: `key-${action}-${index}`, eventId: `event-${action}-${index}`, effortId: "all-actions", sessionId: "session", timestamp: `2026-07-22T00:00:${String(index).padStart(2, "0")}Z`, predecessors: predecessor ? [predecessor] : [], ...extra }; predecessor = request.eventId; return request; };
    await execute(tool, base("create", { checkpointId: ".awf/memory/all.md", creationMode: "independent" })); assert.equal(h.entries.length, 0); await writeFile(join(project, ".awf/metrics/efforts/all-actions/sessions/ignored.txt"), "ignored", { mode: 0o600 }); await mkdir(join(project, ".awf/metrics/efforts/all-actions/sessions/ignored-dir")); await writeFile(join(project, ".awf/metrics/efforts/all-actions/sessions/null.jsonl"), "null\n", { mode: 0o600 }); await execute(tool, { action: "create", idempotencyKey: "derived-key", eventId: "derived-event", effortId: "derived-actions", sessionId: "session", timestamp: "2026-07-22T00:00:01Z", predecessors: [], checkpointId: ".awf/memory/derived.md", creationMode: "derived", origin: { effortId: "origin", trajectoryId: "origin-trajectory", anchorId: "origin-anchor" } });
    const requests: any[] = [];
    requests.push(base("start-trajectory", { trajectoryId: "trajectory", anchorId: "anchor" }), base("associate", { trajectoryId: "trajectory", associationOrigin: "created" }), base("select-route", { route: "direct" }), base("change-route", { route: "plan" }), base("change-route", { route: "direct" }));
    const brainstorm = base("start-phase", { phase: "brainstorming" }); requests.push(brainstorm, base("finish-phase", { phase: "brainstorming", startEventId: brainstorm.eventId }));
    const started = base("start-phase", { phase: "implementation", activity: "tdd", implementationMode: "inline" }); requests.push(started, base("finish-phase", { phase: "implementation", startEventId: started.eventId, outcome: "success" }));
    const resumed = base("resume-trajectory", { trajectoryId: "trajectory", anchorId: "anchor" }); const closed = base("close-trajectory", { trajectoryId: "trajectory", anchorId: "anchor" }); const forked = base("fork-trajectory", { trajectoryId: "child", parentTrajectoryId: "trajectory", forkAnchorId: "anchor" }); const detach = base("detach", { reason: "manual" }); requests.push(resumed, closed, forked, detach); const review = base("start-phase", { phase: "implementation-review" }); requests.push(review, base("finish-phase", { phase: "implementation-review", startEventId: review.eventId })); const retro = base("start-phase", { phase: "retrospective" }); requests.push(retro, base("finish-phase", { phase: "retrospective", startEventId: retro.eventId }), base("complete"), base("reopen", { trajectoryId: "reopened", anchorId: "anchor-two" }), base("abandon"), base("waive", { ruleCode: "WFV1-PHASE-ORDER", scope: "effort", evidenceIds: ["evidence"], reasonCode: "approved-route-deviation" }), base("repair", { proposal: { kind: "supersede-event", sourceEventIds: [detach.eventId], replacement: { eventKind: "session_detached", payload: { reason: "manual" } } } }));
    for (const request of requests) await execute(tool, request);
    assert.equal(h.entries.some((entry) => entry.type === ASSOCIATION_ENTRY), true); assert.equal(h.entries.some((entry) => entry.type === "awf.telemetry.detached.v1"), true);
    const stream = await readFile(join(project, ".awf/metrics/efforts/all-actions/sessions/session.jsonl"), "utf8"); const events = stream.trim().split("\n").map((line) => JSON.parse(line)); assert.equal(events.every(validateTelemetryEvent), true); assert.equal(events.find((event) => event.kind === "effort_reopened").payload.terminalEpoch, 2); assert.deepEqual(events.find((event) => event.kind === "repair_applied").payload.replacement, { eventKind: "session_detached", payload: { reason: "manual" } });
    const oldReaddir = h.deps.ledger.readdir; h.deps.ledger.readdir = async () => { const error: any = new Error("readdir failed"); error.code = "EACCES"; throw error; }; await assert.rejects(execute(tool, base("select-route", { route: "direct" })), /readdir failed/); h.deps.ledger.readdir = oldReaddir;
    await h.hooks.get("session_shutdown")({}, {});
  } finally { await rm(project, { recursive: true, force: true, maxRetries: 5, retryDelay: 10 }); }
});

test("invariant: lifecycle projector rejects illegal historical effects and closed transitions", async () => {
  const project = await root(); try { const h = harness(project); const tool = h.tools.get("awf_lifecycle"); const request = (action: string, eventId: string, predecessors: string[], extra: any = {}) => ({ action, idempotencyKey: eventId, eventId, effortId: "illegal-matrix", sessionId: "session", timestamp: "2026-07-22T00:00:00Z", predecessors, ...extra });
    await execute(tool, request("create", "create", [], { checkpointId: ".awf/memory/illegal.md", creationMode: "independent" }));
    await assert.rejects(execute(tool, request("change-route", "change", ["create"], { route: "direct" })), /active state/); await assert.rejects(execute(tool, request("complete", "complete-discovery", ["create"])), /completion requirements/); await assert.rejects(execute(tool, request("reopen", "reopen-discovery", ["create"], { trajectoryId: "t", anchorId: "a" })), /completed effort/);
    await execute(tool, request("select-route", "route", ["create"], { route: "direct" })); await assert.rejects(execute(tool, request("select-route", "route-again", ["route"], { route: "plan" })), /discovery state/); await execute(tool, request("start-phase", "start", ["route"], { phase: "implementation" })); await assert.rejects(execute(tool, request("start-phase", "overlap", ["start"], { phase: "planning" })), /already open/); await assert.rejects(execute(tool, request("finish-phase", "wrong-finish", ["start"], { phase: "planning", startEventId: "other" })), /visible open phase/); await assert.rejects(execute(tool, request("complete", "open-complete", ["start"])), /completion requirements/); await execute(tool, request("finish-phase", "finish", ["start"], { phase: "implementation", startEventId: "start" })); await assert.rejects(execute(tool, request("complete", "incomplete-route", ["finish"])), /completion requirements/); await assert.rejects(execute(tool, request("associate", "stale", [], { trajectoryId: "t", associationOrigin: "manual" })), /causal frontier/); await execute(tool, request("abandon", "abandon", ["finish"])); await assert.rejects(execute(tool, request("associate", "terminal-associate", ["abandon"], { trajectoryId: "t", associationOrigin: "manual" })), /illegal lifecycle source/); await assert.rejects(execute(tool, request("abandon", "terminal-abandon", ["abandon"])), /mutable state/); await assert.rejects(execute(tool, request("reopen", "abandoned-reopen", ["abandon"], { trajectoryId: "t", anchorId: "a" })), /completed effort/);
    for (const action of ["waive", "repair"] as const) await assert.rejects(execute(tool, { ...request(action, `absent-${action}`, []), effortId: "absent", ...(action === "waive" ? { ruleCode: "WFV1-PHASE-ORDER", scope: "effort", evidenceIds: ["e"], reasonCode: "approved-route-deviation" } : { proposal: { kind: "supersede-event", sourceEventIds: ["e"], replacement: { eventKind: "session_detached", payload: { reason: "manual" } } } }) }), /missing or pruned/);
    const cycleCreate = creation("cycle"); await execute(tool, { action: "create", idempotencyKey: "cycle-create", eventId: cycleCreate.eventId, effortId: "cycle", sessionId: "session", timestamp: cycleCreate.timestamp, predecessors: [], checkpointId: cycleCreate.payload.checkpointId, creationMode: "independent" }); const cycleA = association("cycle", "session", "cycle-a"); cycleA.predecessors = ["cycle-b"]; const cycleB = association("cycle", "session", "cycle-b"); cycleB.predecessors = ["cycle-a"]; await writeFile(join(project, ".awf/metrics/efforts/cycle/sessions/session.jsonl"), [JSON.stringify(cycleCreate), JSON.stringify(cycleA), JSON.stringify(cycleB), ""].join("\n"), { mode: 0o600 }); await assert.rejects(execute(tool, { ...request("detach", "cycle-next", [], { reason: "manual" }), effortId: "cycle" }), /current causal frontier/);
  } finally { await rm(project, { recursive: true, force: true }); }
});

test("invariant: historical lifecycle projection excludes every illegal effect class", async () => {
  const make = (id: string, kind: string, payload: any, predecessors: string[] = ["create"], sessionId = "session", extra: any = {}) => ({ version: protocolVersion, eventId: id, idempotencyKey: `${id}-key`, effortId: "history", sessionId, timestamp: "2026-07-22T00:00:00Z", kind, predecessors, payload, ...extra });
  const create = make("create", "effort_created", { checkpointId: ".awf/memory/history.md", creationMode: "independent" }, []);
  const project = async (events: any[]) => { const projectRoot = await root(); const sessions = join(projectRoot, ".awf/metrics/efforts/history/sessions"); await mkdir(sessions, { recursive: true, mode: 0o700 }); const grouped = new Map<string, any[]>(); for (const event of events) grouped.set(event.sessionId, [...(grouped.get(event.sessionId) ?? []), event]); for (const [session, values] of grouped) await writeFile(join(sessions, `${session}.jsonl`), values.map((value) => JSON.stringify(value)).join("\n") + "\n", { mode: 0o600 }); const result = await projectLocalLifecycle(defaultLedgerDependencies(join(projectRoot, ".pi/extensions/awf-dashboard/index.ts")), "history"); await rm(projectRoot, { recursive: true, force: true }); return result; };
  const cases: Array<[string, any[], string]> = [
    ["mutation-before-create", [make("route", "route_selected", { route: "direct" })], "route"],
    ["duplicate-create", [create, make("create-two", "effort_created", { checkpointId: ".awf/memory/history.md", creationMode: "independent" })], "create-two"],
    ["association-without-trajectory", [create, make("associate", "session_associated", { associationOrigin: "manual", trajectoryId: "missing" }, ["create"], "child", { trajectoryId: "missing" })], "associate"],
    ["route-change-without-selection", [create, make("change", "route_changed", { route: "plan" })], "change"],
    ["second-route-selection", [create, make("route", "route_selected", { route: "direct" }), make("route-two", "route_selected", { route: "plan" }, ["route"])], "route-two"],
    ["phase-finish-without-start", [create, make("finish", "phase_finished", { phase: "planning", startEventId: "missing" })], "finish"],
    ["phase-overlap", [create, make("start", "phase_started", { phase: "planning" }), make("overlap", "phase_started", { phase: "implementation" }, ["start"])], "overlap"],
    ["resume-unknown", [create, make("resume", "trajectory_resumed", { trajectoryId: "missing", anchorId: "anchor" }, ["create"], "session", { trajectoryId: "missing" })], "resume"],
    ["close-unknown", [create, make("close", "trajectory_closed", { trajectoryId: "missing", anchorId: "anchor" }, ["create"], "session", { trajectoryId: "missing" })], "close"],
    ["fork-unknown-parent", [create, make("fork", "trajectory_forked", { trajectoryId: "child", parentTrajectoryId: "missing", forkAnchorId: "anchor" }, ["create"], "session", { trajectoryId: "child", parentTrajectoryId: "missing", forkAnchorId: "anchor" })], "fork"],
    ["duplicate-trajectory", [create, make("start", "trajectory_started", { trajectoryId: "one", anchorId: "a" }, ["create"], "session", { trajectoryId: "one" }), make("start-two", "trajectory_started", { trajectoryId: "one", anchorId: "b" }, ["start"], "session", { trajectoryId: "one" })], "start-two"],
    ["close-non-active", [create, make("one", "trajectory_started", { trajectoryId: "one", anchorId: "a" }, ["create"], "session", { trajectoryId: "one" }), make("two", "trajectory_started", { trajectoryId: "two", anchorId: "b" }, ["one"], "session", { trajectoryId: "two" }), make("close", "trajectory_closed", { trajectoryId: "one", anchorId: "a" }, ["two"], "session", { trajectoryId: "one" })], "close"],
    ["close-inactive", [create, make("start", "trajectory_started", { trajectoryId: "one", anchorId: "a" }, ["create"], "session", { trajectoryId: "one" }), make("close", "trajectory_closed", { trajectoryId: "one", anchorId: "a" }, ["start"], "session", { trajectoryId: "one" }), make("close-two", "trajectory_closed", { trajectoryId: "one", anchorId: "a" }, ["close"], "session", { trajectoryId: "one" })], "close-two"],
    ["complete-discovery", [create, make("complete", "effort_completed", { terminalEpoch: 1 })], "complete"],
    ["abandon-wrong-epoch", [create, make("abandon", "effort_abandoned", { terminalEpoch: 2 })], "abandon"],
    ["reopen-discovery", [create, make("reopen", "effort_reopened", { terminalEpoch: 2, trajectoryId: "new", anchorId: "a" }, ["create"], "session", { trajectoryId: "new" })], "reopen"],
    ["post-terminal", [create, make("abandon", "effort_abandoned", { terminalEpoch: 1 }), make("route", "route_selected", { route: "direct" }, ["abandon"])], "route"],
    ["broken-predecessor", [create, make("broken", "route_selected", { route: "direct" }, ["missing"], "other")], "broken"],
    ["concurrent-route", [create, make("left", "route_selected", { route: "direct" }, ["create"], "left"), make("right", "route_selected", { route: "plan" }, ["create"], "right")], "left"],
    ["repair-missing-source", [create, make("repair", "repair_applied", { proposalKind: "supersede-event", sourceEventIds: ["missing"], replacement: { eventKind: "session_detached", payload: { reason: "manual" } } })], "repair"],
  ];
  for (const [name, events, rejected] of cases) { const projection = await project(events); assert.equal(projection.effectApplied.has(rejected), false, name); }
  const replacement = (eventKind: string, payload: any) => ({ eventKind, payload });
  const source = make("source", "route_selected", { route: "direct" });
  const repaired = await project([create, source, make("repair", "repair_applied", { proposalKind: "supersede-event", sourceEventIds: ["source"], replacement: replacement("route_selected", { route: "plan" }) }, ["source"])]); assert.equal(repaired.route, "plan"); assert.equal(repaired.effectApplied.has("source"), false); assert.equal(repaired.effectApplied.has("repair"), true);
  const phase = make("phase", "phase_started", { phase: "planning" }, ["source"]); const multi = await project([create, source, phase, make("multi-repair", "repair_applied", { proposalKind: "supersede-event", sourceEventIds: ["source", "phase"], replacement: replacement("route_selected", { route: "plan" }) }, ["phase"])]); assert.equal(multi.route, "plan"); assert.equal(multi.openPhases.size, 0); assert.equal(multi.effectApplied.has("multi-repair"), true);
  const fallback = await project([create, source, make("bad-repair", "repair_applied", { proposalKind: "supersede-event", sourceEventIds: ["source"], replacement: replacement("trajectory_resumed", { trajectoryId: "missing", anchorId: "anchor" }) }, ["source"])]); assert.equal(fallback.route, "direct"); assert.equal(fallback.effectApplied.has("source"), true); assert.equal(fallback.effectApplied.has("bad-repair"), false);
  const concurrent = await project([create, source, make("left-repair", "repair_applied", { proposalKind: "supersede-event", sourceEventIds: ["source"], replacement: replacement("route_selected", { route: "plan" }) }, ["source"], "left"), make("right-repair", "repair_applied", { proposalKind: "supersede-event", sourceEventIds: ["source"], replacement: replacement("route_selected", { route: "adr" }) }, ["source"], "right")]); assert.equal(concurrent.route, "direct"); assert.equal(concurrent.effectApplied.has("left-repair"), false); assert.equal(concurrent.effectApplied.has("right-repair"), false);
});

test("invariant: dashboard minimum runtime rejects missing factory APIs and degrades context APIs", async () => {
  const project = await root();
  try {
    const notice = Symbol.for("awf.pi.minimum-runtime-notified"); registerDashboard({} as any, { packageVersion: "0.81.1" } as any); delete (globalThis as any)[notice]; const old = harness(project, "0.80.0"); assert.equal(old.tools.size, 0); assert.deepEqual([...old.hooks.keys()], ["session_start"]); await old.hooks.get("session_start")({}, { ui: { notify() {} } }); await old.hooks.get("session_start")({}, { ui: { notify() { throw new Error("duplicate notice"); } } }); delete (globalThis as any)[notice];
    const guardedHooks = new Map<string, any>(); const missingQueue: any = { on(name: string, fn: any) { guardedHooks.set(name, fn); } }; registerDashboard(missingQueue, { packageVersion: "0.81.1" } as any); let missingNotice = ""; await guardedHooks.get("session_start")({}, { ui: { notify(message: string) { missingNotice = message; } } }); assert.match(missingNotice, /Missing runtime APIs: eventsOn, eventsEmit, appendEntry, registerTool, registerCommand, exec/); delete (globalThis as any)[notice];
    const h = harness(project); const unsupported: any = { queueCommand() {}, on() {}, registerTool() {}, registerCommand() {} }; registerDashboard(unsupported, { packageVersion: "0.81.1" } as any); defaultDashboard(h.pi); h.bus.get("awf.telemetry.association.request.v1")({ respond() { throw new Error("listener"); } }); h.bus.get("awf.telemetry.subagent.v1")({ version: { major: 2, minor: 0 } });
    await h.hooks.get("session_start")({}, { sessionManager: { getBranch: () => [] }, ui: {} }); h.hooks.get("tool_execution_end")({ toolCallId: "unknown", toolName: "read", isError: true }, {}); h.hooks.get("turn_end")({}, {}); h.hooks.get("session_compact")({}, {}); h.hooks.get("session_tree")({ newLeafId: "../bad" }); await h.hooks.get("session_shutdown")({}, {});
    const failed = harness(await root()); failed.execs.length = 0; (failed as any).tools.get("awf_metrics").execute = failed.tools.get("awf_metrics").execute.bind(null);
    await assert.rejects(execute(h.tools.get("awf_lifecycle"), { action: "bad" }), /invalid lifecycle/); const canceled = new AbortController(); canceled.abort(); await assert.rejects(h.tools.get("awf_lifecycle").execute("id", { action: "create", idempotencyKey: "cancel", eventId: "cancel", effortId: "cancel", sessionId: "session", timestamp: "2026-07-22T00:00:00Z", predecessors: [], checkpointId: ".awf/memory/cancel.md", creationMode: "independent" }, canceled.signal), /canceled/);
  } finally { await rm(project, { recursive: true, force: true, maxRetries: 5, retryDelay: 10 }); }
});
