import assert from "node:assert/strict";
import test from "node:test";
import handoffDefault, { guardMinimumRuntime, registerHandoff, versionSupported } from "../../../.pi/extensions/awf-handoff/index.ts";

function make(options:any={}) { const tools=new Map<string,any>(),commands=new Map<string,any>(),hooks=new Map<string,any>(),queued:any[]=[],notice:any[]=[],editor:string[]=[],sessions:any[]=[],entries:any[]=[],components:any[]=[]; let component:any,done:any,sendFails=false,sessionFile:any=options.noFile?undefined:"old",leaf:any={type:"message",message:{role:"assistant",content:[{type:"toolCall",id:"id",name:"handoff_session"}]}}; const pi:any={on:(n:string,f:any)=>hooks.set(n,f),registerTool:(x:any)=>tools.set(x.name,x),registerCommand:(n:string,x:any)=>commands.set(n,x),queueCommand:(n:string,id:string)=>{if(options.queueFail)throw Error("queue");queued.push([n,id]);},events:{emit(){}}}; const deps:any={packageVersion:"0.81.1",randomUUID:()=>"id",setInterval:(f:any)=>{if(options.timerFail)throw Error("timer");return {f}},clearInterval(){},setTimeout:(f:any)=>({f}),clearTimeout(){}}; registerHandoff(pi,deps); const ui:any={notify:(...x:any[])=>notice.push(x),setEditorText:(x:string)=>editor.push(x),custom:async(factory:any)=>new Promise(r=>{done=r;component=factory({requestRender(){}},{},{matches:()=>{if(options.keyFail)throw Error("key");return true}},r);component.complete=r;components.push(component);})}; const ctx:any={mode:options.mode??"tui",ui,sessionManager:{getSessionFile:()=>sessionFile,getLeafEntry:()=>leaf},newSession:async(x:any)=>{sessions.push(x);const manager={cleanup:async()=>{if(options.cleanupFail)throw Error("cleanup");entries.push(["cleanup"])}};await x.setup(manager);if(options.newFail)throw Error("new");await x.withSession({ui,sendUserMessage:async(x:string)=>{if(sendFails)throw Error("send");editor.push("sent:"+x)}})}}; return {tools,commands,hooks,queued,notice,editor,sessions,entries,components,ctx,deps,get component(){return component},go:()=>setImmediate(()=>done(true)),cancel:()=>component.handleInput("escape"),sendFails:()=>sendFails=true,setLeaf:(x:any)=>leaf=x,dropFile:()=>sessionFile=undefined}; }
async function execute(h:any,p:any={kickoff:"go"}){return h.tools.get("handoff_session").execute("id",p,undefined,undefined,h.ctx)}
async function continueHandoff(h:any){const promise=h.commands.get("awf-handoff-continue").handler("id",h.ctx);await new Promise(r=>setImmediate(r));return promise;}

test("handoff exposes only bounded required kickoff prose",async()=>{const h=make(), tool=h.tools.get("handoff_session");assert.deepEqual(Object.keys(tool.parameters.properties),["kickoff"]);assert.deepEqual(tool.parameters.required,["kickoff"]);assert.equal(tool.parameters.additionalProperties,false);assert.equal(tool.parameters.properties.kickoff.maxLength,1000);assert.equal("kickoff" in tool.parameters.properties,true);assert.equal(Object.keys(tool.parameters.properties).length,1);for(const value of [{kickoff:1},{kickoff:""},{kickoff:"  "},{kickoff:"x".repeat(1001)}])await assert.rejects(execute(h,value),/kickoff/);await execute(make(),{kickoff:"😀".repeat(500)});await assert.rejects(execute(make(),{kickoff:"😀".repeat(501)}),/1000/);});
test("handoff preserves exact kickoff through details, submission, fallback, and recovery",async()=>{const kickoff="  keep this exact prose  ";const h=make();const result=await execute(h,{kickoff});assert.deepEqual(result.details,{kickoff});assert.equal(result.terminate,true);assert.deepEqual(h.queued,[["awf-handoff-continue","id"]]);const p=continueHandoff(h);h.go();await p;assert.equal(h.editor[0],"sent:"+kickoff);const fallback=make();fallback.sendFails();await execute(fallback,{kickoff});const fp=continueHandoff(fallback);fp;fallback.go();await fp;assert.deepEqual(fallback.editor,[kickoff]);const recovery=make({newFail:true});await execute(recovery,{kickoff});const rp=continueHandoff(recovery);recovery.go();await assert.rejects(rp,/new/);assert.deepEqual(recovery.editor,[kickoff]);});
test("handoff preflight exclusively blocks mixed and unverifiable batches",()=>{const h=make(),pre=h.hooks.get("tool_call");assert.equal(pre({toolCallId:"id",toolName:"handoff_session"},h.ctx),undefined);h.setLeaf({type:"message",message:{role:"assistant",content:[{type:"toolCall",id:"id",name:"handoff_session"},{type:"toolCall",id:"x",name:"read"}]}});assert.match(pre({toolCallId:"x",toolName:"read"},h.ctx).reason,/siblings/);h.setLeaf(undefined);assert.match(pre({toolCallId:"id",toolName:"handoff_session"},h.ctx).reason,/Cannot verify/);assert.equal(pre({toolCallId:"x",toolName:"read"},h.ctx),undefined);});
test("handoff counts down, cancels, and retains pending lifecycle guards",async()=>{const h=make();await execute(h);const p=continueHandoff(h);assert.match(h.component.render(200)[0],/5s/);h.component.render(0);h.component.invalidate();h.component.dispose();h.cancel();await p;assert.deepEqual(h.notice,[["Fresh-session handoff canceled."]]);assert.equal(h.sessions.length,0);await assert.rejects(h.commands.get("awf-handoff-continue").handler("wrong",h.ctx),/matching/);await execute(h);await assert.rejects(execute(h),/already pending/);});
test("handoff rejects a continuation whose pending request changed during countdown",async()=>{const h=make();await execute(h);const first=continueHandoff(h);const second=continueHandoff(h);h.components[1].complete(true);await second;h.components[0].complete(true);await assert.rejects(first,/matching pending/);});
test("handoff revalidates only pending and persisted session after countdown",async()=>{const lost=make();await execute(lost);lost.dropFile();const p=continueHandoff(lost);lost.go();await assert.rejects(p,/no longer persisted/);assert.deepEqual(lost.editor,["go"]);});
test("handoff preserves lineage, cleanup, queue failure, and fault handling",async()=>{const success=make();await execute(success);const p=continueHandoff(success);success.go();await p;assert.equal(success.sessions[0].parentSession,"old");const failed=make({newFail:true});await execute(failed);const fp=continueHandoff(failed);failed.go();await assert.rejects(fp,/new/);assert.deepEqual(failed.entries,[["cleanup"]]);const cleanup=make({newFail:true,cleanupFail:true});await execute(cleanup);const cp=continueHandoff(cleanup);cleanup.go();await assert.rejects(cp,/new/);await assert.rejects(execute(make({mode:"rpc"})),/persisted/);await assert.rejects(execute(make({queueFail:true})),/queue/);const timer=make({timerFail:true});await execute(timer);await continueHandoff(timer).catch(()=>undefined);const key=make({keyFail:true});await execute(key);const kp=continueHandoff(key);assert.throws(()=>key.component.handleInput("escape"),/key/);await kp;});
test("handoff exercises runtime guard and generated entrypoint",async()=>{(globalThis as any)[Symbol.for("awf.pi.minimum-runtime-notified")]=undefined;let noticeHandler:any;const old:any={on:(name:string,handler:any)=>{if(name==="session_start")noticeHandler=handler;}};registerHandoff(old,{...make().deps,packageVersion:"0.80.0",eventsEmit:undefined});await noticeHandler({}, {ui:{notify:(...args:any[])=>assert.equal(args[1],"error")}});await noticeHandler({}, {ui:{notify:()=>assert.fail("duplicate notice")}});assert.equal(versionSupported("0.81.1"),true);assert.equal(versionSupported("bad"),false);assert.equal(guardMinimumRuntime({} as any,{packageVersion:"bad"},[]),false);(globalThis as any)[Symbol.for("awf.pi.minimum-runtime-notified")]=undefined;let versionOnly:any;assert.equal(guardMinimumRuntime({on:(_name:string,handler:any)=>versionOnly=handler} as any,{packageVersion:"0.80.0"},[]),false);await versionOnly({}, {ui:{notify:(message:string)=>assert.equal(message.includes("Missing runtime APIs"),false)}});await handoffDefault({on:()=>{},registerTool(){},registerCommand(){},queueCommand(){}} as any);});
test("handoff accepts optional child APIs",async()=>{const child=make();child.ctx.newSession=async(x:any)=>{await x.setup({})};await execute(child);const p=continueHandoff(child);child.go();await p;});
