import assert from "node:assert/strict";
import test from "node:test";
import { dirname, isAbsolute, resolve } from "node:path";
import handoffDefault, { buildKickoffWrapper, guardMinimumRuntime, registerHandoff, validateMemoryPath, versionSupported } from "../../../.pi/extensions/awf-handoff/index.ts";
const root="/repo";
function make(options:any={}) { const tools=new Map<string,any>(),commands=new Map<string,any>(),hooks=new Map<string,any>(),queued:any[]=[],notice:any[]=[],editor:string[]=[],sessions:any[]=[],entries:any[]=[];let component:any,done:any,sendFails=false,leaf:any={type:"message",message:{role:"assistant",content:[{type:"toolCall",id:"id",name:"handoff_session"}]}};const pi:any={on:(n:string,f:any)=>hooks.set(n,f),registerTool:(x:any)=>tools.set(x.name,x),registerCommand:(n:string,x:any)=>commands.set(n,x),queueCommand:(n:string,id:string)=>{if(options.queueFail)throw Error("queue");queued.push([n,id]);},events:{emit(){}}};const deps:any={packageVersion:"0.81.1",extensionFile:`${root}/.pi/extensions/awf-handoff/index.ts`,path:{resolve,dirname,isAbsolute},randomUUID:()=>"id",setInterval:(f:any)=>{if(options.timerFail)throw Error("timer");return {f}},clearInterval(){},setTimeout:(f:any)=>({f}),clearTimeout(){},lstat:async(p:string)=>({isSymbolicLink:()=>p.includes("link"),isFile:()=>p.endsWith(".md"),isDirectory:()=>!p.endsWith(".md")}),readFile:async()=>""};registerHandoff(pi,deps);const ui:any={notify:(...x:any[])=>notice.push(x),setEditorText:(x:string)=>editor.push(x),custom:async(factory:any)=>new Promise(r=>{done=r;component=factory({requestRender(){}},{},{matches:(x:string)=>{if(options.keyFail)throw Error("key");return x==="escape"}},r);})};const ctx:any={mode:options.mode??"tui",ui,sessionManager:{getSessionFile:()=>options.noFile?undefined:"old",getLeafEntry:()=>leaf},newSession:async(x:any)=>{sessions.push(x);const manager={cleanup:async()=>entries.push(["cleanup"])};await x.setup(manager);if(options.newFail)throw Error("new");await x.withSession({ui,sendUserMessage:async(x:string)=>{if(sendFails)throw Error("send");editor.push("sent:"+x)}})}};return {tools,commands,hooks,queued,notice,editor,sessions,entries,ctx,deps,get component(){return component},go:()=>done(true),cancel:()=>component.handleInput("escape"),sendFails:()=>sendFails=true,setLeaf:(x:any)=>leaf=x};}
async function execute(h:any,p:any={memoryPath:".awf/memory/work.md",kickoff:"go"}){return h.tools.get("handoff_session").execute("id",p,undefined,undefined,h.ctx)}
async function continueHandoff(h:any){const promise=h.commands.get("awf-handoff-continue").handler("id",h.ctx);await new Promise(r=>setImmediate(r));return promise;}
test("handoff validates confined optional regular-file memory paths",async()=>{const h=make();assert.equal(await validateMemoryPath(".awf/memory/work.md",h.deps),".awf/memory/work.md");for(const path of ["", ".awf/memory/../x", "/tmp/x", ".awf/memory/link.md"])await assert.rejects(validateMemoryPath(path,h.deps));const directory={...h.deps,lstat:async()=>({isSymbolicLink:()=>false,isFile:()=>false,isDirectory:()=>false})};await assert.rejects(validateMemoryPath(".awf/memory/work.md",directory));});
test("handoff preflight exclusively blocks mixed and unverifiable batches",()=>{const h=make(),pre=h.hooks.get("tool_call");assert.equal(pre({toolCallId:"id",toolName:"handoff_session"},h.ctx),undefined);h.setLeaf({type:"message",message:{role:"assistant",content:[{type:"toolCall",id:"id",name:"handoff_session"},{type:"toolCall",id:"x",name:"read"}]}});assert.match(pre({toolCallId:"x",toolName:"read"},h.ctx).reason,/siblings/);h.setLeaf(undefined);assert.match(pre({toolCallId:"id",toolName:"handoff_session"},h.ctx).reason,/Cannot verify/);});
test("kickoff exact text only reads a checkpoint when supplied",()=>{assert.equal(buildKickoffWrapper(undefined,"go"),"Then continue with this immediate action: go");assert.equal(buildKickoffWrapper(".awf/memory/work.md","go"),"Read .awf/memory/work.md first. Repository sources and current-state documentation are authoritative over the checkpoint. Then continue with this immediate action: go");});
test("handoff counts down, cancels, cleans pending, and links parent before setup kickoff",async()=>{const h=make();await execute(h);const p=continueHandoff(h);await new Promise(r=>setImmediate(r));assert.match(h.component.render(200)[0],/5s/);h.component.render(0);h.component.invalidate();h.component.dispose();h.cancel();await p;assert.deepEqual(h.notice,[["Fresh-session handoff canceled."]]);assert.equal(h.sessions.length,0);});
test("handoff countdown handles timer and key faults",async()=>{const timer=make({timerFail:true});await execute(timer);await continueHandoff(timer).catch(()=>undefined);const key=make({keyFail:true});await execute(key);const p=continueHandoff(key);await new Promise(r=>setImmediate(r));assert.throws(()=>key.component.handleInput("escape"),/key/);await p;});
test("testHandoffDoesNotInvokeAwfOrSelectEffort",async()=>{const h=make();h.sendFails();await execute(h);const p=continueHandoff(h);await new Promise(r=>setImmediate(r));h.go();await p;assert.equal(h.sessions[0].parentSession,"old");assert.equal(h.entries.length,0);assert.match(h.editor[0],/^Read .awf/);assert.deepEqual(h.notice,[["Automatic kickoff failed; submit the prepared editor text.","warning"]]);assert.equal(JSON.stringify([...h.commands.keys()]).includes("effort"),false);});
test("handoff accepts absent memory and cleans prepared child on failure",async()=>{const h=make({newFail:true});await execute(h,{kickoff:"go"});const p=continueHandoff(h);await new Promise(r=>setImmediate(r));h.go();await assert.rejects(p,/new/);assert.ok(h.entries.some((x:any)=>x[0]==="cleanup"));assert.match(h.editor[0],/^Then continue/);const bad=make({mode:"rpc"});await assert.rejects(execute(bad),/persisted/);const queue=make({queueFail:true});await assert.rejects(execute(queue),/queue/);});
test("handoff exercises runtime guard and generated entrypoint",async()=>{(globalThis as any)[Symbol.for("awf.pi.minimum-runtime-notified")]=undefined;let noticeHandler:any;const old:any={on:(name:string,handler:any)=>{if(name==="session_start")noticeHandler=handler;}};registerHandoff(old,{...make().deps,packageVersion:"0.80.0",eventsEmit:undefined});await noticeHandler({}, {ui:{notify:(...args:any[])=>assert.equal(args[1],"error")}});await noticeHandler({}, {ui:{notify:()=>assert.fail("duplicate notice")}});assert.equal(versionSupported("0.81.1"),true);assert.equal(versionSupported("bad"),false);assert.equal(guardMinimumRuntime({} as any,{packageVersion:"bad"},[]),false);await handoffDefault({on:()=>{},registerTool(){},registerCommand(){},queueCommand(){}} as any);});
test("handoff accepts optional child APIs",async()=>{const child=make();child.ctx.newSession=async(x:any)=>{await x.setup({})};await execute(child);const p=continueHandoff(child);await new Promise(r=>setImmediate(r));child.go();await p;});
