import assert from "node:assert/strict";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { Value } from "typebox/value";
import {
  ASSOCIATION_ENTRY,
  PROVISIONAL_MAX_BYTES,
  PROVISIONAL_MAX_OBSERVATIONS,
  ProvisionalIdentity,
  acknowledgedWorkflowRetry,
  createLedgerWriter,
  dashboardProvisionalPersistence,
  defaultLedgerDependencies,
  deterministicWorkflowIdentity,
  projectLocalLifecycle,
  registerDashboard,
  retrospectiveSettlementIdentity,
  validateWorkflowPredecessor,
  validateWorkflowRouteOrder,
  workflowMappings,
  workflowRouteEffect,
  workflowSkillNames,
  workflowToolPreflight,
} from "../../../.pi/extensions/awf-dashboard/index.ts";
import { protocolVersion } from "../../../.pi/extensions/awf-dashboard/protocol.ts";

async function projectRoot() {
  const root = await mkdtemp(join(tmpdir(), "awf-workflow-"));
  await mkdir(join(root, ".awf"), { recursive: true });
  await mkdir(join(root, ".pi/extensions/awf-dashboard"), { recursive: true });
  await mkdir(join(root, ".pi/awf-workflows"), { recursive: true });
  return root;
}

function canonical(kind: "protocol" | "metrics" | "doctor") {
  if (kind === "protocol") return JSON.stringify({ schemaVersion: 1, protocol: protocolVersion, compatibleMajor: 2, awfVersion: "0.22.0", projectVersion: "0.22.0" });
  if (kind === "metrics") return JSON.stringify({ schemaVersion: 1, protocolMajor: 2, efforts: [], integrity: [], retention: {} });
  return JSON.stringify({ schemaVersion: 1, protocolMajor: 2, findings: [], integrity: [] });
}

async function harness(root: string, settle?: (skill: string, ctx: any) => Promise<any>) {
  const tools = new Map<string, any>(); const commands = new Map<string, any>(); const hooks = new Map<string, any>(); const bus = new Map<string, any>(); const entries: any[] = []; const queued: any[] = [];
  const ledger = defaultLedgerDependencies(join(root, ".pi/extensions/awf-dashboard/index.ts")); let sequence = 0; ledger.uuid = () => `uuid-${++sequence}`;
  const pi: any = {
    registerTool(tool: any) { tools.set(tool.name, tool); }, registerCommand(name: string, command: any) { commands.set(name, command); }, appendEntry(type: string, data: any) { entries.push({ type, data }); }, queueCommand(name: string, args: string) { queued.push([name, args]); },
    events: { on(name: string, handler: any) { bus.set(name, handler); }, emit() {} }, on(name: string, handler: any) { hooks.set(name, handler); },
    exec: async () => ({ stdout: "{}", stderr: "", code: 0 }),
  };
  const deps: any = { packageVersion: "0.81.1", extensionFile: join(root, ".pi/extensions/awf-dashboard/index.ts"), ledger, settleWorkflowIdentity: settle, gracefulProvisional: (identity: any) => identity.graceful(),
    exec: async (_command: string, args: string[]) => args[1] === "protocol" ? { stdout: canonical("protocol"), stderr: "", code: 0 } : args[0] === "metrics" ? { stdout: canonical("metrics"), stderr: "", code: 0 } : { stdout: canonical("doctor"), stderr: "", code: 0 } };
  registerDashboard(pi, deps);
  return { tools, commands, hooks, bus, entries, queued, ledger, deps, pi };
}

async function seed(ledger: any, effortId = "effort", sessionId = "session") {
  const writer = createLedgerWriter(ledger); const at = "2026-07-23T00:00:00Z";
  const create: any = { version: protocolVersion, eventId: "create", idempotencyKey: "create-key", effortId, sessionId, timestamp: at, kind: "effort_created", predecessors: [], payload: { creationMode: "independent" } };
  await writer.create({ effortId, createdAt: at, creationMode: "independent" }, create);
  await writer.mutateLifecycle({ action: "start-trajectory", idempotencyKey: "trajectory-key", eventId: "trajectory", effortId, sessionId, timestamp: at, predecessors: ["create"], trajectoryId: "trajectory", anchorId: "anchor" });
  await writer.mutateLifecycle({ action: "associate", idempotencyKey: "associate-key", eventId: "associate", effortId, sessionId, timestamp: at, predecessors: ["trajectory"], trajectoryId: "trajectory", associationOrigin: "created" });
  await writer.shutdown();
  return { effortId, sessionId, trajectoryId: "trajectory", associationOrigin: "created" } as const;
}

function context(association: any, calls: Array<{ id: string; name: string }> = [{ id: "workflow", name: "awf_workflow" }]) {
  return { sessionManager: { getSessionId: () => association.sessionId, getLeafEntry: () => ({ type: "message", message: { role: "assistant", content: calls.map((call) => ({ type: "toolCall", ...call })) } }) } };
}

async function execute(tool: any, skill: string, ctx: any, signal?: AbortSignal) { return tool.execute("workflow", { skill }, signal, undefined, ctx); }

async function bodies(root: string, names: string[]) { for (const name of names) await writeFile(join(root, `.pi/awf-workflows/${name}.md`), `fixed body ${name}\n`); }
async function events(root: string, effortId: string, sessionId = "session") { return (await readFile(join(root, `.awf/metrics/efforts/${effortId}/sessions/${sessionId}.jsonl`), "utf8")).trim().split("\n").map((line) => JSON.parse(line)); }
const successfulAgentEnd = { messages: [{ role: "assistant", stopReason: "stop" }] };

test("rendered workflow metadata drives a closed semantic-only schema", async () => {
  assert.deepEqual([...workflowSkillNames].sort(), Object.keys(workflowMappings).sort());
  assert.equal(workflowSkillNames.includes("brainstorming"), true); assert.equal(workflowSkillNames.includes("executing-direct"), true);
  const root = await projectRoot(); try { const h = await harness(root); const schema = h.tools.get("awf_workflow").parameters;
    assert.deepEqual(schema.required, ["skill"]); assert.equal(schema.additionalProperties, false); assert.equal(Value.Check(schema, { skill: "brainstorming" }), true);
    for (const input of [{ skill: ".pi/awf-workflows/brainstorming.md" }, { skill: "../brainstorming" }, { skill: "disabled" }, { skill: "brainstorming", path: "x" }]) assert.equal(Value.Check(schema, input), false);
    await assert.rejects(execute(h.tools.get("awf_workflow"), "../brainstorming", context({ sessionId: "session" })), /disabled or unknown/);
  } finally { await rm(root, { recursive: true, force: true }); }
});

test("exclusive trustworthy preflight rejects every workflow sibling and stale leaf", () => {
  const solo = context({ sessionId: "session" }); assert.equal(workflowToolPreflight({ toolCallId: "workflow", toolName: "awf_workflow" }, solo), undefined);
  const mixed = context({ sessionId: "session" }, [{ id: "workflow", name: "awf_workflow" }, { id: "read", name: "read" }]);
  for (const event of [{ toolCallId: "workflow", toolName: "awf_workflow" }, { toolCallId: "read", toolName: "read" }]) assert.match(workflowToolPreflight(event, mixed)!.reason, /cannot contain siblings/);
  for (const ctx of [{}, { sessionManager: { getLeafEntry: () => ({ type: "message", message: { role: "user", content: [] } }) } }, context({ sessionId: "session" }, [{ id: "other", name: "awf_workflow" }]), ...[{ id: "", name: "awf_workflow" }, { id: "bad/id", name: "awf_workflow" }, { id: "workflow", name: "" }, { id: "workflow", name: 1 }].map((call) => ({ sessionManager: { getLeafEntry: () => ({ type: "message", message: { role: "assistant", content: [{ type: "toolCall", ...call }] } }) } }))]) assert.match(workflowToolPreflight({ toolCallId: "workflow", toolName: "awf_workflow" }, ctx)!.reason, /Cannot verify/);
  assert.equal(workflowToolPreflight({ toolCallId: "read", toolName: "read" }, {}), undefined); assert.equal(workflowToolPreflight({ toolCallId: "read", toolName: "read" }, context({ sessionId: "session" }, [{ id: "read", name: "read" }])), undefined);
});

test("rendered route effects and predecessor validation are closed and deterministic", () => {
  const projection = (state: string, route?: string, phase = "brainstorming"): any => ({ state, route, frontier: ["frontier"], openPhases: new Map([["start", { phase, startEventId: "start", terminalEpoch: 1 }]]), phaseIntervals: [], effectApplied: new Set(), events: new Map() });
  const discovery = projection("discovery"); const activeADR = projection("active", "adr", "adr-review");
  assert.deepEqual(workflowRouteEffect({}, discovery, "brainstorming"), {}); assert.deepEqual(workflowRouteEffect({ routeEffect: "" }, discovery, "brainstorming"), {});
  for (const [effect, route] of [["select-direct", "direct"], ["select-adr", "adr"], ["select-plan", "plan"], ["select-bugfix", "bugfix"]]) assert.deepEqual(workflowRouteEffect({ routeEffect: effect }, discovery, "brainstorming"), { routeAction: "select", route });
  assert.deepEqual(workflowRouteEffect({ routeEffect: "select-direct" }, projection("active", "plan"), "brainstorming"), { routeAction: "change", route: "direct" });
  assert.deepEqual(workflowRouteEffect({ routeEffect: "select-direct" }, projection("active", "direct"), "brainstorming"), {}); assert.deepEqual(workflowRouteEffect({ routeEffect: "select-direct" }, projection("active", "bugfix"), "brainstorming"), {});
  assert.deepEqual(workflowRouteEffect({ routeEffect: "promote-adr-plan" }, discovery, "brainstorming"), { routeAction: "select", route: "plan" }); assert.deepEqual(workflowRouteEffect({ routeEffect: "promote-adr-plan" }, activeADR, "adr-review"), { routeAction: "change", route: "adr-plan" });
  for (const route of ["plan", "adr-plan"]) assert.deepEqual(workflowRouteEffect({ routeEffect: "promote-adr-plan" }, projection("active", route), "planning"), {});
  assert.throws(() => workflowRouteEffect({ routeEffect: "promote-adr-plan" }, projection("active", "direct"), "brainstorming"), /planning requires/); assert.throws(() => workflowRouteEffect({ routeEffect: "promote-adr-plan" }, projection("active"), "brainstorming"), /planning requires/);
  assert.deepEqual(workflowRouteEffect({ routeEffect: "select-investigation-if-unrouted" }, projection("discovery", undefined, "investigation"), "investigation"), { routeAction: "select", route: "investigation-only" }); assert.deepEqual(workflowRouteEffect({ routeEffect: "select-investigation-if-unrouted" }, projection("active", "direct"), "implementation-review"), {});
  const implemented = projection("discovery", undefined, "investigation"); implemented.terminalEpoch = 1; implemented.phaseIntervals.push({ phase: "implementation", startEventId: "impl", finishEventId: "impl-finish", terminalEpoch: 1 }); assert.throws(() => workflowRouteEffect({ routeEffect: "select-investigation-if-unrouted" }, implemented, "investigation"), /investigation routing/);
  assert.throws(() => workflowRouteEffect({ routeEffect: "select-investigation-if-unrouted" }, discovery, "brainstorming"), /investigation routing/); assert.throws(() => workflowRouteEffect({ routeEffect: "unknown" }, discovery, "brainstorming"), /unknown rendered/); assert.throws(() => workflowRouteEffect({ routeEffect: "select-plan" }, projection("absent"), "brainstorming"), /mutable route/);
  assert.equal(validateWorkflowPredecessor({ phaseEffect: "transition", requiresPhases: ["brainstorming"] }, discovery)?.phase, "brainstorming"); assert.equal(validateWorkflowPredecessor({ phaseEffect: "transition", requiresPhases: [] }, discovery)?.phase, "brainstorming"); assert.equal(validateWorkflowPredecessor({ phaseEffect: "transition" }, discovery)?.phase, "brainstorming"); assert.throws(() => validateWorkflowPredecessor({ phaseEffect: "start" }, discovery), /no open phase/); assert.throws(() => validateWorkflowPredecessor({ phaseEffect: "transition" }, { ...discovery, openPhases: new Map() }), /exactly one/); assert.throws(() => validateWorkflowPredecessor({ phaseEffect: "transition" }, { ...discovery, openPhases: new Map([["a", {}], ["b", {}]]) }), /exactly one/); assert.throws(() => validateWorkflowPredecessor({ phaseEffect: "transition", requiresPhases: ["planning"] }, discovery), /requires predecessor/); assert.throws(() => validateWorkflowPredecessor({ phaseEffect: "start" }, { ...discovery, state: "completed", openPhases: new Map() }), /mutable effort/);
  assert.equal(validateWorkflowPredecessor({ phaseEffect: "start" }, { ...discovery, openPhases: new Map() }), undefined); validateWorkflowRouteOrder(undefined, "x", "y"); validateWorkflowRouteOrder("direct", "brainstorming", "brainstorming"); validateWorkflowRouteOrder("direct", "brainstorming", "implementation"); assert.throws(() => validateWorkflowRouteOrder("unknown", "x", "y"), /invalid unknown/); assert.throws(() => validateWorkflowRouteOrder("direct", "brainstorming", "retrospective"), /invalid direct/);
  const identity = deterministicWorkflowIdentity("session", [], "skill"); const event: any = { eventId: "event", sessionId: "session", predecessors: [], idempotencyKey: `workflow-${identity}` }; const retryProjection: any = { frontier: ["event"], events: new Map([["event", event]]), effectApplied: new Set(["event"]) }; assert.equal(acknowledgedWorkflowRetry(retryProjection, "session", "skill"), event); assert.equal(acknowledgedWorkflowRetry({ ...retryProjection, frontier: [] }, "session", "skill"), undefined); assert.equal(acknowledgedWorkflowRetry({ ...retryProjection, frontier: ["event", "other"] }, "session", "skill"), undefined); assert.equal(acknowledgedWorkflowRetry({ ...retryProjection, events: new Map() }, "session", "skill"), undefined); assert.equal(acknowledgedWorkflowRetry(retryProjection, "other", "skill"), undefined); assert.equal(acknowledgedWorkflowRetry({ ...retryProjection, effectApplied: new Set() }, "session", "skill"), undefined); event.idempotencyKey = `workflow-${identity}-phase`; assert.equal(acknowledgedWorkflowRetry(retryProjection, "session", "skill"), event); delete event.predecessors; assert.equal(acknowledgedWorkflowRetry(retryProjection, "session", "skill"), event); event.idempotencyKey = "other"; assert.equal(acknowledgedWorkflowRetry(retryProjection, "session", "skill"), undefined);
});

test("invariant: workflow router acknowledges durably before returning fixed bodies", async () => {
  const root = await projectRoot(); try {
    await bodies(root, ["brainstorming", "exploring", "executing-direct", "reviewing-impl"]); const association = await seed(defaultLedgerDependencies(join(root, ".pi/extensions/awf-dashboard/index.ts"))); const h = await harness(root, async () => association); const tool = h.tools.get("awf_workflow"); const ctx = context(association);
    const first = await execute(tool, "brainstorming", ctx); assert.equal(first.content[0].text, "fixed body brainstorming\n"); assert.equal(first.details.durable, true); assert.equal(first.details.effortId, "effort"); const firstID = first.details.eventIds[0];
    const retry = await execute(tool, "brainstorming", ctx); assert.deepEqual(retry.details.eventIds, [firstID]); assert.equal(retry.content[0].text, first.content[0].text);
    const activity = await execute(tool, "exploring", ctx); assert.equal(activity.content[0].text, "fixed body exploring\n");
    const direct = await execute(tool, "executing-direct", ctx); assert.equal(direct.content[0].text, "fixed body executing-direct\n");
    const projection = await projectLocalLifecycle(h.ledger, "effort"); assert.equal(projection.route, "direct"); assert.deepEqual([...projection.openPhases.values()].map((phase: any) => phase.phase), ["implementation"]);
    await assert.rejects(execute(tool, "reviewing-impl", { sessionManager: { getSessionId: () => "stale" } }), /session association is stale/);
    const stream = await readFile(join(root, ".awf/metrics/efforts/effort/sessions/session.jsonl"), "utf8"); assert.match(stream, /phase_started/); assert.match(stream, /phase_transitioned/); assert.match(stream, /"route":"direct"/);
    assert.equal(deterministicWorkflowIdentity("session", ["b", "a"], "brainstorming"), deterministicWorkflowIdentity("session", ["a", "b"], "brainstorming"));
  } finally { await rm(root, { recursive: true, force: true }); }
});

test("invariant: workflow router enforces mapped lifecycle effects", async () => {
  const cases = [
    { effort: "direct-chain", skills: ["brainstorming", "executing-direct", "reviewing-impl", "retrospective"], edges: [["brainstorming", "implementation"], ["implementation", "implementation-review"], ["implementation-review", "retrospective"]], route: "direct", mode: "inline-execution" },
    { effort: "plan-inline", skills: ["brainstorming", "writing-plans", "reviewing-plan", "executing-plans", "reviewing-impl", "retrospective"], edges: [["brainstorming", "planning"], ["planning", "plan-review"], ["plan-review", "implementation"], ["implementation", "implementation-review"], ["implementation-review", "retrospective"]], route: "plan", mode: "inline-execution" },
    { effort: "plan-subagent", skills: ["brainstorming", "writing-plans", "reviewing-plan", "subagent-driven-development", "reviewing-impl", "retrospective"], edges: [["brainstorming", "planning"], ["planning", "plan-review"], ["plan-review", "implementation"], ["implementation", "implementation-review"], ["implementation-review", "retrospective"]], route: "plan", mode: "subagent-driven-development" },
    { effort: "adr-plan-chain", skills: ["brainstorming", "proposing-adr", "reviewing-adr", "writing-plans", "reviewing-plan", "reviewing-plan-resync", "executing-plans", "reviewing-impl", "retrospective"], edges: [["brainstorming", "adr-authoring"], ["adr-authoring", "adr-review"], ["adr-review", "planning"], ["planning", "plan-review"], ["plan-review", "adr-plan-resync"], ["adr-plan-resync", "implementation"], ["implementation", "implementation-review"], ["implementation-review", "retrospective"]], route: "adr-plan", mode: "inline-execution" },
    { effort: "investigation-chain", skills: ["debugging", "retrospective"], edges: [["investigation", "retrospective"]], route: "investigation-only" },
  ] as const;
  for (const current of cases) { const root = await projectRoot(); try { await bodies(root, [...current.skills]); const association = await seed(defaultLedgerDependencies(join(root, ".pi/extensions/awf-dashboard/index.ts")), current.effort); const h = await harness(root, async () => association); const tool = h.tools.get("awf_workflow"); for (const skill of current.skills) await execute(tool, skill, context(association)); const projection = await projectLocalLifecycle(h.ledger, current.effort); assert.equal(projection.route, current.route); assert.equal([...projection.openPhases.values()][0]?.phase, "retrospective"); const stream = await events(root, current.effort); const transitions = stream.filter((event: any) => event.kind === "phase_transitioned"); assert.deepEqual(transitions.map((event: any) => [event.payload.phase, event.payload.nextPhase]), current.edges); assert.equal(transitions.length, current.edges.length); for (const event of transitions) { assert.equal(event.predecessors.length > 0, true); assert.equal(typeof event.payload.startEventId, "string"); } if ("mode" in current) assert.equal(transitions.find((event: any) => event.payload.nextPhase === "implementation")?.payload.implementationMode, current.mode); if (current.effort === "adr-plan-chain") assert.equal(transitions.find((event: any) => event.payload.routeAction === "change")?.payload.route, "adr-plan"); }
    finally { await rm(root, { recursive: true, force: true }); }
  }
});

test("direct downstream calls, task starts, and current-phase activities enforce exact lifecycle order", async () => {
  const root = await projectRoot(); try { await bodies(root, ["brainstorming", "reviewing-impl", "retrospective", "exploring"]); const association = await seed(defaultLedgerDependencies(join(root, ".pi/extensions/awf-dashboard/index.ts")), "order-rejection"); const h = await harness(root, async () => association); const tool = h.tools.get("awf_workflow"); await execute(tool, "brainstorming", context(association)); await assert.rejects(execute(tool, "reviewing-impl", context(association)), /requires predecessor phase implementation/); await assert.rejects(execute(tool, "retrospective", context(association)), /requires predecessor phase implementation-review or investigation/); await execute(tool, "exploring", context(association)); const stream = await events(root, "order-rejection"); const activity = stream.find((event: any) => event.kind === "phase_transitioned" && event.payload.activity === "exploration"); assert.deepEqual([activity.payload.phase, activity.payload.nextPhase], ["brainstorming", "brainstorming"]); }
  finally { await rm(root, { recursive: true, force: true }); }
});

test("invariant: workflow router completes retrospective mechanically", async () => {
  const root = await projectRoot(); try { const names = ["brainstorming", "executing-direct", "reviewing-impl", "retrospective"]; await bodies(root, names); const association = await seed(defaultLedgerDependencies(join(root, ".pi/extensions/awf-dashboard/index.ts")), "retro-retry"); const h = await harness(root, async () => association); const tool = h.tools.get("awf_workflow"); for (const skill of names) await execute(tool, skill, context(association)); let failComplete = true; const originalOpen = h.ledger.open; h.ledger.open = async (path: string, flags: any, mode?: number) => { const handle: any = await originalOpen(path, flags, mode); const write = handle.writeFile.bind(handle); handle.writeFile = async (data: string) => { if (failComplete && data.includes(`"kind":"effort_completed"`)) { failComplete = false; throw new Error("completion interruption"); } return write(data); }; return handle; }; await assert.rejects(h.hooks.get("agent_end")(successfulAgentEnd, {}), /completion interruption/); let projection = await projectLocalLifecycle(h.ledger, "retro-retry"); assert.equal(projection.state, "active"); assert.equal(projection.openPhases.size, 0); await h.hooks.get("agent_end")(successfulAgentEnd, {}); projection = await projectLocalLifecycle(h.ledger, "retro-retry"); assert.equal(projection.state, "completed"); const before = (await events(root, "retro-retry")).length; await h.hooks.get("agent_end")(successfulAgentEnd, {}); assert.equal((await events(root, "retro-retry")).length, before); const stream = await events(root, "retro-retry"); assert.equal(stream.filter((event: any) => event.kind === "phase_finished").length, 1); assert.equal(stream.filter((event: any) => event.kind === "effort_completed").length, 1); }
  finally { await rm(root, { recursive: true, force: true }); }
});

test("invariant: retrospective settlement observes externally finished and completed state", async () => {
  for (const mode of ["finished", "completed"] as const) { const root = await projectRoot(); try { const names = ["brainstorming", "executing-direct", "reviewing-impl", "retrospective"]; await bodies(root, names); const effortId = `retro-external-${mode}`; const association = await seed(defaultLedgerDependencies(join(root, ".pi/extensions/awf-dashboard/index.ts")), effortId); const h = await harness(root, async () => association); for (const skill of names) await execute(h.tools.get("awf_workflow"), skill, context(association)); let projection = await projectLocalLifecycle(h.ledger, effortId); const open: any = [...projection.openPhases.values()][0]; const writer = createLedgerWriter(h.ledger); await writer.mutateLifecycle({ action: "finish-phase", idempotencyKey: `external-finish-${mode}`, eventId: `external-finish-${mode}`, effortId, sessionId: "session", timestamp: "2026-07-23T00:00:00Z", predecessors: projection.frontier, phase: "retrospective", startEventId: open.startEventId, outcome: "success" }); if (mode === "completed") { projection = await projectLocalLifecycle(h.ledger, effortId); await writer.mutateLifecycle({ action: "complete", idempotencyKey: "external-complete", eventId: "external-complete", effortId, sessionId: "session", timestamp: "2026-07-23T00:00:00Z", predecessors: projection.frontier }); } await writer.shutdown(); await h.hooks.get("agent_end")(successfulAgentEnd, {}); projection = await projectLocalLifecycle(h.ledger, effortId); assert.equal(projection.state, mode === "completed" ? "completed" : "active"); } finally { await rm(root, { recursive: true, force: true }); } }
});

test("retrospective remains open after failed tools, cancellation, unsuccessful agent end, or shutdown", async () => {
  for (const branch of ["failed-tool", "cancelled", "unsuccessful", "shutdown"] as const) { const root = await projectRoot(); try { const names = ["brainstorming", "executing-direct", "reviewing-impl", "retrospective"]; await bodies(root, names); const association = await seed(defaultLedgerDependencies(join(root, ".pi/extensions/awf-dashboard/index.ts")), `retro-${branch}`); const h = await harness(root, async () => association); for (const skill of names) await execute(h.tools.get("awf_workflow"), skill, context(association)); if (branch === "failed-tool") { h.hooks.get("tool_execution_end")({ toolCallId: "failed", toolName: "bash", isError: true }, {}); await h.hooks.get("agent_end")(successfulAgentEnd, {}); } else if (branch === "cancelled") { const controller = new AbortController(); controller.abort(); await h.hooks.get("agent_end")(successfulAgentEnd, { signal: controller.signal }); } else if (branch === "unsuccessful") await h.hooks.get("agent_end")({ messages: [{ role: "assistant", stopReason: "error" }] }, {}); else await h.hooks.get("session_shutdown")({}, {}); const projection = await projectLocalLifecycle(h.ledger, `retro-${branch}`); assert.equal(projection.state, "active"); assert.deepEqual([...projection.openPhases.values()].map((phase: any) => phase.phase), ["retrospective"]); assert.equal((await events(root, `retro-${branch}`)).some((event: any) => event.kind === "effort_completed"), false); }
    finally { await rm(root, { recursive: true, force: true }); }
  }
  const settlement = { effortId: "effort", sessionId: "session", phaseStartEventId: "phase", toolCallId: "tool", failedTool: false }; assert.equal(retrospectiveSettlementIdentity(settlement), retrospectiveSettlementIdentity({ ...settlement, failedTool: true })); assert.notEqual(retrospectiveSettlementIdentity(settlement), retrospectiveSettlementIdentity({ ...settlement, toolCallId: "later-tool" }));
});

test("loader fails closed at identity, session, post-ack cancellation, and body-read boundaries", async () => {
  const root = await projectRoot(); try {
    await bodies(root, ["brainstorming"]); const association = await seed(defaultLedgerDependencies(join(root, ".pi/extensions/awf-dashboard/index.ts")), "boundaries"); const unsettled = await harness(root); await assert.rejects(execute(unsettled.tools.get("awf_workflow"), "brainstorming", context(association)), /identity is not settled/);
    const malformed = await harness(root, async () => ({ ...association, effortId: "../bad" })); await assert.rejects(execute(malformed.tools.get("awf_workflow"), "brainstorming", context(association)), /identity is not settled/);
    const fallback = await harness(root, async () => association); const noSessionAPI = { sessionManager: { getLeafEntry: context(association).sessionManager.getLeafEntry } }; assert.equal((await execute(fallback.tools.get("awf_workflow"), "brainstorming", noSessionAPI)).details.durable, true);
    const readFailureRoot = await projectRoot(); try { await bodies(readFailureRoot, ["brainstorming"]); const readAssociation = await seed(defaultLedgerDependencies(join(readFailureRoot, ".pi/extensions/awf-dashboard/index.ts")), "read-failure"); const readFailure = await harness(readFailureRoot, async () => readAssociation); const originalRead = readFailure.ledger.readFile; readFailure.ledger.readFile = async (path: string, encoding: "utf8") => { if (path.includes("/.pi/awf-workflows/")) throw new Error("removed"); return originalRead(path, encoding); }; await assert.rejects(execute(readFailure.tools.get("awf_workflow"), "brainstorming", context(readAssociation)), /missing after lifecycle acknowledgment/); assert.match(await readFile(join(readFailureRoot, ".awf/metrics/efforts/read-failure/sessions/session.jsonl"), "utf8"), /phase_started/); }
    finally { await rm(readFailureRoot, { recursive: true, force: true }); }
    const cancelRoot = await projectRoot(); try { await bodies(cancelRoot, ["brainstorming"]); const cancelAssociation = await seed(defaultLedgerDependencies(join(cancelRoot, ".pi/extensions/awf-dashboard/index.ts")), "post-cancel"); const postCancel = await harness(cancelRoot, async () => cancelAssociation); const controller = new AbortController(); const originalOpen = postCancel.ledger.open; postCancel.ledger.open = async (path: string, flags: any, mode?: number) => { const handle: any = await originalOpen(path, flags, mode); const write = handle.writeFile.bind(handle); handle.writeFile = async (data: string) => { await write(data); if (data.includes(`"kind":"phase_started"`)) controller.abort(); }; return handle; }; await assert.rejects(execute(postCancel.tools.get("awf_workflow"), "brainstorming", context(cancelAssociation), controller.signal), /canceled after durable acknowledgment/); assert.match(await readFile(join(cancelRoot, ".awf/metrics/efforts/post-cancel/sessions/session.jsonl"), "utf8"), /phase_started/); }
    finally { await rm(cancelRoot, { recursive: true, force: true }); }
  } finally { await rm(root, { recursive: true, force: true }); }
});

test("task loaders select bugfix routing and record investigation activity on phase start", async () => {
  const root = await projectRoot(); try { await bodies(root, ["bugfix"]); const association = await seed(defaultLedgerDependencies(join(root, ".pi/extensions/awf-dashboard/index.ts")), "bugfix-effort"); const h = await harness(root, async () => association); const result = await execute(h.tools.get("awf_workflow"), "bugfix", context(association)); assert.equal(result.details.eventIds.length, 2); const projection = await projectLocalLifecycle(h.ledger, "bugfix-effort"); assert.equal(projection.route, "bugfix"); assert.equal([...projection.openPhases.values()][0]?.phase, "brainstorming"); const stream = await readFile(join(root, ".awf/metrics/efforts/bugfix-effort/sessions/session.jsonl"), "utf8"); assert.ok(stream.indexOf("route_selected") < stream.indexOf("phase_started")); }
  finally { await rm(root, { recursive: true, force: true }); }
  const investigation = await projectRoot(); try { await bodies(investigation, ["debugging"]); const association = await seed(defaultLedgerDependencies(join(investigation, ".pi/extensions/awf-dashboard/index.ts")), "debug-effort"); const h = await harness(investigation, async () => association); await execute(h.tools.get("awf_workflow"), "debugging", context(association)); const stream = await readFile(join(investigation, ".awf/metrics/efforts/debug-effort/sessions/session.jsonl"), "utf8"); assert.match(stream, /"phase":"investigation","activity":"debugging"/); }
  finally { await rm(investigation, { recursive: true, force: true }); }
});

test("invariant: workflow router rejects competing frontiers", async () => {
  const root = await projectRoot(); try {
    await bodies(root, ["reviewing-impl", "brainstorming"]); const association = await seed(defaultLedgerDependencies(join(root, ".pi/extensions/awf-dashboard/index.ts")), "reject"); let release!: () => void; let entered!: () => void; const waiting = new Promise<void>((done) => { entered = done; }); const settle = new Promise<void>((done) => { release = done; }); let calls = 0;
    const h = await harness(root, async () => { calls++; entered(); await settle; return association; }); const tool = h.tools.get("awf_workflow"); const ctx = context(association);
    const first = execute(tool, "brainstorming", ctx); await waiting; await assert.rejects(execute(tool, "brainstorming", ctx), /parallel competing/); release(); await first; assert.equal(calls, 1);
    await assert.rejects(execute(tool, "reviewing-impl", ctx), /requires predecessor phase implementation/);
    const controller = new AbortController(); controller.abort(); await assert.rejects(execute(tool, "brainstorming", ctx, controller.signal), /canceled/);
    await rm(join(root, ".pi/awf-workflows/brainstorming.md")); const before = await readFile(join(root, ".awf/metrics/efforts/reject/sessions/session.jsonl"), "utf8"); await assert.rejects(execute(tool, "brainstorming", ctx), /body is missing/); assert.equal(await readFile(join(root, ".awf/metrics/efforts/reject/sessions/session.jsonl"), "utf8"), before); await mkdir(join(root, ".pi/awf-workflows/brainstorming.md")); await assert.rejects(execute(tool, "brainstorming", ctx), /missing or unsafe/);
  } finally { await rm(root, { recursive: true, force: true }); }
});

test("provisional settlement retries custom persistence and partial ordered flush with deterministic identities", async () => {
  const root = await projectRoot(); try {
    assert.equal(PROVISIONAL_MAX_OBSERVATIONS, 256); assert.equal(PROVISIONAL_MAX_BYTES, 1024 * 1024);
    const ledger = defaultLedgerDependencies(join(root, ".pi/extensions/awf-dashboard/index.ts")); const durable = createLedgerWriter(ledger); let failAppend = true;
    const writer: any = { ...durable, append: async (event: any) => { if (event.observationId === "observation-b" && failAppend) { failAppend = false; throw new Error("partial flush"); } return durable.append(event); } };
    const persisted: any[] = []; let failCustom = true; const provisional = new ProvisionalIdentity(writer, ledger, "session", "candidate", { associate(value) { if (failCustom) { failCustom = false; throw new Error("custom entry"); } persisted.push(value); } });
    await provisional.observe("compaction_observed", { count: 1 }, undefined, "observation-a"); await provisional.observe("compaction_observed", { count: 2 }, undefined, "observation-b"); const buffered = provisional.snapshot(); assert.equal(buffered.count, 2); assert.ok(buffered.bytes > 0 && buffered.bytes < PROVISIONAL_MAX_BYTES);
    await assert.rejects(provisional.settleCandidate(), /custom entry/); assert.equal(provisional.snapshot().committed, true); assert.equal(provisional.snapshot().customPersisted, false);
    await assert.rejects(provisional.settleCandidate(), /partial flush/); assert.equal(provisional.snapshot().flushed, 1); const association = await provisional.settleCandidate(); assert.equal(association.effortId, "candidate"); assert.equal(persisted.length, 1); assert.equal(provisional.snapshot().flushed, 2);
    const stream = (await readFile(join(root, ".awf/metrics/efforts/candidate/sessions/session.jsonl"), "utf8")).trim().split("\n").map((line) => JSON.parse(line)); assert.deepEqual(stream.map((event: any) => event.kind), ["effort_created", "trajectory_started", "session_associated", "compaction_observed", "compaction_observed"]); assert.deepEqual(stream.slice(3).map((event: any) => event.observationId), ["observation-a", "observation-b"]); for (const event of stream) assert.match(event.eventId, /^provisional-event-[0-9a-f]{64}$/); for (const event of stream.slice(0, 3)) assert.match(event.idempotencyKey, /^provisional-[0-9a-f]{64}$/);
    await durable.shutdown();
  } finally { await rm(root, { recursive: true, force: true }); }
});

test("provisional bounds settle before overflow and individually oversized observations", async () => {
  for (const [limits, count] of [[{ maxObservations: 2, maxBytes: PROVISIONAL_MAX_BYTES }, 3], [{ maxObservations: PROVISIONAL_MAX_OBSERVATIONS, maxBytes: 1 }, 1]] as const) {
    const root = await projectRoot(); try { const ledger = defaultLedgerDependencies(join(root, ".pi/extensions/awf-dashboard/index.ts")); const writer = createLedgerWriter(ledger); const warnings: string[] = []; const manager = new ProvisionalIdentity(writer, ledger, "session", `candidate-${count}-${limits.maxBytes}`, { associate() {}, warn(message) { warnings.push(message); } }, limits);
      for (let index = 0; index < count; index++) await manager.observe("compaction_observed", { count: index + 1 }, undefined, `observation-${index}`);
      assert.equal(manager.snapshot().overflowCommitted, true); assert.equal(manager.snapshot().count, Math.max(0, count - 1)); assert.equal(warnings.length, 1); const stream = await readFile(join(root, `.awf/metrics/efforts/${manager.candidateId}/sessions/session.jsonl`), "utf8"); assert.equal(stream.match(/compaction_observed/g)?.length, count); await writer.shutdown();
    } finally { await rm(root, { recursive: true, force: true }); }
  }
});

test("provisional resume discards precommit candidates while graceful settlement persists and crash loss stays bounded", async () => {
  const root = await projectRoot(); try { const ledger = defaultLedgerDependencies(join(root, ".pi/extensions/awf-dashboard/index.ts")); const target = await seed(ledger, "target", "prior-session"); const writer = createLedgerWriter(ledger); const entries: any[] = []; const manager = new ProvisionalIdentity(writer, ledger, "session", "discarded-candidate", { associate(value) { entries.push(value); } }); await manager.observe("compaction_observed", { count: 1 }, undefined, "before-resume"); const resumed = await manager.resume("target"); assert.equal(resumed.trajectoryId, target.trajectoryId); assert.equal(manager.snapshot().discarded, true); assert.equal((await projectLocalLifecycle(ledger, "discarded-candidate")).state, "absent"); const targetStream = await readFile(join(root, ".awf/metrics/efforts/target/sessions/session.jsonl"), "utf8"); assert.ok(targetStream.indexOf("session_associated") < targetStream.indexOf("compaction_observed")); assert.equal(entries.length, 1);
    const graceful = new ProvisionalIdentity(writer, ledger, "graceful-session", "graceful-candidate", { associate() {} }); await graceful.observe("compaction_observed", { count: 1 }, undefined, "graceful-observation"); await graceful.graceful(); assert.equal((await projectLocalLifecycle(ledger, "graceful-candidate")).state, "discovery");
    const crashing = new ProvisionalIdentity(writer, ledger, "crash-session", "crash-candidate", { associate() {} }); await crashing.observe("compaction_observed", { count: 1 }, undefined, "crash-observation"); const lost = crashing.crashLoss(); assert.equal(lost.observations, 1); assert.ok(lost.bytes > 0 && lost.bytes <= PROVISIONAL_MAX_BYTES); assert.equal((await projectLocalLifecycle(ledger, "crash-candidate")).state, "absent"); await assert.rejects(crashing.settleCandidate(), /discarded/); await writer.shutdown();
  } finally { await rm(root, { recursive: true, force: true }); }
});

test("overflow resume durably abandons then detaches before associating without reassigning observations", async () => {
  const root = await projectRoot(); try { const ledger = defaultLedgerDependencies(join(root, ".pi/extensions/awf-dashboard/index.ts")); await seed(ledger, "resume-target", "prior-session"); const durable = createLedgerWriter(ledger); const actions: string[] = []; const writer: any = { ...durable, appendCausal: async (event: any) => { actions.push(event.kind); return durable.appendCausal(event); }, mutateLifecycle: async (request: any) => { actions.push(request.action); return durable.mutateLifecycle(request); } }; const custom: string[] = []; const manager = new ProvisionalIdentity(writer, ledger, "session", "overflow-candidate", { associate(value) { custom.push(`associate:${value.effortId}`); }, detach() { custom.push("detach"); } }, { maxObservations: 0, maxBytes: PROVISIONAL_MAX_BYTES }); await manager.observe("compaction_observed", { count: 1 }, undefined, "overflow-observation"); actions.length = 0; custom.length = 0; await manager.resume("resume-target"); assert.deepEqual(actions, ["effort_abandoned", "detach", "associate"]); assert.deepEqual(custom, ["detach", "associate:resume-target"]); const candidate = await projectLocalLifecycle(ledger, "overflow-candidate"); assert.equal(candidate.state, "abandoned"); assert.equal(candidate.associations.has("session"), false); assert.match(await readFile(join(root, ".awf/metrics/efforts/overflow-candidate/sessions/session.jsonl"), "utf8"), /overflow-observation/); assert.doesNotMatch(await readFile(join(root, ".awf/metrics/efforts/resume-target/sessions/session.jsonl"), "utf8"), /overflow-observation/); await durable.shutdown();
  } finally { await rm(root, { recursive: true, force: true }); }
});

async function completeEffort(ledger: any, effortId: string, sessionId: string) {
  await seed(ledger, effortId, sessionId); const writer = createLedgerWriter(ledger); let sequence = 0;
  const mutate = async (action: string, values: any = {}) => { const projection = await projectLocalLifecycle(ledger, effortId); const id = `complete-${++sequence}`; return writer.mutateLifecycle({ action, idempotencyKey: `${id}-key`, eventId: id, effortId, sessionId, timestamp: "2026-07-23T00:00:00Z", predecessors: projection.frontier, ...values }); };
  await mutate("start-phase", { phase: "brainstorming" }); let projection = await projectLocalLifecycle(ledger, effortId); let current: any = [...projection.openPhases.values()][0]; await mutate("transition-phase", { phase: "brainstorming", startEventId: current.startEventId, nextPhase: "implementation", outcome: "success", routeAction: "select", route: "direct" }); projection = await projectLocalLifecycle(ledger, effortId); current = [...projection.openPhases.values()][0]; await mutate("transition-phase", { phase: "implementation", startEventId: current.startEventId, nextPhase: "implementation-review", outcome: "success" }); projection = await projectLocalLifecycle(ledger, effortId); current = [...projection.openPhases.values()][0]; await mutate("transition-phase", { phase: "implementation-review", startEventId: current.startEventId, nextPhase: "retrospective", outcome: "success" }); projection = await projectLocalLifecycle(ledger, effortId); current = [...projection.openPhases.values()][0]; await mutate("finish-phase", { phase: "retrospective", startEventId: current.startEventId, outcome: "success" }); await mutate("complete"); await writer.shutdown();
}

test("queued effort replacement cancels without append, retries one persisted setup, and recovers partial settlement", async () => {
  const root = await projectRoot(); try { const ledger = defaultLedgerDependencies(join(root, ".pi/extensions/awf-dashboard/index.ts")); await seed(ledger, "replacement-target", "prior"); const h = await harness(root); const publicCommand = h.commands.get("awf-resume-effort"); const privateCommand = h.commands.get("awf-resume-effort-continue"); await assert.rejects(publicCommand.handler(" bad "), /usage/);
    const before = await readFile(join(root, ".awf/metrics/efforts/replacement-target/sessions/prior.jsonl"), "utf8"); await publicCommand.handler("replacement-target"); const firstID = h.queued.at(-1)[1]; await privateCommand.handler(firstID, { newSession: async () => ({ cancelled: true }) }); assert.equal(await readFile(join(root, ".awf/metrics/efforts/replacement-target/sessions/prior.jsonl"), "utf8"), before); await assert.rejects(privateCommand.handler(firstID, { newSession() {} }), /no matching/);
    await publicCommand.handler("replacement-target"); const retryID = h.queued.at(-1)[1]; const attempts: any[][] = []; let calls = 0; const replacement = { newSession: async (options: any) => { const entries: any[] = []; attempts.push(entries); calls++; await options.setup({ getSessionId: () => "replacement", appendCustomEntry(type: string, data: any) { entries.push({ type, data }); if (calls === 1) throw new Error("persist failed"); } }); await options.withSession(); return { cancelled: false }; } }; await privateCommand.handler(retryID, replacement); assert.deepEqual(h.queued.at(-1), ["awf-resume-effort-continue", retryID]); await privateCommand.handler(retryID, replacement); assert.equal(attempts.length, 2); assert.equal(attempts[1][0].type, ASSOCIATION_ENTRY); await assert.rejects(privateCommand.handler(retryID, replacement), /no matching/); const projection = await projectLocalLifecycle(ledger, "replacement-target"); assert.equal(projection.associations.get("replacement")?.effortId, "replacement-target"); await publicCommand.handler("replacement-target"); const cancelAfterSetupID = h.queued.at(-1)[1]; const cancelAfterSetup = { newSession: async (options: any) => { await options.setup({ getSessionId: () => "replacement", appendCustomEntry() {} }); return { cancelled: true }; } }; await privateCommand.handler(cancelAfterSetupID, cancelAfterSetup); await privateCommand.handler(cancelAfterSetupID, cancelAfterSetup); await assert.rejects(privateCommand.handler(cancelAfterSetupID, cancelAfterSetup), /no matching/);
  } finally { await rm(root, { recursive: true, force: true }); }
});

test("replacement refuses completed, abandoned, and pruned efforts until a separate reopen", async () => {
  const root = await projectRoot(); try { const ledger = defaultLedgerDependencies(join(root, ".pi/extensions/awf-dashboard/index.ts")); await completeEffort(ledger, "completed-target", "prior"); const completedManagerWriter = createLedgerWriter(ledger); const completedManager = new ProvisionalIdentity(completedManagerWriter, ledger, "replacement", "completed-candidate", { associate() {} }); await assert.rejects(completedManager.resume("completed-target"), /completed effort requires/); await completedManagerWriter.shutdown(); const completedDetach = createLedgerWriter(ledger); const completedProjection = await projectLocalLifecycle(ledger, "completed-target"); await assert.rejects(completedDetach.mutateLifecycle({ action: "detach", idempotencyKey: "completed-detach-key", eventId: "completed-detach", effortId: "completed-target", sessionId: "prior", timestamp: "2026-07-23T00:00:00Z", predecessors: completedProjection.frontier, reason: "manual" }), /illegal lifecycle source/); await completedDetach.shutdown(); await seed(ledger, "abandoned-target", "prior"); const terminal = createLedgerWriter(ledger); let abandoned = await projectLocalLifecycle(ledger, "abandoned-target"); await terminal.mutateLifecycle({ action: "abandon", idempotencyKey: "abandon-key", eventId: "abandon", effortId: "abandoned-target", sessionId: "prior", timestamp: "2026-07-23T00:00:00Z", predecessors: abandoned.frontier }); await terminal.shutdown(); const h = await harness(root); let replacements = 0; const ctx = { newSession: async () => { replacements++; return { cancelled: false }; } };
    for (const [effort, pattern] of [["completed-target", /completed effort requires awf_lifecycle reopen/], ["abandoned-target", /abandoned or pruned/], ["missing-target", /abandoned or pruned/]] as const) { await h.commands.get("awf-resume-effort").handler(effort); const id = h.queued.at(-1)[1]; await assert.rejects(h.commands.get("awf-resume-effort-continue").handler(id, ctx), pattern); } assert.equal(replacements, 0);
    const reopenWriter = createLedgerWriter(ledger); const completed = await projectLocalLifecycle(ledger, "completed-target"); await reopenWriter.mutateLifecycle({ action: "reopen", idempotencyKey: "reopen-key", eventId: "reopen", effortId: "completed-target", sessionId: "prior", timestamp: "2026-07-23T00:00:00Z", predecessors: completed.frontier, trajectoryId: "reopened-trajectory", anchorId: "reopen-anchor" }); await reopenWriter.shutdown(); await h.commands.get("awf-resume-effort").handler("completed-target"); const reopenedID = h.queued.at(-1)[1]; const entries: any[] = []; await h.commands.get("awf-resume-effort-continue").handler(reopenedID, { newSession: async (options: any) => { replacements++; await options.setup({ getSessionId: () => "replacement", appendCustomEntry: (type: string, data: any) => entries.push({ type, data }) }); return { cancelled: false }; } }); assert.equal(replacements, 1); assert.equal(entries[0].data.trajectoryId, "reopened-trajectory");
  } finally { await rm(root, { recursive: true, force: true }); }
});

test("provisional edge state and dashboard persistence callbacks are explicit and fail closed", async () => {
  const callbackEntries: any[] = []; const notices: any[] = []; const persistence = dashboardProvisionalPersistence({ appendEntry(type: string, data: any) { callbackEntries.push({ type, data }); } } as any, () => ({ ui: { notify(...args: any[]) { notices.push(args); } } })); persistence.associate({ effortId: "effort", sessionId: "session", trajectoryId: "trajectory", associationOrigin: "created" }); persistence.detach!("detach-event"); persistence.warn!("warning"); assert.deepEqual(callbackEntries.map((entry) => entry.type), [ASSOCIATION_ENTRY, "awf.telemetry.detached.v1"]); assert.deepEqual(notices, [["warning", "warning"]]); dashboardProvisionalPersistence({ appendEntry() {} } as any, () => undefined).warn!("quiet");
  const root = await projectRoot(); try { const ledger = defaultLedgerDependencies(join(root, ".pi/extensions/awf-dashboard/index.ts")); const writer = createLedgerWriter(ledger); assert.throws(() => new ProvisionalIdentity(writer, ledger, "bad/session", "candidate", { associate() {} }), /invalid provisional/); assert.throws(() => new ProvisionalIdentity(writer, ledger, "session", "bad/candidate", { associate() {} }), /invalid provisional/);
    const manager = new ProvisionalIdentity(writer, ledger, "session", "edge-candidate", { associate() {} }); await manager.observe("compaction_observed", { count: 1 }, "anchor"); await manager.settleCandidate(); await manager.observe("compaction_observed", { count: 2 }); assert.equal((await manager.graceful())?.effortId, "edge-candidate"); assert.deepEqual(manager.crashLoss(), { observations: 0, bytes: 0 }); await assert.rejects(manager.resume("bad/id"), /invalid effort/); await assert.rejects(manager.resume("edge-candidate", "bad/session"), /invalid effort/); assert.throws(() => (manager as any).remap({ observationId: "bad/id" }, { effortId: "x", sessionId: "y", trajectoryId: "z", associationOrigin: "manual" }), /invalid remapped/);
    const at = "2026-07-23T00:00:00Z"; const create: any = { version: protocolVersion, eventId: "empty-create", idempotencyKey: "empty-create-key", effortId: "no-trajectory", sessionId: "prior", timestamp: at, kind: "effort_created", predecessors: [], payload: { creationMode: "independent" } }; await writer.create({ effortId: "no-trajectory", createdAt: at, creationMode: "independent" }, create); const empty = new ProvisionalIdentity(writer, ledger, "session", "empty-candidate", { associate() {} }); await assert.rejects(empty.resume("no-trajectory"), /no active trajectory/); await assert.rejects(empty.resume("missing-effort"), /abandoned or pruned/); await seed(ledger, "edge-abandoned", "prior"); let abandonedProjection = await projectLocalLifecycle(ledger, "edge-abandoned"); await writer.mutateLifecycle({ action: "abandon", idempotencyKey: "edge-abandon-key", eventId: "edge-abandon", effortId: "edge-abandoned", sessionId: "prior", timestamp: at, predecessors: abandonedProjection.frontier }); await assert.rejects(empty.resume("edge-abandoned"), /abandoned or pruned/); await seed(ledger, "verification-target", "prior"); const noopWriter: any = { ...writer, mutateLifecycle: async () => ({ idempotent: false }) }; const verification = new ProvisionalIdentity(noopWriter, ledger, "new-session", "verification-candidate", { associate() {} }); await assert.rejects(verification.resume("verification-target"), /not durably applied/); await assert.rejects(empty.observe("not-a-kind", {}), /invalid provisional/); await writer.shutdown();
  } finally { await rm(root, { recursive: true, force: true }); }
});

test("invariant: registered provisional overflow associates the settled candidate", async () => {
  const root = await projectRoot(); try { const h = await harness(root); const ctx: any = { sessionManager: { getBranch: () => [], getSessionId: () => "overflow-session", getLeafId: () => "anchor" }, ui: {} }; await h.hooks.get("session_start")({}, ctx); for (let index = 0; index <= PROVISIONAL_MAX_OBSERVATIONS; index++) { h.hooks.get("turn_end")({ message: { model: "model", usage: { input: index, output: 1, cacheRead: 0, cacheWrite: 0, cost: { total: 0 } } } }, ctx); await new Promise((done) => setImmediate(done)); } for (let attempt = 0; attempt < 2000 && !h.entries.some((entry) => entry.type === ASSOCIATION_ENTRY); attempt++) await new Promise((done) => setTimeout(done, 5)); assert.equal(h.entries.some((entry) => entry.type === ASSOCIATION_ENTRY), true); await h.hooks.get("session_shutdown")({}, ctx);
  } finally { await rm(root, { recursive: true, force: true }); }
});

test("invariant: workflow router settles provisional identity before loading", async () => {
  const root = await projectRoot(); try { await bodies(root, ["brainstorming"]); const h = await harness(root); const ctx: any = { sessionManager: { getBranch: () => [], getSessionId: () => "session", getLeafId: () => "anchor", getLeafEntry: context({ sessionId: "session" }).sessionManager.getLeafEntry }, ui: {} }; await h.hooks.get("session_start")({}, ctx); const loaded = await execute(h.tools.get("awf_workflow"), "brainstorming", ctx); assert.equal(loaded.details.durable, true); assert.equal(h.entries.some((entry) => entry.type === ASSOCIATION_ENTRY), true);
    await h.commands.get("awf-resume-effort").handler("uuid-1"); await assert.rejects(h.commands.get("awf-resume-effort").handler("uuid-1"), /already pending/); const queuedID = h.queued.at(-1)[1]; const invalidReplacement = { newSession: async (options: any) => { await options.setup({ getSessionId: () => "bad/session", appendCustomEntry() {} }); } }; await h.commands.get("awf-resume-effort-continue").handler(queuedID, invalidReplacement); await assert.rejects(h.commands.get("awf-resume-effort-continue").handler(queuedID, invalidReplacement), /replacement session identity/); h.pi.queueCommand = () => { throw new Error("queue failed"); }; await assert.rejects(h.commands.get("awf-resume-effort").handler("uuid-1"), /queue failed/); await h.hooks.get("session_shutdown")({}, ctx);
  } finally { await rm(root, { recursive: true, force: true }); }
});
