package plan_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/hypnotox/agentic-workflows/internal/plan"
)

// TestParseDirParsesFrontmatterAndSkipsNonPlans covers the happy path (a plan
// with frontmatter, a frontmatter-less plan) and the FilenameRe exclusions
// (template.md, README.md, and a non-plan .md are skipped).
func TestParseDirParsesFrontmatterAndSkipsNonPlans(t *testing.T) {
	dir := t.TempDir()
	write := func(name, content string) {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(content), 0o644); err != nil {
			t.Fatalf("write %s: %v", name, err)
		}
	}
	write("2026-07-12-with-frontmatter.md", "---\ndate: 2026-07-12\nadrs: [97, 98]\nstatus: Proposed\n---\n# Plan: With Frontmatter\n")
	write("2026-06-24-legacy.md", "# Plan: Legacy\n\nNo frontmatter here.\n")
	write("template.md", "---\ndate: YYYY-MM-DD\n---\n# Plan: Title\n")
	write("README.md", "# Plans\n")
	write("notes.md", "# scratch\n")

	plans, err := plan.ParseDir(dir)
	if err != nil {
		t.Fatalf("ParseDir: %v", err)
	}
	byName := map[string]plan.Plan{}
	for _, pl := range plans {
		byName[pl.Filename] = pl
	}
	if len(byName) != 2 {
		t.Fatalf("expected 2 plans (template.md, README.md, notes.md skipped), got %d: %v", len(byName), plans)
	}

	fm := byName["2026-07-12-with-frontmatter.md"]
	if !fm.HasFrontmatter {
		t.Error("expected HasFrontmatter true for the frontmatter plan")
	}
	if fm.Date != "2026-07-12" {
		t.Errorf("Date = %q, want 2026-07-12", fm.Date)
	}
	if fm.Status != "Proposed" {
		t.Errorf("Status = %q, want Proposed", fm.Status)
	}
	if len(fm.ADRs) != 2 || fm.ADRs[0] != 97 || fm.ADRs[1] != 98 {
		t.Errorf("ADRs = %v, want [97 98]", fm.ADRs)
	}

	legacy := byName["2026-06-24-legacy.md"]
	if legacy.HasFrontmatter {
		t.Error("expected HasFrontmatter false for the frontmatter-less plan")
	}
}

// TestParseDirGlobError exercises the glob-pattern failure path: a directory
// whose name contains an unterminated "[" yields an ErrBadPattern from Glob.
func TestParseDirGlobError(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "bad[")
	if err := os.Mkdir(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	if _, err := plan.ParseDir(dir); err == nil {
		t.Fatal("expected glob error for malformed pattern, got nil")
	}
}

// TestParseDirReadError exercises the os.ReadFile failure path: a directory
// squatting on a path that matches the plan filename pattern cannot be read as
// a file.
func TestParseDirReadError(t *testing.T) {
	dir := t.TempDir()
	if err := os.Mkdir(filepath.Join(dir, "2026-07-12-squatter.md"), 0o755); err != nil {
		t.Fatal(err)
	}
	if _, err := plan.ParseDir(dir); err == nil {
		t.Fatal("expected read error for directory in file's place, got nil")
	}
}

// TestParseDirParseError exercises the frontmatter parse failure path:
// malformed YAML makes frontmatter.Parse return an error.
func TestParseDirParseError(t *testing.T) {
	dir := t.TempDir()
	content := "---\nstatus: [unterminated\n---\n# Plan: Broken\n"
	if err := os.WriteFile(filepath.Join(dir, "2026-07-12-broken.md"), []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := plan.ParseDir(dir); err == nil {
		t.Fatal("expected parse error for malformed frontmatter, got nil")
	}
}

// swapNow overrides the plan package's now seam for the duration of a test.
func swapNow(t *testing.T, fn func() time.Time) {
	t.Helper()
	orig := plan.SetNowForTest(fn)
	t.Cleanup(func() { plan.SetNowForTest(orig) })
}

func fixedNow() time.Time { return time.Date(2026, 7, 12, 0, 0, 0, 0, time.UTC) }

// planTemplateFixture mirrors the shape NewFile expects: a rendered template
// with marker comments, the date placeholder, and the title heading.
const planTemplateFixture = `---
date: YYYY-MM-DD
adrs: []
status: Proposed
---
<!-- GENERATED by awf — do not edit; change .awf/ and run ` + "`awf sync`" + ` -->
# Plan: Title

<!-- awf:edit positioning — default -->
Fixture body.
`

func writePlanTemplate(t *testing.T, dir string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(dir, "template.md"), []byte(planTemplateFixture), 0o644); err != nil {
		t.Fatal(err)
	}
}

func TestNewFileHappyPath(t *testing.T) {
	dir := t.TempDir()
	writePlanTemplate(t, dir)
	swapNow(t, fixedNow)

	path, err := plan.NewFile(dir, "My Cool Plan")
	if err != nil {
		t.Fatalf("NewFile: %v", err)
	}
	want := filepath.Join(dir, "2026-07-12-my-cool-plan.md")
	// invariant: plan-new-unnumbered
	if path != want {
		t.Errorf("NewFile path = %q, want %q", path, want)
	}
	body, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read created file: %v", err)
	}
	s := string(body)
	if strings.Contains(s, "GENERATED by awf") || strings.Contains(s, "awf:edit") {
		t.Errorf("marker comment survived: %q", s)
	}
	if !strings.Contains(s, "# Plan: My Cool Plan") {
		t.Errorf("heading not filled in: %q", s)
	}
	if !strings.Contains(s, "date: 2026-07-12") {
		t.Errorf("date not filled in: %q", s)
	}
}

func TestNewFileRefusesOverwrite(t *testing.T) {
	dir := t.TempDir()
	writePlanTemplate(t, dir)
	swapNow(t, fixedNow)
	if _, err := plan.NewFile(dir, "Same Plan"); err != nil {
		t.Fatalf("first NewFile: %v", err)
	}
	if _, err := plan.NewFile(dir, "Same Plan"); err == nil {
		t.Fatal("expected overwrite refusal on same-day same-title plan, got nil")
	}
}

func TestNewFileRejectsUnusableTitle(t *testing.T) {
	dir := t.TempDir()
	writePlanTemplate(t, dir)
	if _, err := plan.NewFile(dir, "!!! ???"); err == nil {
		t.Fatal("expected error for a title with no usable characters, got nil")
	}
}

func TestNewFileErrorsOnMissingTemplate(t *testing.T) {
	dir := t.TempDir() // no template.md written
	swapNow(t, fixedNow)
	if _, err := plan.NewFile(dir, "No Template"); err == nil {
		t.Fatal("expected error when template.md is absent, got nil")
	}
}

func TestNewFileErrorsOnDriftedTemplate(t *testing.T) {
	dir := t.TempDir()
	// A template missing the date: placeholder trips replaceOnce.
	if err := os.WriteFile(filepath.Join(dir, "template.md"), []byte("---\nstatus: Proposed\n---\n# Plan: Title\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	swapNow(t, fixedNow)
	if _, err := plan.NewFile(dir, "Drifted"); err == nil {
		t.Fatal("expected error for template missing the date: placeholder, got nil")
	}
}

func TestNewFileErrorsOnMissingTitlePlaceholder(t *testing.T) {
	dir := t.TempDir()
	// Has date: but no "# Plan: Title" heading — the second replaceOnce trips.
	if err := os.WriteFile(filepath.Join(dir, "template.md"), []byte("---\ndate: YYYY-MM-DD\n---\n# Wrong Heading\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	swapNow(t, fixedNow)
	if _, err := plan.NewFile(dir, "No Heading"); err == nil {
		t.Fatal("expected error for template missing the # Plan: Title heading, got nil")
	}
}
