// GENERATED by awf: do not edit; change .awf/ and run `awf render`
// @ts-nocheck
import type { RunRequest } from "./runner.ts";

export const PREFERENCE_ROLES = ["grounding", "exploration", "review", "implementation"] as const;
export const PREFERENCE_TIERS = ["small", "standard", "large"] as const;
export const PREFERENCE_FIELDS = ["default", ...PREFERENCE_ROLES, ...PREFERENCE_TIERS] as const;
export type PreferenceRole = (typeof PREFERENCE_ROLES)[number];
export type PreferenceTier = (typeof PREFERENCE_TIERS)[number];
export type PreferenceField = (typeof PREFERENCE_FIELDS)[number];
export type SourceScope = "global" | "project";
export type SourceReason = "read-error" | "malformed-json" | "non-object" | "unknown-key";
export type FieldReason = "malformed" | "overlong" | "unregistered" | "unauthenticated" | "unavailable";
export type InvalidState = { kind: "source"; scope: SourceScope; reason: SourceReason } | { kind: "field"; scope: SourceScope; field: PreferenceField; reason: FieldReason };
export interface SubagentModelPreferences { default?: string; grounding?: string; exploration?: string; review?: string; implementation?: string; small?: string; standard?: string; large?: string; }
export interface PreferenceSourceState { path: string; scope: SourceScope; values: SubagentModelPreferences; invalid: InvalidState[]; }
export interface EffectivePreferenceState { global: PreferenceSourceState; project: PreferenceSourceState; effective: Partial<Record<PreferenceField, { reference: string; scope: SourceScope }>>; missing: PreferenceField[]; invalid: InvalidState[]; blocked: boolean; errors: string[]; }
export const RECOMMENDED_PRESET: Required<SubagentModelPreferences> = { default: "openai-codex/gpt-5.6-terra", grounding: "openai-codex/gpt-5.6-sol", exploration: "openai-codex/gpt-5.6-luna", review: "openai-codex/gpt-5.6-sol", implementation: "openai-codex/gpt-5.6-terra", small: "openai-codex/gpt-5.6-luna", standard: "openai-codex/gpt-5.6-terra", large: "openai-codex/gpt-5.6-sol" };
const roles: Record<RunRequest["role"], PreferenceRole> = { grounding: "grounding", explore: "exploration", review: "review", implement: "implementation" };
const sourceOrder: SourceReason[] = ["read-error", "malformed-json", "non-object", "unknown-key"];
export function parseExactModelReference(value: unknown): { provider: string; id: string } | { reason: "malformed" | "overlong" } { if (typeof value !== "string") return { reason: "malformed" }; if (Array.from(value).length > 256) return { reason: "overlong" }; if (value === "default" || value === "auto" || value === "inherit parent") return { reason: "malformed" }; const slash = value.indexOf("/"); return value.length < 3 || slash <= 0 || slash === value.length - 1 || /\s/.test(value) ? { reason: "malformed" } : { provider: value.slice(0, slash), id: value.slice(slash + 1) }; }
function invalidText(value: InvalidState): string { return value.kind === "source" ? `${value.scope}:source:${value.reason}` : `${value.scope}:${value.field}:${value.reason}`; }
export function buildRoutingCard(state: EffectivePreferenceState): string {
 const effective = (field: PreferenceField) => state.effective[field]?.reference ?? "missing";
 const role = (field: PreferenceRole) => effective(field);
 const missing = state.missing.length ? state.missing.join(", ") : "none";
 const invalid = state.invalid.length ? state.invalid.map(invalidText).join("; ") : "none";
 const lines = ["[awf subagent routing]", `default: ${effective("default")}`, `roles: grounding=${role("grounding")}; exploration=${role("exploration")}; review=${role("review")}; implementation=${role("implementation")}`, `tiers: small=${effective("small")}; standard=${effective("standard")}; large=${effective("large")}`, `missing: ${missing}`, `invalid: ${invalid}`];
 if (invalid !== "none") lines.push("repair: Run /awf-subagent-models; omit model only after invalid preferences are repaired.");
 lines.push("selection: omit model for the role default; otherwise override deliberately with the selected tier's exact provider/model-id.");
 const card = lines.join("\n");
 return Buffer.byteLength(card, "utf8") <= 4096 ? card : "[awf subagent routing]\nstate: unavailable (routing card exceeded 4096 UTF-8 bytes)\nrepair: Run /awf-subagent-models and retry; implicit routing remains strict.";
}
export const ROUTING_CARD_OVERFLOW_WARNING = "awf subagent routing card exceeded 4096 UTF-8 bytes; injected a failure card. Run /awf-subagent-models and retry.";
