// GENERATED by awf: do not edit; change .awf/ and run `awf sync`
import { spawn as nodeSpawn } from "node:child_process";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { basename, join } from "node:path";

export type Role = "explore" | "review" | "implement";
export type ChildSignal = "SIGTERM" | "SIGKILL";
export type ThinkingLevel = "off" | "minimal" | "low" | "medium" | "high" | "xhigh" | "max";

export const MAX_OUTPUT_BYTES = 50 * 1024;
export const MAX_OUTPUT_LINES = 2000;
export const MAX_STDERR_BYTES = 50 * 1024;
export const MAX_SUMMARIES = 20;
export const MAX_SUMMARY_BYTES = 2 * 1024;
export const KILL_DELAY_MS = 5000;

export interface SpawnedProcess {
  stdout: NodeJS.ReadableStream;
  stderr: NodeJS.ReadableStream;
  once(event: "close", listener: (code: number | null) => void): this;
  once(event: "error", listener: (error: Error) => void): this;
  kill(signal: ChildSignal): boolean;
}

export interface SpawnOptions {
  cwd: string;
  shell: false;
  stdio: ["ignore", "pipe", "pipe"];
}

export interface RunnerDependencies {
  spawn(command: string, args: readonly string[], options: SpawnOptions): SpawnedProcess;
  mkdtemp(prefix: string): Promise<string>;
  writeFile(path: string, content: string, options: { encoding: "utf8"; mode: number }): Promise<void>;
  rm(path: string, options: { recursive: true; force: true }): Promise<void>;
  setTimer(callback: () => void, delayMs: number): ReturnType<typeof setTimeout>;
  clearTimer(timer: ReturnType<typeof setTimeout>): void;
  argv: readonly string[];
  execPath: string;
  tempRoot: string;
}

export interface RunRequest {
  role: Role;
  task: string;
  cwd: string;
  model: { provider: string; id: string };
  thinkingLevel: ThinkingLevel;
  tools: readonly string[];
  systemPrompt: string;
  signal?: AbortSignal;
  onUpdate?: (update: RunUpdate) => void;
}

export interface RunUpdate { text: string; summaries: readonly EventSummary[]; }
export interface EventSummary { kind: "text" | "tool" | "error"; text: string; }
export interface Usage { input: number; output: number; cacheRead: number; cacheWrite: number; cost: number; turns: number; }
export interface RunResult { output: string; stderr: string; summaries: readonly EventSummary[]; usage: Usage; model?: string; stopReason?: string; }
export interface Runner { run(request: RunRequest): Promise<RunResult>; }

const emptyUsage = (): Usage => ({ input: 0, output: 0, cacheRead: 0, cacheWrite: 0, cost: 0, turns: 0 });

function utf8Prefix(value: string, maximum: number): string {
  if (Buffer.byteLength(value, "utf8") <= maximum) return value;
  let end = Math.min(value.length, maximum);
  while (end > 0 && Buffer.byteLength(value.slice(0, end), "utf8") > maximum) end--;
  return value.slice(0, end);
}

export function truncateOutput(value: string): string {
  const lines = value.split("\n");
  const lineLimited = lines.length > MAX_OUTPUT_LINES ? lines.slice(0, MAX_OUTPUT_LINES).join("\n") : value;
  const content = utf8Prefix(lineLimited, MAX_OUTPUT_BYTES);
  if (content === value) return value;
  const omittedBytes = Buffer.byteLength(value, "utf8") - Buffer.byteLength(content, "utf8");
  const omittedLines = Math.max(0, lines.length - content.split("\n").length);
  return `${content}\n\n[Output truncated: ${omittedBytes} bytes and ${omittedLines} lines omitted]`;
}

export function truncateStderr(value: string): string {
  const total = Buffer.byteLength(value, "utf8");
  if (total <= MAX_STDERR_BYTES) return value;
  let start = Math.max(0, value.length - MAX_STDERR_BYTES);
  while (start < value.length && Buffer.byteLength(value.slice(start), "utf8") > MAX_STDERR_BYTES) start++;
  return `[stderr truncated: ${total - Buffer.byteLength(value.slice(start), "utf8")} bytes omitted]\n${value.slice(start)}`;
}

function addSummary(summaries: EventSummary[], summary: EventSummary): void {
  const text = utf8Prefix(summary.text, MAX_SUMMARY_BYTES);
  summaries.push({ ...summary, text: text === summary.text ? text : `${text}\n[summary truncated]` });
  if (summaries.length > MAX_SUMMARIES) summaries.splice(0, summaries.length - MAX_SUMMARIES);
}

function finalText(message: any): string {
  if (message?.role !== "assistant" || !Array.isArray(message.content)) return "";
  return message.content.filter((part: any) => part?.type === "text").map((part: any) => String(part.text ?? "")).join("\n");
}

export function resolvePiInvocation(argv: readonly string[], execPath: string): { command: string; args: string[] } {
  const script = argv[1];
  if (script && !script.startsWith("/$bunfs/root/") && !script.startsWith("node:")) {
    return { command: execPath, args: [script] };
  }
  const executable = basename(execPath).toLowerCase();
  return /^(node|bun)(\.exe)?$/.test(executable)
    ? { command: "pi", args: [] }
    : { command: execPath, args: [] };
}

export const productionRunnerDependencies: RunnerDependencies = {
  spawn: (command, args, options) => nodeSpawn(command, args, options) as SpawnedProcess,
  mkdtemp,
  writeFile,
  rm,
  setTimer: setTimeout,
  clearTimer: clearTimeout,
  argv: process.argv,
  execPath: process.execPath,
  tempRoot: tmpdir(),
};

export function createRunner(deps: RunnerDependencies): Runner {
  return {
    async run(request: RunRequest): Promise<RunResult> {
      if (request.signal?.aborted) throw new Error("Subagent was aborted before start");
      const directory = await deps.mkdtemp(join(deps.tempRoot, "awf-pi-subagent-"));
      const promptPath = join(directory, `${request.role}.md`);
      await deps.writeFile(promptPath, request.systemPrompt, { encoding: "utf8", mode: 0o600 });
      const invocation = resolvePiInvocation(deps.argv, deps.execPath);
      const args = [...invocation.args, "--mode", "json", "-p", "--no-session",
        "--model", `${request.model.provider}/${request.model.id}`,
        "--thinking", request.thinkingLevel,
        "--tools", request.tools.join(","),
        "--append-system-prompt", promptPath,
        `Task: ${request.task}`];
      const summaries: EventSummary[] = [];
      const usage = emptyUsage();
      let output = "";
      let stderr = "";
      let model: string | undefined;
      let stopReason: string | undefined;
      let buffer = "";
      let closed = false;
      let timer: ReturnType<typeof setTimeout> | undefined;
      let abortListener: (() => void) | undefined;

      try {
        const result = await new Promise<RunResult>((resolve, reject) => {
          const child = deps.spawn(invocation.command, args, { cwd: request.cwd, shell: false, stdio: ["ignore", "pipe", "pipe"] });
          let settled = false;
          const finish = (error?: Error): void => {
            if (settled) return;
            settled = true;
            if (timer !== undefined) deps.clearTimer(timer);
            if (request.signal && abortListener) request.signal.removeEventListener("abort", abortListener);
            if (error) reject(error);
            else resolve({ output: truncateOutput(output || "(no output)"), stderr: truncateStderr(stderr), summaries: [...summaries], usage, model, stopReason });
          };
          const processEvent = (line: string): void => {
            if (!line.trim()) return;
            let event: any;
            try { event = JSON.parse(line); }
            catch {
              child.kill("SIGTERM");
              finish(new Error(`Malformed child event: ${truncateOutput(line)}`));
              return;
            }
            if (event.type === "message_end" && event.message?.role === "assistant") {
              const text = finalText(event.message);
              if (text) { output = text; addSummary(summaries, { kind: "text", text }); }
              const current = event.message.usage;
              usage.input += current?.input ?? 0;
              usage.output += current?.output ?? 0;
              usage.cacheRead += current?.cacheRead ?? 0;
              usage.cacheWrite += current?.cacheWrite ?? 0;
              usage.cost += current?.cost?.total ?? 0;
              usage.turns++;
              /* node:coverage ignore next -- defensive fallback; child assistant messages normally name their model */
              model = event.message.model ?? model;
              /* node:coverage ignore next -- defensive fallback; child assistant messages normally carry a stop reason */
              stopReason = event.message.stopReason ?? stopReason;
            }
            /* node:coverage ignore next -- V8/tsx reports the tested false edge as a zero-width branch */
            if (event.type === "tool_execution_start") {
              addSummary(summaries, { kind: "tool", text: `${event.toolName ?? "tool"} ${JSON.stringify(event.args ?? {})}` });
            }
            request.onUpdate?.({ text: truncateOutput(output || "(running...)"), summaries: [...summaries] });
          };
          child.stdout.on("data", (chunk: Buffer | string) => {
            buffer += chunk.toString();
            const lines = buffer.split("\n");
            buffer = lines.pop() as string;
            for (const line of lines) processEvent(line);
          });
          child.stderr.on("data", (chunk: Buffer | string) => { stderr = truncateStderr(stderr + chunk.toString()); });
          child.once("error", (error) => finish(error));
          child.once("close", (code) => {
            closed = true;
            if (buffer.trim()) processEvent(buffer);
            if (code !== 0) finish(new Error(`Subagent exited ${code}: ${truncateStderr(stderr) || "no diagnostics"}`));
            else if (stopReason === "error" || stopReason === "aborted") finish(new Error(`Subagent ${stopReason}: ${truncateOutput(output)}`));
            else finish();
          });
          abortListener = () => {
            if (closed) return;
            child.kill("SIGTERM");
            timer = deps.setTimer(() => { if (!closed) child.kill("SIGKILL"); }, KILL_DELAY_MS);
          };
          request.signal?.addEventListener("abort", abortListener, { once: true });
          if (request.signal?.aborted) abortListener();
        });
        return result;
      } finally {
        await deps.rm(directory, { recursive: true, force: true });
      }
    },
  };
}
