package projector

import (
	"bytes"
	"embed"
	"io/fs"
	"sort"
	"strings"
	"text/template"

	awfdocs "github.com/hypnotox/agentic-workflows/internal/docs"
)

const (
	markdownMarker = "<!-- GENERATED by awf; remove this comment to take ownership -->"
	textMarker     = "# GENERATED by awf; remove this comment to take ownership"
	// VersionPath is reserved AWF-owned renderer metadata, not configuration.
	VersionPath = ".awf/VERSION"
)

//go:embed VERSION
var versionFile string

//go:embed templates/*.tmpl
var templateFiles embed.FS

var outputTemplates = template.Must(template.ParseFS(templateFiles, "templates/*.tmpl"))

// Version is the release identity embedded in this binary.
var Version = strings.TrimSpace(versionFile)

// Output is one complete generated file.
type Output struct {
	Path  string
	Bytes []byte
	Mode  fs.FileMode
}

// Build returns the fixed output set from embedded AWF content, independently of
// repository instructions and topics.
func Build() []Output {
	data := templateData{Version: Version, Repository: true}
	outputs := []Output{
		{Path: ".awf/.gitignore", Bytes: renderTemplate("gitignore.tmpl", data), Mode: 0o644},
		{Path: VersionPath, Bytes: renderTemplate("VERSION.tmpl", data), Mode: 0o644},
		{Path: "awf", Bytes: renderTemplate("awf.tmpl", data), Mode: 0o755},
		{Path: ".awf/bootstrap.sh", Bytes: renderTemplate("downloader.sh.tmpl", data), Mode: 0o755},
	}
	for _, workflow := range []string{"topics", "effort", "changes", "adr", "completion"} {
		body, ok := awfdocs.Page(workflow)
		if !ok {
			panic("missing embedded workflow: " + workflow)
		}
		skill := renderTemplate("awf-"+workflow+".tmpl", templateData{Body: string(body)})
		for _, harness := range []string{".pi", ".claude"} {
			outputs = append(outputs, Output{
				Path: harness + "/skills/awf-" + workflow + "/SKILL.md", Bytes: skill, Mode: 0o644,
			})
		}
	}
	sort.Slice(outputs, func(i, j int) bool { return outputs[i].Path < outputs[j].Path })
	return outputs
}

type templateData struct {
	Version    string
	Repository bool
	Body       string
}

func renderTemplate(name string, data templateData) []byte {
	var output bytes.Buffer
	if err := outputTemplates.ExecuteTemplate(&output, name, data); err != nil {
		panic(err)
	}
	return output.Bytes()
}

// PublicLauncher returns the self-contained launcher for this exact release.
func PublicLauncher() []byte {
	return renderTemplate("downloader.sh.tmpl", templateData{Version: Version})
}
