package projector

import (
	"bytes"
	_ "embed"
	"io/fs"
	"sort"
	"strings"
	"text/template"
)

const (
	markdownMarker = "<!-- GENERATED by awf; remove this comment to take ownership -->"
	textMarker     = "# GENERATED by awf; remove this comment to take ownership"
)

//go:embed VERSION
var versionFile string

//go:embed downloader.sh
var downloaderTemplate string

//go:embed templates/AGENTS.md
var agentGuideTemplateSource string

var agentGuideTemplate = template.Must(template.New("AGENTS.md").Parse(agentGuideTemplateSource))

// Version is the release identity embedded in this binary.
var Version = strings.TrimSpace(versionFile)

// Output is one complete generated file.
type Output struct {
	Path       string
	Bytes      []byte
	Mode       fs.FileMode
	markerless bool
}

// Build returns the complete fixed output set for sources.
func Build(sources SourceTree) []Output {
	agents := renderAgentGuide(sources.Project.Body)

	topicSkill := skillDocument("awf-topics", "Find and maintain path-routed current project guidance.",
		"# AWF topics\n\n"+
			"When path-routed repository context becomes relevant, run the repository's AWF command with `docs topics`, read the guide, and follow it for the task. Reuse the guide during the task; do not reload it before every action.\n")
	effortSkill := skillDocument("awf-effort", "Use effort memory, intents, specifications, plans, ADRs, and implementation worktrees; complete or integrate work.",
		"# AWF efforts\n\n"+
			"When work needs continuity across stages, sessions, or handoffs, when an implementation worktree, intent, specification, plan, or ADR becomes relevant, or before completing or integrating implementation work, run the repository's AWF command with `docs effort`, read the guide, and follow it for the task. Reuse the guide during the task; do not load it at every session start or before every action.\n")

	outputs := []Output{
		{Path: "AGENTS.md", Bytes: []byte(agents), Mode: 0o644},
		{Path: "CLAUDE.md", Bytes: []byte("@AGENTS.md"), Mode: 0o644, markerless: true},
		{Path: ".pi/skills/awf-topics/SKILL.md", Bytes: []byte(topicSkill), Mode: 0o644},
		{Path: ".claude/skills/awf-topics/SKILL.md", Bytes: []byte(topicSkill), Mode: 0o644},
		{Path: ".pi/skills/awf-effort/SKILL.md", Bytes: []byte(effortSkill), Mode: 0o644},
		{Path: ".claude/skills/awf-effort/SKILL.md", Bytes: []byte(effortSkill), Mode: 0o644},
		{Path: ".awf/.gitignore", Bytes: []byte(textMarker + "\n/efforts/\n/worktrees/\n/effort-archive/\n"), Mode: 0o644},
		{Path: "awf", Bytes: []byte(withScriptMarker(wrapperScript)), Mode: 0o755},
		{Path: ".awf/bootstrap.sh", Bytes: []byte(withScriptMarker(repositoryBootstrap())), Mode: 0o755},
	}
	sort.Slice(outputs, func(i, j int) bool { return outputs[i].Path < outputs[j].Path })
	return outputs
}

type agentGuideData struct {
	Marker      string
	TopicsPath  string
	ProjectBody string
}

func renderAgentGuide(projectBody []byte) string {
	var agents bytes.Buffer
	if err := agentGuideTemplate.Execute(&agents, agentGuideData{
		Marker:      markdownMarker,
		TopicsPath:  TopicsPath,
		ProjectBody: string(projectBody),
	}); err != nil {
		panic(err)
	}
	return agents.String()
}

func skillDocument(name, description, body string) string {
	return "---\nname: " + name + "\ndescription: " + description + "\n---\n" + markdownMarker + "\n\n" + body
}

func withScriptMarker(script string) string {
	const shebang = "#!/usr/bin/env bash\n"
	return shebang + textMarker + "\n" + strings.TrimPrefix(script, shebang)
}

const wrapperScript = `#!/usr/bin/env bash
set -euo pipefail

binary="$(bash .awf/bootstrap.sh)"
exec "$binary" "$@"
`

func repositoryBootstrap() string {
	return renderDownloader(
		"Fetch a pinned AWF release, verify it, cache it, and print its binary path.",
		`AWF_VERSION="${AWF_VERSION:-`+Version+`}"`,
		`printf '%s\n' "$binary"`,
	)
}

// PublicLauncher returns the self-contained launcher for this exact release.
func PublicLauncher() []byte {
	return []byte(renderDownloader(
		"Fetch this AWF release, verify it, cache it, and run the requested command.",
		`AWF_VERSION="`+Version+`"`,
		`exec "$binary" "$@"`,
	))
}

func renderDownloader(purpose, versionAssignment, finalAction string) string {
	return strings.NewReplacer(
		"@@PURPOSE@@", purpose,
		"@@VERSION_ASSIGNMENT@@", versionAssignment,
		"@@FINAL_ACTION@@", finalAction,
	).Replace(downloaderTemplate)
}
