package projector

import (
	_ "embed"
	"io/fs"
	"sort"
	"strings"
)

const (
	markdownMarker = "<!-- GENERATED by awf; remove this comment to take ownership -->"
	textMarker     = "# GENERATED by awf; remove this comment to take ownership"
)

//go:embed VERSION
var versionFile string

// Version is the release identity embedded in this binary.
var Version = strings.TrimSpace(versionFile)

// Output is one complete generated file.
type Output struct {
	Path  string
	Bytes []byte
	Mode  fs.FileMode
}

// Build returns the complete fixed output set for sources.
func Build(sources SourceTree) []Output {
	agents := markdownMarker + "\n" +
		"# Agent guide\n\n" +
		"This file is generated by AWF. Edit `.awf/project.md` and `.awf/topics/**/*.md`, then run this repository's documented render and check commands.\n\n" +
		"Use the repository's AWF command with `resolve <path>...` to find relevant current guidance before changing a path. Use the generated `awf-topics` and `awf-effort` skills for their respective workflows.\n\n" +
		"If available, use `agentic-artifact-design` for substantial prose work and `agentic-code-design` for structural code judgment.\n" +
		string(sources.Project.Body)

	topicSkill := skillDocument("awf-topics", "Find and maintain path-routed current project guidance.",
		"# AWF topics\n\n"+
			"Before changing repository paths, run the repository's documented AWF command with `resolve <path>...` and read every returned `.awf/topics/...md` source. Keep affected topic guidance current with the implementation.\n\n"+
			"A topic is ordinary Markdown with positive `paths` patterns in its frontmatter. AWF does not validate or otherwise interpret the body.\n")
	effortSkill := skillDocument("awf-effort", "Keep lightweight local continuity for an active effort.",
		"# AWF efforts\n\n"+
			"Use the repository's documented AWF command with `effort new <slug>`, `effort list`, `effort show <slug>`, and `effort finish <slug>`. Keep the active outcome, current state, decisions, and next action in `.awf/efforts/<slug>/memory.md`. Finishing moves the whole resident to `.awf/effort-archive/<slug>` without replacing an existing archive.\n\n"+
			"AWF does not manage Git. When isolation helps, create a native worktree yourself from the primary checkout:\n\n"+
			"```sh\n"+
			"git worktree add -b awf/<slug> .awf/worktrees/<slug>\n"+
			"```\n\n"+
			"The effort memory remains in the primary checkout. After integrating through the repository's normal Git workflow, clean up explicitly:\n\n"+
			"```sh\n"+
			"git worktree remove .awf/worktrees/<slug>\n"+
			"git branch -d awf/<slug>\n"+
			"```\n\n"+
			"Then finish the AWF effort.\n")

	bootstrap := strings.ReplaceAll(bootstrapScript, "@@VERSION@@", Version)
	outputs := []Output{
		{Path: "AGENTS.md", Bytes: []byte(agents), Mode: 0o644},
		{Path: "CLAUDE.md", Bytes: []byte(markdownMarker + "\n# Claude guidance\n\nFollow [`AGENTS.md`](AGENTS.md).\n"), Mode: 0o644},
		{Path: ".pi/skills/awf-topics/SKILL.md", Bytes: []byte(topicSkill), Mode: 0o644},
		{Path: ".claude/skills/awf-topics/SKILL.md", Bytes: []byte(topicSkill), Mode: 0o644},
		{Path: ".pi/skills/awf-effort/SKILL.md", Bytes: []byte(effortSkill), Mode: 0o644},
		{Path: ".claude/skills/awf-effort/SKILL.md", Bytes: []byte(effortSkill), Mode: 0o644},
		{Path: ".awf/.gitignore", Bytes: []byte(textMarker + "\n/efforts/\n/worktrees/\n/effort-archive/\n"), Mode: 0o644},
		{Path: "awf", Bytes: []byte(withScriptMarker(wrapperScript)), Mode: 0o755},
		{Path: ".awf/bootstrap.sh", Bytes: []byte(withScriptMarker(bootstrap)), Mode: 0o755},
	}
	sort.Slice(outputs, func(i, j int) bool { return outputs[i].Path < outputs[j].Path })
	return outputs
}

func skillDocument(name, description, body string) string {
	return "---\nname: " + name + "\ndescription: " + description + "\n---\n" + markdownMarker + "\n\n" + body
}

func withScriptMarker(script string) string {
	const shebang = "#!/usr/bin/env bash\n"
	return shebang + textMarker + "\n" + strings.TrimPrefix(script, shebang)
}

const wrapperScript = `#!/usr/bin/env bash
set -euo pipefail

binary="$(bash .awf/bootstrap.sh)"
exec "$binary" "$@"
`

const bootstrapScript = `#!/usr/bin/env bash
# Fetch a pinned AWF release, verify it, cache it, and print its binary path.
set -euo pipefail

AWF_VERSION="${AWF_VERSION:-@@VERSION@@}"
repo="hypnotox/agentic-workflows"
cache_dir="${XDG_CACHE_HOME:-$HOME/.cache}/awf/${AWF_VERSION}"
binary="${cache_dir}/awf"

if [ -x "$binary" ]; then
  printf '%s\n' "$binary"
  exit 0
fi

os="$(uname -s | tr '[:upper:]' '[:lower:]')"
arch="$(uname -m)"
case "$arch" in
  x86_64|amd64) arch="amd64" ;;
  arm64|aarch64) arch="arm64" ;;
  *) echo "awf bootstrap: unsupported architecture: $arch" >&2; exit 1 ;;
esac
case "$os" in
  linux|darwin) ;;
  *) echo "awf bootstrap: unsupported operating system: $os" >&2; exit 1 ;;
esac

asset="awf_${AWF_VERSION}_${os}_${arch}.tar.gz"
base="https://github.com/${repo}/releases/download/v${AWF_VERSION}"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

curl -fsSL "${base}/${asset}" -o "${tmp}/${asset}"
curl -fsSL "${base}/checksums.txt" -o "${tmp}/checksums.txt"
if command -v sha256sum >/dev/null 2>&1; then
  (cd "$tmp" && grep " ${asset}$" checksums.txt | sha256sum -c - >&2)
else
  (cd "$tmp" && grep " ${asset}$" checksums.txt | shasum -a 256 -c - >&2)
fi

tar -xzf "${tmp}/${asset}" -C "$tmp"
mkdir -p "$cache_dir"
install -m 0755 "${tmp}/awf" "$binary"
printf '%s\n' "$binary"
`
