package projector

import (
	"bytes"
	"errors"
	"io/fs"
	"os"
	"path/filepath"
	"reflect"
	"slices"
	"strings"
	"testing"
)

func TestLoadAndBuildPreserveLiteralProjectBody(t *testing.T) {
	root := t.TempDir()
	body := []byte("\r\n# Project\r\n\r\nKeep {{VERSION}}, ${name}, and <!-- GENERATED by awf: text --> literal.\r\n")
	writeTestFile(t, filepath.Join(root, ".awf", "project.md"), append([]byte("---\r\nunknown: ignored\r\nformat: 1\r\n---\r\n"), body...), 0o644)
	writeTestFile(t, filepath.Join(root, ".awf", "topics", "z-last.md"), []byte("---\npaths: [docs/**]\nextra: ignored\n---\nopaque\n"), 0o644)
	writeTestFile(t, filepath.Join(root, ".awf", "topics", "nested", "a-first.md"), []byte("---\npaths: [./internal//**/*.go]\n---\nBODY\r\n"), 0o644)

	sources, err := Load(root)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(sources.Project.Body, body) {
		t.Fatalf("project body = %q, want exact %q", sources.Project.Body, body)
	}
	if got := []string{sources.Topics[0].ID, sources.Topics[1].ID}; !slices.Equal(got, []string{"nested/a-first", "z-last"}) {
		t.Fatalf("topic IDs = %v", got)
	}
	if got := string(sources.Topics[0].Body); got != "BODY\r\n" {
		t.Fatalf("topic body = %q", got)
	}

	outputs := Build(sources)
	wantPaths := []string{
		".awf/.gitignore",
		".awf/bootstrap.sh",
		".claude/skills/awf-effort/SKILL.md",
		".claude/skills/awf-topics/SKILL.md",
		".pi/skills/awf-effort/SKILL.md",
		".pi/skills/awf-topics/SKILL.md",
		"AGENTS.md",
		"CLAUDE.md",
		"awf",
	}
	if got := outputPathsForTest(outputs); !slices.Equal(got, wantPaths) {
		t.Fatalf("output paths = %v, want %v", got, wantPaths)
	}
	agents := outputForTest(t, outputs, "AGENTS.md")
	if !bytes.HasSuffix(agents.Bytes, body) {
		t.Fatalf("AGENTS does not end with literal body:\n%s", agents.Bytes)
	}
	if bytes.Count(agents.Bytes, body) != 1 {
		t.Fatal("project body was transformed or inserted more than once")
	}
	if !bytes.HasPrefix(agents.Bytes, []byte(markdownMarker+"\n")) {
		t.Fatal("AGENTS marker is not first")
	}

	piTopic := outputForTest(t, outputs, ".pi/skills/awf-topics/SKILL.md")
	claudeTopic := outputForTest(t, outputs, ".claude/skills/awf-topics/SKILL.md")
	if !bytes.Equal(piTopic.Bytes, claudeTopic.Bytes) {
		t.Fatal("Pi and Claude topic skills differ")
	}
	if !bytes.Contains(piTopic.Bytes, []byte("\n---\n"+markdownMarker+"\n")) {
		t.Fatal("skill marker is not immediately after frontmatter")
	}
	piEffort := outputForTest(t, outputs, ".pi/skills/awf-effort/SKILL.md")
	for _, phrase := range []string{"effort new <slug>", "git worktree add -b awf/<slug> .awf/worktrees/<slug>", "AWF does not manage Git"} {
		if !bytes.Contains(piEffort.Bytes, []byte(phrase)) {
			t.Errorf("effort skill missing %q", phrase)
		}
	}
	for _, path := range []string{"awf", ".awf/bootstrap.sh"} {
		output := outputForTest(t, outputs, path)
		lines := strings.Split(string(output.Bytes), "\n")
		if len(lines) < 2 || !strings.HasPrefix(lines[0], "#!") || lines[1] != textMarker {
			t.Errorf("%s marker is not after shebang", path)
		}
		if output.Mode.Perm()&0o111 == 0 {
			t.Errorf("%s is not executable", path)
		}
	}
	bootstrap := outputForTest(t, outputs, ".awf/bootstrap.sh")
	for _, phrase := range []string{`AWF_VERSION="${AWF_VERSION:-0.51.0}"`, "checksums.txt", "sha256sum -c -", "shasum -a 256 -c -"} {
		if !bytes.Contains(bootstrap.Bytes, []byte(phrase)) {
			t.Errorf("bootstrap missing %q", phrase)
		}
	}
	if bytes.Contains(bootstrap.Bytes, []byte("command -v awf")) {
		t.Fatal("bootstrap retained PATH probing")
	}
}

func TestLoadRejectsInvalidSources(t *testing.T) {
	tests := []struct {
		name    string
		project string
		topic   string
	}{
		{name: "project frontmatter", project: "plain\n"},
		{name: "project format", project: "---\nformat: 2\n---\nbody\n"},
		{name: "topic frontmatter", project: validProject("body\n"), topic: "plain\n"},
		{name: "topic paths", project: validProject("body\n"), topic: "---\npaths: []\n---\nbody\n"},
		{name: "topic escape", project: validProject("body\n"), topic: "---\npaths: [../**]\n---\nbody\n"},
		{name: "topic unsupported glob", project: validProject("body\n"), topic: "---\npaths: ['docs/[ab]']\n---\nbody\n"},
		{name: "global mixed with path", project: validProject("body\n"), topic: "---\npaths: ['**', 'src/**']\n---\nbody\n"},
		{name: "global duplicated", project: validProject("body\n"), topic: "---\npaths: ['**', '**']\n---\nbody\n"},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			root := t.TempDir()
			writeTestFile(t, filepath.Join(root, ".awf", "project.md"), []byte(test.project), 0o644)
			if test.topic != "" {
				writeTestFile(t, filepath.Join(root, ".awf", "topics", "bad.md"), []byte(test.topic), 0o644)
			}
			if _, err := Load(root); err == nil {
				t.Fatal("Load accepted invalid source")
			}
		})
	}
}

func TestResolveGlobalsPathsAndEmptyResults(t *testing.T) {
	root := t.TempDir()
	writeTestFile(t, filepath.Join(root, ".awf", "project.md"), []byte(validProject("body\n")), 0o644)
	writeTopicForTest(t, root, "z-global.md", []string{"**"})
	writeTopicForTest(t, root, "a-go.md", []string{"src/**/*.go"})
	writeTopicForTest(t, root, "m-root.md", []string{"*", "docs/**"})
	writeTopicForTest(t, root, "n-normalized-double-star.md", []string{"./**"})

	matches, err := Resolve(root, nil)
	if err != nil {
		t.Fatal(err)
	}
	want := []TopicMatch{{ID: "z-global", SourcePath: ".awf/topics/z-global.md"}}
	if !reflect.DeepEqual(matches, want) {
		t.Fatalf("empty Resolve = %#v, want %#v", matches, want)
	}

	matches, err = Resolve(root, []string{`src\new\future.go`, "unknown/file.txt", "src/new/future.go"})
	if err != nil {
		t.Fatal(err)
	}
	want = []TopicMatch{
		{ID: "a-go", SourcePath: ".awf/topics/a-go.md"},
		{ID: "n-normalized-double-star", SourcePath: ".awf/topics/n-normalized-double-star.md"},
		{ID: "z-global", SourcePath: ".awf/topics/z-global.md"},
	}
	if !reflect.DeepEqual(matches, want) {
		t.Fatalf("path Resolve = %#v, want %#v", matches, want)
	}
	if _, err := os.Stat(filepath.Join(root, "src", "new", "future.go")); !errors.Is(err, fs.ErrNotExist) {
		t.Fatalf("resolve target unexpectedly exists: %v", err)
	}

	matches, err = Resolve(root, []string{"README.md"})
	if err != nil {
		t.Fatal(err)
	}
	want = []TopicMatch{
		{ID: "m-root", SourcePath: ".awf/topics/m-root.md"},
		{ID: "n-normalized-double-star", SourcePath: ".awf/topics/n-normalized-double-star.md"},
		{ID: "z-global", SourcePath: ".awf/topics/z-global.md"},
	}
	if !reflect.DeepEqual(matches, want) {
		t.Fatalf("root Resolve = %#v, want %#v", matches, want)
	}

	writeTestFile(t, filepath.Join(root, ".awf", "topics", "z-global.md"), []byte("---\npaths: [elsewhere/**]\n---\nbody\n"), 0o644)
	writeTestFile(t, filepath.Join(root, ".awf", "topics", "n-normalized-double-star.md"), []byte("---\npaths: [elsewhere/**]\n---\nbody\n"), 0o644)
	matches, err = Resolve(root, []string{"nested/no-match"})
	if err != nil || len(matches) != 0 {
		t.Fatalf("no-match Resolve = %#v, %v", matches, err)
	}
}

func TestResolveValidatesPathsWhenGlobalsExist(t *testing.T) {
	root := t.TempDir()
	writeTestFile(t, filepath.Join(root, ".awf", "project.md"), []byte(validProject("body\n")), 0o644)
	writeTopicForTest(t, root, "global.md", []string{"**"})
	for _, bad := range []string{"", "/absolute", "../escape", `C:\absolute`} {
		if _, err := Resolve(root, []string{bad}); err == nil {
			t.Errorf("Resolve accepted %q", bad)
		}
	}
}

func TestRenderCheckRepairAndUnmanagedMarkers(t *testing.T) {
	root := t.TempDir()
	writeTestFile(t, filepath.Join(root, ".awf", "project.md"), []byte(validProject("\n"+markdownMarker+"\n# Local\n")), 0o644)
	writeTestFile(t, filepath.Join(root, ".awf", "topics", "marker.md"), []byte("---\npaths: [src/**]\n---\n"+markdownMarker+"\nopaque\n"), 0o644)

	first, err := Render(root)
	if err != nil {
		t.Fatal(err)
	}
	if len(first.Changed) != 9 || !slices.IsSorted(first.Changed) {
		t.Fatalf("first changed = %v", first.Changed)
	}
	findings, err := Check(root)
	if err != nil || len(findings) != 0 {
		t.Fatalf("clean Check = %#v, %v", findings, err)
	}

	writeTestFile(t, filepath.Join(root, "AGENTS.md"), []byte(markdownMarker+"\nmodified\n"), 0o644)
	if err := os.Chmod(filepath.Join(root, "awf"), 0o611); err != nil {
		t.Fatal(err)
	}
	writeTestFile(t, filepath.Join(root, "old.md"), []byte("<!-- GENERATED by awf: do not edit; change .awf/ and run `awf render` -->\nold\n"), 0o644)
	writeTestFile(t, filepath.Join(root, ".awf", "efforts", "ignored", "memory.md"), []byte(markdownMarker+"\nignored\n"), 0o644)
	adrBody := []byte(markdownMarker + "\nauthor-owned decision content\n")
	adrPath := filepath.Join(root, "docs", "decisions", "opaque.md")
	writeTestFile(t, adrPath, adrBody, 0o644)

	findings, err = Check(root)
	if err != nil {
		t.Fatal(err)
	}
	want := []Finding{
		{Path: "AGENTS.md", Message: "generated content differs"},
		{Path: "awf", Message: "generated executable state differs"},
		{Path: "old.md", Message: "unmanaged file still carries an AWF ownership marker"},
	}
	if !reflect.DeepEqual(findings, want) {
		t.Fatalf("drift findings = %#v, want %#v", findings, want)
	}

	repaired, err := Render(root)
	if err != nil {
		t.Fatal(err)
	}
	if !slices.Equal(repaired.Changed, []string{"AGENTS.md", "awf"}) {
		t.Fatalf("repaired = %v", repaired.Changed)
	}
	if !slices.Equal(repaired.Unmanaged, []string{"old.md"}) {
		t.Fatalf("render unmanaged = %v", repaired.Unmanaged)
	}
	if _, err := os.Stat(filepath.Join(root, "old.md")); err != nil {
		t.Fatalf("render removed unmanaged file: %v", err)
	}
	preservedADR, err := os.ReadFile(adrPath)
	if err != nil || !bytes.Equal(preservedADR, adrBody) {
		t.Fatalf("author-owned ADR after render/check = %q, %v", preservedADR, err)
	}
}

func TestRenderPreflightsUnmanagedCollision(t *testing.T) {
	root := t.TempDir()
	writeTestFile(t, filepath.Join(root, ".awf", "project.md"), []byte(validProject("body\n")), 0o644)
	writeTestFile(t, filepath.Join(root, "CLAUDE.md"), []byte("<!-- GENERATED by awf: not an ownership marker -->\nrepository-owned\n"), 0o644)

	if _, err := Render(root); err == nil || !strings.Contains(err.Error(), "not marked") {
		t.Fatalf("Render error = %v", err)
	}
	if _, err := os.Stat(filepath.Join(root, "AGENTS.md")); !errors.Is(err, fs.ErrNotExist) {
		t.Fatalf("preflight allowed a partial write: %v", err)
	}
	got, err := os.ReadFile(filepath.Join(root, "CLAUDE.md"))
	if err != nil || string(got) != "<!-- GENERATED by awf: not an ownership marker -->\nrepository-owned\n" {
		t.Fatalf("collision file = %q, %v", got, err)
	}
}

func TestRetiredResidentMarkerIsReportedWithoutScanningMemory(t *testing.T) {
	root := t.TempDir()
	writeTestFile(t, filepath.Join(root, ".awf", "project.md"), []byte(validProject("body\n")), 0o644)
	if _, err := Render(root); err != nil {
		t.Fatal(err)
	}
	legacy := "# GENERATED by awf: do not edit; change .awf/ and run `awf render`\n"
	writeTestFile(t, filepath.Join(root, ".awf", "efforts", ".gitignore"), []byte(legacy), 0o644)
	writeTestFile(t, filepath.Join(root, ".awf", "efforts", "active", "memory.md"), []byte(markdownMarker+"\nopaque\n"), 0o644)

	result, err := Render(root)
	if err != nil {
		t.Fatal(err)
	}
	if !slices.Equal(result.Unmanaged, []string{".awf/efforts/.gitignore"}) {
		t.Fatalf("unmanaged = %v", result.Unmanaged)
	}
	findings, err := Check(root)
	if err != nil || len(findings) != 1 || findings[0].Path != ".awf/efforts/.gitignore" {
		t.Fatalf("Check = %#v, %v", findings, err)
	}
}

func TestInitCreatesStarterAndProjectionWithoutGit(t *testing.T) {
	root := t.TempDir()
	t.Setenv("PATH", t.TempDir())

	result, err := Init(root)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Changed) != 9 {
		t.Fatalf("Init changed %d files", len(result.Changed))
	}
	got, err := os.ReadFile(filepath.Join(root, ".awf", "project.md"))
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != InitialProject {
		t.Fatalf("initial project differs:\n%s", got)
	}
	if _, err := os.Stat(filepath.Join(root, ".git")); !errors.Is(err, fs.ErrNotExist) {
		t.Fatalf("Init created or required Git: %v", err)
	}
	if findings, err := Check(root); err != nil || len(findings) != 0 {
		t.Fatalf("Check after Init = %#v, %v", findings, err)
	}
	if _, err := Init(root); err == nil || !strings.Contains(err.Error(), "already exists") {
		t.Fatalf("second Init error = %v", err)
	}
}

func validProject(body string) string {
	return "---\nformat: 1\n---\n" + body
}

func writeTopicForTest(t *testing.T, root, name string, patterns []string) {
	t.Helper()
	var source strings.Builder
	source.WriteString("---\npaths:\n")
	for _, pattern := range patterns {
		source.WriteString("  - '")
		source.WriteString(pattern)
		source.WriteString("'\n")
	}
	source.WriteString("---\nbody\n")
	writeTestFile(t, filepath.Join(root, ".awf", "topics", filepath.FromSlash(name)), []byte(source.String()), 0o644)
}

func writeTestFile(t *testing.T, path string, content []byte, mode fs.FileMode) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, content, mode); err != nil {
		t.Fatal(err)
	}
}

func outputPathsForTest(outputs []Output) []string {
	paths := make([]string, len(outputs))
	for i, output := range outputs {
		paths[i] = output.Path
	}
	return paths
}

func outputForTest(t *testing.T, outputs []Output, path string) Output {
	t.Helper()
	for _, output := range outputs {
		if output.Path == path {
			return output
		}
	}
	t.Fatalf("output %s not found", path)
	return Output{}
}
