package projector

import (
	"bufio"
	"bytes"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// InitialProject is the source created by Init.
const InitialProject = `---
format: 1
---

# Project guidance

You are a coding agent responsible for developing and maintaining this project. Own both the immediate task and the project's long-term health.

> Replace and refine this starter guidance with concise instructions specific to this repository.

## Identity

Describe the project's purpose, primary technology or module, maturity, and intended audience in one short paragraph.

## Agent responsibility

State what an agent working here owns beyond merely completing the immediate task.

## Invariants

List only genuinely cross-cutting hard rules. Use one terse imperative per rule and link to canonical documentation where useful.

## Workflow

Describe only repository-specific workflow. Do not duplicate generic engineering procedures or inventories of available skills.

## Commands

List the commands agents routinely need for building, testing, checking, and maintaining the project.

## Documentation

Link to the small set of canonical documents needed to navigate the repository. Keep detailed guidance in those documents rather than repeating it here.
`

// RenderResult describes visible render changes and marked files AWF no longer owns.
type RenderResult struct {
	Changed   []string
	Unmanaged []string
}

// Finding is one reason check considers the projection stale.
type Finding struct {
	Path    string
	Message string
}

// Init creates the initial project source and renders the fixed output set.
func Init(root string) (RenderResult, error) {
	filename := filepath.Join(root, filepath.FromSlash(projectPath))
	if err := os.MkdirAll(filepath.Dir(filename), 0o755); err != nil {
		return RenderResult{}, fmt.Errorf("create .awf directory: %w", err)
	}
	file, err := os.OpenFile(filename, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o644)
	if err != nil {
		if errors.Is(err, fs.ErrExist) {
			return RenderResult{}, fmt.Errorf("%s already exists", projectPath)
		}
		return RenderResult{}, fmt.Errorf("create %s: %w", projectPath, err)
	}
	if _, err := io.WriteString(file, InitialProject); err != nil {
		_ = file.Close()
		return RenderResult{}, fmt.Errorf("write %s: %w", projectPath, err)
	}
	if err := file.Close(); err != nil {
		return RenderResult{}, fmt.Errorf("close %s: %w", projectPath, err)
	}
	return Render(root)
}

// Render validates sources and writes the complete fixed output set. It never
// deletes files that are no longer outputs.
func Render(root string) (RenderResult, error) {
	sources, err := Load(root)
	if err != nil {
		return RenderResult{}, err
	}
	outputs := Build(sources)
	if err := preflightOutputs(root, outputs); err != nil {
		return RenderResult{}, err
	}

	var changed []string
	for _, output := range outputs {
		filename := filepath.Join(root, filepath.FromSlash(output.Path))
		current, info, err := readRegularOptional(filename)
		if err != nil {
			return RenderResult{}, fmt.Errorf("inspect %s: %w", output.Path, err)
		}
		if info != nil && bytes.Equal(current, output.Bytes) && sameExecutableClass(info.Mode(), output.Mode) {
			continue
		}
		if err := writeAtomic(filename, output.Bytes, output.Mode); err != nil {
			return RenderResult{}, fmt.Errorf("write %s: %w", output.Path, err)
		}
		changed = append(changed, output.Path)
	}
	unmanaged, err := unmanagedMarkedFiles(root, outputs)
	if err != nil {
		return RenderResult{}, err
	}
	sort.Strings(changed)
	return RenderResult{Changed: changed, Unmanaged: unmanaged}, nil
}

// Check compares the fixed projection with the filesystem without changing it.
func Check(root string) ([]Finding, error) {
	sources, err := Load(root)
	if err != nil {
		return nil, err
	}
	outputs := Build(sources)
	findings := make([]Finding, 0)
	for _, output := range outputs {
		filename := filepath.Join(root, filepath.FromSlash(output.Path))
		content, info, err := readRegularOptional(filename)
		if err != nil {
			return nil, fmt.Errorf("inspect %s: %w", output.Path, err)
		}
		if info == nil {
			findings = append(findings, Finding{Path: output.Path, Message: "missing generated file"})
			continue
		}
		if !info.Mode().IsRegular() {
			findings = append(findings, Finding{Path: output.Path, Message: "generated path is not a regular file"})
			continue
		}
		if !hasOwnershipMarker(content) {
			findings = append(findings, Finding{Path: output.Path, Message: "existing file is not marked as generated by AWF"})
			continue
		}
		if !bytes.Equal(content, output.Bytes) {
			findings = append(findings, Finding{Path: output.Path, Message: "generated content differs"})
		}
		if !sameExecutableClass(info.Mode(), output.Mode) {
			findings = append(findings, Finding{Path: output.Path, Message: "generated executable state differs"})
		}
	}
	unmanaged, err := unmanagedMarkedFiles(root, outputs)
	if err != nil {
		return nil, err
	}
	for _, path := range unmanaged {
		findings = append(findings, Finding{Path: path, Message: "unmanaged file still carries an AWF ownership marker"})
	}
	sort.Slice(findings, func(i, j int) bool {
		if findings[i].Path == findings[j].Path {
			return findings[i].Message < findings[j].Message
		}
		return findings[i].Path < findings[j].Path
	})
	return findings, nil
}

func preflightOutputs(root string, outputs []Output) error {
	for _, output := range outputs {
		filename := filepath.Join(root, filepath.FromSlash(output.Path))
		content, info, err := readRegularOptional(filename)
		if err != nil {
			return fmt.Errorf("inspect %s: %w", output.Path, err)
		}
		if info == nil {
			continue
		}
		if !info.Mode().IsRegular() {
			return fmt.Errorf("refuse to replace %s: existing path is not a regular file", output.Path)
		}
		if !hasOwnershipMarker(content) {
			return fmt.Errorf("refuse to replace %s: existing file is not marked as generated by AWF", output.Path)
		}
	}
	return nil
}

func readRegularOptional(filename string) ([]byte, fs.FileInfo, error) {
	info, err := os.Lstat(filename)
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return nil, nil, nil
		}
		return nil, nil, err
	}
	if !info.Mode().IsRegular() {
		return nil, info, nil
	}
	content, err := os.ReadFile(filename)
	return content, info, err
}

func sameExecutableClass(left, right fs.FileMode) bool {
	leftExecutable := left.Perm()&0o100 != 0
	rightExecutable := right.Perm()&0o100 != 0
	return leftExecutable == rightExecutable
}

func writeAtomic(filename string, content []byte, mode fs.FileMode) error {
	directory := filepath.Dir(filename)
	if err := os.MkdirAll(directory, 0o755); err != nil {
		return err
	}
	temporary, err := os.CreateTemp(directory, ".awf-*")
	if err != nil {
		return err
	}
	temporaryName := temporary.Name()
	defer func() {
		_ = temporary.Close()
		_ = os.Remove(temporaryName)
	}()
	if err := temporary.Chmod(mode.Perm()); err != nil {
		return err
	}
	if _, err := temporary.Write(content); err != nil {
		return err
	}
	if err := temporary.Close(); err != nil {
		return err
	}
	return os.Rename(temporaryName, filename)
}

func unmanagedMarkedFiles(root string, outputs []Output) ([]string, error) {
	managed := make(map[string]bool, len(outputs))
	for _, output := range outputs {
		managed[output.Path] = true
	}
	var unmanaged []string
	err := filepath.WalkDir(root, func(filename string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			if entry != nil && entry.IsDir() {
				return filepath.SkipDir
			}
			return nil
		}
		relative := displayPath(root, filename)
		if entry.IsDir() {
			if relative != "." && ignoredScanDirectory(relative) {
				return filepath.SkipDir
			}
			return nil
		}
		if managed[relative] || relative == projectPath || entry.Type()&os.ModeSymlink != 0 {
			return nil
		}
		info, err := entry.Info()
		if err != nil || !info.Mode().IsRegular() {
			return nil
		}
		file, err := os.Open(filename)
		if err != nil {
			return nil
		}
		content, readErr := io.ReadAll(io.LimitReader(file, 64*1024))
		closeErr := file.Close()
		if readErr != nil || closeErr != nil {
			return nil
		}
		if hasOwnershipMarker(content) {
			unmanaged = append(unmanaged, relative)
		}
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("scan for unmanaged AWF markers: %w", err)
	}
	for _, relative := range []string{
		".awf/efforts/.gitignore",
		".awf/worktrees/.gitignore",
		".awf/effort-archive/.gitignore",
	} {
		content, info, err := readRegularOptional(filepath.Join(root, filepath.FromSlash(relative)))
		if err != nil {
			return nil, fmt.Errorf("inspect %s: %w", relative, err)
		}
		if info != nil && info.Mode().IsRegular() && hasOwnershipMarker(content) {
			unmanaged = append(unmanaged, relative)
		}
	}
	sort.Strings(unmanaged)
	return unmanaged, nil
}

func ignoredScanDirectory(relative string) bool {
	switch relative {
	case ".git", topicsPath, ".awf/efforts", ".awf/worktrees", ".awf/effort-archive", "docs/decisions":
		return true
	default:
		return false
	}
}

func hasOwnershipMarker(content []byte) bool {
	scanner := bufio.NewScanner(bytes.NewReader(content))
	lines := make([]string, 0, 12)
	for scanner.Scan() && len(lines) < 64 {
		lines = append(lines, strings.TrimSuffix(scanner.Text(), "\r"))
	}
	if len(lines) == 0 {
		return false
	}
	index := 0
	if strings.HasPrefix(lines[index], "#!") {
		index++
	} else if lines[index] == "---" {
		index++
		for index < len(lines) && lines[index] != "---" {
			index++
		}
		if index >= len(lines) {
			return false
		}
		index++
	}
	if index >= len(lines) {
		return false
	}
	line := lines[index]
	const legacyMarkdownMarker = "<!-- GENERATED by awf: do not edit; change .awf/ and run `awf render` -->"
	const legacyTextMarker = "# GENERATED by awf: do not edit; change .awf/ and run `awf render`"
	return line == markdownMarker || line == textMarker || line == legacyMarkdownMarker || line == legacyTextMarker
}
